/**
 * Seed content for Listening Exam Prep (training). All clips use TTS mock (`scriptNl` / `scriptLines`).
 * Replace with `audioUrl` when studio assets exist.
 */
import { listeningTrainingItemSchema, type ListeningTrainingItem } from '@/lib/schemas/exam/listeningTrainingItem.schema'

const raw: unknown[] = [
  {
    id: 'lt-gist-station-1',
    questionType: 'gist',
    scenarioTag: 'station',
    difficultyBand: 1,
    contextNl: 'U hoort een omroep op het station.',
    instructionNl: 'Waar gaat deze mededeling vooral over?',
    scriptNl:
      'Goedemiddag, reizigers naar Utrecht Centraal. Door werkzaamheden vertrekt de trein van spoor drie vijf minuten later. Onze excuses.',
    options: [
      { id: 'a', labelNl: 'Een vertraging voor een trein naar Utrecht' },
      { id: 'b', labelNl: 'Het station is vandaag gesloten' },
      { id: 'c', labelNl: 'Er zijn geen treinen meer vanavond' },
      { id: 'd', labelNl: 'De bus rijdt niet' },
    ],
    correctOptionId: 'a',
    feedbackCorrectNl: 'Klopt — het gaat om een vertraging op spoor drie voor reizigers naar Utrecht.',
    feedbackIncorrectNl: 'Niet helemaal. De stem zegt dat de trein vijf minuten later vertrekt vanwege werkzaamheden.',
    keyPhraseNl: 'vijf minuten later',
    metadata: {},
  },
  {
    id: 'lt-gist-shop-2',
    questionType: 'gist',
    scenarioTag: 'winkel',
    difficultyBand: 2,
    contextNl: 'U hoort een medewerker in de supermarkt.',
    instructionNl: 'Wat is het hoofdonderwerp van deze mededeling?',
    scriptNl:
      'Let op: vandaag is de broodafdeling gesloten wegens technisch onderhoud. Brood en broodjes zijn in de filiaal aan de Hoofdstraat wel verkrijgbaar tot acht uur.',
    options: [
      { id: 'a', labelNl: 'De kassa is kapot' },
      { id: 'b', labelNl: 'De broodafdeling is tijdelijk dicht' },
      { id: 'c', labelNl: 'De winkel sluit voor altijd' },
      { id: 'd', labelNl: 'Er is geen melk meer' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Goed gehoord — de broodafdeling is dicht; ergens anders kun je nog brood halen.',
    feedbackIncorrectNl: 'De medewerker spreekt over de broodafdeling die dicht is, niet over de hele winkel.',
    keyPhraseNl: 'broodafdeling gesloten',
    metadata: {},
  },
  {
    id: 'lt-gist-werk-3',
    questionType: 'gist',
    scenarioTag: 'werk',
    difficultyBand: 3,
    contextNl: 'Twee collega’s praten kort op het werk.',
    instructionNl: 'Waar gaat dit gesprek over?',
    scriptLines: [
      'Hé, weet jij al iets over de vergadering vanmiddag?',
      'Ja, die is verplaatst. We beginnen nu om half drie in plaats van twee uur.',
    ],
    options: [
      { id: 'a', labelNl: 'Een nieuwe klant' },
      { id: 'b', labelNl: 'Een vergadering die later begint' },
      { id: 'c', labelNl: 'Iemand is ziek' },
      { id: 'd', labelNl: 'De printer werkt niet' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Juist — het gaat om een vergadering die naar half drie verschuift.',
    feedbackIncorrectNl: 'Ze hebben het over de tijd van de vergadering, niet over andere onderwerpen.',
    keyPhraseNl: 'half drie',
    metadata: {},
  },
  {
    id: 'lt-detail-trein-1',
    questionType: 'detail',
    scenarioTag: 'station',
    difficultyBand: 1,
    contextNl: 'Omroep op het perron.',
    instructionNl: 'Hoeveel minuten vertraging heeft de trein volgens de omroep?',
    scriptNl: 'De intercity naar Rotterdam heeft tien minuten vertraging en vertrekt van spoor vijf.',
    options: [
      { id: 'a', labelNl: 'Vijf minuten' },
      { id: 'b', labelNl: 'Tien minuten' },
      { id: 'c', labelNl: 'Vijftien minuten' },
      { id: 'd', labelNl: 'Geen vertraging' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Goed — de omroep zegt expliciet tien minuten vertraging.',
    feedbackIncorrectNl: 'Luister naar het getal bij “vertraging”: het is tien minuten.',
    keyPhraseNl: 'tien minuten',
    metadata: {},
  },
  {
    id: 'lt-detail-dokter-2',
    questionType: 'detail',
    scenarioTag: 'gezondheid',
    difficultyBand: 2,
    contextNl: 'Telefoonbericht van de huisartsenpraktijk.',
    instructionNl: 'Wanneer moet de patiënt volgens het bericht komen?',
    scriptNl:
      'Dag mevrouw Jansen, dit is de assistente van de huisarts. Uw afspraak van morgenochtend wordt een uur later: om half elf in plaats van half tien. Tot dan.',
    options: [
      { id: 'a', labelNl: 'Om half tien' },
      { id: 'b', labelNl: 'Om half elf' },
      { id: 'c', labelNl: 'Om twaalf uur' },
      { id: 'd', labelNl: 'De afspraak is afgezegd' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Precies — de nieuwe tijd is half elf.',
    feedbackIncorrectNl: 'De assistente zegt dat de afspraak een uur later is: half elf.',
    keyPhraseNl: 'half elf',
    metadata: {},
  },
  {
    id: 'lt-detail-winkel-3',
    questionType: 'detail',
    scenarioTag: 'winkel',
    difficultyBand: 3,
    contextNl: 'Kassamedewerker tegen een klant.',
    instructionNl: 'Hoeveel moet de klant in totaal betalen?',
    scriptLines: [
      'Dat wordt samen twaalf euro en vijftig cent, alstublieft.',
      'Wilt u pinnen of contant?',
    ],
    options: [
      { id: 'a', labelNl: '10,50 euro' },
      { id: 'b', labelNl: '11,50 euro' },
      { id: 'c', labelNl: '12,50 euro' },
      { id: 'd', labelNl: '13,50 euro' },
    ],
    correctOptionId: 'c',
    feedbackCorrectNl: 'Klopt — “twaalf euro en vijftig cent”.',
    feedbackIncorrectNl: 'De kassière noemt het totaalbedrag: twaalf vijftig.',
    keyPhraseNl: 'twaalf euro en vijftig cent',
    metadata: {},
  },
  {
    id: 'lt-intent-bel-1',
    questionType: 'intent',
    scenarioTag: 'telefoon',
    difficultyBand: 1,
    contextNl: 'Iemand laat een kort telefoonbericht horen.',
    instructionNl: 'Waarom belt deze persoon?',
    scriptNl:
      'Hallo, met Lisa. Ik bel even omdat ik vandaag niet kan komen naar de cursus. Ik ben ziek. Groetjes.',
    options: [
      { id: 'a', labelNl: 'Om een afspraak te maken' },
      { id: 'b', labelNl: 'Om af te zeggen dat ze niet komt' },
      { id: 'c', labelNl: 'Om de docent te feliciteren' },
      { id: 'd', labelNl: 'Om de huiswerkopdracht te vragen' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Goed — ze geeft aan dat ze ziek is en niet naar de cursus kan.',
    feedbackIncorrectNl: 'Ze legt uit dat ze niet komt omdat ze ziek is — dus afmelden.',
    keyPhraseNl: 'niet kan komen',
    metadata: {},
  },
  {
    id: 'lt-intent-buur-2',
    questionType: 'intent',
    scenarioTag: 'buurt',
    difficultyBand: 2,
    contextNl: 'Uw buurman spreekt u aan op de gang.',
    instructionNl: 'Wat wil de buurman van u?',
    scriptNl:
      'Hoi, sorry dat ik stoor. Zou jij volgende week één keer op mijn planten willen letten? Ik ben een paar dagen weg. Alvast bedankt!',
    options: [
      { id: 'a', labelNl: 'Dat u stil bent ’s avonds' },
      { id: 'b', labelNl: 'Dat u op zijn planten let als hij weg is' },
      { id: 'c', labelNl: 'Dat u zijn pakket aanneemt vandaag' },
      { id: 'd', labelNl: 'Dat u mee naar de film gaat' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Juist — hij vraagt hulp met de planten tijdens zijn afwezigheid.',
    feedbackIncorrectNl: 'Hij vraagt specifiek om op de planten te letten.',
    keyPhraseNl: 'op mijn planten',
    metadata: {},
  },
  {
    id: 'lt-intent-werk-3',
    questionType: 'intent',
    scenarioTag: 'werk',
    difficultyBand: 3,
    contextNl: 'Korte voicemail van uw leidinggevende.',
    instructionNl: 'Wat is de bedoeling van dit bericht?',
    scriptNl:
      'Hoi, dit is Mark. Kun je vanmiddag even langskomen? We moeten het rooster voor volgende week nog aanpassen vóór vijf uur. Bel me terug als het niet lukt.',
    options: [
      { id: 'a', labelNl: 'U krijgt vrij' },
      { id: 'b', labelNl: 'U moet langskomen om het rooster te bespreken' },
      { id: 'c', labelNl: 'De vergadering is afgelast' },
      { id: 'd', labelNl: 'U moet een klant bellen' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Goed gehoord — hij wil het rooster vóór vijf uur afstemmen en vraagt om langs te komen.',
    feedbackIncorrectNl: 'Het gaat om het rooster volgende week en een kort gesprek vanmiddag.',
    keyPhraseNl: 'rooster',
    metadata: {},
  },
]

export const LISTENING_TRAINING_BANK: ListeningTrainingItem[] = raw.map((r) => listeningTrainingItemSchema.parse(r))
