/**
 * Seed content for Reading Exam Prep (training). Dutch A2, practical genres.
 * Extend by appending validated rows — UI stays data-driven.
 */
import { readingTrainingItemSchema, type ReadingTrainingItem } from '@/lib/schemas/exam/readingTrainingItem.schema'

const raw: unknown[] = [
  {
    id: 'rt-scan-dienstregeling-1',
    readingSkill: 'scanning',
    scenarioTag: 'openbaar_vervoer',
    difficultyBand: 1,
    textKindNl: 'Dienstregeling',
    bodyNl:
      'Bus 12 — Centrum ↔ Station\nMaandag t/m vrijdag: elke 15 minuten van 06:00 tot 22:00.\nZaterdag: elke 20 minuten van 08:00 tot 20:00.\nZondag: geen dienst.',
    instructionNl: 'Hoe laat begint de bus op zaterdagochtend volgens de dienstregeling?',
    options: [
      { id: 'a', labelNl: 'Om 06:00' },
      { id: 'b', labelNl: 'Om 08:00' },
      { id: 'c', labelNl: 'Om 10:00' },
      { id: 'd', labelNl: 'Er rijdt geen bus op zaterdag' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Klopt — op zaterdag start de dienst om 08:00.',
    feedbackIncorrectNl: 'Kijk bij “Zaterdag”: de eerste ritten beginnen om 08:00, niet om 06:00.',
    evidenceSnippetNl: 'Zaterdag: elke 20 minuten van 08:00 tot 20:00.',
    metadata: {},
  },
  {
    id: 'rt-scan-winkel-1',
    readingSkill: 'scanning',
    scenarioTag: 'winkel',
    difficultyBand: 1,
    textKindNl: 'Aankondiging',
    textTitleNl: 'Supermarkt De Markt',
    bodyNl: 'Let op: op woensdag 15 mei openen wij een uur later. We openen om 10:00 in plaats van 9:00. De avondopen blijft tot 20:00.',
    instructionNl: 'Hoe laat opent de winkel op woensdag 15 mei?',
    options: [
      { id: 'a', labelNl: 'Om 9:00' },
      { id: 'b', labelNl: 'Om 10:00' },
      { id: 'c', labelNl: 'Om 11:00' },
      { id: 'd', labelNl: 'De winkel is die dag dicht' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Goed — er staat expliciet om 10:00.',
    feedbackIncorrectNl: 'De tekst zegt dat 9:00 niet geldt op die woensdag; het wordt 10:00.',
    evidenceSnippetNl: 'We openen om 10:00 in plaats van 9:00.',
    metadata: {},
  },
  {
    id: 'rt-scan-bericht-1',
    readingSkill: 'scanning',
    scenarioTag: 'sms',
    difficultyBand: 2,
    textKindNl: 'Sms-bericht',
    bodyNl: 'Hoi! Vergeet je legitimatie niet morgen bij de afspraak bij de gemeente. Groet, Sam.',
    instructionNl: 'Wat moet de lezer volgens het bericht meenemen?',
    options: [
      { id: 'a', labelNl: 'Geld' },
      { id: 'b', labelNl: 'Legitimatie' },
      { id: 'c', labelNl: 'Een foto' },
      { id: 'd', labelNl: 'Een broodje' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Juist — er staat “legitimatie”.',
    feedbackIncorrectNl: 'Het bericht waarschuwt om legitimatie niet te vergeten.',
    evidenceSnippetNl: 'Vergeet je legitimatie niet',
    metadata: {},
  },
  {
    id: 'rt-scan-app-1',
    readingSkill: 'scanning',
    scenarioTag: 'app_melding',
    difficultyBand: 2,
    textKindNl: 'Melding',
    textTitleNl: 'Teamrooster',
    bodyNl: 'Je dienst is verplaatst.\nNieuwe datum: dinsdag 18 juni.\nTijd ongewijzigd: 14:00–22:00.',
    instructionNl: 'Op welke dag is de dienst volgens de melding?',
    options: [
      { id: 'a', labelNl: 'Maandag 17 juni' },
      { id: 'b', labelNl: 'Dinsdag 18 juni' },
      { id: 'c', labelNl: 'Woensdag 19 juni' },
      { id: 'd', labelNl: 'De datum staat er niet' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Goed gezien — dinsdag 18 juni.',
    feedbackIncorrectNl: 'Zoek de regel “Nieuwe datum”.',
    evidenceSnippetNl: 'Nieuwe datum: dinsdag 18 juni.',
    metadata: {},
  },
  {
    id: 'rt-scan-bibliotheek-1',
    readingSkill: 'scanning',
    scenarioTag: 'bibliotheek',
    difficultyBand: 3,
    textKindNl: 'Bord bij de ingang',
    bodyNl: 'Bibliotheek Stadshart\nVandaag gesloten wegens jaarlijkse inventaris.\nMorgen weer open van 10:00 tot 18:00.',
    instructionNl: 'Waarom is de bibliotheek vandaag dicht?',
    options: [
      { id: 'a', labelNl: 'Vanwege een feestdag' },
      { id: 'b', labelNl: 'Wegens jaarlijkse inventaris' },
      { id: 'c', labelNl: 'Omdat er geen personeel is' },
      { id: 'd', labelNl: 'Vanwege renovatie' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Klopt — de inventaris is de reden.',
    feedbackIncorrectNl: 'Het bord noemt “jaarlijkse inventaris”, geen feestdag of renovatie.',
    evidenceSnippetNl: 'gesloten wegens jaarlijkse inventaris',
    metadata: {},
  },
  {
    id: 'rt-scan-werk-1',
    readingSkill: 'scanning',
    scenarioTag: 'werkplek',
    difficultyBand: 3,
    textKindNl: 'Briefje op het prikbord',
    bodyNl: 'Collega’s — de vergaderzaal op de 2e verdieping is vandaag gereserveerd tot 16:00. Gebruik zaal B op de 1e voor overleg tot die tijd. Dank!',
    instructionNl: 'Welke vergaderruimte moet je gebruiken tot 16:00 volgens het briefje?',
    options: [
      { id: 'a', labelNl: 'Zaal op de 2e verdieping' },
      { id: 'b', labelNl: 'Zaal B op de 1e verdieping' },
      { id: 'c', labelNl: 'De kantine' },
      { id: 'd', labelNl: 'Thuiswerken' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Goed — zaal B op de 1e is het alternatief.',
    feedbackIncorrectNl: 'De 2e verdieping is gereserveerd; het briefje wijst naar zaal B op de 1e.',
    evidenceSnippetNl: 'Gebruik zaal B op de 1e',
    metadata: {},
  },
  {
    id: 'rt-comp-email-1',
    readingSkill: 'comprehension',
    scenarioTag: 'email',
    difficultyBand: 1,
    textKindNl: 'E-mail',
    textTitleNl: 'Onderwerp: afspraak huisarts',
    bodyNl: 'Beste mevrouw Jansen,\n\nUw afspraak op 3 juli wordt een week vervroegd. De nieuwe datum is 26 juni om 09:40 bij praktijk De Linde.\n\nAls dit niet uitkomt, bel ons dan vóór vrijdag.\n\nMet vriendelijke groet,\nAssistente De Linde',
    instructionNl: 'Waar gaat deze e-mail vooral over?',
    options: [
      { id: 'a', labelNl: 'Een nieuwe klacht' },
      { id: 'b', labelNl: 'Het verplaatsen van een afspraak' },
      { id: 'c', labelNl: 'Een factuur' },
      { id: 'd', labelNl: 'Een sollicitatie' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Juist — de kern is dat de afspraak wordt vervroegd.',
    feedbackIncorrectNl: 'De praktijk meldt een nieuwe datum voor dezelfde soort afspraak.',
    evidenceSnippetNl: 'Uw afspraak … wordt een week vervroegd.',
    metadata: {},
  },
  {
    id: 'rt-comp-werk-1',
    readingSkill: 'comprehension',
    scenarioTag: 'werkplek',
    difficultyBand: 1,
    textKindNl: 'Intern bericht',
    textTitleNl: 'Voor alle medewerkers',
    bodyNl: 'Vanaf volgende week gelden nieuwe regels voor het meenemen van eten naar je werkplek. Gebruik alleen de daarvoor bestemde koelkast op de begane grond en label je naam op je bakje. Zo houden we de keuken hygiënisch.',
    instructionNl: 'Wat moeten medewerkers vooral doen volgens het bericht?',
    options: [
      { id: 'a', labelNl: 'Thuis blijven eten' },
      { id: 'b', labelNl: 'Eten in de juiste koelkast leggen en een naam op het bakje zetten' },
      { id: 'c', labelNl: 'Geen eten meer meenemen' },
      { id: 'd', labelNl: 'Alleen koffie drinken' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Goed — de instructies gaan over koelkast en label.',
    feedbackIncorrectNl: 'Het bericht vraagt om hygiëne via de koelkast beneden en een naam op je bakje.',
    evidenceSnippetNl: 'Gebruik alleen de … koelkast … en label je naam',
    metadata: {},
  },
  {
    id: 'rt-comp-wijk-1',
    readingSkill: 'comprehension',
    scenarioTag: 'gemeenschap',
    difficultyBand: 2,
    textKindNl: 'Briefje in de hal',
    bodyNl: 'Buurtinitiatief “Groen voor de deur”\nWe zoeken vrijwilligers om zaterdagochtend planten te verzorgen bij de speeltuin. Geen ervaring nodig — alleen goede schoenen en enthousiasme. Meld je bij de voordeur van nr. 14.',
    instructionNl: 'Wat is het doel van dit briefje?',
    options: [
      { id: 'a', labelNl: 'Klachten over lawaai verzamelen' },
      { id: 'b', labelNl: 'Mensen uitnodigen om mee te helpen in de buurt' },
      { id: 'c', labelNl: 'Een feest aankondigen' },
      { id: 'd', labelNl: 'Waarschuwen dat de speeltuin dicht is' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Klopt — het zoekt vrijwilligers voor een buurtactie.',
    feedbackIncorrectNl: 'De tekst nodigt uit om mee te doen met planten verzorgen.',
    evidenceSnippetNl: 'We zoeken vrijwilligers om … planten te verzorgen',
    metadata: {},
  },
  {
    id: 'rt-comp-gemeente-1',
    readingSkill: 'comprehension',
    scenarioTag: 'brief_officieel',
    difficultyBand: 2,
    textKindNl: 'Brief van de gemeente',
    bodyNl: 'Geachte bewoner,\n\nUw container voor plastic wordt voortaan op woensdag geleegd in plaats van dinsdag. Zet de container uiterlijk 07:30 aan de straat. Hartelijk dank voor uw medewerking.',
    instructionNl: 'Waarom schrijft de gemeente deze brief?',
    options: [
      { id: 'a', labelNl: 'Om de huur te verhogen' },
      { id: 'b', labelNl: 'Om de ophaaldag van de plasticcontainer te veranderen' },
      { id: 'c', labelNl: 'Om een boete te melden' },
      { id: 'd', labelNl: 'Om een nieuw paspoort aan te bieden' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Goed — de wijziging van de ophaaldag is het hoofddoel.',
    feedbackIncorrectNl: 'De brief gaat over plastic en een andere weekdag.',
    evidenceSnippetNl: 'Uw container voor plastic wordt voortaan op woensdag geleegd',
    metadata: {},
  },
  {
    id: 'rt-comp-advert-1',
    readingSkill: 'comprehension',
    scenarioTag: 'advertentie',
    difficultyBand: 3,
    textKindNl: 'Advertentie',
    bodyNl: 'Taalcafé De Brug — elke dinsdag 18:30–20:00.\nOefen gratis Nederlands in een kleine groep. Koffie en thee aanwezig. Aanmelden niet nodig; gewoon binnenlopen.',
    instructionNl: 'Wat biedt De Brug vooral aan?',
    options: [
      { id: 'a', labelNl: 'Betaalde cursussen met examen' },
      { id: 'b', labelNl: 'Informeel Nederlands oefenen zonder aanmelding' },
      { id: 'c', labelNl: 'Alleen koffie verkopen' },
      { id: 'd', labelNl: 'Werk zoeken voor vluchtelingen' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Juist — gratis oefenen, geen aanmelding.',
    feedbackIncorrectNl: 'De advertentie benadrukt informeel oefenen en “Aanmelden niet nodig”.',
    evidenceSnippetNl: 'Oefen gratis Nederlands … Aanmelden niet nodig',
    metadata: {},
  },
  {
    id: 'rt-comp-notificatie-1',
    readingSkill: 'comprehension',
    scenarioTag: 'app_melding',
    difficultyBand: 3,
    textKindNl: 'Schermmelding',
    textTitleNl: 'OV-chipkaart',
    bodyNl: 'Uw saldo is bijna op. Voeg saldo toe vóór uw volgende reis om boetes te voorkomen. Tip: automatisch opladen inschakelen in de app.',
    instructionNl: 'Wat wil de app van de gebruiker?',
    options: [
      { id: 'a', labelNl: 'Een nieuwe kaart bestellen' },
      { id: 'b', labelNl: 'Saldo toevoegen (of automatisch opladen) voordat er gereisd wordt' },
      { id: 'c', labelNl: 'Een klacht indienen' },
      { id: 'd', labelNl: 'De app verwijderen' },
    ],
    correctOptionId: 'b',
    feedbackCorrectNl: 'Goed — de waarschuwing gaat over saldo en reizen.',
    feedbackIncorrectNl: 'De boodschap is: geld op de kaart zetten om problemen te voorkomen.',
    evidenceSnippetNl: 'Voeg saldo toe vóór uw volgende reis',
    metadata: {},
  },
]

function parseBank(rows: unknown[]): ReadingTrainingItem[] {
  return rows.map((row, i) => {
    const r = readingTrainingItemSchema.safeParse(row)
    if (!r.success) {
      throw new Error(`readingTrainingBank row ${i}: ${r.error.message}`)
    }
    return r.data
  })
}

export const READING_TRAINING_BANK: ReadingTrainingItem[] = parseBank(raw)
