import { listeningClipSchema, listeningPackSchema, type ListeningClip, type ListeningPack } from '@/lib/listening-mode/schema'

/** Canonical clip bank — scenario-linked, short-form Dutch (TTS). */
export const LISTENING_CLIP_BANK: Record<string, ListeningClip> = {
  'cafe-gist-1': listeningClipSchema.parse({
    id: 'cafe-gist-1',
    scenarioId: 'cafe',
    level: 'A2',
    drillType: 'gist',
    instructionEn: 'What is the customer mainly doing?',
    speakLinesNl: ['Goedemiddag. Twee koffie graag, en mag ik ook een stuk appeltaart?'],
    transcriptNl: 'Goedemiddag. Twee koffie graag, en mag ik ook een stuk appeltaart?',
    meaningEn: 'They politely order two coffees and ask for a slice of apple pie.',
    optionLabels: ['Ordering food and drink', 'Complaining about the bill', 'Asking for directions', 'Booking a table for ten'],
    correctIndex: 0,
    listeningTags: ['gist', 'service_phrases', 'quantities'],
    speechRate: 0.9,
  }),
  'cafe-detail-1': listeningClipSchema.parse({
    id: 'cafe-detail-1',
    scenarioId: 'cafe',
    level: 'A2',
    drillType: 'detail_catch',
    instructionEn: 'How many coffees did they ask for?',
    speakLinesNl: ['Twee koffie, alstublieft. Zwart, zonder suiker.'],
    transcriptNl: 'Twee koffie, alstublieft. Zwart, zonder suiker.',
    meaningEn: 'Two coffees, black, no sugar.',
    optionLabels: ['One', 'Two', 'Three', 'Four'],
    correctIndex: 1,
    listeningTags: ['key_details', 'numbers', 'quantities'],
    speechRate: 0.9,
    detailFacet: 'quantity',
  }),
  'cafe-respond-1': listeningClipSchema.parse({
    id: 'cafe-respond-1',
    scenarioId: 'cafe',
    level: 'A2',
    drillType: 'listen_respond',
    instructionEn: 'You are the customer. What do you say next?',
    speakLinesNl: ['Wilt u melk bij de koffie?'],
    transcriptNl: 'Wilt u melk bij de koffie?',
    meaningEn: 'The server asks if you want milk with the coffee — a short polite reply fits.',
    optionLabels: ['Nee, zwart graag.', 'Ik zoek de trein.', 'Waar is de uitgang?', 'Ik heb pijn hier.'],
    correctIndex: 0,
    listeningTags: ['response_readiness', 'service_phrases', 'natural_reply'],
    speechRate: 0.92,
  }),
  'train-gist-1': listeningClipSchema.parse({
    id: 'train-gist-1',
    scenarioId: 'train',
    level: 'A2',
    drillType: 'gist',
    instructionEn: 'What is this announcement mainly about?',
    speakLinesNl: [
      'Goede reizigers, intercity naar Utrecht vertrekt van spoor zeven. Er is een vertraging van vijf minuten.',
    ],
    transcriptNl:
      'Goede reizigers, intercity naar Utrecht vertrekt van spoor zeven. Er is een vertraging van vijf minuten.',
    meaningEn: 'Train to Utrecht from platform seven, five-minute delay.',
    optionLabels: [
      'A delay and platform info',
      'An on-time departure with no changes',
      'A full cancellation of the Utrecht train',
      'Another city’s train from platform seven (not Utrecht)',
    ],
    correctIndex: 0,
    listeningTags: ['gist', 'route_words', 'times'],
    speechRate: 0.9,
  }),
  'train-detail-1': listeningClipSchema.parse({
    id: 'train-detail-1',
    scenarioId: 'train',
    level: 'A2',
    drillType: 'detail_catch',
    instructionEn: 'Which platform?',
    speakLinesNl: ['De sprinter naar Haarlem vertrekt van spoor vier, over ongeveer drie minuten.'],
    transcriptNl: 'De sprinter naar Haarlem vertrekt van spoor vier, over ongeveer drie minuten.',
    meaningEn: 'Platform four for the Haarlem sprinter in about three minutes.',
    optionLabels: ['Spoor twee', 'Spoor drie', 'Spoor vier', 'Spoor vijf'],
    correctIndex: 2,
    listeningTags: ['key_details', 'route_words', 'numbers'],
    speechRate: 0.88,
    detailFacet: 'platform',
  }),
  'train-order-1': listeningClipSchema.parse({
    id: 'train-order-1',
    scenarioId: 'train',
    level: 'B1',
    drillType: 'order_instruction',
    instructionEn: 'What should you do first, according to the voice?',
    speakLinesNl: [
      'Stap eerst uit bij Station Zuid. Daarna neemt u tram zestien richting VU medisch centrum. Controleer uw OV-chipkaart bij het inchecken.',
    ],
    transcriptNl:
      'Stap eerst uit bij Station Zuid. Daarna neemt u tram zestien richting VU medisch centrum. Controleer uw OV-chipkaart bij het inchecken.',
    meaningEn: 'First exit at Zuid, then tram 16 toward VUmc; check in with your OV-chipkaart.',
    optionLabels: [
      'Exit at Zuid, then take tram 16',
      'Take tram 16 before exiting at Zuid',
      'Go to platform twelve before you exit',
      'Take metro 52 first, then the tram to VUmc',
    ],
    correctIndex: 0,
    listeningTags: ['instruction_following', 'route_words', 'next_action'],
    speechRate: 0.88,
  }),
  'super-detail-1': listeningClipSchema.parse({
    id: 'super-detail-1',
    scenarioId: 'supermarket_shop',
    level: 'A2',
    drillType: 'detail_catch',
    instructionEn: 'Where can they find the yoghurt?',
    speakLinesNl: ['De yoghurt staat in gang drie, rechts na de zuivelkoeling.'],
    transcriptNl: 'De yoghurt staat in gang drie, rechts na de zuivelkoeling.',
    meaningEn: 'Aisle three, to the right after the dairy fridge.',
    optionLabels: ['Gang één', 'Gang twee', 'Gang drie', 'Bij de kassa'],
    correctIndex: 2,
    listeningTags: ['key_details', 'route_words', 'service_phrases'],
    speechRate: 0.9,
    detailFacet: 'route',
  }),
  'super-fast-1': listeningClipSchema.parse({
    id: 'super-fast-1',
    scenarioId: 'supermarket_shop',
    level: 'B1',
    drillType: 'fast_dutch',
    instructionEn: 'Quick ear-check: what do they want to know?',
    speakLinesNl: ['Hé sorry, hebben jullie nog lactosevrije melk, halfvol?'],
    transcriptNl: 'Hé sorry, hebben jullie nog lactosevrije melk, halfvol?',
    meaningEn: 'They ask if you still have lactose-free semi-skimmed milk.',
    optionLabels: ['If lactose-free milk is in stock', 'Where the bread is', 'If they can return meat', 'If the shop is hiring'],
    correctIndex: 0,
    listeningTags: ['fast_speech', 'reduced_speech', 'key_details'],
    speechRate: 1.06,
  }),
  'doctor-gist-1': listeningClipSchema.parse({
    id: 'doctor-gist-1',
    scenarioId: 'doctor',
    level: 'A2',
    drillType: 'gist',
    instructionEn: 'What is the patient mainly explaining?',
    speakLinesNl: [
      'Dokter, sinds gisteren heb ik koorts en een zere keel. Ik hoest ook, vooral ’s nachts.',
    ],
    transcriptNl: 'Dokter, sinds gisteren heb ik koorts en een zere keel. Ik hoest ook, vooral ’s nachts.',
    meaningEn: 'They describe fever, sore throat, and coughing since yesterday.',
    optionLabels: ['Cold-like symptoms since yesterday', 'They want a prescription refill only', 'They are booking a holiday', 'They need directions to the pharmacy'],
    correctIndex: 0,
    listeningTags: ['gist', 'symptom', 'key_details'],
    speechRate: 0.9,
  }),
  'doctor-detail-1': listeningClipSchema.parse({
    id: 'doctor-detail-1',
    scenarioId: 'doctor',
    level: 'B1',
    drillType: 'detail_catch',
    instructionEn: 'When should they take the first tablet?',
    speakLinesNl: ['Neem de eerste tablet vandaag na het avondeten, en daarna elke ochtend.'],
    transcriptNl: 'Neem de eerste tablet vandaag na het avondeten, en daarna elke ochtend.',
    meaningEn: 'First tablet after dinner today, then every morning.',
    optionLabels: ['Before breakfast', 'After dinner today', 'Only if fever returns', 'At noon with milk'],
    correctIndex: 1,
    listeningTags: ['instruction_following', 'times', 'key_details'],
    speechRate: 0.9,
    detailFacet: 'time',
  }),
  'booking-replay-1': listeningClipSchema.parse({
    id: 'booking-replay-1',
    scenarioId: 'booking_reservations',
    level: 'A2',
    drillType: 'replay_reveal',
    instructionEn: 'Listen once, answer, then you can replay slower and reveal the line.',
    speakLinesNl: ['Uw tafel voor twee personen is klaar. Wilt u nog water met of zonder bruis?'],
    transcriptNl: 'Uw tafel voor twee personen is klaar. Wilt u nog water met of zonder bruis?',
    meaningEn: 'Table for two is ready; they ask still or sparkling water.',
    optionLabels: ['Table is ready; they ask about water', 'They cancel the reservation', 'They ask you to pay now', 'They offer a new menu only'],
    correctIndex: 0,
    listeningTags: ['gist', 'service_phrases', 'follow_up_questions'],
    speechRate: 0.92,
  }),
  'weak-route-1': listeningClipSchema.parse({
    id: 'weak-route-1',
    scenarioId: 'directions_getting_somewhere',
    level: 'A2',
    drillType: 'weak_area',
    instructionEn: 'Personal rep: catch the key turn.',
    speakLinesNl: ['Ga hier links de eerste straat in, dan ziet u de brug al.'],
    transcriptNl: 'Ga hier links de eerste straat in, dan ziet u de brug al.',
    meaningEn: 'Turn left into the first street, then you will see the bridge.',
    optionLabels: ['Turn left into the first street', 'Turn right at the lights', 'Go straight for two kilometres', 'Take the second exit on the roundabout'],
    correctIndex: 0,
    listeningTags: ['route_words', 'key_details', 'instruction_following'],
    speechRate: 0.9,
  }),
  'weak-numbers-1': listeningClipSchema.parse({
    id: 'weak-numbers-1',
    scenarioId: 'phone_appointment',
    level: 'A2',
    drillType: 'weak_area',
    instructionEn: 'Personal rep: lock the time you heard.',
    speakLinesNl: ['We hebben een plek om kwart over drie, of om half vijf. Wat past beter?'],
    transcriptNl: 'We hebben een plek om kwart over drie, of om half vijf. Wat past beter?',
    meaningEn: 'They offer 3:15 or 4:30 as appointment slots.',
    optionLabels: ['3:15 or 4:30', '2:00 or 2:30', '10:00 or 11:00', 'Only next Monday'],
    correctIndex: 0,
    listeningTags: ['numbers', 'times', 'key_details'],
    speechRate: 0.88,
  }),
}

export const LISTENING_PACKS: ListeningPack[] = [
  listeningPackSchema.parse({
    id: 'pack-cafe-burst',
    scenarioId: 'cafe',
    title: 'Café — catch the order',
    subtitle: 'Short bursts: gist, a number, and a natural reply.',
    level: 'A2',
    clipIds: ['cafe-gist-1', 'cafe-detail-1', 'cafe-respond-1'],
  }),
  listeningPackSchema.parse({
    id: 'pack-train-platform',
    scenarioId: 'train',
    title: 'Train & tram — platforms and steps',
    subtitle: 'Announcements, a platform detail, and a short route script.',
    level: 'A2',
    clipIds: ['train-gist-1', 'train-detail-1', 'train-order-1'],
  }),
  listeningPackSchema.parse({
    id: 'pack-shop-fast',
    scenarioId: 'supermarket_shop',
    title: 'Shop floor — aisle + fast question',
    subtitle: 'Where things live, then a quicker line at the shelf.',
    level: 'A2',
    clipIds: ['super-detail-1', 'super-fast-1'],
  }),
  listeningPackSchema.parse({
    id: 'pack-clinic-instructions',
    scenarioId: 'doctor',
    title: 'Clinic desk — symptoms and timing',
    subtitle: 'Gist of the complaint, then a precise instruction.',
    level: 'A2',
    clipIds: ['doctor-gist-1', 'doctor-detail-1'],
  }),
  listeningPackSchema.parse({
    id: 'pack-booking-reveal',
    scenarioId: 'booking_reservations',
    title: 'Booking line — listen, answer, then reveal',
    subtitle: 'Replay + reveal style rep for service Dutch.',
    level: 'A2',
    clipIds: ['booking-replay-1'],
  }),
]

export function getListeningPack(packId: string): ListeningPack | undefined {
  return LISTENING_PACKS.find((p) => p.id === packId)
}

/** Rough session length from clip count (weak-area rep adds ~1 clip in-session). */
export function estimatePackDurationMinutes(packId: string): number {
  const pack = getListeningPack(packId)
  if (!pack) return 2
  const clips = pack.clipIds.length
  return Math.max(1, Math.min(12, Math.round(clips * 0.75 + 0.5)))
}

export function clipsForPack(pack: ListeningPack): ListeningClip[] {
  return pack.clipIds.map((id) => LISTENING_CLIP_BANK[id]).filter(Boolean) as ListeningClip[]
}
