/**
 * Analytics event taxonomy. Replace with actual provider (e.g. segment, mixpanel) later.
 * Central dispatch adds session_id, user_id, timestamp_iso, event_category via `track()` → emitAnalyticsEvent.
 */
import { emitAnalyticsEvent } from '@/lib/analytics/analyticsService'
import { LEARNING_INTELLIGENCE_EVENTS } from '@/lib/analytics/learningIntelligenceEvents'

export const ANALYTICS_EVENTS = {
  onboarding_started: 'onboarding_started',
  onboarding_step: 'onboarding_step',
  onboarding_step_viewed: 'onboarding_step_viewed',
  onboarding_step_completed: 'onboarding_step_completed',
  onboarding_resumed: 'onboarding_resumed',
  onboarding_abandoned: 'onboarding_abandoned',
  onboarding_completed: 'onboarding_completed',
  /** Profile document updated during onboarding (incremental save). */
  onboarding_profile_updated: 'onboarding_profile_updated',
  /** Durable onboarding signal fields changed on profile (subset of profile_updated). */
  onboarding_answer_saved: 'onboarding_answer_saved',
  /** Resume path hydrated onboarding store from persisted profile. */
  onboarding_resume_loaded: 'onboarding_resume_loaded',
  onboarding_start_route_resolved: 'onboarding_start_route_resolved',
  onboarding_start_experience_shown: 'onboarding_start_experience_shown',
  onboarding_start_path_selected: 'onboarding_start_path_selected',
  onboarding_personalized_route_entered: 'onboarding_personalized_route_entered',
  lesson_started: 'lesson_started',
  lesson_completed: 'lesson_completed',
  lesson_quiz_completed: 'lesson_quiz_completed',
  flashcards_completed: 'flashcards_completed',
  simulation_started: 'simulation_started',
  simulation_message_sent: 'simulation_message_sent',
  /** Scenario lifecycle (product funnel) */
  scenario_viewed: 'scenario_viewed',
  scenario_catalog_viewed: 'scenario_catalog_viewed',
  scenario_abandoned: 'scenario_abandoned',
  scenario_completed: 'scenario_completed',
  scenario_first_response: 'scenario_first_response',
  scenario_started: 'scenario_started',
  /** Guided structured scenarios (Practice hub) */
  guided_scenario_opened: 'guided_scenario_opened',
  guided_scenario_started: 'guided_scenario_started',
  guided_scenario_chat_restarted: 'guided_scenario_chat_restarted',
  guided_scenario_reply_submitted: 'guided_scenario_reply_submitted',
  guided_scenario_completed: 'guided_scenario_completed',
  guided_scenario_support_used: 'guided_scenario_support_used',
  guided_micro_nudge_shown: 'guided_micro_nudge_shown',
  guided_suggestion_loaded_to_composer: 'guided_suggestion_loaded_to_composer',
  /** Open conversation (semi-guided / free) */
  practice_open_conversation_started: 'practice_open_conversation_started',
  practice_open_conversation_completed: 'practice_open_conversation_completed',
  practice_support_tool_used: 'practice_support_tool_used',
  /** Support layer — granular learning signals (usage ≠ failure). */
  support_tool_opened: 'support_tool_opened',
  hint_used: 'hint_used',
  phrase_suggestion_used: 'phrase_suggestion_used',
  slower_reply_requested: 'slower_reply_requested',
  translation_requested: 'translation_requested',
  natural_rephrase_requested: 'natural_rephrase_requested',
  explanation_requested: 'explanation_requested',
  turn_restarted: 'turn_restarted',
  easier_mode_requested: 'easier_mode_requested',
  /** Post-conversation practice feedback */
  practice_feedback_shown: 'practice_feedback_shown',
  practice_feedback_strength_viewed: 'practice_feedback_strength_viewed',
  practice_feedback_improvement_viewed: 'practice_feedback_improvement_viewed',
  phrasing_upgrade_viewed: 'phrasing_upgrade_viewed',
  next_practice_clicked: 'next_practice_clicked',
  review_from_practice_clicked: 'review_from_practice_clicked',
  /** Weakness funnel */
  weak_area_shown: 'weak_area_shown',
  /** Improve weak-area drill screen opened (not deduped with weak_area_shown). */
  weak_area_drill_viewed: 'weak_area_drill_viewed',
  weak_area_practice_started: 'weak_area_practice_started',
  /** Modality */
  typing_mode_used: 'typing_mode_used',
  speaking_mode_used: 'speaking_mode_used',
  retry_scenario_clicked: 'retry_scenario_clicked',
  harder_mode_clicked: 'harder_mode_clicked',
  skill_tracks_hub_viewed: 'skill_tracks_hub_viewed',
  skill_track_detail_viewed: 'skill_track_detail_viewed',
  skill_track_session_started: 'skill_track_session_started',
  skill_track_session_completed: 'skill_track_session_completed',
  skill_track_exercise_answered: 'skill_track_exercise_answered',
  skill_track_speaking_model_played: 'skill_track_speaking_model_played',
  skill_track_speaking_mic_check: 'skill_track_speaking_mic_check',
  skill_track_level_progressed: 'skill_track_level_progressed',
  voice_tutor_started: 'voice_tutor_started',
  voice_tutor_recording_completed: 'voice_tutor_recording_completed',
  premium_cta_viewed: 'premium_cta_viewed',
  premium_cta_clicked: 'premium_cta_clicked',
  premium_block_shown: 'premium_block_shown',
  premium_feature_exposed: 'premium_feature_exposed',
  premium_upgrade_clicked: 'premium_upgrade_clicked',
  /** Plan gating: user saw a Premium-only feature (locked or preview). */
  premium_feature_locked: 'premium_feature_locked',
  premium_feature_viewed: 'premium_feature_viewed',
  premium_feature_cta_clicked: 'premium_feature_cta_clicked',
  pricing_opened_from_lock: 'pricing_opened_from_lock',
  basic_user_hit_lock: 'basic_user_hit_lock',
  premium_user_accessed_feature: 'premium_user_accessed_feature',
  permission_requested: 'permission_requested',
  permission_granted: 'permission_granted',
  permission_denied: 'permission_denied',
  reflection_lesson_generated: 'reflection_lesson_generated',
  exam_section_viewed: 'exam_section_viewed',
  exam_prep_landing_viewed: 'exam_prep_landing_viewed',
  exam_prep_entry_clicked: 'exam_prep_entry_clicked',
  exam_prep_type_selected: 'exam_prep_type_selected',
  exam_prep_type_hub_viewed: 'exam_prep_type_hub_viewed',
  /** Speaking exam prep — training vertical slice */
  speaking_exam_question_viewed: 'speaking_exam_question_viewed',
  speaking_exam_started: 'speaking_exam_started',
  speaking_exam_answer_submitted: 'speaking_exam_answer_submitted',
  speaking_exam_scored: 'speaking_exam_scored',
  speaking_exam_feedback_viewed: 'speaking_exam_feedback_viewed',
  speaking_exam_model_answer_viewed: 'speaking_exam_model_answer_viewed',
  speaking_exam_retry_clicked: 'speaking_exam_retry_clicked',
  speaking_exam_next_clicked: 'speaking_exam_next_clicked',
  speaking_exam_category_viewed: 'speaking_exam_category_viewed',
  speaking_exam_corrections_viewed: 'speaking_exam_corrections_viewed',
  speaking_exam_improved_version_viewed: 'speaking_exam_improved_version_viewed',
  speaking_exam_ideal_answer_viewed: 'speaking_exam_ideal_answer_viewed',
  speaking_exam_next_action_clicked: 'speaking_exam_next_action_clicked',
  speaking_exam_session_started: 'speaking_exam_session_started',
  speaking_exam_question_completed: 'speaking_exam_question_completed',
  speaking_exam_session_completed: 'speaking_exam_session_completed',
  speaking_exam_session_summary_viewed: 'speaking_exam_session_summary_viewed',
  speaking_exam_confidence_viewed: 'speaking_exam_confidence_viewed',
  speaking_exam_next_step_clicked: 'speaking_exam_next_step_clicked',
  /** Speaking exam prep — simulation (timed, no mid-session coaching) */
  speaking_exam_simulation_started: 'speaking_exam_simulation_started',
  speaking_exam_simulation_question_started: 'speaking_exam_simulation_question_started',
  speaking_exam_simulation_question_timed_out: 'speaking_exam_simulation_question_timed_out',
  speaking_exam_simulation_question_completed: 'speaking_exam_simulation_question_completed',
  speaking_exam_simulation_completed: 'speaking_exam_simulation_completed',
  speaking_exam_simulation_result_viewed: 'speaking_exam_simulation_result_viewed',
  speaking_exam_simulation_retry_clicked: 'speaking_exam_simulation_retry_clicked',
  speaking_exam_simulation_next_training_clicked: 'speaking_exam_simulation_next_training_clicked',
  /** Writing exam prep — training vertical slice */
  writing_exam_category_selected: 'writing_exam_category_selected',
  writing_exam_task_viewed: 'writing_exam_task_viewed',
  writing_exam_started: 'writing_exam_started',
  writing_exam_answer_submitted: 'writing_exam_answer_submitted',
  writing_exam_scored: 'writing_exam_scored',
  writing_exam_feedback_viewed: 'writing_exam_feedback_viewed',
  writing_exam_model_answer_viewed: 'writing_exam_model_answer_viewed',
  writing_exam_retry_clicked: 'writing_exam_retry_clicked',
  writing_exam_next_clicked: 'writing_exam_next_clicked',
  writing_exam_category_viewed: 'writing_exam_category_viewed',
  writing_exam_corrections_viewed: 'writing_exam_corrections_viewed',
  writing_exam_improved_version_viewed: 'writing_exam_improved_version_viewed',
  writing_exam_rewritten_version_viewed: 'writing_exam_rewritten_version_viewed',
  writing_exam_ideal_answer_viewed: 'writing_exam_ideal_answer_viewed',
  writing_exam_next_action_clicked: 'writing_exam_next_action_clicked',
  /** Writing exam prep — simulation (4-part timed exam run) */
  writing_exam_simulation_started: 'writing_exam_simulation_started',
  writing_exam_simulation_task_started: 'writing_exam_simulation_task_started',
  writing_exam_simulation_task_completed: 'writing_exam_simulation_task_completed',
  writing_exam_simulation_task_timed_out: 'writing_exam_simulation_task_timed_out',
  writing_exam_simulation_completed: 'writing_exam_simulation_completed',
  writing_exam_simulation_result_viewed: 'writing_exam_simulation_result_viewed',
  writing_exam_simulation_retry_clicked: 'writing_exam_simulation_retry_clicked',
  writing_exam_simulation_next_training_clicked: 'writing_exam_simulation_next_training_clicked',
  /** Listening exam prep — training (structured MCQ after audio / TTS) */
  listening_exam_training_started: 'listening_exam_training_started',
  listening_exam_task_viewed: 'listening_exam_task_viewed',
  listening_exam_audio_played: 'listening_exam_audio_played',
  listening_exam_audio_replayed: 'listening_exam_audio_replayed',
  listening_exam_answer_selected: 'listening_exam_answer_selected',
  listening_exam_answer_submitted: 'listening_exam_answer_submitted',
  listening_exam_result_viewed: 'listening_exam_result_viewed',
  listening_exam_next_clicked: 'listening_exam_next_clicked',
  listening_exam_training_session_completed: 'listening_exam_training_session_completed',
  /** Reading exam prep — training (short text + structured MCQ) */
  reading_exam_training_started: 'reading_exam_training_started',
  reading_exam_task_viewed: 'reading_exam_task_viewed',
  reading_exam_answer_selected: 'reading_exam_answer_selected',
  reading_exam_answer_submitted: 'reading_exam_answer_submitted',
  reading_exam_result_viewed: 'reading_exam_result_viewed',
  reading_exam_next_clicked: 'reading_exam_next_clicked',
  reading_exam_training_session_completed: 'reading_exam_training_session_completed',
  /** KMN exam prep — society knowledge (quiz, SRS flashcards, scenarios) */
  kmn_home_viewed: 'kmn_home_viewed',
  kmn_topic_viewed: 'kmn_topic_viewed',
  kmn_quiz_started: 'kmn_quiz_started',
  kmn_quiz_answered: 'kmn_quiz_answered',
  kmn_flashcard_session_started: 'kmn_flashcard_session_started',
  kmn_flashcard_reviewed: 'kmn_flashcard_reviewed',
  kmn_scenario_started: 'kmn_scenario_started',
  kmn_scenario_completed: 'kmn_scenario_completed',
  kmn_mistake_made: 'kmn_mistake_made',
  kmn_mastery_updated: 'kmn_mastery_updated',
  /** Exam prep → review / weakness learning loop */
  exam_mistakes_extracted: 'exam_mistakes_extracted',
  exam_review_items_generated: 'exam_review_items_generated',
  exam_weakness_updated: 'exam_weakness_updated',
  exam_signal_deduped: 'exam_signal_deduped',
  exam_next_practice_recommended: 'exam_next_practice_recommended',
  exam_recommendation_generated: 'exam_recommendation_generated',
  exam_recommendation_shown: 'exam_recommendation_shown',
  exam_recommendation_clicked: 'exam_recommendation_clicked',
  /** Exam readiness layer (overall + per-module; not official pass prediction) */
  exam_readiness_viewed: 'exam_readiness_viewed',
  exam_readiness_state_changed: 'exam_readiness_state_changed',
  exam_readiness_recommendation_clicked: 'exam_readiness_recommendation_clicked',
  pass_likelihood_viewed: 'pass_likelihood_viewed',
  weak_category_viewed: 'weak_category_viewed',
  exam_module_ready_state_viewed: 'exam_module_ready_state_viewed',
  /** Fixed practice exams (mock exams per type) */
  practice_exam_set_viewed: 'practice_exam_set_viewed',
  practice_exam_started: 'practice_exam_started',
  practice_exam_completed: 'practice_exam_completed',
  practice_exam_abandoned: 'practice_exam_abandoned',
  practice_exam_result_viewed: 'practice_exam_result_viewed',
  practice_exam_retake_started: 'practice_exam_retake_started',
  practice_exam_compare_viewed: 'practice_exam_compare_viewed',
  listening_completed: 'listening_completed',
  pronunciation_feedback_viewed: 'pronunciation_feedback_viewed',
  // FD-08 Smart Prompts
  smart_prompt_intro_viewed: 'smart_prompt_intro_viewed',
  smart_prompt_enable_clicked: 'smart_prompt_enable_clicked',
  location_permission_requested: 'location_permission_requested',
  location_permission_granted: 'location_permission_granted',
  location_permission_denied: 'location_permission_denied',
  smart_prompt_viewed: 'smart_prompt_viewed',
  smart_prompt_saved: 'smart_prompt_saved',
  smart_prompt_dismissed: 'smart_prompt_dismissed',
  smart_prompt_practice_clicked: 'smart_prompt_practice_clicked',
  smart_prompt_settings_updated: 'smart_prompt_settings_updated',
  smart_prompt_premium_cta_clicked: 'smart_prompt_premium_cta_clicked',
  // FD-09 Daily Life Lessons
  daily_lesson_intro_viewed: 'daily_lesson_intro_viewed',
  daily_lesson_enable_clicked: 'daily_lesson_enable_clicked',
  daily_lesson_permission_requested: 'daily_lesson_permission_requested',
  daily_lesson_permission_granted: 'daily_lesson_permission_granted',
  daily_lesson_manual_capture_started: 'daily_lesson_manual_capture_started',
  daily_lesson_manual_capture_saved: 'daily_lesson_manual_capture_saved',
  daily_lesson_generation_requested: 'daily_lesson_generation_requested',
  daily_lesson_generation_succeeded: 'daily_lesson_generation_succeeded',
  daily_lesson_generation_failed: 'daily_lesson_generation_failed',
  daily_lesson_opened: 'daily_lesson_opened',
  daily_lesson_completed: 'daily_lesson_completed',
  daily_lesson_history_opened: 'daily_lesson_history_opened',
  daily_lesson_delete_history_clicked: 'daily_lesson_delete_history_clicked',
  daily_lesson_premium_cta_clicked: 'daily_lesson_premium_cta_clicked',
  /** Schema-driven lesson player (vertical slice) */
  schema_lesson_step_started: 'schema_lesson_step_started',
  schema_lesson_step_completed: 'schema_lesson_step_completed',
  schema_lesson_answer_correct: 'schema_lesson_answer_correct',
  schema_lesson_answer_incorrect: 'schema_lesson_answer_incorrect',
  schema_lesson_hint_used: 'schema_lesson_hint_used',
  schema_lesson_speaking_attempt: 'schema_lesson_speaking_attempt',
  schema_lesson_completed: 'schema_lesson_completed',
  /** Stage 4 review engine */
  review_session_started: 'review_session_started',
  review_session_completed: 'review_session_completed',
  review_card_started: 'review_card_started',
  /** Alias for product taxonomy “answer_submitted”. */
  review_answer_submitted: 'review_answer_submitted',
  review_card_answered: 'review_card_answered',
  review_answer_correct: 'review_answer_correct',
  review_answer_incorrect: 'review_answer_incorrect',
  review_card_failed: 'review_card_failed',
  review_card_completed: 'review_card_completed',
  review_card_recovered: 'review_card_recovered',
  review_hint_used: 'review_hint_used',
  streak_extended: 'streak_extended',
  streak_updated: 'streak_updated',
  streak_milestone_reached: 'streak_milestone_reached',
  mastery_improved: 'mastery_improved',
  /** Retention / gamification layer */
  xp_awarded: 'xp_awarded',
  review_card_shown: 'review_card_shown',
  review_started: 'review_started',
  review_completed: 'review_completed',
  fix_mistakes_shown: 'fix_mistakes_shown',
  fix_mistakes_started: 'fix_mistakes_started',
  fix_mistakes_completed: 'fix_mistakes_completed',
  ability_unlocked: 'ability_unlocked',
  module_unlocked: 'module_unlocked',
  module_completed: 'module_completed',
  stage_unlocked: 'stage_unlocked',
  milestone_viewed: 'milestone_viewed',
  continue_learning_clicked: 'continue_learning_clicked',
  dashboard_card_clicked: 'dashboard_card_clicked',
  leaderboard_viewed: 'leaderboard_viewed',
  /** Daily / weekly practice missions */
  mission_assigned: 'mission_assigned',
  mission_viewed: 'mission_viewed',
  mission_started: 'mission_started',
  mission_replay_clicked: 'mission_replay_clicked',
  mission_progressed: 'mission_progressed',
  mission_completed: 'mission_completed',
  mission_reward_claimed: 'mission_reward_claimed',
  weekly_mission_completed: 'weekly_mission_completed',
  /** Exam prep missions (extends daily / weekly / skill-focus slots) */
  exam_mission_generated: 'exam_mission_generated',
  exam_mission_shown: 'exam_mission_shown',
  exam_mission_started: 'exam_mission_started',
  exam_mission_progressed: 'exam_mission_progressed',
  exam_mission_completed: 'exam_mission_completed',
  exam_mission_reward_granted: 'exam_mission_reward_granted',
  scenario_streak_updated: 'scenario_streak_updated',
  skill_mission_completed: 'skill_mission_completed',
  /** Practice ↔ retention integration */
  practice_session_completed: 'practice_session_completed',
  practice_xp_awarded: 'practice_xp_awarded',
  practice_streak_applied: 'practice_streak_applied',
  streak_extended_by_practice: 'streak_extended_by_practice',
  practice_unlock_earned: 'practice_unlock_earned',
  practice_ability_upgraded: 'practice_ability_upgraded',
  ability_state_changed: 'ability_state_changed',
  practice_milestone_reached: 'practice_milestone_reached',
  practice_reward_shown: 'practice_reward_shown',
  practice_reward_cta_clicked: 'practice_reward_cta_clicked',
  /** Exam prep → retention / motivation loop */
  exam_xp_awarded: 'exam_xp_awarded',
  exam_streak_extended: 'exam_streak_extended',
  exam_badge_earned: 'exam_badge_earned',
  exam_improvement_bonus_awarded: 'exam_improvement_bonus_awarded',
  exam_reward_shown: 'exam_reward_shown',
  exam_reward_clicked: 'exam_reward_clicked',
  exam_pass_milestone_reached: 'exam_pass_milestone_reached',
  exam_readiness_milestone_reached: 'exam_readiness_milestone_reached',
  ...LEARNING_INTELLIGENCE_EVENTS,
  /** Post-A2 continuation (after A2 path complete) */
  post_a2_transition_viewed: 'post_a2_transition_viewed',
  post_a2_pathways_viewed: 'post_a2_pathways_viewed',
  post_a2_recommendation_shown: 'post_a2_recommendation_shown',
  post_a2_option_selected: 'post_a2_option_selected',
  post_a2_option_changed: 'post_a2_option_changed',
  post_a2_path_routed: 'post_a2_path_routed',
  post_a2_home_surface_updated: 'post_a2_home_surface_updated',
  post_a2_banner_clicked: 'post_a2_banner_clicked',
  /** Dashboard — primary next action CTA */
  dashboard_next_action_clicked: 'dashboard_next_action_clicked',
  /** Practice hub — Do / Improve / Explore mode switcher */
  practice_mode_changed: 'practice_mode_changed',
  /** Public marketing site (pre-auth) */
  public_page_viewed: 'public_page_viewed',
  pricing_viewed: 'pricing_viewed',
  exam_prep_page_viewed: 'exam_prep_page_viewed',
  beta_page_viewed: 'beta_page_viewed',
  login_page_viewed: 'login_page_viewed',
  sign_in_clicked: 'sign_in_clicked',
  waitlist_clicked: 'waitlist_clicked',
  mailto_triggered: 'mailto_triggered',
  pricing_cta_clicked: 'pricing_cta_clicked',
  plan_card_viewed: 'plan_card_viewed',
  signup_disabled_clicked: 'signup_disabled_clicked',
  waitlist_cta_viewed: 'waitlist_cta_viewed',
  waitlist_cta_clicked: 'waitlist_cta_clicked',
  waitlist_mailto_triggered: 'waitlist_mailto_triggered',
  beta_request_form_viewed: 'beta_request_form_viewed',
  beta_request_submitted: 'beta_request_submitted',
  beta_request_succeeded: 'beta_request_succeeded',
  beta_request_failed: 'beta_request_failed',
  contact_form_viewed: 'contact_form_viewed',
  contact_form_submitted: 'contact_form_submitted',
  contact_form_succeeded: 'contact_form_succeeded',
  contact_form_failed: 'contact_form_failed',
  public_hero_cta_clicked: 'public_hero_cta_clicked',
  /** Plan snapshot for Basic vs Premium funnel analysis (no PII). */
  plan_context_on_login: 'plan_context_on_login',
  plan_context_on_onboarding_complete: 'plan_context_on_onboarding_complete',
  plan_context_on_start_route: 'plan_context_on_start_route',
  /** User landed on the post-onboarding destination (handoff banner). */
  onboarding_start_route_entered: 'onboarding_start_route_entered',
  /** Mock closed-beta auth lifecycle */
  login_attempted: 'login_attempted',
  login_succeeded: 'login_succeeded',
  login_failed: 'login_failed',
  logout_clicked: 'logout_clicked',
  session_restored: 'session_restored',
  session_restore_failed: 'session_restore_failed',
  /** Route guards + layout */
  route_guard_redirected_to_login: 'route_guard_redirected_to_login',
  route_guard_redirected_to_app: 'route_guard_redirected_to_app',
  auth_only_page_redirected: 'auth_only_page_redirected',
  session_bootstrap_started: 'session_bootstrap_started',
  session_bootstrap_completed: 'session_bootstrap_completed',
  /** Account bootstrap (profile + progress + onboarding resolution) */
  bootstrap_started: 'bootstrap_started',
  bootstrap_completed: 'bootstrap_completed',
  profile_initialized: 'profile_initialized',
  profile_loaded: 'profile_loaded',
  /** Learner profile document persisted (stable layer; not progress). */
  profile_updated: 'profile_updated',
  selected_pathway_updated: 'selected_pathway_updated',
  onboarding_completion_state_changed: 'onboarding_completion_state_changed',
  plan_state_loaded: 'plan_state_loaded',
  progress_initialized: 'progress_initialized',
  progress_loaded: 'progress_loaded',
  /** Mutable learner progress aggregate refreshed or domain updated. */
  progress_updated: 'progress_updated',
  user_progress_hydrated: 'user_progress_hydrated',
  user_progress_switched: 'user_progress_switched',
  /** First device-local cold start for a beta user (empty slate). */
  first_login_cold_start: 'first_login_cold_start',
  returning_user_detected: 'returning_user_detected',
  new_user_routed_to_onboarding: 'new_user_routed_to_onboarding',
  onboarding_routed: 'onboarding_routed',
  app_home_routed: 'app_home_routed',
  bootstrap_recovery_triggered: 'bootstrap_recovery_triggered',
  /** Incremental persistence pipeline (beta diagnostics). */
  incremental_save_triggered: 'incremental_save_triggered',
  incremental_save_completed: 'incremental_save_completed',
  incremental_save_failed: 'incremental_save_failed',
  /** Long-form / session draft autosave (debounced); complements incremental milestone saves. */
  autosave_triggered: 'autosave_triggered',
  autosave_completed: 'autosave_completed',
  autosave_restored: 'autosave_restored',
  autosave_discarded: 'autosave_discarded',
  autosave_failed: 'autosave_failed',
  /** Resume / “continue where you left off” layer (explicit CTAs + routing) */
  resumable_flow_detected: 'resumable_flow_detected',
  resume_cta_shown: 'resume_cta_shown',
  resume_cta_clicked: 'resume_cta_clicked',
  resume_restarted: 'resume_restarted',
  stale_resume_discarded: 'stale_resume_discarded',
  /** Onboarding continuation (guard or explicit CTA) */
  onboarding_resume_forced: 'onboarding_resume_forced',
  lesson_resume_started: 'lesson_resume_started',
  simulation_resume_started: 'simulation_resume_started',
  /** Account / settings (closed beta) */
  account_settings_viewed: 'account_settings_viewed',
  sign_out_clicked: 'sign_out_clicked',
  reset_progress_clicked: 'reset_progress_clicked',
  reset_progress_confirmed: 'reset_progress_confirmed',
  pricing_from_account_clicked: 'pricing_from_account_clicked',
} as const

export type AnalyticsEvent = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS]

export function track(event: AnalyticsEvent, properties?: Record<string, unknown>) {
  emitAnalyticsEvent(event, properties ?? {})
}

/** Advanced: direct dispatch, same envelope as `track`. */
export { emitAnalyticsEvent, setAnalyticsSink } from '@/lib/analytics/analyticsService'
export { getOrCreateAnalyticsSession } from '@/lib/analytics/analyticsSession'
export { buildAnalyticsBaseContext } from '@/lib/analytics/analyticsContextBuilder'
export { categoryForEvent, ANALYTICS_EVENT_CATEGORY } from '@/lib/analytics/eventCategories'
export {
  trackScenarioAbandoned,
  trackScenarioViewed,
  trackScenarioFirstResponse,
  trackScenarioStarted,
  trackScenarioCompleted,
} from '@/lib/analytics/practiceScenarioAnalytics'
export { learningIntelligenceBase, type LearningModuleKey, type LearningSurfaceKey } from '@/lib/analytics/analyticsTypes'
export {
  trackLearningUnitStarted,
  trackLearningUnitCompleted,
  trackLearningUnitAbandoned,
  trackLearningStepStarted,
  trackLearningStepCompleted,
  trackLearningStepAbandoned,
  trackInputModalitySwitched,
} from '@/lib/analytics/learningFlowAnalytics'
export { trackLearningScoreProgress } from '@/lib/analytics/learningScoreAnalytics'
export {
  normalizeMockLoginFailureReason,
  trackLoginAttempted,
  trackLoginSucceeded,
  trackLoginFailed,
} from '@/lib/analytics/authAnalytics'
export {
  trackWaitlistCtaViewed,
  trackWaitlistCtaClicked,
  trackWaitlistMailtoTriggered,
  trackSignupDisabledClicked,
  trackBetaRequestFormViewed,
  trackBetaRequestSubmitted,
  trackBetaRequestSucceeded,
  trackBetaRequestFailed,
  trackPublicHeroCtaClicked,
  type WaitlistSignedInState,
} from '@/lib/analytics/waitlistAnalytics'
export {
  trackContactFormViewed,
  trackContactFormSubmitted,
  trackContactFormSucceeded,
  trackContactFormFailed,
} from '@/lib/analytics/supportContactAnalytics'
export {
  getSignedInPlanContext,
  trackPremiumFeatureLockedForBasicUser,
} from '@/lib/analytics/planAnalytics'
export {
  trackOnboardingStepViewed,
  trackOnboardingStepCompleted,
  trackOnboardingAbandoned,
} from '@/lib/analytics/onboardingFunnelAnalytics'
export { trackBetaPageViewed } from '@/lib/analytics/betaFunnelAnalytics'
export type {
  LoginSurface,
  LoginFailureReason,
  UserPlanAnalytics,
  OnboardingSessionSource,
  OnboardingAbandonReason,
  UserStateTypeBootstrap,
} from '@/lib/analytics/funnelAnalyticsTypes'
export { trackExamPrepUnitStarted, trackExamPrepUnitCompleted } from '@/lib/analytics/examAnalytics'
export {
  trackPracticeHubRecommendationShown,
  trackPracticeHubRecommendationClicked,
} from '@/lib/analytics/practiceAnalytics'
export { trackLearningLoopStage, type LearningLoopStage } from '@/lib/analytics/learningLoopAnalytics'
export { trackReadinessBandTransition } from '@/lib/analytics/readinessAnalytics'
