import { defineConfig } from 'vitest/config'
import path from 'node:path'

export default defineConfig({
  test: {
    include: [
      'src/content-engine/tests/**/*.test.ts',
      'src/ai-conversation-engine/tests/**/*.test.ts',
      'src/personalization-engine/tests/**/*.test.ts',
      'src/lib/lesson-engine/**/*.test.ts',
      'src/lib/review-engine/**/*.test.ts',
      'src/lib/listening-mode/**/*.test.ts',
      'src/lib/practice/**/*.test.ts',
      'src/lib/practice-orchestration/__tests__/**/*.test.ts',
      'src/lib/exam-scoring/**/*.test.ts',
      'src/lib/exam-prep/**/*.test.ts',
      'src/lib/auth/**/*.test.ts',
      'src/lib/api/**/*.test.ts',
      'src/lib/speech/**/*.test.ts',
      'src/lib/speaking/**/*.test.ts',
      'backend/src/services/ai/**/*.test.ts',
      'backend/src/domain/speakLive/**/*.test.ts',
      'backend/src/domain/speaking-assessment/**/*.test.ts',
      'backend/src/services/speaking-assessment/**/*.test.ts',
      'backend/src/services/speech/**/*.test.ts',
      'backend/src/services/speak-live/**/*.test.ts',
      'backend/src/services/language-coach/**/*.test.ts',
      'backend/src/services/learning-memory/**/*.test.ts',
      'backend/src/services/skills/**/*.test.ts',
      'backend/src/domain/learningMemory/**/*.test.ts',
      'backend/src/domain/generatedExercisePack/**/*.test.ts',
      'backend/src/domain/skills/**/*.test.ts',
      'backend/src/domain/trainingLoops/**/*.test.ts',
      'backend/src/services/training-loops/**/*.test.ts',
      'backend/src/services/listening/**/*.test.ts',
      'backend/src/domain/listening/**/*.test.ts',
      'backend/src/domain/exam/**/*.test.ts',
      'src/features/speak-live/live/**/*.test.ts',
      'src/features/speak-live/evaluation/__tests__/**/*.test.ts',
      'src/features/speak-live/evaluation/__tests__/**/*.test.tsx',
      'src/components/report/**/*.test.ts',
      'src/features/talk/**/*.test.ts',
      'src/features/practice-hub/**/*.test.ts',
      'src/features/skills/**/*.test.ts',
      'src/lib/progression/**/*.test.ts',
      'src/lib/exam-system/**/*.test.ts',
      'src/features/library/capture/**/*.test.ts',
      'src/features/quick-capture/**/*.test.ts',
      'src/store/**/*.test.ts',
      'backend/src/services/quick-capture/**/*.test.ts',
      'backend/src/services/generated-exercise-packs/**/*.test.ts',
      'backend/src/services/storage/**/*.test.ts',
    ],
    environment: 'node',
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
})
