from .common import (
    LM,
    MID,
    discovery_step,
    fb,
    listening_step,
    mcq,
    pl,
    preview_step,
    recap_step,
    ro_tokens,
    rt_fb,
    rt_listen_mcq,
    rt_ro,
    rt_speak,
    scenario_chat_step,
    speak_step,
)


def lesson_l09() -> dict:
    lid = "a2-m08-l09-task-make-appointment-guided"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Real-life task · Make an appointment (guided)",
        "lessonType": "task",
        "order": 8,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-admin-appointments", "a2.2-admin-formal-u"],
        "vocabTargets": ["lemma-afspraak-m8", "lemma-gemeente", "lemma-inschrijven", "lemma-paspoort-m8", "lemma-document"],
        "canDoStatements": ["I can complete a guided flow to request a gemeente-style appointment with polite phrases."],
        "mistakeFocus": ["formal-tone", "practical-phrases"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m08-l09-preview",
                "Warm-up — 5 woorden",
                [
                    ("bellen", "bellen", "to call", "📞"),
                    ("online", "online", "online", "💻"),
                    ("beschikbaar", "beschikbaar", "available", "📅"),
                    ("volgende week", "week", "next week", "📆"),
                    ("bevestigen", "bevestigen", "to confirm", "✔️"),
                ],
            ),
            listening_step(
                "m08-l09-listen",
                "Model — telefoon (kort)",
                [
                    (
                        "Medewerker",
                        "Gemeente Rotterdam, goedemiddag.",
                        "Rotterdam municipality, good afternoon.",
                    ),
                    (
                        "Jij",
                        "Goedemiddag. Ik wil graag een afspraak maken voor mijn inschrijving.",
                        "Good afternoon. I'd like to make an appointment for my registration.",
                    ),
                    (
                        "Medewerker",
                        "Prima. Wanneer heeft u tijd? Volgende week dinsdag om tien uur?",
                        "Fine. When do you have time? Next Tuesday at ten o'clock?",
                    ),
                    (
                        "Jij",
                        "Ja, dat is goed. Kunt u dat bevestigen per e-mail?",
                        "Yes, that's fine. Could you confirm that by email?",
                    ),
                    (
                        "Medewerker",
                        "Natuurlijk. Wat is uw e-mailadres?",
                        "Of course. What is your email address?",
                    ),
                ],
                [
                    ("Waar bel je?", ["Gemeente", "Pizzeria", "Trein"], "Gemeente"),
                    ("Wat wil je?", ["Afspraak inschrijving", "Nieuwe fiets", "Zwemles"],
                        "Afspraak inschrijving"),
                    ("Welke dag noemt de medewerker?", ["Dinsdag tien uur", "Zondag middernacht", "Geen dag"],
                        "Dinsdag tien uur"),
                    ("Wat vraag je over bevestiging?", ["Per e-mail", "Per brief zonder mail", "Geen bevestiging"],
                        "Per e-mail"),
                    ("Wat vraagt de medewerker op het eind?", ["E-mailadres", "Favoriete kleur", "Huisdiernaam"],
                        "E-mailadres"),
                ],
            ),
            scenario_chat_step(
                "m08-l09-chat",
                "Mini-sim — kies je antwoord",
                [
                    (
                        "Medewerker",
                        "Goedemorgen. Waarvoor wilt u een afspraak?",
                        "Good morning. What do you want an appointment for?",
                    ),
                    (
                        "Jij (kies)",
                        "Ik wil graag een afspraak voor een nieuw identiteitsbewijs.",
                        "I'd like an appointment for a new ID card.",
                    ),
                    (
                        "Medewerker",
                        "Heeft u uw oude identiteitsbewijs en een pasfoto bij u?",
                        "Do you have your old ID card and a passport photo with you?",
                    ),
                    (
                        "Jij (kies)",
                        "Ja, ik heb beide documenten bij me.",
                        "Yes, I have both documents with me.",
                    ),
                    (
                        "Medewerker",
                        "Mooi. Ik plan u in op woensdag om 14:15. U ontvangt een bevestiging.",
                        "Good. I'll schedule you for Wednesday at 14:15. You'll receive a confirmation.",
                    ),
                    (
                        "Jij (kies)",
                        "Dank u wel. Wat moet ik nog meenemen?",
                        "Thank you. What else do I have to bring?",
                    ),
                    (
                        "Medewerker",
                        "Neem ook uw bankpas voor betaling mee, alstublieft.",
                        "Please also bring your bank card for payment.",
                    ),
                ],
                [
                    ("Waarvoor is de afspraak?", ["Nieuw identiteitsbewijs", "Rijbewijs zonder aanvraag", "Paspoort voor de kat"],
                        "Nieuw identiteitsbewijs"),
                    ("Wat vraagt de medewerker over documenten?", ["Oud ID + pasfoto", "Alleen een brief zonder foto", "Geen documenten"],
                        "Oud ID + pasfoto"),
                    ("Wanneer is de afspraak?", ["Woensdag 14:15", "Donderdag 04:00", "Zonder tijd"],
                        "Woensdag 14:15"),
                    ("Wat moet je extra meenemen?", ["Bankpas voor betaling", "Een plant", "Een boek zonder kaft"],
                        "Bankpas voor betaling"),
                    ("Welke zin is beleefd?", ["Dank u wel. Wat moet ik nog meenemen?", "Geef nu antwoord.", "Dank meenemen wat?"],
                        "Dank u wel. Wat moet ik nog meenemen?"),
                ],
            ),
            discovery_step(
                "m08-l09-discovery",
                "Vaste zinnen",
                [
                    ("Ik wil graag een afspraak maken voor …", "I'd like to make an appointment for …", "doel"),
                    ("Wanneer heeft u tijd?", "When do you have time?", "planning"),
                    ("Kunt u dat bevestigen?", "Could you confirm that?", "check"),
                    ("Wat moet ik meenemen?", "What do I have to bring?", "documenten"),
                ],
            ),
            pl(
                "m08-l09-pl1",
                "Practice — 6×",
                ["afspraak", "bevestiging", "email"],
                [
                    mcq(
                        "m08-l09-a1",
                        "Openingszin telefoon",
                        ["Goedemiddag, ik wil graag een afspraak maken.", "Hoi, geef nu een tijd.", "Afspraak wil ik zonder hallo."],
                        "Goedemiddag, ik wil graag een afspraak maken.",
                    ),
                    fb("m08-l09-a2", "Kunt u dat ___ per e-mail? (confirm)", ["bevestigen", "vergeten", "breken"], "bevestigen"),
                    ro_tokens("m08-l09-r1", ["tijd?", "heeft", "u", "Wanneer"], "Wanneer heeft u tijd?"),
                    mcq(
                        "m08-l09-a3",
                        "Als de tijd niet uitkomt",
                        ["Helaas, die tijd gaat niet. Heeft u misschien een andere mogelijkheid?", "Helaas, ik wil nooit een afspraak.", "Die tijd kan helaas niet zonder vraag."],
                        "Helaas, die tijd gaat niet. Heeft u misschien een andere mogelijkheid?",
                    ),
                    mcq(
                        "m08-l09-a4",
                        "Formeel slot",
                        ["Dank u wel voor uw hulp.", "Dag, ik hang op.", "Dank hulp zonder u."],
                        "Dank u wel voor uw hulp.",
                    ),
                    mcq(
                        "m08-l09-a5",
                        "Check: inschrijven",
                        ["Ik moet me inschrijven in deze gemeente.", "Ik moet me inschrijven in de supermarkt.", "Inschrijven moet ik zonder gemeente."],
                        "Ik moet me inschrijven in deze gemeente.",
                    ),
                    mcq(
                        "m08-l09-a6",
                        "Online vs balie (A2)",
                        ["Soms kunt u online plannen; soms moet u bellen.", "Altijd zonder afspraak binnenlopen", "Nooit online"],
                        "Soms kunt u online plannen; soms moet u bellen.",
                    ),
                ],
                depth=True,
            ),
            pl(
                "m08-l09-pl2",
                "Variatie — 6×",
                ["document", "paspoort", "betaling"],
                [
                    mcq(
                        "m08-l09-b1",
                        "Vraag over kosten",
                        ["Hoeveel kost het ongeveer?", "Hoeveel kost uw lunch?", "Kost het hoeveel zonder vraag?"],
                        "Hoeveel kost het ongeveer?",
                    ),
                    fb("m08-l09-b2", "Neem uw ___ en uw formulier mee. (travel ID)", ["paspoort", "brood", "jas"], "paspoort"),
                    ro_tokens("m08-l09-r2", ["maken.", "afspraak", "een", "graag", "wil", "Ik"], "Ik wil graag een afspraak maken."),
                    mcq(
                        "m08-l09-b3",
                        "Juiste zin",
                        ["Kunt u mij helpen?", "Kunt mij u helpen?", "Helpen kunt u mij?"],
                        "Kunt u mij helpen?",
                    ),
                    mcq(
                        "m08-l09-b4",
                        "Als je de datum niet hoort",
                        ["Kunt u de datum nog een keer zeggen?", "Kunt u de datum vergeten?", "Datum de zeggen kunt?"],
                        "Kunt u de datum nog een keer zeggen?",
                    ),
                    mcq(
                        "m08-l09-b5",
                        "Praktisch",
                        ["Ik noteer de tijd in mijn agenda.", "Ik noteer de tijd nergens.", "Agenda zonder tijd."],
                        "Ik noteer de tijd in mijn agenda.",
                    ),
                    mcq(
                        "m08-l09-b6",
                        "Laatste check",
                        ["Klopt mijn naam zo op de uitnodiging?", "Klopt mijn naam zonder uitnodiging?", "Naam klopt mijn?"],
                        "Klopt mijn naam zo op de uitnodiging?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m08-l09-sp1",
                "Jouw beurt",
                "Goedemiddag. Ik wil graag een afspraak maken voor mijn inschrijving.",
                [
                    "Goedemiddag ik wil graag een afspraak maken voor mijn inschrijving",
                    "Goedemiddag. Ik wil graag een afspraak maken voor mijn inschrijving.",
                ],
                "Goedemiddag ik wil graag een afspraak maken voor mijn inschrijving",
            ),
            speak_step(
                "m08-l09-sp2",
                "Vervolg",
                "Wanneer heeft u tijd volgende week?",
                ["Wanneer heeft u tijd volgende week", "wanneer heeft u tijd volgende week"],
                "Wanneer heeft u tijd volgende week",
            ),
            speak_step(
                "m08-l09-sp3",
                "Bevestiging",
                "Kunt u dat bevestigen per e-mail, alstublieft?",
                [
                    "Kunt u dat bevestigen per e-mail alstublieft",
                    "Kunt u dat bevestigen per e-mail, alstublieft?",
                ],
                "Kunt u dat bevestigen per e-mail alstublieft",
            ),
            speak_step(
                "m08-l09-sp4",
                "Afsluiten",
                "Dank u wel voor uw hulp. Tot ziens.",
                ["Dank u wel voor uw hulp tot ziens", "Dank u wel voor uw hulp. Tot ziens."],
                "Dank u wel voor uw hulp tot ziens",
            ),
            recap_step(
                "m08-l09-recap",
                "Recap",
                ["afspraak", "bevestigen", "document"],
                [
                    rt_fb("Ik wil graag een ___ maken. (appointment)", ["afspraak", "broodje", "feest"], "afspraak"),
                    rt_ro(["mee?", "moet", "Wat", "ik", "nog", "nemen"], "Wat moet ik nog meenemen?"),
                    rt_speak("Zeg: *Kunt u dat herhalen?*", "Kunt u dat herhalen?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Neem ook uw bankpas voor betaling mee, alstublieft.",
                        ["Extra meenemen", "Geen betaling", "Gratis zonder pas"],
                        "Extra meenemen",
                    ),
                    rt_fb("___ u dat per e-mail bevestigen? (could)", ["Kunt", "Eet", "Zwemt"], "Kunt"),
                    rt_speak("Zeg: *Ik heb een afspraak.*", "Ik heb een afspraak."),
                    rt_speak("Zeg: *Wanneer heeft u tijd?*", "Wanneer heeft u tijd?"),
                ],
            ),
        ],
    }


def lesson_l10() -> dict:
    lid = "a2-m08-l10-task-attend-appointment-simulation"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Real-life task · Attend an appointment (simulation)",
        "lessonType": "task",
        "order": 9,
        "cefrLevel": "A2",
        "durationEstimate": 17,
        "grammarTargets": ["a2.2-admin-personal-details", "a2.2-admin-instructions"],
        "vocabTargets": ["lemma-balie", "lemma-identiteitsbewijs", "lemma-handtekening", "lemma-formulier", "lemma-wachten-m8"],
        "canDoStatements": ["I can follow a short appointment simulation: check-in, questions, documents, signing."],
        "mistakeFocus": ["listening-gist", "instructions"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m08-l10-preview",
                "Warm-up — 4 woorden",
                [
                    ("check-in", "check-in", "check-in", "✅"),
                    ("loket", "loket", "window / desk", "🪟"),
                    ("procedure", "procedure", "procedure", "📋"),
                    ("volgende stap", "stap", "next step", "➡️"),
                ],
            ),
            scenario_chat_step(
                "m08-l10-chat",
                "Sim — bij binnenkomst",
                [
                    (
                        "Medewerker",
                        "Goedemiddag. U heeft een afspraak om half twee, klopt dat?",
                        "Good afternoon. You have an appointment at half past one, is that correct?",
                    ),
                    (
                        "Jij (kies)",
                        "Ja, dat klopt. Mijn naam is Ines Costa.",
                        "Yes, that's correct. My name is Ines Costa.",
                    ),
                    (
                        "Medewerker",
                        "Mooi. Mag ik uw paspoort en het ingevulde formulier zien?",
                        "Good. May I see your passport and the completed form?",
                    ),
                    (
                        "Jij (kies)",
                        "Ja, alstublieft. Hier zijn ze.",
                        "Yes, please. Here they are.",
                    ),
                    (
                        "Medewerker",
                        "Dank u. Mag ik uw geboortedatum nog even bevestigen?",
                        "Thank you. May I just confirm your date of birth?",
                    ),
                    (
                        "Jij (kies)",
                        "Die is 15 mei 1988.",
                        "It's 15 May 1988.",
                    ),
                    (
                        "Medewerker",
                        "Dank u. Gaat u even zitten? Ik kom zo bij u.",
                        "Thank you. Could you sit down for a moment? I'll come to you shortly.",
                    ),
                ],
                [
                    ("Wat checkt de medewerker eerst?", ["Of de afspraaktijd klopt", "Of u pizza bestelde", "Of u zonder naam bent"],
                        "Of de afspraaktijd klopt"),
                    ("Welke naam geeft de klant?", ["Ines Costa", "Ines Pizza", "Anna Jansen"],
                        "Ines Costa"),
                    ("Welke documenten wil de medewerker zien?", ["Paspoort + ingevuld formulier", "Alleen een foto", "Geen documenten"],
                        "Paspoort + ingevuld formulier"),
                    ("Welke geboortedatum geeft de klant?", ["15 mei 1988", "3 maart 1999", "Geen datum"],
                        "15 mei 1988"),
                    ("Wat moet de klant daarna doen?", ["Even gaan zitten en wachten", "Direct naar huis", "Hard rennen"],
                        "Even gaan zitten en wachten"),
                ],
            ),
            listening_step(
                "m08-l10-listen",
                "Input — aan tafel",
                [
                    (
                        "Medewerker",
                        "Dank u voor uw geduld. Ik heb uw gegevens gecontroleerd. Alles is compleet.",
                        "Thank you for your patience. I've checked your details. Everything is complete.",
                    ),
                    (
                        "Jij",
                        "Fijn. Wat is de volgende stap?",
                        "Good. What's the next step?",
                    ),
                    (
                        "Medewerker",
                        "U ontvangt binnen vijf werkdagen een brief thuis. Teken hier nog even voor ontvangst.",
                        "You'll receive a letter at home within five working days. Please sign here for receipt.",
                    ),
                    (
                        "Jij",
                        "Oké. Moet ik nog iets doen online?",
                        "Okay. Do I still have to do something online?",
                    ),
                    (
                        "Medewerker",
                        "Nee, voor nu niet. Heeft u verder nog vragen?",
                        "No, not for now. Do you have any other questions?",
                    ),
                    (
                        "Jij",
                        "Nee, dank u wel. Fijne dag.",
                        "No, thank you. Have a nice day.",
                    ),
                ],
                [
                    ("Zijn de gegevens oké?", ["Ja, alles compleet", "Nee, zonder controle", "Onbekend"],
                        "Ja, alles compleet"),
                    ("Wat gebeurt er daarna?", ["Brief binnen 5 werkdagen", "Direct paspoort zonder brief", "Geen post"],
                        "Brief binnen 5 werkdagen"),
                    ("Wat moet je nog doen bij de tafel?", ["Tekenen voor ontvangst", "Zingen", "Zwemmen"],
                        "Tekenen voor ontvangst"),
                    ("Moet je nu nog online iets doen?", ["Nee, voor nu niet", "Ja, altijd 10 uur", "Alleen gamen"],
                        "Nee, voor nu niet"),
                    ("Hoe eindigt het gesprek?", ["Beleefd dank + fijne dag", "Zonder dank", "Boos weglopen"],
                        "Beleefd dank + fijne dag"),
                ],
            ),
            discovery_step(
                "m08-l10-discovery",
                "Taal voor ‘even wachten’",
                [
                    ("Gaat u even zitten?", "Could you sit for a moment?", "wachten"),
                    ("Dank u voor uw geduld.", "Thank you for your patience.", "rust"),
                    ("Wat is de volgende stap?", "What's the next step?", "vervolg"),
                    ("Heeft u verder nog vragen?", "Do you have any other questions?", "check"),
                ],
            ),
            pl(
                "m08-l10-pl1",
                "Practice — 6×",
                ["ondertekenen", "brief", "werkdag"],
                [
                    mcq(
                        "m08-l10-a1",
                        "Werkdagen (simpel)",
                        ["Maandag t/m vrijdag (meestal)", "Alleen zondag", "Elke dag zonder uitzondering"],
                        "Maandag t/m vrijdag (meestal)",
                    ),
                    fb("m08-l10-a2", "Ik ontvang een ___ thuis. (letter)", ["brief", "pizza", "kat"], "brief"),
                    ro_tokens("m08-l10-r1", ["stap?", "de", "volgende", "Wat", "is"], "Wat is de volgende stap?"),
                    mcq(
                        "m08-l10-a3",
                        "Als je stress voelt",
                        ["Dat is normaal. Vraag rustig om herhaling.", "Je mag niet praten.", "Zwijgen is verplicht."],
                        "Dat is normaal. Vraag rustig om herhaling.",
                    ),
                    mcq(
                        "m08-l10-a4",
                        "‘Compleet’ hier",
                        ["Alle benodigde stukken zijn er", "Er mist alles", "Geen formulier"],
                        "Alle benodigde stukken zijn er",
                    ),
                    mcq(
                        "m08-l10-a5",
                        "Tekenen",
                        ["Hier, op de lijn, alstublieft.", "Hier, zonder lijn.", "Teken nergens."],
                        "Hier, op de lijn, alstublieft.",
                    ),
                    mcq(
                        "m08-l10-a6",
                        "Vraag over vervolg",
                        ["Wat moet ik daarna doen?", "Wat moet ik zonder reden doen?", "Daarna moet ik wat?"],
                        "Wat moet ik daarna doen?",
                    ),
                ],
                depth=True,
            ),
            pl(
                "m08-l10-pl2",
                "Variatie — 6×",
                ["geduld", "controle", "afscheid"],
                [
                    mcq(
                        "m08-l10-b1",
                        "Dank voor geduld",
                        ["Dank u voor uw geduld.", "Dank u voor uw haast.", "Geduld dank zonder u."],
                        "Dank u voor uw geduld.",
                    ),
                    fb("m08-l10-b2", "De medewerker ___ mijn paspoort. (check: past)", ["controleerde", "at", "kocht"], "controleerde"),
                    ro_tokens("m08-l10-r2", ["vragen?", "nog", "Heeft", "u", "verder"], "Heeft u verder nog vragen?"),
                    mcq(
                        "m08-l10-b3",
                        "Afscheid formeel",
                        ["Fijne dag verder.", "Tot nooit.", "Dag zonder groet."],
                        "Fijne dag verder.",
                    ),
                    mcq(
                        "m08-l10-b4",
                        "Als iets ontbreekt",
                        ["Wat mist er nog precies?", "Wat mist er zonder uitleg?", "Mist wat er?"],
                        "Wat mist er nog precies?",
                    ),
                    mcq(
                        "m08-l10-b5",
                        "Bevestigen",
                        ["Dus ik hoef vandaag niets meer te betalen?", "Dus ik betaal altijd dubbel?", "Hoef ik dus betalen?"],
                        "Dus ik hoef vandaag niets meer te betalen?",
                    ),
                    mcq(
                        "m08-l10-b6",
                        "Praktische tip",
                        ["Bewaar de brief op een vaste plek.", "Gooi de brief direct weg.", "Brief zonder lezen verbranden."],
                        "Bewaar de brief op een vaste plek.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m08-l10-sp1",
                "Jouw beurt",
                "Ja, dat klopt. Ik heb een afspraak om half twee.",
                [
                    "Ja dat klopt ik heb een afspraak om half twee",
                    "Ja, dat klopt. Ik heb een afspraak om half twee.",
                ],
                "Ja dat klopt ik heb een afspraak om half twee",
            ),
            speak_step(
                "m08-l10-sp2",
                "Documenten",
                "Hier is mijn paspoort en het formulier.",
                ["Hier is mijn paspoort en het formulier", "hier is mijn paspoort en het formulier"],
                "Hier is mijn paspoort en het formulier",
            ),
            speak_step(
                "m08-l10-sp3",
                "Vervolg",
                "Wat is de volgende stap?",
                ["Wat is de volgende stap", "wat is de volgende stap"],
                "Wat is de volgende stap",
            ),
            speak_step(
                "m08-l10-sp4",
                "Geboortedatum",
                "Mijn geboortedatum is 15 mei 1988.",
                [
                    "Mijn geboortedatum is 15 mei 1988",
                    "Mijn geboortedatum is 15 mei 1988.",
                ],
                "Mijn geboortedatum is 15 mei 1988",
            ),
            speak_step(
                "m08-l10-sp5",
                "Postcode + plaats",
                "Ik woon aan de Spui 10 in Den Haag. De postcode is 2511 CD.",
                [
                    "Ik woon aan de Spui 10 in Den Haag de postcode is 2511 CD",
                    "Ik woon aan de Spui 10 in Den Haag. De postcode is 2511 CD.",
                ],
                "Ik woon aan de Spui 10 in Den Haag de postcode is 2511 CD",
            ),
            speak_step(
                "m08-l10-sp6",
                "Afsluiten",
                "Nee, dank u wel. Ik begrijp het. Fijne dag.",
                [
                    "Nee dank u wel ik begrijp het fijne dag",
                    "Nee, dank u wel. Ik begrijp het. Fijne dag.",
                ],
                "Nee dank u wel ik begrijp het fijne dag",
            ),
            recap_step(
                "m08-l10-recap",
                "Recap",
                ["afspraak", "formulier", "brief"],
                [
                    rt_fb("___ u uw paspoort bij u? (do you have)", ["Heeft", "Eet", "Zwemt"], "Heeft"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Teken hier nog even voor ontvangst.",
                        ["Handtekening voor ontvangst", "Geen handtekening", "Teken op de deur"],
                        "Handtekening voor ontvangst",
                    ),
                    rt_ro(["geduld.", "uw", "Dank", "voor", "u"], "Dank u voor uw geduld."),
                    rt_speak("Zeg: *Wat is de volgende stap?*", "Wat is de volgende stap?"),
                    rt_fb("Ik ontvang een brief binnen vijf ___. (working days)", ["werkdagen", "minuten", "seconden"], "werkdagen"),
                    rt_speak("Zeg: *Kunt u dat uitleggen?*", "Kunt u dat uitleggen?"),
                    rt_speak("Zeg: *Fijne dag verder.*", "Fijne dag verder."),
                ],
            ),
        ],
    }


def lesson_l11() -> dict:
    lid = "a2-m08-l11-review-government-administration"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Review · Government & administration",
        "lessonType": "review",
        "order": 10,
        "cefrLevel": "A2",
        "durationEstimate": 17,
        "grammarTargets": ["a2.2-admin-formal-u", "a2.2-admin-modals", "a2.2-admin-documents"],
        "vocabTargets": ["lemma-gemeente", "lemma-afspraak-m8", "lemma-formulier", "lemma-inschrijven", "lemma-document"],
        "canDoStatements": ["I can retrieve formal phrases, modals, and admin vocabulary from this module in mixed tasks."],
        "mistakeFocus": ["mixed-retrieval", "formal-tone"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m08-l11-preview",
                "Warm-up — 5 woorden",
                [
                    ("balie", "balie", "counter", "🪟"),
                    ("bewijs", "bewijs", "proof / ID", "🪪"),
                    ("procedure", "procedure", "procedure", "📑"),
                    ("beleefd", "beleefd", "polite", "🙂"),
                    ("duidelijk", "duidelijk", "clear", "💡"),
                ],
            ),
            listening_step(
                "m08-l11-listen",
                "Mix — korte balie",
                [
                    (
                        "Medewerker",
                        "Goedemorgen. Wilt u eerst dit formulier invullen en daarna terugkomen naar balie 1?",
                        "Good morning. Would you first fill in this form and then come back to counter 1?",
                    ),
                    (
                        "Jij",
                        "Ja, is goed. Moet ik ook een kopie van mijn huurcontract meenemen?",
                        "Yes, fine. Do I also have to bring a copy of my rental contract?",
                    ),
                    (
                        "Medewerker",
                        "Ja, graag. En vergeet uw identiteitsbewijs niet.",
                        "Yes, please. And don't forget your ID card.",
                    ),
                ],
                [
                    ("Wat moet je eerst?", ["Formulier invullen", "Naar huis", "Koffie drinken"],
                        "Formulier invullen"),
                    ("Waar moet je daarna?", ["Terug naar balie 1", "Naar balie 99", "Naar buiten zonder formulier"],
                        "Terug naar balie 1"),
                    ("Welke extra vraag stel je?", ["Kopie huurcontract", "Kopie menukaart", "Geen vraag"],
                        "Kopie huurcontract"),
                    ("Wat zegt de medewerker over ID?", ["Identiteitsbewijs niet vergeten", "ID niet nodig", "ID alleen thuis"],
                        "Identiteitsbewijs niet vergeten"),
                ],
            ),
            pl(
                "m08-l11-pl1",
                "Mixed loop — 12×",
                ["gemeente", "afspraak", "u", "moeten", "document"],
                [
                    mcq("m08-l11-m1", "Formeel begin", ["Ik wil graag een afspraak maken.", "Ik wil nu zonder groet.", "Afspraak wil ik."], "Ik wil graag een afspraak maken."),
                    fb("m08-l11-m2", "Ik moet me ___ in de gemeente. (register)", ["inschrijven", "uitschrijven", "wegschrijven"], "inschrijven"),
                    ro_tokens("m08-l11-m3", ["helpen?", "kan", "Waarmee", "ik", "u"], "Waarmee kan ik u helpen?"),
                    mcq("m08-l11-m4", "Moeten", ["U moet dit formulier invullen.", "U moet dit formulier eten.", "Moet u formulier zonder."], "U moet dit formulier invullen."),
                    mcq("m08-l11-m5", "Kunnen", ["U kunt hier wachten.", "U kunt hier slapen.", "Kunt u hier zonder wachten."], "U kunt hier wachten."),
                    mcq("m08-l11-m6", "Documenten", ["Welke documenten heb ik nodig?", "Welke pizza heb ik nodig?", "Documenten welke ik heb?"], "Welke documenten heb ik nodig?"),
                    mcq("m08-l11-m7", "Persoonsgegevens", ["Mijn geboortedatum is 4 april 1993.", "Mijn geboortedatum is 4 pizza.", "Geboortedatum mijn is april."], "Mijn geboortedatum is 4 april 1993."),
                    mcq("m08-l11-m8", "Clarificatie", ["Kunt u dat uitleggen?", "Kunt u stoppen?", "Uitleg u dat?"], "Kunt u dat uitleggen?"),
                    mcq("m08-l11-m9", "Herhaling", ["Kunt u dat herhalen, alstublieft?", "Kunt u dat vergeten?", "Herhaal u nooit."], "Kunt u dat herhalen, alstublieft?"),
                    ro_tokens("m08-l11-m10", ["mee?", "moet", "Wat", "ik", "nemen"], "Wat moet ik meenemen?"),
                    mcq("m08-l11-m11", "Tijd", ["Het duurt ongeveer tien minuten.", "Het duurt tien jaar.", "Duurt het zonder tijd."], "Het duurt ongeveer tien minuten."),
                    mcq("m08-l11-m12", "Slot", ["Dank u wel voor uw hulp.", "Dank zonder hulp.", "Hulp dank u."], "Dank u wel voor uw hulp."),
                ],
                depth=True,
            ),
            pl(
                "m08-l11-pl2",
                "Speaking prep — 6×",
                ["adres", "nationaliteit", "handtekening"],
                [
                    mcq("m08-l11-s1", "Adres", ["Ik woon aan de Hoofdweg 22 in Den Haag.", "Ik woon zonder adres.", "Woon ik aan de Hoofdweg."], "Ik woon aan de Hoofdweg 22 in Den Haag."),
                    fb("m08-l11-s2", "Ik heb de Canadese ___. (nationality)", ["nationaliteit", "pizza", "tram"], "nationaliteit"),
                    ro_tokens("m08-l11-s3", ["hier.", "Teken", "alstublieft,"], "Teken hier, alstublieft."),
                    mcq("m08-l11-s4", "Begrip", ["Ik begrijp het niet helemaal.", "Ik begrijp alles zonder luisteren.", "Begrijp ik niet."], "Ik begrijp het niet helemaal."),
                    mcq("m08-l11-s5", "Mag ik", ["Mag ik een vraag stellen?", "Mag ik zonder vraag schreeuwen?", "Vraag mag ik?"], "Mag ik een vraag stellen?"),
                    mcq("m08-l11-s6", "Check", ["Klopt mijn naam zo?", "Klopt mijn naam nooit?", "Naam klopt mijn?"], "Klopt mijn naam zo?"),
                ],
                depth=True,
            ),
            speak_step(
                "m08-l11-sp1",
                "Output — mix",
                "Ik wil graag een afspraak maken. Ik moet me inschrijven. Wat moet ik meenemen?",
                [
                    "Ik wil graag een afspraak maken ik moet me inschrijven wat moet ik meenemen",
                    "Ik wil graag een afspraak maken. Ik moet me inschrijven. Wat moet ik meenemen?",
                ],
                "Ik wil graag een afspraak maken ik moet me inschrijven wat moet ik meenemen",
            ),
            speak_step(
                "m08-l11-sp2",
                "Output — formeel",
                "Kunt u mij helpen, alstublieft? Ik begrijp het formulier niet helemaal.",
                [
                    "Kunt u mij helpen alstublieft ik begrijp het formulier niet helemaal",
                    "Kunt u mij helpen, alstublieft? Ik begrijp het formulier niet helemaal.",
                ],
                "Kunt u mij helpen alstublieft ik begrijp het formulier niet helemaal",
            ),
            speak_step(
                "m08-l11-sp3",
                "Output — gegevens",
                "Mijn naam is … Mijn adres is … Mijn geboortedatum is …",
                [
                    "Mijn naam is Peter Janssen mijn adres is Kade 5 Rotterdam mijn geboortedatum is 2 juni 1989",
                    "Mijn naam is Peter Janssen. Mijn adres is Kade 5, Rotterdam. Mijn geboortedatum is 2 juni 1989.",
                ],
                "Mijn naam is Peter Janssen mijn adres is Kade 5 Rotterdam mijn geboortedatum is 2 juni 1989",
            ),
            speak_step(
                "m08-l11-sp4",
                "Output — postcode",
                "De postcode is 2271 BB. Ik woon in Voorburg.",
                [
                    "De postcode is 2271 BB ik woon in Voorburg",
                    "De postcode is 2271 BB. Ik woon in Voorburg.",
                ],
                "De postcode is 2271 BB ik woon in Voorburg",
            ),
            recap_step(
                "m08-l11-recap",
                "Recap — lang",
                ["admin", "gemeente", "formeel"],
                [
                    rt_fb("Ik wil graag een ___ maken voor mijn inschrijving. (appointment)", ["afspraak", "broodje", "feest"], "afspraak"),
                    rt_ro(["invullen.", "formulier", "Dit", "moet", "u"], "Dit formulier moet u invullen."),
                    rt_speak("Zeg: *Heeft u een identiteitsbewijs bij u?*", "Heeft u een identiteitsbewijs bij u?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Neem ook een kopie van uw huurcontract mee.",
                        ["Extra document", "Geen document", "Alleen een grap"],
                        "Extra document",
                    ),
                    rt_fb("___ u dat herhalen? (could)", ["Kunt", "Eet", "Zwemt"], "Kunt"),
                    rt_speak("Zeg: *U kunt hier wachten.*", "U kunt hier wachten."),
                    rt_fb("Het ___ ongeveer tien minuten. (takes time)", ["duurt", "eet", "zingt"], "duurt"),
                    rt_ro(["nodig?", "documenten", "Welke", "heb", "ik"], "Welke documenten heb ik nodig?"),
                    rt_speak("Zeg: *Met vriendelijke groet.*", "Met vriendelijke groet."),
                    rt_speak("Zeg: *Dank u wel voor uw hulp.*", "Dank u wel voor uw hulp."),
                ],
            ),
        ],
    }
