from .common import (
    LM,
    MID,
    discovery_step,
    fb,
    grammar_card,
    listen_read_step,
    listening_step,
    match_ex,
    mcq,
    pl,
    preview_step,
    recap_step,
    ro_tokens,
    rt_fb,
    rt_listen_mcq,
    rt_ro,
    rt_speak,
    speak_step,
)


def lesson_l01() -> dict:
    lid = "a2-m08-l01-listening-gemeente-catch-situation"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Listening · At the gemeente · catch the situation",
        "lessonType": "input",
        "order": 0,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-admin-formal-u", "a2.2-admin-appointments"],
        "vocabTargets": ["lemma-gemeente", "lemma-afspraak-m8", "lemma-balie", "lemma-formulier", "lemma-inschrijven"],
        "canDoStatements": [
            "I can follow a short counter conversation and identify why the person is there and what happens next.",
        ],
        "mistakeFocus": ["listening-gist", "formal-tone", "vocab"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m08-l01-preview",
                "Warm-up — 5 woorden",
                [
                    ("gemeente", "gemeente", "municipality", "🏛️"),
                    ("afspraak", "afspraak", "appointment", "📅"),
                    ("formulier", "formulier", "form", "📄"),
                    ("balie", "balie", "counter", "🪟"),
                    ("document", "document", "document", "📎"),
                ],
            ),
            listening_step(
                "m08-l01-listen",
                "Input — balie burgerservice",
                [
                    (
                        "Medewerker",
                        "Goedemorgen. Waarmee kan ik u helpen?",
                        "Good morning. How can I help you?",
                    ),
                    (
                        "Rania",
                        "Goedemorgen. Ik wil graag een afspraak maken. Ik moet me inschrijven.",
                        "Good morning. I'd like to make an appointment. I have to register.",
                    ),
                    (
                        "Medewerker",
                        "Prima. Heeft u al een DigiD of een brief van de gemeente?",
                        "Fine. Do you already have a DigiD or a letter from the municipality?",
                    ),
                    (
                        "Rania",
                        "Ja, ik heb een brief. En mijn paspoort heb ik bij me.",
                        "Yes, I have a letter. And I have my passport with me.",
                    ),
                    (
                        "Medewerker",
                        "Mooi. Ik plan u in op dinsdag om half elf. U krijgt een bevestiging per e-mail.",
                        "Good. I'll schedule you for Tuesday at half past ten. You'll get a confirmation by email.",
                    ),
                ],
                [
                    ("Waar is Rania?", ["Bij de gemeente / balie", "In de supermarkt", "Op het strand"], "Bij de gemeente / balie"),
                    ("Wat wil Rania?", ["Afspraak + inschrijven", "Alleen koffie", "Een fiets kopen"], "Afspraak + inschrijven"),
                    ("Wat vraagt de medewerker eerst over papieren?", ["DigiD of brief gemeente", "Een recept", "Een filmkaartje"], "DigiD of brief gemeente"),
                    ("Welk document noemt Rania?", ["Paspoort", "Rijbewijs alleen", "Foto van de kat"], "Paspoort"),
                    ("Wanneer is de afspraak?", ["Dinsdag half elf", "Vrijdag middernacht", "Geen afspraak"], "Dinsdag half elf"),
                ],
            ),
            discovery_step(
                "m08-l01-discovery",
                "Zinnen die je vaak hoort",
                [
                    ("Ik wil graag een afspraak maken.", "I'd like to make an appointment.", "afspraak"),
                    ("Ik moet me inschrijven.", "I have to register.", "inschrijven"),
                    ("Heeft u … bij u?", "Do you have … with you? (formal)", "u"),
                    ("U krijgt een bevestiging.", "You'll get a confirmation.", "bevestiging"),
                ],
            ),
            pl(
                "m08-l01-pl1",
                "Practice — 6×",
                ["afspraak", "gemeente", "formulier"],
                [
                    mcq(
                        "m08-l01-a1",
                        "Beleefd beginnen",
                        ["Ik wil graag een afspraak maken.", "Ik wil nu een afspraak zonder hallo.", "Afspraak wil ik graag nu."],
                        "Ik wil graag een afspraak maken.",
                    ),
                    fb("m08-l01-a2", "Ik moet me ___ in de gemeente. (register reflexive)", ["inschrijven", "uitschrijven", "opschrijven"], "inschrijven"),
                    ro_tokens("m08-l01-r1", ["maken.", "afspraak", "een", "graag", "wil", "Ik"], "Ik wil graag een afspraak maken."),
                    mcq(
                        "m08-l01-a3",
                        "‘Formulier’ =",
                        ["Een papier om in te vullen", "Een soort broodje", "Een treinkaartje"],
                        "Een papier om in te vullen",
                    ),
                    mcq(
                        "m08-l01-a4",
                        "Natuurlijke vraag aan de balie",
                        ["Wat moet ik meenemen?", "Wat moet ik vergeten?", "Meenemen moet ik wat nooit."],
                        "Wat moet ik meenemen?",
                    ),
                    mcq(
                        "m08-l01-a5",
                        "Balie vs kantoor thuis",
                        ["Aan de balie vraag je iets aan een medewerker.", "Aan de balie slaap je.", "Balie is altijd een café."],
                        "Aan de balie vraag je iets aan een medewerker.",
                    ),
                ],
            ),
            pl(
                "m08-l01-pl2",
                "Variatie — 6×",
                ["paspoort", "brief", "bevestiging"],
                [
                    mcq(
                        "m08-l01-b1",
                        "Goed antwoord op: *Heeft u uw paspoort bij u?*",
                        ["Ja, ik heb mijn paspoort bij me.", "Nee, ik wil niet antwoorden.", "Paspoort bij mij is niet."],
                        "Ja, ik heb mijn paspoort bij me.",
                    ),
                    fb("m08-l01-b2", "Ik heb een ___ van de gemeente. (official letter)", ["brief", "kat", "fiets"], "brief"),
                    ro_tokens("m08-l01-r2", ["helpen?", "kan", "ik", "u", "Waarmee"], "Waarmee kan ik u helpen?"),
                    mcq(
                        "m08-l01-b3",
                        "Bevestiging betekent hier ongeveer",
                        ["Een mail/bericht dat de afspraak klopt", "Een extra formulier zonder datum", "Geen afspraak"],
                        "Een mail/bericht dat de afspraak klopt",
                    ),
                    mcq(
                        "m08-l01-b4",
                        "Kies beleefd antwoord",
                        ["Dank u wel voor uw hulp.", "Dank u wel, ik ga zonder antwoord.", "Dank hulp u wel nooit."],
                        "Dank u wel voor uw hulp.",
                    ),
                    mcq(
                        "m08-l01-b5",
                        "Inschrijven in de gemeente: typisch voor",
                        ["Nieuwe bewoner in een stad", "Nieuwe smaak ijs", "Nieuwe hobby zonder adres"],
                        "Nieuwe bewoner in een stad",
                    ),
                    mcq(
                        "m08-l01-b6",
                        "Als je het niet snapt",
                        ["Kunt u dat uitleggen?", "Kunt u stoppen met praten?", "Uitleg u dat kunt nooit."],
                        "Kunt u dat uitleggen?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m08-l01-sp1",
                "Production",
                "Ik wil graag een afspraak maken.",
                ["Ik wil graag een afspraak maken", "ik wil graag een afspraak maken"],
                "Ik wil graag een afspraak maken",
            ),
            speak_step(
                "m08-l01-sp2",
                "Production",
                "Ik moet me inschrijven in de gemeente.",
                ["Ik moet me inschrijven in de gemeente", "ik moet me inschrijven in de gemeente"],
                "Ik moet me inschrijven in de gemeente",
            ),
            speak_step(
                "m08-l01-sp3",
                "Production",
                "Wat moet ik meenemen?",
                ["Wat moet ik meenemen", "wat moet ik meenemen"],
                "Wat moet ik meenemen",
            ),
            speak_step(
                "m08-l01-sp4",
                "Production",
                "Dank u wel voor uw hulp.",
                ["Dank u wel voor uw hulp", "dank u wel voor uw hulp"],
                "Dank u wel voor uw hulp",
            ),
            recap_step(
                "m08-l01-recap",
                "Recap",
                ["afspraak", "inschrijven", "gemeente"],
                [
                    rt_fb("Ik wil graag een ___ maken.", ["afspraak", "pizza", "feest"], "afspraak"),
                    rt_ro(["gemeente.", "de", "in", "schrijven", "moet", "Ik", "me"], "Ik moet me inschrijven in de gemeente."),
                    rt_speak("Zeg: *Heeft u een identiteitsbewijs?*", "Heeft u een identiteitsbewijs?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Ik plan u in op dinsdag om half elf.",
                        ["Afspraak plannen", "Formulier weggooien", "Geen tijd"],
                        "Afspraak plannen",
                    ),
                    rt_fb("___ moet ik meenemen? (what)", ["Wat", "Wie", "Waarom"], "Wat"),
                    rt_speak("Zeg: *Kunt u dat herhalen?*", "Kunt u dat herhalen?"),
                    rt_fb("U krijgt een ___ per e-mail. (confirmation)", ["bevestiging", "pizza", "fout"], "bevestiging"),
                ],
            ),
        ],
    }


def lesson_l02() -> dict:
    lid = "a2-m08-l02-listen-read-appointments-documents"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Listening & reading · Appointments and documents",
        "lessonType": "input",
        "order": 1,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-admin-documents", "a2.2-admin-appointments"],
        "vocabTargets": ["lemma-document", "lemma-paspoort-m8", "lemma-kopie", "lemma-brief-m8", "lemma-meennemen"],
        "canDoStatements": [
            "I can read a short official-style note and list what to bring and when to come.",
        ],
        "mistakeFocus": ["instruction-meaning", "vocab"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m08-l02-preview",
                "Warm-up — 5 woorden",
                [
                    ("kopie", "kopie", "copy", "📑"),
                    ("paspoort", "paspoort", "passport", "🛂"),
                    ("brief", "brief", "letter", "✉️"),
                    ("meenemen", "meenemen", "to bring", "🎒"),
                    ("identiteitsbewijs", "identiteitsbewijs", "ID card", "🪪"),
                ],
            ),
            listen_read_step(
                "m08-l02-lr",
                "Input — e-mail + antwoord",
                [
                    (
                        "Gemeente (mail)",
                        "Geachte mevrouw Nkosi, uw afspraak is op woensdag 14 juni om 10:30 bij balie 2. Neem uw paspoort en een kopie van uw huurcontract mee. Zonder deze documenten kunnen we u niet helpen.",
                        "Dear Ms Nkosi, your appointment is on Wednesday 14 June at 10:30 at counter 2. Bring your passport and a copy of your rental contract. Without these documents we cannot help you.",
                    ),
                    (
                        "Jij (antwoord)",
                        "Dank u wel. Moet ik ook een foto meenemen?",
                        "Thank you. Do I also have to bring a photo?",
                    ),
                    (
                        "Gemeente",
                        "Nee, voor deze afspraak is geen pasfoto nodig.",
                        "No, for this appointment a passport photo is not needed.",
                    ),
                ],
                [
                    ("Wanneer is de afspraak?", ["Woensdag 14 juni 10:30", "Donderdag 15 juni", "Zonder datum"], "Woensdag 14 juni 10:30"),
                    ("Waar moet je zijn?", ["Balie 2", "Balie 22 alleen", "In de bibliotheek"], "Balie 2"),
                    ("Welke documenten moet je meenemen?", ["Paspoort + kopie huurcontract", "Alleen een brief zonder paspoort", "Geen documenten"], "Paspoort + kopie huurcontract"),
                    ("Wat vraag jij in de mail?", ["Of een foto nodig is", "Of pizza gratis is", "Foto nodig is of?"],
                        "Of een foto nodig is"),
                    ("Is een pasfoto nodig?", ["Nee", "Ja, altijd", "Alleen op zondag"], "Nee"),
                    ("Wat betekent ‘zonder deze documenten’?", ["Dan kan de gemeente niet helpen", "Dan is alles gratis", "Dan hoeft u niet te komen"],
                        "Dan kan de gemeente niet helpen"),
                ],
            ),
            discovery_step(
                "m08-l02-discovery",
                "Instructies lezen",
                [
                    ("Neem … mee.", "Bring … with you.", "meenemen"),
                    ("Zonder … kunnen we niet helpen.", "Without … we cannot help.", "vereiste"),
                    ("Uw afspraak is op …", "Your appointment is on …", "tijd"),
                    ("Is … nodig?", "Is … needed?", "nodig"),
                ],
            ),
            pl(
                "m08-l02-pl1",
                "Practice — 6×",
                ["kopie", "paspoort", "document"],
                [
                    mcq(
                        "m08-l02-p1",
                        "Welke zin is duidelijk voor de balie?",
                        ["Welke documenten heb ik nodig?", "Welke documenten heb ik zonder vraag?", "Documenten welke nodig heb ik?"],
                        "Welke documenten heb ik nodig?",
                    ),
                    fb("m08-l02-p2", "Neem uw ___ en uw verblijfsvergunning mee. (travel ID)", ["paspoort", "fiets", "brood"], "paspoort"),
                    ro_tokens("m08-l02-r1", ["bij", "u?", "identiteitsbewijs", "Heeft", "een"], "Heeft u een identiteitsbewijs bij u?"),
                    mcq(
                        "m08-l02-p3",
                        "‘Kopie’ in deze context",
                        ["Een extra papier van het origineel", "Een kop koffie", "Een nieuw paspoort"],
                        "Een extra papier van het origineel",
                    ),
                    mcq(
                        "m08-l02-p4",
                        "Beleefd slot",
                        ["Met vriendelijke groet", "Met onvriendelijke groet", "Groet vriendelijk met nooit."],
                        "Met vriendelijke groet",
                    ),
                    mcq(
                        "m08-l02-p5",
                        "Als je twijfelt",
                        ["Kunt u dat nog een keer zeggen?", "Kunt u dat nooit meer zeggen?", "Zeggen u dat kunt?"],
                        "Kunt u dat nog een keer zeggen?",
                    ),
                ],
            ),
            pl(
                "m08-l02-pl2",
                "Variatie — 6×",
                ["brief", "afspraak", "balie"],
                [
                    mcq(
                        "m08-l02-q1",
                        "Wat hoort bij ‘u moet wachten’?",
                        ["U kunt hier zitten; het duurt ongeveer tien minuten.", "U kunt hier slapen; het duurt een jaar.", "Wacht u hier nooit."],
                        "U kunt hier zitten; het duurt ongeveer tien minuten.",
                    ),
                    fb("m08-l02-q2", "Uw ___ is om 9:00 uur. (appointment)", ["afspraak", "pizza", "feest"], "afspraak"),
                    ro_tokens("m08-l02-r2", ["formulier.", "dit", "invullen.", "moet", "U"], "U moet dit formulier invullen."),
                    mcq(
                        "m08-l02-q3",
                        "Zin over verplichting (simpel)",
                        ["U moet hier tekenen.", "U moet hier zingen.", "Tekenen u hier moet nooit."],
                        "U moet hier tekenen.",
                    ),
                    mcq(
                        "m08-l02-q4",
                        "Praktische check vóór vertrek",
                        ["Heb ik alles in mijn tas?", "Heb ik alles zonder tas?", "Tas alles heb ik?"],
                        "Heb ik alles in mijn tas?",
                    ),
                    mcq(
                        "m08-l02-q5",
                        "‘Huurcontract’ in de mail",
                        ["Bewijs van waar je woont", "Bewijs van je hobby", "Een treinkaartje"],
                        "Bewijs van waar je woont",
                    ),
                    mcq(
                        "m08-l02-q6",
                        "Ik begrijp het niet — volgende stap",
                        ["Kunt u dat uitleggen in eenvoudige woorden?", "Kunt u stoppen?", "Uitleg ik niet begrijp."],
                        "Kunt u dat uitleggen in eenvoudige woorden?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m08-l02-sp1",
                "Production",
                "Welke documenten heb ik nodig?",
                ["Welke documenten heb ik nodig", "welke documenten heb ik nodig"],
                "Welke documenten heb ik nodig",
            ),
            speak_step(
                "m08-l02-sp2",
                "Production",
                "Ik heb mijn paspoort bij me.",
                ["Ik heb mijn paspoort bij me", "ik heb mijn paspoort bij me"],
                "Ik heb mijn paspoort bij me",
            ),
            speak_step(
                "m08-l02-sp3",
                "Production",
                "Moet ik eerst een nummer halen?",
                ["Moet ik eerst een nummer halen", "moet ik eerst een nummer halen"],
                "Moet ik eerst een nummer halen",
            ),
            speak_step(
                "m08-l02-sp4",
                "Production",
                "Ik begrijp het niet helemaal.",
                ["Ik begrijp het niet helemaal", "ik begrijp het niet helemaal"],
                "Ik begrijp het niet helemaal",
            ),
            recap_step(
                "m08-l02-recap",
                "Recap",
                ["document", "meenemen", "afspraak"],
                [
                    rt_fb("Neem uw paspoort ___. (with you)", ["mee", "weg", "op"], "mee"),
                    rt_speak("Zeg: *Ik heb een afspraak.*", "Ik heb een afspraak."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Zonder deze documenten kunnen we u niet helpen.",
                        ["Waarschuwing: documenten nodig", "U hoeft niets", "Gratis paspoort"],
                        "Waarschuwing: documenten nodig",
                    ),
                    rt_ro(["bij", "balie", "2.", "naar", "Ga"], "Ga naar balie 2."),
                    rt_fb("___ u een kopie van het contract? (do you have)", ["Heeft", "Eet", "Zwemt"], "Heeft"),
                    rt_speak("Zeg: *Kunt u dat uitleggen?*", "Kunt u dat uitleggen?"),
                ],
            ),
        ],
    }


def lesson_l03() -> dict:
    lid = "a2-m08-l03-grammar-formal-requests"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Grammar & patterns · Formal requests (u, kunt u, moet ik)",
        "lessonType": "pattern",
        "order": 2,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-admin-formal-u", "a2.2-admin-modals"],
        "vocabTargets": ["lemma-kunnen-m8", "lemma-moeten-m8", "lemma-alstublieft-m8", "lemma-mag-ik", "lemma-uitleggen"],
        "canDoStatements": ["I can use short formal requests and ‘moet ik’ questions without odd word order."],
        "mistakeFocus": ["formal-tone", "word-order", "modals"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m08-l03-preview",
                "Warm-up — 4 woorden",
                [
                    ("u", "u", "you (formal)", "🙋"),
                    ("alstublieft", "alstublieft", "please", "🙏"),
                    ("mogen", "mogen", "may / to be allowed", "✅"),
                    ("uitleggen", "uitleggen", "to explain", "💬"),
                ],
            ),
            grammar_card(
                "m08-l03-gc",
                "Patroon",
                "Formeel vragen (kort)",
                "**Kunt u** …? **Wilt u** …? **Mag ik** …? **Moet ik** …? Bij de balie: **u** naar de medewerker, **ik** over jezelf. In de praktijk hoor je soms ook **je** — **u** is het veiligst als je het niet zeker weet. Korte zinnen zijn prima.",
                [
                    ("Kunt u mij helpen, alstublieft?", "Could you help me, please?"),
                    ("Moet ik eerst een nummer halen?", "Do I have to take a number first?"),
                ],
            ),
            listening_step(
                "m08-l03-listen",
                "Input — rustig tempo",
                [
                    (
                        "Jij",
                        "Goedemiddag. Mag ik u iets vragen?",
                        "Good afternoon. May I ask you something?",
                    ),
                    (
                        "Medewerker",
                        "Natuurlijk. Waarmee kan ik u helpen?",
                        "Of course. How can I help you?",
                    ),
                    (
                        "Jij",
                        "Moet ik dit formulier nu invullen, of mag ik dat later doen?",
                        "Do I have to fill in this form now, or may I do that later?",
                    ),
                    (
                        "Medewerker",
                        "Vul het nu in, alstublieft. Dan gaat het sneller.",
                        "Please fill it in now. Then it goes faster.",
                    ),
                ],
                [
                    ("Hoe begint de klant beleefd?", ["Mag ik u iets vragen?", "Geef mij nu antwoord", "Vraag ik mag u?"], "Mag ik u iets vragen?"),
                    ("Wat vraag je over het formulier?", ["Nu invullen of later", "Kleur van de pen", "Formulier zonder vragen"],
                        "Nu invullen of later"),
                    ("Wat zegt de medewerker?", ["Nu invullen", "Niet invullen", "Alleen thuis invullen zonder balie"],
                        "Nu invullen"),
                    ("Waarom nu invullen?", ["Dan gaat het sneller", "Dan is het gratis", "Dan is het onmogelijk"],
                        "Dan gaat het sneller"),
                    ("Welke toon past bij de balie?", ["Kort en beleefd", "Luid en boos", "Geen oogcontact nodig"],
                        "Kort en beleefd"),
                ],
            ),
            discovery_step(
                "m08-l03-discovery",
                "Let op",
                [
                    ("Kunt u …?", "Can you …? (formal)", "kunt"),
                    ("Wilt u …?", "Would you …? (formal)", "wilt"),
                    ("Mag ik …?", "May I …?", "mag"),
                    ("Moet ik …?", "Do I have to …?", "moet"),
                ],
            ),
            pl(
                "m08-l03-pl1",
                "Practice — 6×",
                ["u", "alstublieft", "mag"],
                [
                    mcq(
                        "m08-l03-a1",
                        "Juiste formele vraag",
                        ["Kunt u mij helpen?", "Kunt jij mij helpen zonder u?", "Help u mij kunt?"],
                        "Kunt u mij helpen?",
                    ),
                    fb("m08-l03-a2", "Wilt u dit ___, alstublieft? (sign)", ["tekenen", "zwemmen", "zingen"], "tekenen"),
                    ro_tokens("m08-l03-r1", ["ik", "een", "afspraak", "maken?", "Moet", "eerst"], "Moet ik eerst een afspraak maken?"),
                    mcq(
                        "m08-l03-a3",
                        "Informeel vs formeel (balie)",
                        ["Aan de balie: liever u + alstublieft", "Aan de balie: altijd je zonder groet", "Balie is informeel altijd"],
                        "Aan de balie: liever u + alstublieft",
                    ),
                    mcq(
                        "m08-l03-a4",
                        "Mag ik …?",
                        ["Mag ik hier even zitten wachten?", "Mag ik hier slapen de hele dag?", "Mag hier ik zitten wachten?"],
                        "Mag ik hier even zitten wachten?",
                    ),
                    mcq(
                        "m08-l03-a5",
                        "Juiste woordorde",
                        ["Kunt u dat herhalen?", "Kunt dat u herhalen?", "Herhalen kunt u dat?"],
                        "Kunt u dat herhalen?",
                    ),
                    mcq(
                        "m08-l03-a6",
                        "Als je stress hebt",
                        ["Eén vraag per keer is oké.", "Je moet alles in één zin zeggen.", "Zwijgen is altijd beter."],
                        "Eén vraag per keer is oké.",
                    ),
                ],
            ),
            pl(
                "m08-l03-pl2",
                "Variatie — 6×",
                ["moeten", "invullen", "wachten"],
                [
                    mcq(
                        "m08-l03-b1",
                        "Moet ik …?",
                        ["Moet ik een nummer trekken?", "Moet ik een nummer eten?", "Nummer moet ik trekken?"],
                        "Moet ik een nummer trekken?",
                    ),
                    fb("m08-l03-b2", "U ___ dit formulier invullen. (must: u)", ["moet", "wil", "kan"], "moet"),
                    ro_tokens("m08-l03-r2", ["alstublieft?", "langzamer", "Kunt", "praten", "u"], "Kunt u langzamer praten, alstublieft?"),
                    mcq(
                        "m08-l03-b3",
                        "Wilt u vs wil je",
                        ["Aan onbekende ambtenaar: liever Wilt u", "Altijd Wil je tegen iedereen", "Wilt u alleen voor vrienden"],
                        "Aan onbekende ambtenaar: liever Wilt u",
                    ),
                    mcq(
                        "m08-l03-b4",
                        "Uitleg vragen",
                        ["Kunt u dat in twee stappen uitleggen?", "Kunt u dat in één woord van tien pagina’s?", "Uitleg u dat in stappen?"],
                        "Kunt u dat in twee stappen uitleggen?",
                    ),
                    mcq(
                        "m08-l03-b5",
                        "Bevestigen",
                        ["Dus ik moet eerst betalen?", "Dus ik moet eerst rennen?", "Dus moet ik eerst betalen zonder vraag?"],
                        "Dus ik moet eerst betalen?",
                    ),
                    mcq(
                        "m08-l03-b6",
                        "Ik begrijp het niet",
                        ["Ik begrijp het niet. Kunt u het op papier zetten?", "Ik begrijp het niet. Zwijg maar.", "Begrijp ik niet het."],
                        "Ik begrijp het niet. Kunt u het op papier zetten?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m08-l03-sp1",
                "Production",
                "Kunt u mij helpen, alstublieft?",
                ["Kunt u mij helpen alstublieft", "Kunt u mij helpen, alstublieft?"],
                "Kunt u mij helpen alstublieft",
            ),
            speak_step(
                "m08-l03-sp2",
                "Production",
                "Moet ik eerst een nummer halen?",
                ["Moet ik eerst een nummer halen", "moet ik eerst een nummer halen"],
                "Moet ik eerst een nummer halen",
            ),
            speak_step(
                "m08-l03-sp3",
                "Production",
                "Mag ik hier even wachten?",
                ["Mag ik hier even wachten", "mag ik hier even wachten"],
                "Mag ik hier even wachten",
            ),
            recap_step(
                "m08-l03-recap",
                "Recap",
                ["u", "moet", "mag"],
                [
                    rt_fb("___ ik u iets vragen? (may)", ["Mag", "Eet", "Zwem"], "Mag"),
                    rt_ro(["helpen?", "mij", "Kunt", "u"], "Kunt u mij helpen?"),
                    rt_speak("Zeg: *Wilt u dit formulier invullen?*", "Wilt u dit formulier invullen?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Vul het nu in, alstublieft.",
                        ["Instructie: nu invullen", "Instructie: niet komen", "Gratis formulier"],
                        "Instructie: nu invullen",
                    ),
                    rt_fb("Moet ik dit formulier ___? (fill in)", ["invullen", "vergeten", "weggooien"], "invullen"),
                    rt_speak("Zeg: *Kunt u dat herhalen?*", "Kunt u dat herhalen?"),
                ],
            ),
        ],
    }


def lesson_l04() -> dict:
    lid = "a2-m08-l04-practice-personal-details-admin"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Controlled practice · Personal details and admin phrases",
        "lessonType": "practice",
        "order": 3,
        "cefrLevel": "A2",
        "durationEstimate": 16,
        "grammarTargets": ["a2.2-admin-personal-details", "a2.2-admin-formal-u"],
        "vocabTargets": ["lemma-adres-m8", "lemma-postcode-m8", "lemma-geboortedatum", "lemma-nationaliteit", "lemma-handtekening"],
        "canDoStatements": ["I can produce and fix short answers about name, address, DOB, and nationality."],
        "mistakeFocus": ["personal-details", "word-order"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m08-l04-preview",
                "Warm-up — 5 woorden",
                [
                    ("adres", "adres", "address", "🏠"),
                    ("postcode", "postcode", "postcode", "📮"),
                    ("geboortedatum", "geboortedatum", "date of birth", "🎂"),
                    ("nationaliteit", "nationaliteit", "nationality", "🌍"),
                    ("handtekening", "handtekening", "signature", "✍️"),
                ],
            ),
            listening_step(
                "m08-l04-listen",
                "Input — gegevens aan de balie",
                [
                    (
                        "Medewerker",
                        "Mag ik uw naam en geboortedatum, alstublieft?",
                        "May I have your name and date of birth, please?",
                    ),
                    (
                        "Jij",
                        "Mijn naam is Omar El Amrani. Mijn geboortedatum is 3 maart 1988.",
                        "My name is Omar El Amrani. My date of birth is 3 March 1988.",
                    ),
                    (
                        "Medewerker",
                        "Dank u. Wat is uw adres en postcode in Nederland?",
                        "Thank you. What is your address and postcode in the Netherlands?",
                    ),
                    (
                        "Jij",
                        "Ik woon aan de Kerkstraat 45 in Utrecht. De postcode is 3511 AB.",
                        "I live at Kerkstraat 45 in Utrecht. The postcode is 3511 AB.",
                    ),
                    (
                        "Medewerker",
                        "En uw nationaliteit?",
                        "And your nationality?",
                    ),
                    (
                        "Jij",
                        "Ik heb de Marokkaanse nationaliteit.",
                        "I have Moroccan nationality.",
                    ),
                ],
                [
                    ("Welke naam noemt de klant?", ["Omar El Amrani", "Ali van Dam", "Sara Jansen"], "Omar El Amrani"),
                    ("Wanneer is hij geboren?", ["3 maart 1988", "3 maart 1998", "13 maart 1888"], "3 maart 1988"),
                    ("In welke stad woont hij?", ["Utrecht", "Amsterdam", "Rotterdam"], "Utrecht"),
                    ("Welke straat?", ["Kerkstraat 45", "Kerkstraat 54", "Domplein 1"], "Kerkstraat 45"),
                    ("Welke postcode?", ["3511 AB", "3511 BA", "1234 ZZ"], "3511 AB"),
                ],
            ),
            discovery_step(
                "m08-l04-discovery",
                "Vaste antwoordpatronen",
                [
                    ("Mijn naam is …", "My name is …", "naam"),
                    ("Mijn geboortedatum is …", "My date of birth is …", "geboorte"),
                    ("Ik woon aan …", "I live at …", "adres"),
                    ("Ik heb de … nationaliteit.", "I have … nationality.", "nationaliteit"),
                ],
            ),
            pl(
                "m08-l04-pl1",
                "Practice — 8×",
                ["adres", "postcode", "nationaliteit"],
                [
                    ro_tokens("m08-l04-r1", ["is", "Mijn", "naam", "Elena", "Varga."], "Mijn naam is Elena Varga."),
                    mcq(
                        "m08-l04-a1",
                        "Geboortedatum formuleren",
                        ["Mijn geboortedatum is 22 juli 1995.", "Mijn geboortedatum is 22 pizza 1995.", "Geboortedatum mijn is juli."],
                        "Mijn geboortedatum is 22 juli 1995.",
                    ),
                    fb("m08-l04-a2", "De ___ is 1012 AB. (postcode)", ["postcode", "naam", "kat"], "postcode"),
                    mcq(
                        "m08-l04-a3",
                        "Adreszin",
                        ["Ik woon aan de Prinsengracht 120 in Amsterdam.", "Ik woon in de Prinsengracht zonder nummer.", "Woon ik aan de Prinsengracht Amsterdam."],
                        "Ik woon aan de Prinsengracht 120 in Amsterdam.",
                    ),
                    match_ex(
                        "m08-l04-m1",
                        "Match",
                        [("nationaliteit", "nationality"), ("handtekening", "signature"), ("formulier", "form")],
                        {"nationaliteit": "nationality", "handtekening": "signature", "formulier": "form"},
                    ),
                    mcq(
                        "m08-l04-a4",
                        "Nationaliteit",
                        ["Ik heb de Nederlandse nationaliteit.", "Ik heb de Nederlandse pizza.", "Nationaliteit Nederlandse heb ik."],
                        "Ik heb de Nederlandse nationaliteit.",
                    ),
                    mcq(
                        "m08-l04-a5",
                        "Spellen op verzoek (simpel)",
                        ["Kunt u dat langzaam spellen?", "Kunt u dat zonder letters spellen?", "Spellen u dat kunt?"],
                        "Kunt u dat langzaam spellen?",
                    ),
                    mcq(
                        "m08-l04-a6",
                        "Juiste bevestiging",
                        ["Klopt dat zo?", "Klopt dat nooit?", "Dat klopt zo zonder vraag?"],
                        "Klopt dat zo?",
                    ),
                ],
            ),
            pl(
                "m08-l04-pl2",
                "Variatie — 8×",
                ["handtekening", "invullen", "begrijpen"],
                [
                    mcq(
                        "m08-l04-b1",
                        "Waar teken je?",
                        ["Hier, op de stippellijn.", "Hier, op de muur.", "Teken je nergens."],
                        "Hier, op de stippellijn.",
                    ),
                    fb("m08-l04-b2", "U moet uw ___ zetten hier. (signature)", ["handtekening", "fiets", "brood"], "handtekening"),
                    ro_tokens("m08-l04-r2", ["Nederlandse", "de", "Ik", "heb", "nationaliteit."], "Ik heb de Nederlandse nationaliteit."),
                    mcq(
                        "m08-l04-b3",
                        "Als een cijfer onduidelijk is",
                        ["Sorry, welke postcode bedoelt u?", "Sorry, welke pizza bedoelt u?", "Postcode welke bedoelt u?"],
                        "Sorry, welke postcode bedoelt u?",
                    ),
                    mcq(
                        "m08-l04-b4",
                        "Korte reactie op instructie",
                        ["Oké, ik vul het in.", "Oké, ik weiger het.", "Oké vul ik zonder."],
                        "Oké, ik vul het in.",
                    ),
                    mcq(
                        "m08-l04-b5",
                        "‘Mag ik uw paspoort zien?’ — antwoord",
                        ["Ja, natuurlijk. Hier is het.", "Nee, zonder reden.", "Hier is het zonder ja."],
                        "Ja, natuurlijk. Hier is het.",
                    ),
                    mcq(
                        "m08-l04-b6",
                        "Fout herstellen",
                        ["Mijn adres is Hoofdstraat 2, Groningen.", "Mijn adres is Hoofdstraat zonder plaats.", "Adres mijn is Hoofdstraat."],
                        "Mijn adres is Hoofdstraat 2, Groningen.",
                    ),
                    mcq(
                        "m08-l04-b7",
                        "Wil / wilt (formeel)",
                        ["Wilt u nog iets weten?", "Wil jij nu zonder u?", "Wilt weten u iets?"],
                        "Wilt u nog iets weten?",
                    ),
                    mcq(
                        "m08-l04-b8",
                        "Stress-tip",
                        ["U mag rustig antwoorden; u hoeft niet te haasten.", "U moet binnen 5 seconden alles zeggen.", "Haast is altijd verplicht."],
                        "U mag rustig antwoorden; u hoeft niet te haasten.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m08-l04-sp1",
                "Production",
                "Mijn naam is … Mijn geboortedatum is …",
                [
                    "Mijn naam is Jan de Vries mijn geboortedatum is 10 april 1992",
                    "Mijn naam is Jan de Vries. Mijn geboortedatum is 10 april 1992.",
                ],
                "Mijn naam is Jan de Vries mijn geboortedatum is 10 april 1992",
            ),
            speak_step(
                "m08-l04-sp2",
                "Production",
                "Ik woon aan de Stationsweg 8 in Haarlem.",
                ["Ik woon aan de Stationsweg 8 in Haarlem", "ik woon aan de stationsweg 8 in haarlem"],
                "Ik woon aan de Stationsweg 8 in Haarlem",
            ),
            speak_step(
                "m08-l04-sp3",
                "Production",
                "Ik heb de Braziliaanse nationaliteit.",
                ["Ik heb de Braziliaanse nationaliteit", "ik heb de braziliaanse nationaliteit"],
                "Ik heb de Braziliaanse nationaliteit",
            ),
            speak_step(
                "m08-l04-sp4",
                "Production",
                "De postcode is 3511 AB.",
                ["De postcode is 3511 AB", "de postcode is 3511 ab"],
                "De postcode is 3511 AB",
            ),
            recap_step(
                "m08-l04-recap",
                "Recap",
                ["adres", "geboortedatum", "nationaliteit"],
                [
                    rt_fb("Mijn ___ is 5 november 2001. (date of birth)", ["geboortedatum", "adres", "postcode"], "geboortedatum"),
                    rt_ro(["AB.", "postcode", "De", "is", "1234"], "De postcode is 1234 AB."),
                    rt_speak("Zeg: *Ik woon aan de …*", "Ik woon aan de Kerkstraat 12."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Wat is uw adres en postcode in Nederland?",
                        ["Vraag om adres + postcode", "Vraag om hobby", "Vraag om kleur"],
                        "Vraag om adres + postcode",
                    ),
                    rt_fb("Ik heb de Franse ___. (nationality)", ["nationaliteit", "pizza", "tram"], "nationaliteit"),
                    rt_speak("Zeg: *Kunt u dat herhalen?*", "Kunt u dat herhalen?"),
                    rt_fb("___ u hier, alstublieft. (sign)", ["Teken", "Eet", "Zwem"], "Teken"),
                ],
            ),
        ],
    }
