from .common import (
    LM,
    MID,
    discovery_step,
    fb,
    grammar_card,
    listen_read_step,
    listening_step,
    mcq,
    pl,
    preview_step,
    recap_step,
    ro_tokens,
    rt_fb,
    rt_listen_mcq,
    rt_ro,
    rt_speak,
    speak_step,
    writing_step,
)


def lesson_l05() -> dict:
    lid = "a2-m08-l05-speaking-give-details-clearly"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Speaking · Give your details clearly",
        "lessonType": "speaking",
        "order": 4,
        "cefrLevel": "A2",
        "durationEstimate": 16,
        "grammarTargets": ["a2.2-admin-personal-details", "a2.2-admin-formal-u"],
        "vocabTargets": ["lemma-begrijpen-m8", "lemma-herhalen-m8", "lemma-adres-m8", "lemma-geboortedatum", "lemma-nationaliteit"],
        "canDoStatements": [
            "I can answer follow-up questions about my details and ask for repetition calmly.",
        ],
        "mistakeFocus": ["production", "clarification"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m08-l05-preview",
                "Warm-up — 5 woorden",
                [
                    ("rustig", "rustig", "calm / slowly", "🧘"),
                    ("herhalen", "herhalen", "to repeat", "🔁"),
                    ("spellen", "spellen", "to spell", "🔤"),
                    ("begrijpen", "begrijpen", "to understand", "💡"),
                    ("even", "even", "a moment", "⏸️"),
                ],
            ),
            listening_step(
                "m08-l05-model",
                "Model — vragen en antwoorden",
                [
                    (
                        "Medewerker",
                        "Kunt u uw achternaam spellen, alstublieft?",
                        "Could you spell your last name, please?",
                    ),
                    (
                        "Jij",
                        "Ja: S – M – I – T.",
                        "Yes: S – M – I – T.",
                    ),
                    (
                        "Medewerker",
                        "Dank u. En uw geboorteplaats?",
                        "Thank you. And your place of birth?",
                    ),
                    (
                        "Jij",
                        "Ik ben geboren in Brussel.",
                        "I was born in Brussels.",
                    ),
                    (
                        "Medewerker",
                        "Prima. Begrijpt u wat u hierna moet doen?",
                        "Fine. Do you understand what you have to do next?",
                    ),
                    (
                        "Jij",
                        "Ik denk het wel. Moet ik nog een kopie maken?",
                        "I think so. Do I still have to make a copy?",
                    ),
                ],
                [
                    ("Wat vraagt de medewerker eerst?", ["Achternaam spellen", "Adres zonder naam", "Telefoonnummer zingen"],
                        "Achternaam spellen"),
                    ("Hoe spelt de klant?", ["S-M-I-T", "S-M-E-T", "Zonder letters"], "S-M-I-T"),
                    ("Wat is de geboorteplaats?", ["Brussel", "Amsterdam", "Parijs"], "Brussel"),
                    ("Wat vraagt de klant op het eind?", ["Of een kopie nodig is", "Of lunch gratis is", "Kopie nodig is of"],
                        "Of een kopie nodig is"),
                    ("Welke check doet de medewerker?", ["Of je de volgende stap begrijpt", "Of je honger hebt", "Of je auto rijdt"],
                        "Of je de volgende stap begrijpt"),
                ],
            ),
            discovery_step(
                "m08-l05-discovery",
                "Helder antwoorden",
                [
                    ("Kunt u dat herhalen?", "Could you repeat that?", "herhaling"),
                    ("Ik begrijp het niet.", "I don't understand.", "hulp"),
                    ("Een moment, alstublieft.", "One moment, please.", "rust"),
                    ("Klopt dat zo?", "Is that correct?", "check"),
                ],
            ),
            pl(
                "m08-l05-pl1",
                "Variatie — 6×",
                ["spellen", "begrijpen", "kopie"],
                [
                    mcq(
                        "m08-l05-a1",
                        "Als je iets niet hoort",
                        ["Sorry, kunt u dat nog een keer zeggen?", "Sorry, zwijg maar.", "Zeggen u dat kunt?"],
                        "Sorry, kunt u dat nog een keer zeggen?",
                    ),
                    fb("m08-l05-a2", "Ik ___ het niet goed. (understand)", ["begrijp", "eet", "zwem"], "begrijp"),
                    ro_tokens("m08-l05-r1", ["even.", "wacht", "Een", "alstublieft."], "Een moment, alstublieft."),
                    mcq(
                        "m08-l05-a3",
                        "Spellen: beleefd",
                        ["Kunt u dat letter voor letter spellen?", "Kunt u dat zonder letters spellen?", "Spellen letter voor letter?"],
                        "Kunt u dat letter voor letter spellen?",
                    ),
                    mcq(
                        "m08-l05-a4",
                        "Bevestigen",
                        ["Dus mijn adres is nog steeds hetzelfde?", "Dus mijn adres is een grap?", "Adres mijn is dus?"],
                        "Dus mijn adres is nog steeds hetzelfde?",
                    ),
                    mcq(
                        "m08-l05-a5",
                        "Als je tijd nodig hebt",
                        ["Mag ik even nadenken?", "Mag ik zonder nadenken?", "Nadenken mag ik even?"],
                        "Mag ik even nadenken?",
                    ),
                    mcq(
                        "m08-l05-a6",
                        "Natuurlijke reactie",
                        ["Oké, ik noteer het.", "Oké, ik vergeet het meteen.", "Noteer ik oké het."],
                        "Oké, ik noteer het.",
                    ),
                ],
                depth=True,
            ),
            pl(
                "m08-l05-pl2",
                "Follow-up — 6×",
                ["geboorteplaats", "telefoon", "email"],
                [
                    mcq(
                        "m08-l05-b1",
                        "Telefoonnummer doorgeven",
                        ["Mijn nummer is nul zes, een twee drie …", "Mijn nummer is een geheim.", "Nummer mijn is zonder cijfers."],
                        "Mijn nummer is nul zes, een twee drie …",
                    ),
                    fb("m08-l05-b2", "Ik ben geboren in ___. (city)", ["Antwerpen", "de maan", "de pizza"], "Antwerpen"),
                    ro_tokens("m08-l05-r2", ["Klopt", "dat", "zo?"], "Klopt dat zo?"),
                    mcq(
                        "m08-l05-b3",
                        "E-mail spellen (simpel)",
                        ["Kunt u uw e-mail langzaam spellen?", "Kunt u uw e-mail zonder @ spellen?", "E-mail spellen u kunt?"],
                        "Kunt u uw e-mail langzaam spellen?",
                    ),
                    mcq(
                        "m08-l05-b4",
                        "Als de medewerker te snel praat",
                        ["Kunt u wat langzamer praten?", "Kunt u wat harder schreeuwen?", "Langzamer praten u kunt?"],
                        "Kunt u wat langzamer praten?",
                    ),
                    mcq(
                        "m08-l05-b5",
                        "Dank + check",
                        ["Dank u, dan is het duidelijk.", "Dank u, dan is het onmogelijk.", "Dank duidelijk is het."],
                        "Dank u, dan is het duidelijk.",
                    ),
                    mcq(
                        "m08-l05-b6",
                        "Fout antwoord herstellen",
                        ["Sorry, ik bedoelde postcode 2025 CD.", "Sorry, ik bedoelde zonder postcode.", "Bedoelde sorry ik."],
                        "Sorry, ik bedoelde postcode 2025 CD.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m08-l05-sp1",
                "Jouw beurt",
                "Mijn naam is … Ik ben geboren op …",
                [
                    "Mijn naam is Anna Kovacs ik ben geboren op 8 januari 1994",
                    "Mijn naam is Anna Kovacs. Ik ben geboren op 8 januari 1994.",
                ],
                "Mijn naam is Anna Kovacs ik ben geboren op 8 januari 1994",
            ),
            speak_step(
                "m08-l05-sp2",
                "Clarificatie",
                "Kunt u dat herhalen, alstublieft? Ik begrijp het niet helemaal.",
                [
                    "Kunt u dat herhalen alstublieft ik begrijp het niet helemaal",
                    "Kunt u dat herhalen, alstublieft? Ik begrijp het niet helemaal.",
                ],
                "Kunt u dat herhalen alstublieft ik begrijp het niet helemaal",
            ),
            speak_step(
                "m08-l05-sp3",
                "Adres",
                "Ik woon aan de Lindelaan 3 in Eindhoven.",
                ["Ik woon aan de Lindelaan 3 in Eindhoven", "ik woon aan de lindelaan 3 in eindhoven"],
                "Ik woon aan de Lindelaan 3 in Eindhoven",
            ),
            speak_step(
                "m08-l05-sp4",
                "Nationaliteit",
                "Ik heb de Turkse nationaliteit.",
                ["Ik heb de Turkse nationaliteit", "ik heb de turkse nationaliteit"],
                "Ik heb de Turkse nationaliteit",
            ),
            speak_step(
                "m08-l05-sp5",
                "Postcode",
                "De postcode is 2025 CD.",
                ["De postcode is 2025 CD", "de postcode is 2025 cd"],
                "De postcode is 2025 CD",
            ),
            speak_step(
                "m08-l05-sp6",
                "Afsluiten",
                "Dank u wel. Fijne dag nog.",
                ["Dank u wel fijne dag nog", "Dank u wel. Fijne dag nog."],
                "Dank u wel fijne dag nog",
            ),
            recap_step(
                "m08-l05-recap",
                "Recap",
                ["herhalen", "begrijpen", "spellen"],
                [
                    rt_speak("Zeg: *Kunt u dat langzamer zeggen?*", "Kunt u dat langzamer zeggen?"),
                    rt_fb("Ik ___ het niet. (understand)", ["begrijp", "eet", "ren"], "begrijp"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Kunt u uw achternaam spellen, alstublieft?",
                        ["Vraag om spellen", "Vraag om te zingen", "Stop het gesprek"],
                        "Vraag om spellen",
                    ),
                    rt_ro(["zo?", "Klopt", "dat"], "Klopt dat zo?"),
                    rt_fb("Een moment, ___. (please)", ["alstublieft", "nu", "snel"], "alstublieft"),
                    rt_speak("Zeg: *Mag ik even nadenken?*", "Mag ik even nadenken?"),
                    rt_speak("Zeg: *Mijn geboortedatum is …*", "Mijn geboortedatum is 14 mei 1991."),
                ],
            ),
        ],
    }


def lesson_l06() -> dict:
    lid = "a2-m08-l06-listening-instructions-processes"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Listening · Instructions and processes",
        "lessonType": "input",
        "order": 5,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-admin-instructions", "a2.2-admin-modals"],
        "vocabTargets": ["lemma-wachten-m8", "lemma-nummer-m8", "lemma-invullen", "lemma-balie", "lemma-duurt"],
        "canDoStatements": [
            "I can follow simple instructions: where to wait, what to fill in, how long it takes.",
        ],
        "mistakeFocus": ["instruction-meaning", "listening-detail"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m08-l06-preview",
                "Warm-up — 5 woorden",
                [
                    ("nummer", "nummer", "ticket number", "🎟️"),
                    ("wachtruimte", "wachtruimte", "waiting area", "🪑"),
                    ("rij", "rij", "queue / line", "↔️"),
                    ("stap", "stap", "step", "👣"),
                    ("duurt", "duren", "takes (time)", "⏱️"),
                ],
            ),
            listening_step(
                "m08-l06-a",
                "Input — bij binnenkomst",
                [
                    (
                        "Medewerker",
                        "Goedemiddag. Neem alstublieft een nummer bij de machine. U kunt daar in de wachtruimte gaan zitten.",
                        "Good afternoon. Please take a number at the machine. You can sit in the waiting area over there.",
                    ),
                    (
                        "Jij",
                        "Oké. Hoe lang duurt het ongeveer?",
                        "Okay. How long does it take approximately?",
                    ),
                    (
                        "Host",
                        "Vandaag ongeveer vijftien minuten. Luister goed naar het scherm: uw nummer verschijnt daar.",
                        "Today about fifteen minutes. Listen carefully to the screen: your number appears there.",
                    ),
                ],
                [
                    ("Wat moet je eerst doen?", ["Een nummer nemen", "Direct naar huis", "Een formulier verbranden"],
                        "Een nummer nemen"),
                    ("Waar kun je wachten?", ["In de wachtruimte", "Op straat zonder nummer", "In de kelder zonder licht"],
                        "In de wachtruimte"),
                    ("Hoe lang duurt het vandaag?", ["Ongeveer vijftien minuten", "Ongeveer vijf uur", "Geen wachttijd"],
                        "Ongeveer vijftien minuten"),
                    ("Waar zie je je nummer?", ["Op het scherm", "Alleen op papier thuis", "Nergens"],
                        "Op het scherm"),
                ],
            ),
            listening_step(
                "m08-l06-b",
                "Input — aan de balie (vervolg)",
                [
                    (
                        "Medewerker",
                        "U bent aan de beurt. Ga naar balie 3. Neem uw paspoort en het formulier mee.",
                        "It's your turn. Go to counter 3. Bring your passport and the form.",
                    ),
                    (
                        "Jij",
                        "Moet ik nog betalen?",
                        "Do I still have to pay?",
                    ),
                    (
                        "Medewerker",
                        "Nee, voor dit gesprek niet. Teken hieronder en u kunt weggaan.",
                        "No, not for this conversation. Sign below and you can leave.",
                    ),
                ],
                [
                    ("Naar welke balie?", ["Balie 3", "Balie 13", "Geen balie"], "Balie 3"),
                    ("Wat moet je meenemen?", ["Paspoort + formulier", "Alleen koffie", "Niets"],
                        "Paspoort + formulier"),
                    ("Moet je betalen?", ["Nee", "Ja, altijd 100 euro", "Alleen met kaas"],
                        "Nee"),
                    ("Wat moet je als laatste?", ["Tekenen en weggaan", "Slapen aan de balie", "Formulier vergeten"],
                        "Tekenen en weggaan"),
                ],
            ),
            discovery_step(
                "m08-l06-discovery",
                "Instructie-brokken",
                [
                    ("Neem een nummer.", "Take a number.", "nummer"),
                    ("U kunt hier wachten.", "You can wait here.", "wachten"),
                    ("Het duurt ongeveer …", "It takes about …", "tijd"),
                    ("Ga naar balie …", "Go to counter …", "balie"),
                ],
            ),
            pl(
                "m08-l06-pl1",
                "Practice — 6×",
                ["wachten", "nummer", "scherm"],
                [
                    mcq(
                        "m08-l06-a1",
                        "Welke zin is een duidelijke instructie?",
                        ["Wacht tot uw nummer op het scherm staat.", "Wacht zonder nummer voor altijd.", "Wacht scherm nummer zonder."],
                        "Wacht tot uw nummer op het scherm staat.",
                    ),
                    fb("m08-l06-a2", "Het ___ ongeveer tien minuten. (takes time)", ["duurt", "eet", "zingt"], "duurt"),
                    ro_tokens("m08-l06-r1", ["een", "Neem", "nummer.", "alstublieft"], "Neem een nummer, alstublieft."),
                    mcq(
                        "m08-l06-a3",
                        "‘U bent aan de beurt’ betekent",
                        ["Nu is het jouw tijd / je mag naar de balie", "Je moet naar huis", "Je bent te laat"],
                        "Nu is het jouw tijd / je mag naar de balie",
                    ),
                    mcq(
                        "m08-l06-a4",
                        "Luister goed",
                        ["Let op het scherm en de omroep.", "Let op uw telefoon alleen.", "Let op zonder scherm."],
                        "Let op het scherm en de omroep.",
                    ),
                    mcq(
                        "m08-l06-a5",
                        "Formulier eerst of later?",
                        ["Soms moet je eerst invullen in de hal", "Je mag nooit invullen", "Formulier zonder pen"],
                        "Soms moet je eerst invullen in de hal",
                    ),
                ],
            ),
            pl(
                "m08-l06-pl2",
                "Variatie — 6×",
                ["tekenen", "balie", "weg"],
                [
                    mcq(
                        "m08-l06-b1",
                        "Tekenen",
                        ["Teken hier op de lijn, alstublieft.", "Teken op de muur zonder toestemming.", "Teken hier zonder lijn."],
                        "Teken hier op de lijn, alstublieft.",
                    ),
                    fb("m08-l06-b2", "Ga naar ___ 1. (counter)", ["balie", "station", "strand"], "balie"),
                    ro_tokens("m08-l06-r2", ["wachten.", "hier", "U", "kunt"], "U kunt hier wachten."),
                    mcq(
                        "m08-l06-b3",
                        "Als je de instructie mist",
                        ["Sorry, welke balie moet ik?", "Sorry, ik ga zonder vragen.", "Welke balie moet sorry ik?"],
                        "Sorry, welke balie moet ik?",
                    ),
                    mcq(
                        "m08-l06-b4",
                        "Rustig blijven",
                        ["Het is normaal dat u even moet wachten.", "Het is verboden om te wachten.", "Wachten is altijd fout."],
                        "Het is normaal dat u even moet wachten.",
                    ),
                    mcq(
                        "m08-l06-b5",
                        "Volgende stap",
                        ["Daarna gaat u naar de uitgang.", "Daarna slaapt u aan de balie.", "Daarna zonder uitgang."],
                        "Daarna gaat u naar de uitgang.",
                    ),
                    mcq(
                        "m08-l06-b6",
                        "‘Nee, voor dit gesprek niet’ — over",
                        ["Betaling voor dit bezoek", "Paspoort", "Adres"],
                        "Betaling voor dit bezoek",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m08-l06-sp1",
                "Production",
                "Waar moet ik wachten?",
                ["Waar moet ik wachten", "waar moet ik wachten"],
                "Waar moet ik wachten",
            ),
            speak_step(
                "m08-l06-sp2",
                "Production",
                "Hoe lang duurt het ongeveer?",
                ["Hoe lang duurt het ongeveer", "hoe lang duurt het ongeveer"],
                "Hoe lang duurt het ongeveer",
            ),
            speak_step(
                "m08-l06-sp3",
                "Production",
                "Moet ik nog iets betalen?",
                ["Moet ik nog iets betalen", "moet ik nog iets betalen"],
                "Moet ik nog iets betalen",
            ),
            speak_step(
                "m08-l06-sp4",
                "Production",
                "Waar moet ik tekenen?",
                ["Waar moet ik tekenen", "waar moet ik tekenen"],
                "Waar moet ik tekenen",
            ),
            recap_step(
                "m08-l06-recap",
                "Recap",
                ["nummer", "wachten", "balie"],
                [
                    rt_fb("Neem een ___, alstublieft.", ["nummer", "brood", "fiets"], "nummer"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Ga naar balie 3.",
                        ["Naar welke balie", "Naar welke supermarkt", "Naar huis"],
                        "Naar welke balie",
                    ),
                    rt_ro(["minuten.", "Het", "ongeveer", "tien", "duurt"], "Het duurt ongeveer tien minuten."),
                    rt_speak("Zeg: *U kunt hier wachten.*", "U kunt hier wachten."),
                    rt_fb("___ hier, alstublieft. (sign)", ["Teken", "Eet", "Zwem"], "Teken"),
                    rt_speak("Zeg: *Kunt u dat uitleggen?*", "Kunt u dat uitleggen?"),
                ],
            ),
        ],
    }


def lesson_l07() -> dict:
    lid = "a2-m08-l07-grammar-modals-admin-context"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Grammar & patterns · Modal verbs in admin context",
        "lessonType": "pattern",
        "order": 6,
        "cefrLevel": "A2",
        "durationEstimate": 14,
        "grammarTargets": ["a2.2-admin-modals", "a2.2-admin-instructions"],
        "vocabTargets": ["lemma-moeten-m8", "lemma-kunnen-m8", "lemma-invullen", "lemma-meennemen", "lemma-wachten-m8"],
        "canDoStatements": ["I can understand and produce short u-moet / ik-moet / kunt u sentences in admin settings."],
        "mistakeFocus": ["modals", "formal-tone"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m08-l07-preview",
                "Warm-up — 4 woorden",
                [
                    ("moeten", "moeten", "must", "📌"),
                    ("kunnen", "kunnen", "can", "✅"),
                    ("mogen", "mogen", "may", "🚦"),
                    ("hoeven", "hoeven", "to need to (neg.)", "🚫"),
                ],
            ),
            grammar_card(
                "m08-l07-gc",
                "Patroon",
                "Moeten / kunnen / mogen (kort)",
                "**U moet** … (instructie). **U kunt** … (mogelijkheid). **Moet ik** …? (vraag). **Ik kan niet** … + korte reden (*want …*).",
                [
                    ("U moet eerst dit deel invullen.", "You have to fill in this part first."),
                    ("Kunt u morgen terugkomen?", "Can you come back tomorrow?"),
                ],
            ),
            listening_step(
                "m08-l07-listen",
                "Input — balie",
                [
                    (
                        "Medewerker",
                        "U moet beide pagina’s invullen. U mag geen vakken open laten.",
                        "You have to fill in both pages. You may not leave any boxes open.",
                    ),
                    (
                        "Jij",
                        "Kan ik hulp krijgen bij vraag zes?",
                        "Can I get help with question six?",
                    ),
                    (
                        "Medewerker",
                        "Ja, dat kan. U kunt hier even zitten; ik kom zo bij u.",
                        "Yes, that’s possible. You can sit here for a moment; I'll come to you shortly.",
                    ),
                ],
                [
                    ("Wat moet de klant invullen?", ["Beide pagina’s", "Alleen pagina 1", "Geen pagina’s"],
                        "Beide pagina’s"),
                    ("Wat mag niet?", ["Open vakken laten", "Alles invullen", "Vragen stellen"],
                        "Open vakken laten"),
                    ("Wat vraagt de klant?", ["Hulp bij vraag zes", "Hulp bij koffie", "Geen hulp"],
                        "Hulp bij vraag zes"),
                    ("Wat kan de medewerker?", ["Even helpen bij de tafel", "Alleen weigeren", "Niets"],
                        "Even helpen bij de tafel"),
                ],
            ),
            discovery_step(
                "m08-l07-discovery",
                "Let op",
                [
                    ("U moet …", "You must …", "plicht"),
                    ("U kunt …", "You can …", "mogelijkheid"),
                    ("Mag ik …?", "May I …?", "toestemming"),
                    ("Ik moet … want …", "I have to … because …", "reden"),
                ],
            ),
            pl(
                "m08-l07-pl1",
                "Practice — 6×",
                ["moeten", "kunnen", "invullen"],
                [
                    mcq(
                        "m08-l07-a1",
                        "Juiste instructie",
                        ["U moet hier uw handtekening zetten.", "U moet hier uw naam vergeten.", "Moet u hier zonder handtekening."],
                        "U moet hier uw handtekening zetten.",
                    ),
                    fb("m08-l07-a2", "___ ik morgen terugkomen? (can: ik)", ["Kan", "Moet", "Wil"], "Kan"),
                    ro_tokens("m08-l07-r1", ["niet", "Ik", "kan", "zonder", "afspraak", "komen."], "Ik kan niet zonder afspraak komen."),
                    mcq(
                        "m08-l07-a3",
                        "U hoeft niet =",
                        ["Het is niet nodig", "Het is verplicht", "Het is onmogelijk"],
                        "Het is niet nodig",
                    ),
                    mcq(
                        "m08-l07-a4",
                        "Want-zin (simpel)",
                        ["Ik moet een kopie maken, want mijn paspoort is verlopen.", "Ik moet een kopie maken, want ik hou van pizza.", "Moet ik kopie want paspoort."],
                        "Ik moet een kopie maken, want mijn paspoort is verlopen.",
                    ),
                    mcq(
                        "m08-l07-a5",
                        "Formeel: kunnen",
                        ["Kunt u dit formulier controleren?", "Kun je dit zonder respect controleren?", "Controleren u dit kunt?"],
                        "Kunt u dit formulier controleren?",
                    ),
                    mcq(
                        "m08-l07-a6",
                        "Mag ik …",
                        ["Mag ik een vraag stellen?", "Mag ik zonder vraag schreeuwen?", "Vraag mag ik stellen?"],
                        "Mag ik een vraag stellen?",
                    ),
                ],
            ),
            pl(
                "m08-l07-pl2",
                "Variatie — 6×",
                ["omdat", "wachten", "terugkomen"],
                [
                    mcq(
                        "m08-l07-b1",
                        "Omdat-zin",
                        ["Ik kom morgen terug, omdat ik vandaag geen tijd heb.", "Ik kom morgen terug omdat ik geen tijd zonder komma.", "Terug kom ik morgen omdat."],
                        "Ik kom morgen terug, omdat ik vandaag geen tijd heb.",
                    ),
                    fb("m08-l07-b2", "U ___ hier wachten tot uw nummer wordt geroepen. (can)", ["kunt", "moet", "wil"], "kunt"),
                    ro_tokens("m08-l07-r2", ["invullen.", "formulier", "Dit", "moet", "u"], "Dit formulier moet u invullen."),
                    mcq(
                        "m08-l07-b3",
                        "Wat is zachter / beleefder?",
                        ["Kunt u dit controleren, alstublieft?", "Doe dit nu meteen.", "Controleer nu zonder groet."],
                        "Kunt u dit controleren, alstublieft?",
                    ),
                    mcq(
                        "m08-l07-b4",
                        "Ik kan niet vandaag",
                        ["Ik kan niet vandaag, want ik moet werken.", "Ik kan niet vandaag, want ik wil slapen altijd.", "Kan ik niet vandaag want."],
                        "Ik kan niet vandaag, want ik moet werken.",
                    ),
                    mcq(
                        "m08-l07-b5",
                        "Moeten in regel",
                        ["In Nederland moet u vaak een afspraak maken.", "In Nederland moet u nooit een afspraak.", "Moet u nooit afspraak Nederland."],
                        "In Nederland moet u vaak een afspraak maken.",
                    ),
                    mcq(
                        "m08-l07-b6",
                        "Check begrip",
                        ["Begrijpt u deze instructie?", "Begrijpt u zonder instructie?", "Begrijpt instructie u?"],
                        "Begrijpt u deze instructie?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m08-l07-sp1",
                "Production",
                "Ik moet dit formulier invullen.",
                ["Ik moet dit formulier invullen", "ik moet dit formulier invullen"],
                "Ik moet dit formulier invullen",
            ),
            speak_step(
                "m08-l07-sp2",
                "Production",
                "Kan ik morgen terugkomen?",
                ["Kan ik morgen terugkomen", "kan ik morgen terugkomen"],
                "Kan ik morgen terugkomen",
            ),
            speak_step(
                "m08-l07-sp3",
                "Production",
                "U moet eerst een nummer nemen.",
                ["U moet eerst een nummer nemen", "u moet eerst een nummer nemen"],
                "U moet eerst een nummer nemen",
            ),
            recap_step(
                "m08-l07-recap",
                "Recap",
                ["moeten", "kunnen", "invullen"],
                [
                    rt_fb("___ u dit formulier invullen? (must: u)", ["Moet", "Wil", "Kan"], "Moet"),
                    rt_ro(["terugkomen?", "ik", "morgen", "Kan"], "Kan ik morgen terugkomen?"),
                    rt_speak("Zeg: *Mag ik hulp krijgen?*", "Mag ik hulp krijgen?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "U mag geen vakken open laten.",
                        ["Regel over formulier", "Regel over eten", "Geen regel"],
                        "Regel over formulier",
                    ),
                    rt_fb("Ik kan niet vandaag, ___ ik ziek ben. (because)", ["want", "maar", "dus"], "want"),
                    rt_speak("Zeg: *U kunt hier wachten.*", "U kunt hier wachten."),
                ],
            ),
        ],
    }


def lesson_l08() -> dict:
    lid = "a2-m08-l08-writing-formal-messages-forms"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Writing · Simple formal messages and forms",
        "lessonType": "writing",
        "order": 7,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-admin-formal-u", "a2.2-admin-appointments"],
        "vocabTargets": ["lemma-afspraak-m8", "lemma-gemeente", "lemma-brief-m8", "lemma-alstublieft-m8", "lemma-met-vriendelijke-groet"],
        "canDoStatements": ["I can write a very short formal email fragment requesting an appointment or confirming details."],
        "mistakeFocus": ["register", "word-order"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m08-l08-preview",
                "Warm-up — 4 woorden",
                [
                    ("onderwerp", "onderwerp", "subject line", "📧"),
                    ("groet", "groet", "greeting", "👋"),
                    ("afsluiting", "afsluiting", "closing", "✉️"),
                    ("bevestigen", "bevestigen", "to confirm", "✔️"),
                ],
            ),
            listen_read_step(
                "m08-l08-lr",
                "Model — korte mail",
                [
                    (
                        "Jij (concept)",
                        "Onderwerp: Afspraak inschrijven — Amsterdam\n\nGeachte medewerker,\n\nIk wil graag een afspraak maken voor mijn inschrijving. Mijn naam is Li Wei. Kunt u bevestigen welke documenten ik nodig heb?\n\nMet vriendelijke groet,\nLi Wei",
                        "Subject: Appointment registration — Amsterdam\n\nDear staff member,\n\nI would like to make an appointment for my registration. My name is Li Wei. Could you confirm which documents I need?\n\nKind regards,\nLi Wei",
                    ),
                ],
                [
                    ("Wat wil Li in de mail?", ["Een afspraak voor inschrijving", "Een klacht over pizza", "Een baan bij de gemeente"],
                        "Een afspraak voor inschrijving"),
                    ("Hoe begint de mail formeel?", ["Geachte medewerker", "Hoi allemaal", "Hey"],
                        "Geachte medewerker"),
                    ("Welke vraag stelt Li?", ["Welke documenten nodig zijn", "Welke kleur het kantoor heeft", "Documenten welke zonder vraag"],
                        "Welke documenten nodig zijn"),
                    ("Hoe sluit Li af?", ["Met vriendelijke groet", "Groetjes zonder naam", "Doei"],
                        "Met vriendelijke groet"),
                ],
            ),
            discovery_step(
                "m08-l08-discovery",
                "Mail-skelet",
                [
                    ("Geachte …,", "Dear …,", "aanhef"),
                    ("Ik wil graag …", "I would like …", "doel"),
                    ("Kunt u …?", "Could you …?", "vraag"),
                    ("Met vriendelijke groet,", "Kind regards,", "afsluiting"),
                ],
            ),
            grammar_card(
                "m08-l08-gc",
                "Tip",
                "Kort houden",
                "3–5 zinnen is genoeg: **wie ben je** + **wat wil je** + **één duidelijke vraag**. Geen lange uitleg nodig.",
                [
                    ("Ik wil graag een afspraak maken voor volgende week.", "I'd like to make an appointment for next week."),
                    ("Kunt u mij een bevestiging sturen?", "Could you send me a confirmation?"),
                ],
            ),
            pl(
                "m08-l08-pl1",
                "Practice — 6×",
                ["geachte", "afspraak", "bevestigen"],
                [
                    mcq(
                        "m08-l08-a1",
                        "Beste openingszin (formeel)",
                        ["Geachte heer/mevrouw,", "Hoi chef,", "Hey gemeente,"],
                        "Geachte heer/mevrouw,",
                    ),
                    fb("m08-l08-a2", "Ik wil graag een ___ maken. (appointment)", ["afspraak", "broodje", "feest"], "afspraak"),
                    ro_tokens("m08-l08-r1", ["nodig?", "documenten", "Welke", "heb", "ik"], "Welke documenten heb ik nodig?"),
                    mcq(
                        "m08-l08-a3",
                        "Beleefd verzoek",
                        ["Zou u mijn aanvraag willen bevestigen?", "Zou u nu stoppen?", "Bevestigen u mijn zonder vraag?"],
                        "Zou u mijn aanvraag willen bevestigen?",
                    ),
                    mcq(
                        "m08-l08-a4",
                        "Fout register",
                        ["Ik kom morgen, oké? doei — te informeel voor deze mail", "Met vriendelijke groet — passend", "Geachte — altijd fout"],
                        "Ik kom morgen, oké? doei — te informeel voor deze mail",
                    ),
                    mcq(
                        "m08-l08-a5",
                        "Onderwerpregel",
                        ["Afspraak inschrijving — naam", "Pizza bestellen — naam", "Zonder onderwerp"],
                        "Afspraak inschrijving — naam",
                    ),
                    mcq(
                        "m08-l08-a6",
                        "Sluiten",
                        ["Met vriendelijke groet,", "Groetjes haha,", "Bye bye,"],
                        "Met vriendelijke groet,",
                    ),
                ],
            ),
            pl(
                "m08-l08-pl2",
                "Variatie — 6×",
                ["antwoord", "datum", "telefoon"],
                [
                    mcq(
                        "m08-l08-b1",
                        "Vraag om terugbelen",
                        ["Kunt u mij bellen op dit nummer?", "Kunt u mij bellen zonder nummer?", "Bellen u mij kunt?"],
                        "Kunt u mij bellen op dit nummer?",
                    ),
                    fb("m08-l08-b2", "Ik ben beschikbaar op ___ 10 juni. (Tuesday)", ["dinsdag", "januari", "nacht"], "dinsdag"),
                    ro_tokens("m08-l08-r2", ["bevestigen.", "graag", "Ik", "wil", "een"], "Ik wil graag een bevestiging."),
                    mcq(
                        "m08-l08-b3",
                        "Als je twijfelt over de toon",
                        ["Kies formele zinnen aan de gemeente", "Kies straattaal", "Gebruik alleen emoji’s"],
                        "Kies formele zinnen aan de gemeente",
                    ),
                    mcq(
                        "m08-l08-b4",
                        "Korte zin over doel",
                        ["Ik schrijf u over mijn inschrijving.", "Ik schrijf u over mijn vakantie.", "Schrijf ik u over."],
                        "Ik schrijf u over mijn inschrijving.",
                    ),
                    mcq(
                        "m08-l08-b5",
                        "‘Met vriendelijke groet’ + naam",
                        ["Correct: afsluiting + nieuwe regel + naam", "Fout: geen naam", "Fout: alleen emoji"],
                        "Correct: afsluiting + nieuwe regel + naam",
                    ),
                    mcq(
                        "m08-l08-b6",
                        "Spam / overdrijving vermijden",
                        ["Eén duidelijke vraag is genoeg.", "Zet twintig vragen in één zin.", "Geen vragen stellen."],
                        "Eén duidelijke vraag is genoeg.",
                    ),
                ],
                depth=True,
            ),
            writing_step(
                "m08-l08-w1",
                "Schrijven — afspraak",
                "Schrijf 3–4 korte zinnen (u tegen de gemeente): u wilt een afspraak voor inschrijving; noem uw naam; vraag welke documenten nodig zijn.",
                [
                    "geachte",
                    "afspraak",
                    "inschrijving",
                    "mijn naam is",
                    "documenten",
                    "nodig",
                    "met vriendelijke groet",
                ],
                "Geachte medewerker, ik wil graag een afspraak maken voor mijn inschrijving. Mijn naam is Sofia Mendes. Welke documenten heb ik nodig? Met vriendelijke groet, Sofia Mendes",
                min_chars=40,
            ),
            speak_step(
                "m08-l08-sp1",
                "Hardop — kernzin",
                "Ik wil graag een afspraak maken voor mijn inschrijving.",
                [
                    "Ik wil graag een afspraak maken voor mijn inschrijving",
                    "ik wil graag een afspraak maken voor mijn inschrijving",
                ],
                "Ik wil graag een afspraak maken voor mijn inschrijving",
            ),
            writing_step(
                "m08-l08-w2",
                "Schrijven — bevestiging",
                "Schrijf 2–3 zinnen: u bevestigt uw adres en vraagt of de afspraakdatum klopt.",
                [
                    "mijn adres is",
                    "postcode",
                    "klopt",
                    "afspraak",
                    "bevestigen",
                ],
                "Mijn adres is Nieuwezijds Voorburgwal 100, 1012 AB Amsterdam. Klopt de afspraak op 12 juni om 11:00? Kunt u dat bevestigen? Met vriendelijke groet",
                min_chars=35,
            ),
            speak_step(
                "m08-l08-sp2",
                "Hardop",
                "Kunt u bevestigen of de datum klopt?",
                ["Kunt u bevestigen of de datum klopt", "kunt u bevestigen of de datum klopt"],
                "Kunt u bevestigen of de datum klopt",
            ),
            recap_step(
                "m08-l08-recap",
                "Recap",
                ["geachte", "afspraak", "groet"],
                [
                    rt_fb("___ medewerker, (formal dear)", ["Geachte", "Hoi", "Hey"], "Geachte"),
                    rt_speak("Zeg: *Met vriendelijke groet.*", "Met vriendelijke groet."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Kunt u bevestigen welke documenten ik nodig heb?",
                        ["Vraag om documentenlijst", "Vraag om koffie", "Stop de mail"],
                        "Vraag om documentenlijst",
                    ),
                    rt_ro(["maken.", "afspraak", "een", "graag", "wil", "Ik"], "Ik wil graag een afspraak maken."),
                    rt_fb("Welke documenten heb ik ___? (need)", ["nodig", "lekker", "warm"], "nodig"),
                    rt_speak("Zeg: *Kunt u dat uitleggen?*", "Kunt u dat uitleggen?"),
                ],
            ),
        ],
    }
