/**
 * Seed KMN content (Dutch A2 / inburgering-oriented). Extend via this file or future CMS.
 */
import type { KmnFlashcardDef, KmnQuizQuestion, KmnScenario } from '@/lib/exam-prep/kmn/types'

export const KMN_QUIZ_QUESTIONS: KmnQuizQuestion[] = [
  {
    id: 'q-work-1',
    topicId: 'work',
    subtopicId: 'contracts',
    level: 1,
    sceneId: 'employment_contract',
    promptNl: 'Wat heeft u minstens nodig om legaal te werken in Nederland?',
    options: [
      { id: 'a', labelNl: 'Alleen een bankrekening' },
      { id: 'b', labelNl: 'Toestemming om te werken (indien nodig) en een geldig contract of afspraken' },
      { id: 'c', labelNl: 'Alleen een rijbewijs' },
      { id: 'd', labelNl: 'Een uitnodiging van de buurman' },
    ],
    correctOptionId: 'b',
    explanationNl:
      'U heeft een geldige werkrelatie (contract of duidelijke afspraken) en, afhankelijk van uw situatie, een verblijfsvergunning waarin werken mag.',
    linkedReviewItemId: 'kmn-flash-work-contract',
  },
  {
    id: 'q-work-2',
    topicId: 'work',
    subtopicId: 'hours',
    level: 2,
    sceneId: 'employment_contract',
    promptNl: 'Uw contract zegt 40 uur per week. Uw werkgever vraagt elke week structureel 48 uur zonder extra betaling. Wat is het meest praktische eerste stap?',
    options: [
      { id: 'a', labelNl: 'Direct ontslag nemen' },
      { id: 'b', labelNl: 'Het gesprek aangaan en contract/regels checken; zo nodig vakbond of juridisch loket' },
      { id: 'c', labelNl: 'Gewoon meewerken zonder vragen' },
      { id: 'd', labelNl: 'Een klacht bij de politie' },
    ],
    correctOptionId: 'b',
    explanationNl: 'Eerst helderheid: contract en cao. Daarna kunt u ondersteuning zoeken (vakbond, juridisch loket, inspectie).',
    linkedReviewItemId: 'kmn-flash-work-hours',
  },
  {
    id: 'q-work-3',
    topicId: 'work',
    subtopicId: 'taxes_work',
    level: 1,
    sceneId: 'payslip_document',
    promptNl: 'Waarom ziet u op uw loonstrook minder geld dan uw “bruto” loon?',
    options: [
      { id: 'a', labelNl: 'Omdat de werkgever een cadeau inhoudt' },
      { id: 'b', labelNl: 'Omdat loonheffing (belasting en premies) wordt ingehouden' },
      { id: 'c', labelNl: 'Omdat de bank kosten rekent' },
      { id: 'd', labelNl: 'Dat mag niet in Nederland' },
    ],
    correctOptionId: 'b',
    explanationNl: 'Uw werkgever houdt loonheffing in en betaalt dat door aan de Belastingdienst.',
    linkedReviewItemId: 'kmn-flash-work-loonstrook',
  },
  {
    id: 'q-health-1',
    topicId: 'healthcare',
    subtopicId: 'gp',
    level: 1,
    sceneId: 'gp_waiting_room',
    promptNl: 'U bent ziek (geen spoed) en heeft medisch advies nodig. Wat is meestal de eerste stap?',
    options: [
      { id: 'a', labelNl: 'Naar de spoedeisende hulp zonder bellen' },
      { id: 'b', labelNl: 'Contact met uw huisartsenpraktijk' },
      { id: 'c', labelNl: 'Alleen naar de apotheek voor zware medicijnen op recept' },
      { id: 'd', labelNl: 'Een specialist bellen zonder verwijzing' },
    ],
    correctOptionId: 'b',
    explanationNl: 'In Nederland start niet-spoedeisende zorg bijna altijd bij de huisarts, die zo nodig doorverwijst.',
    linkedReviewItemId: 'kmn-flash-health-huisarts',
  },
  {
    id: 'q-health-2',
    topicId: 'healthcare',
    subtopicId: 'insurance',
    level: 2,
    sceneId: 'health_insurance_letter',
    promptNl: 'Wat is het “eigen risico” in de basisverzekering?',
    options: [
      { id: 'a', labelNl: 'Een boete als u te laat betaalt' },
      { id: 'b', labelNl: 'Een jaarlijks bedrag dat u eerst zelf betaalt voor veel zorg uit de basisverzekering' },
      { id: 'c', labelNl: 'Het bedrag dat de overheid betaalt' },
      { id: 'd', labelNl: 'Alleen voor tandarts' },
    ],
    correctOptionId: 'b',
    explanationNl: 'Eigen risico geldt voor veel zorg uit de basisverzekering; huisartsbezoek valt daar vaak buiten.',
    linkedReviewItemId: 'kmn-flash-health-eigenrisico',
  },
  {
    id: 'q-health-3',
    topicId: 'healthcare',
    subtopicId: 'emergency',
    level: 1,
    sceneId: 'emergency_112_phone',
    promptNl: 'Levensgevaar of direct gevaar voor leven — welk nummer belt u in Nederland?',
    options: [
      { id: 'a', labelNl: '0800-info' },
      { id: 'b', labelNl: '112' },
      { id: 'c', labelNl: '0900-therapist' },
      { id: 'd', labelNl: '1424' },
    ],
    correctOptionId: 'b',
    explanationNl: '112 is voor acute hulp (ambulance, brandweer, politie). Bij twijfel over “spoed maar niet levensgevaar”: huisartsenpost/lijn.',
    linkedReviewItemId: 'kmn-flash-health-112',
  },
  {
    id: 'q-gov-1',
    topicId: 'government',
    subtopicId: 'municipality',
    level: 1,
    promptNl: 'U verhuist binnen Nederland naar een nieuw adres. Waar moet u zich meestal inschrijven?',
    options: [
      { id: 'a', labelNl: 'Alleen bij de bank' },
      { id: 'b', labelNl: 'Bij de gemeente (adres melden)' },
      { id: 'c', labelNl: 'Alleen bij uw werkgever' },
      { id: 'd', labelNl: 'Nergens — dat gebeurt automatisch' },
    ],
    correctOptionId: 'b',
    explanationNl: 'U meldt uw nieuwe adres bij de gemeente; dat is wettelijk verplicht binnen een termijn.',
    linkedReviewItemId: 'kmn-flash-gov-gemeente',
  },
  {
    id: 'q-gov-2',
    topicId: 'government',
    subtopicId: 'bsn',
    level: 1,
    sceneId: 'passport_application',
    promptNl: 'Wat is een BSN?',
    options: [
      { id: 'a', labelNl: 'Een bankpas' },
      { id: 'b', labelNl: 'Een persoonsnummer voor contact met overheid en veel instanties' },
      { id: 'c', labelNl: 'Een rijbewijsnummer' },
      { id: 'd', labelNl: 'Een belastingtarief' },
    ],
    correctOptionId: 'b',
    explanationNl: 'Het burgerservicenummer koppelt u aan administratieve processen (werk, belasting, zorg).',
    linkedReviewItemId: 'kmn-flash-gov-bsn',
  },
  {
    id: 'q-gov-3',
    topicId: 'government',
    subtopicId: 'taxes_benefits',
    level: 2,
    promptNl: 'Waarvoor gebruikt u de website “Mijn toeslagen”?',
    options: [
      { id: 'a', labelNl: 'Om boodschappen te bestellen' },
      { id: 'b', labelNl: 'Om huur- of zorgtoeslag e.d. te regelen en wijzigingen door te geven' },
      { id: 'c', labelNl: 'Alleen om een paspoort aan te vragen' },
      { id: 'd', labelNl: 'Om een rijbewijs te verlengen' },
    ],
    correctOptionId: 'b',
    explanationNl: 'Toeslagen regelt u via de Belastingdienst / Mijn toeslagen; wijzigingen in inkomen of huur moeten u vaak melden.',
    linkedReviewItemId: 'kmn-flash-gov-toeslagen',
  },
  {
    id: 'q-cult-1',
    topicId: 'culture',
    subtopicId: 'directness',
    level: 1,
    sceneId: 'handshake_greeting',
    promptNl: 'Een collega zegt: “Ik vind dit plan niet goed.” Wat is vaak de bedoeling in Nederland?',
    options: [
      { id: 'a', labelNl: 'Een persoonlijke belediging' },
      { id: 'b', labelNl: 'Vaak directe feedback op het idee, niet per se aanval op u als persoon' },
      { id: 'c', labelNl: 'Ze willen ontslag' },
      { id: 'd', labelNl: 'Ze mogen u niet' },
    ],
    correctOptionId: 'b',
    explanationNl: 'Nederlandse communicatie kan kort en direct zijn; inhoudelijk kritisch betekent niet altijd onvriendelijkheid.',
    linkedReviewItemId: 'kmn-flash-cult-direct',
  },
  {
    id: 'q-cult-2',
    topicId: 'culture',
    subtopicId: 'appointments',
    level: 1,
    sceneId: 'handshake_greeting',
    promptNl: 'U heeft een afspraak om 10:00. Wat wordt het meest gewaardeerd?',
    options: [
      { id: 'a', labelNl: '10:15 komen zonder bericht' },
      { id: 'b', labelNl: 'Ongeveer op tijd komen of tijdig afzeggen' },
      { id: 'c', labelNl: 'Een uur te laat is normaal' },
      { id: 'd', labelNl: 'Alleen een app sturen terwijl u niet komt' },
    ],
    correctOptionId: 'b',
    explanationNl: 'Punctualiteit en tijdig afmelden helpen vertrouwen; te laat zonder bericht voelt vaak respectloos.',
    linkedReviewItemId: 'kmn-flash-cult-afspraak',
  },
  {
    id: 'q-cult-3',
    topicId: 'culture',
    subtopicId: 'social',
    level: 2,
    sceneId: 'integration_neighborhood',
    promptNl: 'U wordt uitgenodigd voor een verjaardag bij buren. Wat is gebruikelijk?',
    options: [
      { id: 'a', labelNl: 'Leeg aankomen zonder iets te zeggen' },
      { id: 'b', labelNl: 'Vaak een klein cadeautje of bloemen en de gastvrouw/heer begroeten' },
      { id: 'c', labelNl: 'Direct naar de koelkast lopen' },
      { id: 'd', labelNl: 'Niet reageren op de uitnodiging' },
    ],
    correctOptionId: 'b',
    explanationNl: 'Een klein gebaar en een begroeting (“gefeliciteerd”) passen goed; exacte gewoonten verschillen per gezin.',
    linkedReviewItemId: 'kmn-flash-cult-verjaardag',
  },
]

export const KMN_FLASHCARDS: KmnFlashcardDef[] = [
  {
    id: 'work-contract',
    topicId: 'work',
    subtopicId: 'contracts',
    frontNl: 'Proeftijd (proeftijdperiode)',
    backNl: 'Een korte beginperiode waarin werkgever en werknemer kunnen beëindigen met kortere termijn, volgens wet en contract.',
    exampleNl: 'Lees uw contract: hoeveel maanden proeftijd en wat zijn de opzegtermijnen?',
  },
  {
    id: 'work-hours',
    topicId: 'work',
    subtopicId: 'hours',
    frontNl: 'Maximum aan werktijd (richtlijn)',
    backNl: 'Fulltime is vaak rond 36–40 uur per week; overwerk en pauzes staan in wet of cao.',
    exampleNl: 'Te veel structureel overwerk zonder afspraak: vraag naar regels en compensatie.',
  },
  {
    id: 'work-loonstrook',
    topicId: 'work',
    subtopicId: 'taxes_work',
    frontNl: 'Bruto vs netto',
    backNl: 'Bruto is vóór inhoudingen; netto is wat op uw rekening komt na loonheffing en andere inhoudingen.',
    exampleNl: 'Vergelijk maanden om te zien of inhoudingen logisch zijn.',
  },
  {
    id: 'health-huisarts',
    topicId: 'healthcare',
    subtopicId: 'gp',
    frontNl: 'Huisarts',
    backNl: 'Uw vaste arts voor niet-spoedeisende klachten, verwijzingen en veel voorschriften.',
    exampleNl: 'Blijf ingeschreven bij een praktijk in uw buurt.',
  },
  {
    id: 'health-eigenrisico',
    topicId: 'healthcare',
    subtopicId: 'insurance',
    frontNl: 'Eigen risico (zorg)',
    backNl: 'Jaarlijks bedrag dat u eerst zelf betaalt voor veel zorg uit de basisverzekering (met uitzonderingen).',
    exampleNl: 'Huisartsbezoek telt meestal niet mee voor het eigen risico.',
  },
  {
    id: 'health-112',
    topicId: 'healthcare',
    subtopicId: 'emergency',
    frontNl: '112',
    backNl: 'Alarmnummer bij direct levensgevaar of acute hulp nodig.',
    exampleNl: 'Bij twijfel: 112 bij levensgevaar; anders huisartsenlijn/post.',
  },
  {
    id: 'gov-gemeente',
    topicId: 'government',
    subtopicId: 'municipality',
    frontNl: 'Gemeente — inschrijving',
    backNl: 'U meldt woonadres en regelt veel paspoort/ID- en lokale zaken bij de gemeente.',
    exampleNl: 'Na verhuizing binnen NL: adres wijzigen binnen de wettelijke termijn.',
  },
  {
    id: 'gov-bsn',
    topicId: 'government',
    subtopicId: 'bsn',
    frontNl: 'BSN',
    backNl: 'Burgerservicenummer: uniek nummer voor overheid en veel organisaties.',
    exampleNl: 'U krijgt het bij registratie in de Basisregistratie Personen.',
  },
  {
    id: 'gov-toeslagen',
    topicId: 'government',
    subtopicId: 'taxes_benefits',
    frontNl: 'Toeslagen',
    backNl: 'Financiële steun (bijv. huur/zorg) op basis van inkomen en situatie — aanvragen en wijzigingen melden.',
    exampleNl: 'Wijziging in inkomen of gezin? Doorgeven om geen schulden op te bouwen.',
  },
  {
    id: 'cult-direct',
    topicId: 'culture',
    subtopicId: 'directness',
    frontNl: 'Directe stijl',
    backNl: 'Vaak inhoudelijk en kort; minder kleine praatjes dan elders; niet automatisch onvriendelijk bedoeld.',
    exampleNl: '“Nee” kan een normaal antwoord zijn zonder slechte bedoeling.',
  },
  {
    id: 'cult-afspraak',
    topicId: 'culture',
    subtopicId: 'appointments',
    frontNl: 'Op tijd / afzeggen',
    backNl: 'Afspraken serieus nemen; te laat of no-show zonder bericht schaadt vertrouwen.',
    exampleNl: 'Bel of app tijdig als u vertraging heeft.',
  },
  {
    id: 'cult-verjaardag',
    topicId: 'culture',
    subtopicId: 'social',
    frontNl: 'Verjaardag — cirkel',
    backNl: 'Bij sommige feestjes feliciteert men de jarige en gaat men langs gasten in een “kring”.',
    exampleNl: 'Niet overal hetzelfde; let op wat de gastheer/vrouw doet.',
  },
]

export const KMN_SCENARIOS: KmnScenario[] = [
  {
    id: 'sc-work-contract',
    topicId: 'work',
    subtopicId: 'contracts',
    level: 2,
    titleNl: 'Nieuw contract',
    situationNl:
      'U krijgt een contract waarin staat dat uw proeftijd 2 jaar is en u geen vakantiedagen heeft in het eerste jaar. U voelt zich onzeker.',
    choices: [
      {
        id: 'a',
        labelNl: 'Tekenen zonder vragen, anders geen baan',
        isCorrect: false,
        feedbackNl: 'U mag altijd vragen stellen. Extreme clausules zijn een signaal om hulp te zoeken (vakbond/juridisch loket).',
      },
      {
        id: 'b',
        labelNl: 'Rustig vragen om uitleg en wetten/cao te checken voordat u tekent',
        isCorrect: true,
        feedbackNl: 'Goed — helderheid over proeftijd en verlof voorkomt problemen later.',
      },
      {
        id: 'c',
        labelNl: 'Het contract publiekelijk op social media zetten',
        isCorrect: false,
        feedbackNl: 'Eerst professioneel informeren en juridische advieslijnen gebruiken werkt meestal beter.',
      },
    ],
    linkedReviewItemId: 'kmn-flash-work-contract',
  },
  {
    id: 'sc-health-sick',
    topicId: 'healthcare',
    subtopicId: 'gp',
    level: 1,
    titleNl: 'U bent ziek (geen spoed)',
    situationNl: 'Het is maandagochtend; u heeft koorts en keelpijn maar ademt normaal en heeft geen ernstige pijn op de borst.',
    choices: [
      {
        id: 'a',
        labelNl: 'Meteen naar de spoedeisende hulp rijden',
        isCorrect: false,
        feedbackNl: 'Spoedeisende hulp is voor acute, ernstige situaties. Start meestal met huisarts/telefoonlijn.',
      },
      {
        id: 'b',
        labelNl: 'Huisartsenpraktijk bellen of online afspraak maken volgens instructies van uw praktijk',
        isCorrect: true,
        feedbackNl: 'Juist — de huisarts coördineert niet-spoedeisende zorg.',
      },
      {
        id: 'c',
        labelNl: 'Een week wachten zonder iets te doen',
        isCorrect: false,
        feedbackNl: 'Bij ziekte die niet overgaat: contact met huisarts; bij verslechtering eerder bellen.',
      },
    ],
    linkedReviewItemId: 'kmn-flash-health-huisarts',
  },
  {
    id: 'sc-gov-move',
    topicId: 'government',
    subtopicId: 'municipality',
    level: 1,
    titleNl: 'Verhuizing',
    situationNl: 'U verhuist volgende maand naar een andere stad in Nederland.',
    choices: [
      {
        id: 'a',
        labelNl: 'Niets doen — de post komt vanzelf mee',
        isCorrect: false,
        feedbackNl: 'U moet uw adres bij de gemeente melden; anders kloppen officiële gegevens niet.',
      },
      {
        id: 'b',
        labelNl: 'Na inschrijving op het nieuwe adres dit melden bij de gemeente (en andere instanties bijwerken)',
        isCorrect: true,
        feedbackNl: 'Goed — gemeente-inschrijving is de kernstap; daarna bank, werkgever, etc. bijwerken.',
      },
      {
        id: 'c',
        labelNl: 'Alleen de buurman informeren',
        isCorrect: false,
        feedbackNl: 'Privé fijn, maar wettelijk moet het via de gemeente.',
      },
    ],
    linkedReviewItemId: 'kmn-flash-gov-gemeente',
  },
  {
    id: 'sc-cult-visit',
    topicId: 'culture',
    subtopicId: 'social',
    level: 2,
    titleNl: 'Bezoek op de koffie',
    situationNl: 'U bent voor het eerst op bezoek bij een Nederlandse collega. De deur gaat open.',
    choices: [
      {
        id: 'a',
        labelNl: 'Binnenlopen zonder te groeten en op de bank gaan zitten',
        isCorrect: false,
        feedbackNl: 'Een begroeting en vaak schoenen uit (als gevraagd) hoort bij respectvol binnenkomen.',
      },
      {
        id: 'b',
        labelNl: 'Begroeten, hand geven of knikken, en wachten tot u wordt binnengenodigd',
        isCorrect: true,
        feedbackNl: 'Netjes — let op signalen (schoenen, plek aan tafel).',
      },
      {
        id: 'c',
        labelNl: 'Direct de koelkast openen',
        isCorrect: false,
        feedbackNl: 'Wacht op de gastheer/vrouw; niet zelf de keuken overnemen tenzij uitgenodigd.',
      },
    ],
    linkedReviewItemId: 'kmn-flash-cult-verjaardag',
  },
  {
    id: 'sc-work-overtime',
    topicId: 'work',
    subtopicId: 'hours',
    level: 3,
    titleNl: 'Structureel overwerk',
    situationNl: 'Als u elke week 8 uur extra werkt zonder dat uw contract dat zegt, en er is geen extra loon.',
    choices: [
      {
        id: 'a',
        labelNl: 'Zwijgen om problemen te vermijden',
        isCorrect: false,
        feedbackNl: 'Langdurig kan dit uitputting geven; check cao/contract en zoek steun.',
      },
      {
        id: 'b',
        labelNl: 'Formeel vragen naar afspraken over overwerk en vergoeding; documenteer uren',
        isCorrect: true,
        feedbackNl: 'Praktisch en beschermend — helderheid over verwachtingen en betaling.',
      },
      {
        id: 'c',
        labelNl: 'Direct stoppen zonder gesprek',
        isCorrect: false,
        feedbackNl: 'Eerst in gesprek gaan voorkomt onnodige conflict; bij misbruik: vakbond/advies.',
      },
    ],
    linkedReviewItemId: 'kmn-flash-work-hours',
  },
  {
    id: 'sc-health-insurance',
    topicId: 'healthcare',
    subtopicId: 'insurance',
    level: 2,
    titleNl: 'Zorgnota',
    situationNl: 'U krijgt een rekening van €400 van de specialist. U dacht dat de basis alles dekte.',
    choices: [
      {
        id: 'a',
        labelNl: 'Niet betalen en hopen dat het weggaat',
        isCorrect: false,
        feedbackNl: 'Negeer rekeningen niet; check dekking, eigen risico en eventueel verzekering.',
      },
      {
        id: 'b',
        labelNl: 'Controleren of het onder eigen risico valt en met zorgverzekeraar/ zorgaanbieder navragen',
        isCorrect: true,
        feedbackNl: 'Slim — vaak speelt eigen risico of niet-gedekte posten mee.',
      },
      {
        id: 'c',
        labelNl: 'Meteen naar de rechtbank',
        isCorrect: false,
        feedbackNl: 'Eerst helderheid bij verzekeraar en factuur — juridische stappen zijn laatste redmiddel.',
      },
    ],
    linkedReviewItemId: 'kmn-flash-health-eigenrisico',
  },
  {
    id: 'sc-gov-bsn-letter',
    topicId: 'government',
    subtopicId: 'bsn',
    level: 1,
    titleNl: 'Brief van de Belastingdienst',
    situationNl: 'U krijgt een brief met termijn om iets in te vullen. U begrijpt het niet goed.',
    choices: [
      {
        id: 'a',
        labelNl: 'De brief weggooien',
        isCorrect: false,
        feedbackNl: 'Officiële termijnen kunnen gevolgen hebben; vraag hulp bij belastingwinkel of belastingadviseur.',
      },
      {
        id: 'b',
        labelNl: 'Hulp zoeken (telefoon Belastingdienst, belastingwinkel, taalhulp) vóór de deadline',
        isCorrect: true,
        feedbackNl: 'Goed — vroeg vragen voorkomt boetes en stress.',
      },
      {
        id: 'c',
        labelNl: 'Wachten tot er een tweede brief komt',
        isCorrect: false,
        feedbackNl: 'Soms is er geen herinnering; beter actief hulp zoeken.',
      },
    ],
    linkedReviewItemId: 'kmn-flash-gov-bsn',
  },
  {
    id: 'sc-cult-feedback',
    topicId: 'culture',
    subtopicId: 'directness',
    level: 2,
    titleNl: 'Korte reactie op uw idee',
    situationNl: 'Uw teamleider zegt: “Dit voorstel is nu niet haalbaar.” U voelt zich aangevallen.',
    choices: [
      {
        id: 'a',
        labelNl: 'Meteen emotioneel reageren in de vergadering',
        isCorrect: false,
        feedbackNl: 'Een korte pauze en doorvragen helpt: vaak gaat het om planning of middelen, niet om u.',
      },
      {
        id: 'b',
        labelNl: 'Doorvragen wat “niet haalbaar” betekent en welke voorwaarden wél zouden helpen',
        isCorrect: true,
        feedbackNl: 'Sterk — u maakt directe feedback productief.',
      },
      {
        id: 'c',
        labelNl: 'Nooit meer ideeën delen',
        isCorrect: false,
        feedbackNl: 'Directe cultuur wil inhoud; blijf constructief deelnemen.',
      },
    ],
    linkedReviewItemId: 'kmn-flash-cult-direct',
  },
]
