import type { WeaknessCategoryDefinition } from '@/lib/weakness/types'

/**
 * Learner-facing taxonomy — grounded in mistake tags, error types, and practice heuristics.
 * Order is not ranking priority; use `priority` on each row.
 */
export const WEAKNESS_CATEGORY_DEFINITIONS: WeaknessCategoryDefinition[] = [
  {
    id: 'question_word_order',
    priority: 45,
    matchTags: [/word[-_]?order/, /inversion/, /verb.?second/, /\bv2\b/, /question.*(word|order)/, /aux_verb/, /auxiliary/],
    matchErrorTypes: ['order'],
    matchMistakeCategories: ['word_order', 'aux_verb'],
    headlines: [
      'Question word order still needs a little rhythm',
      'Word order in questions is still tricky',
    ],
    coachLine:
      'Dutch often pulls the verb forward in questions — short scenarios plus tiny writing reps make it automatic.',
    scenarioIds: ['train', 'work', 'municipality'],
    skillTrackId: 'writing_messages',
    reviewHref: '/app/review/mistakes',
  },
  {
    id: 'polite_requests',
    priority: 42,
    matchTags: [/polite/, /request/, /modal/, /graag/, /alstublieft/, /would like/, /kunnen we/, /mag ik/],
    matchMistakeCategories: ['politeness'],
    headlines: ['Polite requests still need a bit of polish', 'Service Dutch — polite forms — is still shaky'],
    coachLine: 'Shops, doctors, and gemeente all expect short, polite Dutch — worth a focused rep.',
    scenarioIds: ['cafe', 'doctor', 'municipality'],
    skillTrackId: 'writing_messages',
    reviewHref: '/app/review/mistakes',
  },
  {
    id: 'listening_fast',
    priority: 44,
    // Avoid bare `/gist/` — lesson “gist” weak tags are not necessarily listening-mode / fast audio.
    matchTags: [
      /\blisten(ing)?\b/,
      /\b(hearing|audio|playback|tts)\b/,
      /fast.*speech/,
      /comprehension/,
      /listening-fast/,
      /\b(listen|hearing|audio).*\bgist\b|\bgist\b.*\b(listen|hearing|audio)\b/,
    ],
    matchErrorTypes: ['listening'],
    matchMistakeCategories: ['listening_comprehension'],
    headlines: ['Listening to fast Dutch is still weak', 'Catching spoken Dutch on the first try is still hard'],
    coachLine: 'Short listening bursts train gist and detail without the pressure of a full chat.',
    scenarioIds: ['train', 'doctor', 'work'],
    skillTrackId: 'listening_confidence',
    reviewHref: '/app/review/daily',
  },
  {
    id: 'conversation_repair',
    priority: 43,
    matchTags: [/repair/, /clarif/, /repeat/, /conversation-repair/, /misunder/, /pardon/, /sorry.*(mean|say)/],
    headlines: ['Clarifying and repairing is still uncomfortable', 'You could use smoother “repair” lines'],
    coachLine: 'Knowing how to ask for repetition or clarify keeps real talks moving — low stakes to drill.',
    scenarioIds: ['problem_solving', 'social_plans', 'supermarket_shop'],
    skillTrackId: 'conversation_repair',
    reviewHref: '/app/review/daily',
  },
  {
    id: 'admin_formal',
    priority: 38,
    matchTags: [/admin/, /formal/, /gemeente/, /document/, /register/, /official/],
    headlines: ['Admin and formal Dutch still needs practice', 'Official settings still feel stiff'],
    coachLine: 'Gemeente and housing messages use a calmer, clearer register — worth isolating.',
    scenarioIds: ['municipality', 'housing', 'work'],
    skillTrackId: 'reading_real_life',
    reviewHref: '/app/review/mistakes',
  },
  {
    id: 'speaking_fluency',
    priority: 41,
    matchTags: [/register-mix/, /english/, /hesitation/, /pronunciation/, /fluenc/, /speaking/],
    matchErrorTypes: ['hesitation', 'pronunciation'],
    matchMistakeCategories: ['pronunciation', 'hesitation'],
    headlines: ['Speaking smoothly is still the bottleneck', 'Getting Dutch out without freezing needs reps'],
    coachLine: 'Tiny speaking prompts build momentum before long scenarios.',
    scenarioIds: ['cafe', 'social_plans', 'doctor'],
    skillTrackId: 'speaking_fluency',
    reviewHref: '/app/review/daily',
  },
  {
    id: 'symptom_descriptions',
    priority: 36,
    matchTags: [/symptom/, /pain/, /health/, /doctor/, /pharmacy/, /feel ill/],
    headlines: ['Describing symptoms clearly is still tricky', 'Health Dutch needs a few more reps'],
    coachLine: 'Short, precise symptom lines help at huisarts and apotheek.',
    scenarioIds: ['doctor', 'supermarket_shop'],
    reviewHref: '/app/review/mistakes',
  },
  {
    id: 'transport_questions',
    priority: 37,
    matchTags: [/platform/, /ticket/, /station/, /train/, /bus/, /depart/, /track/],
    headlines: ['Transport questions still need work', 'Station Dutch — platforms and times — is still shaky'],
    coachLine: 'Trains and buses are high-frequency — quick scenario reps lock the patterns.',
    scenarioIds: ['train', 'municipality'],
    skillTrackId: 'listening_confidence',
    reviewHref: '/app/review/daily',
  },
  {
    id: 'separable_verbs',
    priority: 35,
    matchTags: [/separable/, /particle/, /phrasal/, /prefix/],
    headlines: ['Separable verbs still trip you up', 'Verb particles in Dutch still need attention'],
    coachLine: 'Shopping and travel sentences hide lots of separable verbs — micro-writing helps.',
    scenarioIds: ['supermarket_shop', 'train', 'housing'],
    skillTrackId: 'writing_messages',
    reviewHref: '/app/review/mistakes',
  },
  {
    id: 'time_phrases',
    priority: 34,
    matchTags: [/time phrase/, /appointment/, /\b(when|wanneer)\b/, /schedule/, /opening/],
    headlines: ['Time and scheduling language needs practice', 'Making appointments in Dutch is still wobbly'],
    coachLine: 'Work and admin flows lean on dates and times — worth a focused pass.',
    scenarioIds: ['work', 'doctor', 'municipality'],
    skillTrackId: 'writing_messages',
    reviewHref: '/app/review/mistakes',
  },
  {
    id: 'sentence_linking',
    priority: 33,
    matchTags: [/linking/, /\bwant\b/, /omdat/, /because/, /daarom/, /dus/],
    headlines: ['Linking ideas in one flow is still hard', 'Connecting sentences smoothly needs reps'],
    coachLine: 'Meetings and chats need short linked sentences — semi-guided scenarios are ideal.',
    scenarioIds: ['work', 'social_plans'],
    skillTrackId: 'writing_messages',
    reviewHref: '/app/review/daily',
  },
  {
    id: 'vocab_clarity',
    priority: 32,
    matchTags: [/vocab/, /word choice/, /lemma/, /spelling/],
    matchErrorTypes: ['vocab', 'spelling'],
    matchMistakeCategories: ['vocab_confusion', 'spelling'],
    headlines: ['Word choice and spelling still slip', 'Vocabulary accuracy needs a little reinforcement'],
    coachLine: 'Review plus a short scenario re-anchors words in context.',
    scenarioIds: ['supermarket_shop', 'cafe', 'housing'],
    reviewHref: '/app/review/mistakes',
  },
  {
    id: 'grammar_clarity',
    priority: 31,
    matchTags: [/grammar/, /article/, /adjective/, /ending/],
    matchErrorTypes: ['grammar'],
    matchMistakeCategories: ['grammar'],
    headlines: ['Grammar clarity still needs tightening', 'Small grammar patterns are still inconsistent'],
    coachLine: 'Short review rounds plus one targeted scenario beat long theory blocks.',
    scenarioIds: ['supermarket_shop', 'municipality', 'work'],
    reviewHref: '/app/review/mistakes',
  },
]

export function getWeaknessCategoryById(id: string): WeaknessCategoryDefinition | undefined {
  return WEAKNESS_CATEGORY_DEFINITIONS.find((c) => c.id === id)
}
