from .common import (
    LM,
    MID,
    discovery_step,
    fb,
    listening_step,
    match_ex,
    mcq,
    pl,
    preview_step,
    recap_step,
    ro_tokens,
    rt_fb,
    rt_listen_mcq,
    rt_ro,
    rt_speak,
    scenario_chat_step,
    speak_step,
)


def lesson_l09() -> dict:
    lid = "a2-m10-l09-task-misunderstanding-guided"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Real-life task · Handle a misunderstanding (guided)",
        "lessonType": "task",
        "order": 8,
        "cefrLevel": "A2",
        "durationEstimate": 18,
        "grammarTargets": ["a2.3-recovery-repair", "a2.3-recovery-clarify"],
        "vocabTargets": ["lemma-misverstand-m10", "lemma-betekenen-m10", "lemma-wacht-m10", "lemma-begrijpen-m10", "lemma-sorry-m10"],
        "canDoStatements": ["I can stay calm, ask for clarification, and fix a simple misunderstanding in a work-like chat."],
        "mistakeFocus": ["misunderstanding", "weak-clarification"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m10-l09-preview",
                "Warm-up — 5 woorden",
                [
                    ("afspraak", "afspraak", "appointment", "📅"),
                    ("online", "online", "online", "💻"),
                    ("kantoor", "kantoor", "office", "🏢"),
                    ("agenda", "agenda", "calendar / agenda", "🗓️"),
                    ("duidelijk", "duidelijk", "clear", "💡"),
                ],
            ),
            scenario_chat_step(
                "m10-l09-chat",
                "Mini-sim — kies je antwoord",
                [
                    ("Tim", "Hé! We zien elkaar om drie uur op kantoor, toch?", "Hey! We're meeting at three at the office, right?"),
                    ("Jij (kies)", "Sorry — ik dacht dat we online zouden vergaderen.", "Sorry — I thought we'd meet online."),
                    ("Tim", "O? In de uitnodiging stond: fysieke meeting in zaal B.", "Oh? The invite said: in-person meeting in room B."),
                    ("Jij (kies)", "Wacht even … Kun je dat herhalen? Welke zaal?", "Wait … Can you repeat that? Which room?"),
                    ("Tim", "Zaal B, derde verdieping. Geen zorgen!", "Room B, third floor. Don't worry!"),
                    ("Jij (kies)", "Ah, nu snap ik het. Dank je! Dan zie ik je daar.", "Ah, now I get it. Thanks! Then I'll see you there."),
                    ("Tim", "Top. Tot straks!", "Great. See you later!"),
                ],
                [
                    ("Wat dacht jij eerst?", ["Online vergadering", "Een feest", "Geen afspraak"], "Online vergadering"),
                    ("Wat zegt Tim over de uitnodiging?", ["Fysieke meeting, zaal B", "Alleen mail zonder info", "Geen locatie"], "Fysieke meeting, zaal B"),
                    ("Welke repair-vraag past bij collega Tim?", ["Kun je dat herhalen? Welke zaal?", "U moet nu stoppen.", "Ik weiger alles"], "Kun je dat herhalen? Welke zaal?"),
                    ("Hoe sluit jij af als het duidelijk is?", ["Nu snap ik het + dank + bevestiging", "Ik word boos", "Geen slot"], "Nu snap ik het + dank + bevestiging"),
                    ("Waar is de meeting?", ["Kantoor, zaal B", "Thuis zonder adres", "In het zwembad"], "Kantoor, zaal B"),
                ],
            ),
            discovery_step(
                "m10-l09-discovery",
                "Repair die werkt",
                [
                    ("Wacht even …", "Wait …", "adem"),
                    ("Kun je / Kunt u … herhalen?", "Can you … repeat? (je = collega; u = balie)", "check"),
                    ("Nu snap ik het.", "Now I get it.", "ok"),
                    ("Geen zorgen.", "Don't worry.", "samen oplossen"),
                ],
            ),
            pl(
                "m10-l09-pl1",
                "Practice — 6×",
                ["misverstand", "bedoelen", "uitnodiging"],
                [
                    mcq(
                        "m10-l09-a1",
                        "Als je iets verkeerd begreep",
                        ["Sorry, ik had het verkeerd begrepen.", "Jij bent altijd fout.", "Begrijp nooit."],
                        "Sorry, ik had het verkeerd begrepen.",
                    ),
                    fb("m10-l09-a2", "Ik denk dat er een ___ is. (misunderstanding)", ["misverstand", "feest", "lied"], "misverstand"),
                    ro_tokens("m10-l09-r1", ["bedoelde?", "Wat", "u"], "Wat bedoelt u?"),
                    mcq(
                        "m10-l09-a3",
                        "Bevestig de kern",
                        ["Dus fysiek op kantoor, niet online?", "Dus nergens?", "Dus zonder check?"],
                        "Dus fysiek op kantoor, niet online?",
                    ),
                    mcq(
                        "m10-l09-a4",
                        "Als de ander stress heeft",
                        ["Geen zorgen, dat kan gebeuren.", "Dat mag nooit gebeuren.", "Stress zonder empathie."],
                        "Geen zorgen, dat kan gebeuren.",
                    ),
                    match_ex(
                        "m10-l09-m1",
                        "Koppel",
                        [
                            ("Ik hoor het niet goed", "Kunt u dat nog een keer zeggen?"),
                            ("Ik weet het niet zeker", "Kunt u dat bevestigen?"),
                            ("Verkeerde tijd in mijn hoofd", "Sorry, welke tijd bedoelt u?"),
                        ],
                        {
                            "Ik hoor het niet goed": "Kunt u dat nog een keer zeggen?",
                            "Ik weet het niet zeker": "Kunt u dat bevestigen?",
                            "Verkeerde tijd in mijn hoofd": "Sorry, welke tijd bedoelt u?",
                        },
                    ),
                ],
            ),
            pl(
                "m10-l09-pl2",
                "Variatie — 6×",
                ["duidelijk", "agenda", "dank"],
                [
                    mcq(
                        "m10-l09-b1",
                        "Als info tegenstrijdig lijkt",
                        ["Even checken: wat staat er precies in de agenda?", "Negeer alles.", "Agenda zonder check."],
                        "Even checken: wat staat er precies in de agenda?",
                    ),
                    fb("m10-l09-b2", "___ me het anders zeggen: ik bedoelde maandag. (let)", ["Laat", "Eet", "Zwem"], "Laat"),
                    ro_tokens("m10-l09-r2", ["verwarring.", "voor", "de", "Sorry"], "Sorry voor de verwarring."),
                    mcq(
                        "m10-l09-b3",
                        "Blijven respectvol",
                        ["Ik snap de verwarring — laten we het zo afspreken.", "Jij bent dom.", "Verwarring zonder respect."],
                        "Ik snap de verwarring — laten we het zo afspreken.",
                    ),
                    mcq(
                        "m10-l09-b4",
                        "Samenvatting",
                        ["Dus ik kom naar kantoor om drie uur, zaal B.", "Dus ik kom nooit.", "Dus zonder tijd."],
                        "Dus ik kom naar kantoor om drie uur, zaal B.",
                    ),
                    mcq(
                        "m10-l09-b5",
                        "Mini-fallback",
                        ["Eén moment, ik zoek de mail even.", "Geen mail zoeken.", "Mail zonder actie."],
                        "Eén moment, ik zoek de mail even.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m10-l09-sp1",
                "Start",
                "Sorry, ik dacht dat we online zouden praten.",
                ["Sorry ik dacht dat we online zouden praten", "Sorry, ik dacht dat we online zouden praten."],
                "Sorry ik dacht dat we online zouden praten",
            ),
            speak_step(
                "m10-l09-sp2",
                "Herhalen (collega)",
                "Kun je dat herhalen? Ik snap het niet helemaal.",
                ["Kun je dat herhalen ik snap het niet helemaal", "Kun je dat herhalen? Ik snap het niet helemaal."],
                "Kun je dat herhalen ik snap het niet helemaal",
                tips="Peer talk: *kun je* (not *u*); *snap* is snappy; *hele-MAAL* stress on the last part.",
            ),
            speak_step(
                "m10-l09-sp3",
                "Bevestigen",
                "Dus zaal B op de derde verdieping?",
                ["Dus zaal B op de derde verdieping", "Dus zaal B op de derde verdieping?"],
                "Dus zaal B op de derde verdieping",
                tips="*derde*: *DER-duh*; *verdieping*: ver-DEE-ping; rising tone on *verdieping?*.",
            ),
            speak_step(
                "m10-l09-sp4",
                "Oplossing",
                "Ah, nu snap ik het. Bedankt voor je geduld!",
                ["Ah nu snap ik het bedankt voor je geduld", "Ah, nu snap ik het. Bedankt voor je geduld!"],
                "Ah nu snap ik het bedankt voor je geduld",
                tips="Warm close: *AH* + *nu SNAP ik het*; *ge-DULD* with clear *d* at the end.",
            ),
            speak_step(
                "m10-l09-sp5",
                "Bal terug",
                "En jij? Was het voor jou ook duidelijk in de uitnodiging?",
                ["En jij was het voor jou ook duidelijk in de uitnodiging", "En jij? Was het voor jou ook duidelijk in de uitnodiging?"],
                "En jij was het voor jou ook duidelijk in de uitnodiging",
            ),
            recap_step(
                "m10-l09-recap",
                "Recap",
                ["misverstand", "herhalen", "snap"],
                [
                    rt_fb("___ even — welke zaal? (wait)", ["Wacht", "Loop", "Spring"], "Wacht"),
                    rt_ro(["het.", "snap", "ik", "Nu"], "Nu snap ik het."),
                    rt_speak("Zeg: *Sorry, ik had het verkeerd begrepen.*", "Sorry, ik had het verkeerd begrepen."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Geen zorgen, zaal B.",
                        ["Geruststellen + antwoord", "Boos worden", "Stoppen"],
                        "Geruststellen + antwoord",
                    ),
                    rt_fb("Kun ___ dat herhalen? (you informal)", ["je", "u", "wij"], "je"),
                    rt_speak("Zeg: *Dus fysiek op kantoor?*", "Dus fysiek op kantoor?"),
                ],
            ),
        ],
    }


def lesson_l10() -> dict:
    lid = "a2-m10-l10-task-problem-solving-simulation"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Real-life task · Problem-solving conversation (simulation)",
        "lessonType": "task",
        "order": 9,
        "cefrLevel": "A2",
        "durationEstimate": 19,
        "grammarTargets": ["a2.3-recovery-problems", "a2.3-recovery-modals"],
        "vocabTargets": ["lemma-bestelling-m10", "lemma-fout-m10", "lemma-helpen-m10", "lemma-adres-m10", "lemma-winkel-m10"],
        "canDoStatements": ["I can handle a short service conversation: state the problem, ask for help, and agree on a fix."],
        "mistakeFocus": ["incorrect-phrasing", "register"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m10-l10-preview",
                "Warm-up — 5 woorden",
                [
                    ("bezorging", "bezorging", "delivery", "📦"),
                    ("adres", "adres", "address", "🏠"),
                    ("pakket", "pakket", "parcel", "📮"),
                    ("fout", "fout", "wrong", "❌"),
                    ("oplossing", "oplossing", "solution", "✅"),
                ],
            ),
            scenario_chat_step(
                "m10-l10-chat",
                "Mini-sim — pakket (guided)",
                [
                    ("Bezorger", "Goedemiddag! Ik heb een pakket voor nummer 12.", "Good afternoon! I have a parcel for number 12."),
                    ("Jij (kies)", "Sorry, ik woon op nummer 21. Dit is niet mijn pakket.", "Sorry, I live at number 21. This isn't my parcel."),
                    ("Bezorger", "O jee. Staat er een andere naam op het label?", "Oh dear. Is there a different name on the label?"),
                    ("Jij (kies)", "Ja — een andere naam. Kun je dat even nakijken?", "Yes — a different name. Can you check that for a moment?"),
                    ("Bezorger", "Een moment … Ah, verkeerde straat ingevoerd. Mijn fout.", "One moment … Ah, wrong street entered. My mistake."),
                    ("Jij (kies)", "Geen probleem. Wat is de beste oplossing?", "No problem. What's the best solution?"),
                    ("Bezorger", "Ik breng het naar het juiste adres vandaag nog. Dank voor je geduld!", "I'll take it to the correct address today. Thanks for your patience!"),
                    ("Jij (kies)", "Super, dank u wel!", "Great, thank you!"),
                ],
                [
                    ("Wat is het probleem?", ["Verkeerd huisnummer / niet jouw pakket", "Te zwaar pakket", "Geen probleem"], "Verkeerd huisnummer / niet jouw pakket"),
                    ("Hoe start je rustig?", ["Sorry + duidelijk zeggen dat het niet jouw pakket is", "Schreeuw direct", "Zwijg"], "Sorry + duidelijk zeggen dat het niet jouw pakket is"),
                    ("Wat vraag je als check?", ["Even nakijken / label checken", "Geld terug zonder reden", "Niets"], "Even nakijken / label checken"),
                    ("Wie geeft de fout toe?", ["De bezorger / systeem", "Alleen de klant", "Niemand"], "De bezorger / systeem"),
                    ("Welke oplossing kies je?", ["Bezorging op juiste adres vandaag", "Pakket weggooien", "Geen oplossing"], "Bezorging op juiste adres vandaag"),
                    ("Welke houding helpt?", ["Geduldig en duidelijk", "Agressief", "Paniek"], "Geduldig en duidelijk"),
                ],
            ),
            discovery_step(
                "m10-l10-discovery",
                "Service-flow",
                [
                    ("Sorry, dit klopt niet: …", "Sorry, this isn't right: …", "probleem"),
                    ("Kunt u dit checken?", "Could you check this?", "actie"),
                    ("Wat is de oplossing?", "What's the solution?", "volgende stap"),
                    ("Dank voor uw hulp.", "Thanks for your help.", "slot"),
                ],
            ),
            listening_step(
                "m10-l10-listen",
                "Input — korte reactie (balie)",
                [
                    ("Klant", "Dit is niet wat ik bestelde. Ik had de vegetarische optie gevraagd.", "This isn't what I ordered. I'd asked for the vegetarian option."),
                    ("Medewerker", "Sorry daarvoor. Ik ruil het meteen om. Wilt u even wachten?", "Sorry about that. I'll swap it right away. Could you wait a moment?"),
                    ("Klant", "Ja, geen probleem. Dank u wel.", "Yes, no problem. Thank you."),
                ],
                [
                    ("Wat wil de klant?", ["De juiste maaltijd (vegetarisch)", "Geld van de kassa", "Een andere winkel"], "De juiste maaltijd (vegetarisch)"),
                    ("Wat doet de medewerker?", ["Ruilen / oplossen", "Weigeren", "Wegrennen"], "Ruilen / oplossen"),
                    ("Hoe reageert de klant?", ["Rustig: geen probleem", "Boos", "Zwijgt"], "Rustig: geen probleem"),
                ],
            ),
            pl(
                "m10-l10-pl1",
                "Practice — 6×",
                ["pakket", "adres", "checken"],
                [
                    mcq(
                        "m10-l10-a1",
                        "Probleem duidelijk maken",
                        ["Er staat een verkeerd adres op het label.", "Er is nooit een label.", "Label zonder adres."],
                        "Er staat een verkeerd adres op het label.",
                    ),
                    fb("m10-l10-a2", "Kunt u dit in uw ___ nakijken? (system)", ["systeem", "brood", "lied"], "systeem"),
                    ro_tokens("m10-l10-r1", ["oplossing?", "de", "Wat", "is"], "Wat is de oplossing?"),
                    mcq(
                        "m10-l10-a3",
                        "Als je tijd nodig hebt",
                        ["Wacht even, ik zoek mijn ordernummer.", "Wacht zonder actie.", "Geen nummer."],
                        "Wacht even, ik zoek mijn ordernummer.",
                    ),
                    mcq(
                        "m10-l10-a4",
                        "Empathie (kort)",
                        ["Dat kan gebeuren, geen probleem.", "Dat mag nooit.", "Geen empathie."],
                        "Dat kan gebeuren, geen probleem.",
                    ),
                    match_ex(
                        "m10-l10-m1",
                        "Stap → zin",
                        [
                            ("Probleem benoemen", "Dit is niet wat ik bestelde."),
                            ("Hulp vragen", "Kunt u mij helpen?"),
                            ("Check vragen", "Kunt u dat bevestigen?"),
                        ],
                        {
                            "Probleem benoemen": "Dit is niet wat ik bestelde.",
                            "Hulp vragen": "Kunt u mij helpen?",
                            "Check vragen": "Kunt u dat bevestigen?",
                        },
                    ),
                ],
            ),
            pl(
                "m10-l10-pl2",
                "Variatie — 6×",
                ["werkt", "terug", "beloven"],
                [
                    mcq(
                        "m10-l10-b1",
                        "Als belofte onduidelijk is",
                        ["Kunt u zeggen wanneer het klaar is?", "Vraag nooit naar tijd.", "Tijd zonder vraag."],
                        "Kunt u zeggen wanneer het klaar is?",
                    ),
                    fb("m10-l10-b2", "Het ___ niet bij de betaling. (works)", ["werkt", "eet", "zingt"], "werkt"),
                    ro_tokens("m10-l10-r2", ["helpen?", "mij", "Kunt", "u"], "Kunt u mij helpen?"),
                    mcq(
                        "m10-l10-b3",
                        "Terugbellen / appen",
                        ["Kunt u me terugbellen als u meer weet?", "Bel nooit.", "Bel zonder vraag."],
                        "Kunt u me terugbellen als u meer weet?",
                    ),
                    mcq(
                        "m10-l10-b4",
                        "Slot",
                        ["Prima, dan wacht ik hier even.", "Ik ren weg zonder woorden.", "Wacht zonder plan."],
                        "Prima, dan wacht ik hier even.",
                    ),
                    mcq(
                        "m10-l10-b5",
                        "Vertrouwen + grens",
                        ["Ik wil het graag opgelost hebben vandaag, als dat kan.", "Ik eis onmogelijke dingen.", "Geen grens."],
                        "Ik wil het graag opgelost hebben vandaag, als dat kan.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m10-l10-sp1",
                "Probleem",
                "Sorry, dit pakket is niet voor mij. Ik woon op nummer 21.",
                ["Sorry dit pakket is niet voor mij ik woon op nummer 21", "Sorry, dit pakket is niet voor mij. Ik woon op nummer 21."],
                "Sorry dit pakket is niet voor mij ik woon op nummer 21",
            ),
            speak_step(
                "m10-l10-sp2",
                "Check (zoals bij de bezorger)",
                "Kun je even nakijken of het adres klopt?",
                ["Kun je even nakijken of het adres klopt", "Kun je even nakijken of het adres klopt?"],
                "Kun je even nakijken of het adres klopt",
                tips="*nakijken*: *nah-KAY-kuh*; *adres*: *A-dres*; *klopt*: crisp final *t*.",
            ),
            speak_step(
                "m10-l10-sp3",
                "Oplossing",
                "Wat is de beste oplossing voor mij?",
                ["Wat is de beste oplossing voor mij", "Wat is de beste oplossing voor mij?"],
                "Wat is de beste oplossing voor mij",
            ),
            speak_step(
                "m10-l10-sp4",
                "Dank",
                "Dank u wel voor uw hulp en geduld.",
                ["Dank u wel voor uw hulp en geduld", "Dank u wel voor uw hulp en geduld."],
                "Dank u wel voor uw hulp en geduld",
            ),
            speak_step(
                "m10-l10-sp5",
                "Winkel",
                "Dit is niet wat ik bestelde. Kunt u het omruilen?",
                ["Dit is niet wat ik bestelde kunt u het omruilen", "Dit is niet wat ik bestelde. Kunt u het omruilen?"],
                "Dit is niet wat ik bestelde kunt u het omruilen",
            ),
            speak_step(
                "m10-l10-sp6",
                "Herhalen",
                "Sorry, ik begrijp het niet. Kunt u dat herhalen?",
                ["Sorry ik begrijp het niet kunt u dat herhalen", "Sorry, ik begrijp het niet. Kunt u dat herhalen?"],
                "Sorry ik begrijp het niet kunt u dat herhalen",
                tips="Stack politely: *SOR-ry* … *BEG-rip* … then *Kunt u* + *HEER-ha-len*.",
            ),
            recap_step(
                "m10-l10-recap",
                "Recap",
                ["pakket", "checken", "oplossing"],
                [
                    rt_fb("Dit is niet wat ik ___. (ordered)", ["bestelde", "zing", "dans"], "bestelde"),
                    rt_ro(["het.", "werkt", "niet", "Het"], "Het werkt niet."),
                    rt_speak("Zeg: *Kun je dat even nakijken?*", "Kun je dat even nakijken?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Ik ruil het meteen om.",
                        ["Oplossing aangeboden", "Weigeren", "Klacht zonder actie"],
                        "Oplossing aangeboden",
                    ),
                    rt_fb("___ is de beste oplossing? (what)", ["Wat", "Wie", "Waar"], "Wat"),
                    rt_speak("Zeg: *Geen probleem.*", "Geen probleem."),
                ],
            ),
        ],
    }


def lesson_l11() -> dict:
    lid = "a2-m10-l11-review-unexpected-situations"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Review · Unexpected situations",
        "lessonType": "review",
        "order": 10,
        "cefrLevel": "A2",
        "durationEstimate": 18,
        "grammarTargets": ["a2.3-recovery-clarify", "a2.3-recovery-repair", "a2.3-recovery-problems"],
        "vocabTargets": ["lemma-begrijpen-m10", "lemma-helpen-m10", "lemma-probleem-m10", "lemma-misverstand-m10", "lemma-want-m10"],
        "canDoStatements": ["I can retrieve and use key phrases to fix misunderstandings and ask for help under light pressure."],
        "mistakeFocus": ["weak-clarification", "connectors", "word-order"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m10-l11-preview",
                "Warm-up — 5 woorden",
                [
                    ("herstel", "herstellen", "to fix / recover", "🔧"),
                    ("duidelijk", "duidelijk", "clear", "💡"),
                    ("rustig", "rustig", "calm", "🧘"),
                    ("nog een keer", "keer", "once more", "🔁"),
                    ("samenvatten", "samenvatten", "to summarise", "📝"),
                ],
            ),
            listening_step(
                "m10-l11-listen",
                "Mix — luister snel mee",
                [
                    ("A", "Ik begrijp het niet. Kunt u langzamer spreken?", "I don't understand. Could you speak more slowly?"),
                    ("B", "Wacht even — ik bedoelde de andere deur.", "Wait — I meant the other door."),
                    ("C", "Er is een probleem met mijn kaartje. Kunt u helpen?", "There's a problem with my ticket. Can you help?"),
                ],
                [
                    ("Wat vraagt A?", ["Langzamer praten", "Geld", "Een taxi"], "Langzamer praten"),
                    ("Wat doet B?", ["Correctie / repair", "Een grap", "Stoppen"], "Correctie / repair"),
                    ("Wat wil C?", ["Hulp bij een probleem", "Een koffie", "Een fiets"], "Hulp bij een probleem"),
                    ("Welke module-thema’s hoor je?", ["Clarify + repair + problem", "Alleen het weer", "Alleen sport"], "Clarify + repair + problem"),
                ],
            ),
            discovery_step(
                "m10-l11-discovery",
                "Jouw ‘noodkit’",
                [
                    ("Ik begrijp het niet.", "I don't understand.", "basis"),
                    ("Kunt u dat herhalen?", "Could you repeat that?", "repeat"),
                    ("Wat bedoelt u?", "What do you mean?", "meaning"),
                    ("Dat klopt niet.", "That's not right.", "fout"),
                    ("Kunt u mij helpen?", "Can you help me?", "hulp"),
                    ("Geen probleem.", "No problem.", "kalmeren"),
                    ("Pardon? Kun je dat nog een keer zeggen?", "Sorry? Can you say that again?", "ultra-kort"),
                ],
            ),
            pl(
                "m10-l11-pl1",
                "Recall — 6×",
                ["herhalen", "langzaam", "bedoelen"],
                [
                    mcq(
                        "m10-l11-a1",
                        "Beste keuze: je hoort het niet",
                        ["Sorry, ik hoor het niet goed. Kunt u dat herhalen?", "Hoor nooit iets.", "Herhaal zonder sorry."],
                        "Sorry, ik hoor het niet goed. Kunt u dat herhalen?",
                    ),
                    fb("m10-l11-a2", "___ u iets langzamer praten? (could)", ["Kunt", "Eet", "Zwem"], "Kunt"),
                    ro_tokens("m10-l11-r1", ["niet.", "begrijp", "Ik", "het"], "Ik begrijp het niet."),
                    mcq(
                        "m10-l11-a3",
                        "Informeel: betekenis",
                        ["Wat bedoel je precies?", "Wat eet je?", "Bedoel zonder vraag?"],
                        "Wat bedoel je precies?",
                    ),
                    mcq(
                        "m10-l11-a4",
                        "Probleem + vraag in één",
                        ["Het werkt niet. Kunt u kijken?", "Het werkt perfect altijd.", "Werkt zonder vraag."],
                        "Het werkt niet. Kunt u kijken?",
                    ),
                    match_ex(
                        "m10-l11-m1",
                        "Situatie → zin",
                        [
                            ("Te ingewikkeld", "Kunt u dat simpeler uitleggen?"),
                            ("Verkeerde info", "Dat klopt niet bij mij."),
                            ("Onzeker", "Ik weet het niet zeker."),
                        ],
                        {
                            "Te ingewikkeld": "Kunt u dat simpeler uitleggen?",
                            "Verkeerde info": "Dat klopt niet bij mij.",
                            "Onzeker": "Ik weet het niet zeker.",
                        },
                    ),
                ],
            ),
            pl(
                "m10-l11-pl2",
                "Mix — 6×",
                ["want", "maar", "sorry"],
                [
                    mcq(
                        "m10-l11-b1",
                        "Reden (kort)",
                        ["Ik ben moe, want ik heb weinig geslapen.", "Ik ben moe want zonder zin.", "Moe zonder want."],
                        "Ik ben moe, want ik heb weinig geslapen.",
                    ),
                    fb("m10-l11-b2", "Mag ik een ___ stellen? (question)", ["vraag", "brood", "lied"], "vraag"),
                    ro_tokens("m10-l11-r2", ["bedoelde.", "niet", "Dat", "is", "wat", "ik"], "Dat is niet wat ik bedoelde."),
                    mcq(
                        "m10-l11-b3",
                        "Tegenstelling",
                        ["Ik wil mee, maar ik moet werken.", "Ik wil mee want ik werk nooit.", "Mee zonder maar."],
                        "Ik wil mee, maar ik moet werken.",
                    ),
                    mcq(
                        "m10-l11-b4",
                        "Power line (confidence)",
                        ["Oké, rustig: ik stel het opnieuw in één zin.", "Paniek nu.", "Geen zin."],
                        "Oké, rustig: ik stel het opnieuw in één zin.",
                    ),
                    mcq(
                        "m10-l11-b5",
                        "Check aan het eind",
                        ["Is dit zo goed voor u?", "Is dit altijd fout?", "Check zonder vraag."],
                        "Is dit zo goed voor u?",
                    ),
                ],
                depth=True,
            ),
            pl(
                "m10-l11-pl3",
                "Vaardig — 6×",
                ["balie", "trein", "bericht"],
                [
                    mcq(
                        "m10-l11-c1",
                        "Balie-open",
                        ["Goedemiddag, ik heb een vraag over …", "Geef nu.", "Zwijg."],
                        "Goedemiddag, ik heb een vraag over …",
                    ),
                    fb("m10-l11-c2", "Er is een ___ met mijn ticket. (problem)", ["probleem", "feest", "lied"], "probleem"),
                    ro_tokens("m10-l11-r3", ["even.", "Wacht"], "Wacht even."),
                    mcq(
                        "m10-l11-c3",
                        "Trein: vertraging",
                        ["Door de vertraging mis ik mijn overstap.", "Vertraging bestaat niet.", "Trein zonder overstap."],
                        "Door de vertraging mis ik mijn overstap.",
                    ),
                    mcq(
                        "m10-l11-c4",
                        "Chat: kort",
                        ["Dit werkt niet. Kunt u helpen?", "Dit werkt altijd zonder uitleg.", "Chat zonder probleem."],
                        "Dit werkt niet. Kunt u helpen?",
                    ),
                    mcq(
                        "m10-l11-c5",
                        "Samenvatten",
                        ["Dus: probleem + wat je wilt + dank.", "Dus: geen info.", "Samenvatten zonder punt."],
                        "Dus: probleem + wat je wilt + dank.",
                    ),
                ],
            ),
            speak_step(
                "m10-l11-sp1",
                "Alles-in-één (kort)",
                "Sorry, ik begrijp het niet. Kunt u dat herhalen?",
                ["Sorry ik begrijp het niet kunt u dat herhalen", "Sorry, ik begrijp het niet. Kunt u dat herhalen?"],
                "Sorry ik begrijp het niet kunt u dat herhalen",
                tips="Core repair line: three beats—*sorry* / *begrijp het niet* / *herhalen*—don’t rush.",
            ),
            speak_step(
                "m10-l11-sp2",
                "Repair",
                "Laat me het anders zeggen: ik zoek de uitgang.",
                ["Laat me het anders zeggen ik zoek de uitgang", "Laat me het anders zeggen: ik zoek de uitgang."],
                "Laat me het anders zeggen ik zoek de uitgang",
                tips="Repair restart: *LAAT me* … *AN-ders ZEG-gen* … then *ZOEK* + *UIT-gang* with clear *g*.",
            ),
            speak_step(
                "m10-l11-sp3",
                "Slot",
                "Dank u wel. Fijne dag nog!",
                ["Dank u wel fijne dag nog", "Dank u wel. Fijne dag nog!"],
                "Dank u wel fijne dag nog",
                tips="Warm sign-off: stress *FIJ-ne* and *DAG*; keep *nog* light and friendly.",
            ),
            recap_step(
                "m10-l11-recap",
                "Recap — brede retrieval",
                ["herstel", "duidelijk", "hulp"],
                [
                    rt_fb("___ bedoelt u? (what — formal)", ["Wat", "Wie", "Waar"], "Wat"),
                    rt_ro(["helpen?", "mij", "Kunt", "u"], "Kunt u mij helpen?"),
                    rt_speak("Zeg: *Ik begrijp het niet.*", "Ik begrijp het niet."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Geen zorgen, ik help je.",
                        ["Hulp aangeboden", "Weigeren", "Klacht"],
                        "Hulp aangeboden",
                    ),
                    rt_fb("Dat ___, maar ik snap de verwarring. (not correct)", ["klopt", "zingt", "danst"], "klopt"),
                    rt_speak("Zeg: *Kunt u langzamer spreken?*", "Kunt u langzamer spreken?"),
                    rt_ro(["niet.", "werkt", "Het"], "Het werkt niet."),
                ],
            ),
        ],
    }
