from .common import (
    LM,
    MID,
    discovery_step,
    fb,
    grammar_card,
    listen_read_step,
    listening_step,
    match_ex,
    mcq,
    pl,
    preview_step,
    recap_step,
    ro_tokens,
    rt_fb,
    rt_listen_mcq,
    rt_ro,
    rt_speak,
    speak_step,
    writing_step,
)


def lesson_l05() -> dict:
    lid = "a2-m10-l05-speaking-ask-help-clearly"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Speaking · Ask for help clearly",
        "lessonType": "speaking",
        "order": 4,
        "cefrLevel": "A2",
        "durationEstimate": 18,
        "grammarTargets": ["a2.3-recovery-modals", "a2.3-recovery-clarify"],
        "vocabTargets": ["lemma-helpen-m10", "lemma-balie-m10", "lemma-perron-m10", "lemma-druk-m10", "lemma-sorry-m10"],
        "canDoStatements": ["I can ask for help in a short sequence: soft opener, problem, clear request."],
        "mistakeFocus": ["weak-clarification", "register"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m10-l05-preview",
                "Warm-up — 5 woorden",
                [
                    ("balie", "balie", "counter", "🏷️"),
                    ("perron", "perron", "platform", "🚉"),
                    ("druk", "druk", "busy", "👥"),
                    ("excuseer", "excuseren", "excuse me", "🙋"),
                    ("richting", "richting", "direction", "🧭"),
                ],
            ),
            listening_step(
                "m10-l05-listen",
                "Input — op het station",
                [
                    ("Reiziger", "Excuseer, mag ik u iets vragen? Ik zoek perron 4b.", "Excuse me, may I ask you something? I'm looking for platform 4b."),
                    ("Medewerker", "Natuurlijk. Ga deze trap op, dan rechts. Het is niet ver.", "Of course. Go up these stairs, then right. It's not far."),
                    ("Reiziger", "Kunt u dat herhalen? Ik begrijp het niet helemaal.", "Could you repeat that? I don't quite understand."),
                    ("Medewerker", "Geen probleem: trap op, rechts, en dan ziet u het bord.", "No problem: up the stairs, right, and then you'll see the sign."),
                    ("Reiziger", "Dank u wel!", "Thank you!"),
                ],
                [
                    ("Wat wil de reiziger?", ["De weg naar perron 4b", "Een koffie", "Een fiets"], "De weg naar perron 4b"),
                    ("Wat vraagt hij als hij het niet snapt?", ["Herhalen", "Geld terug", "Een klacht"], "Herhalen"),
                    ("Hoe klinkt de medewerker?", ["Geduldig en duidelijk", "Geïrriteerd", "Hij weigert"], "Geduldig en duidelijk"),
                    ("Welke repair-uitdrukking gebruikt de reiziger?", ["Ik begrijp het niet helemaal", "Ik haat stations", "Stop"], "Ik begrijp het niet helemaal"),
                    ("Waar speelt dit?", ["Station", "Restaurant", "Zwembad"], "Station"),
                ],
            ),
            discovery_step(
                "m10-l05-discovery",
                "Volgorde die werkt",
                [
                    ("Excuseer / Sorry …", "Excuse me / Sorry …", "open"),
                    ("Ik heb een probleem / ik zoek …", "I have a problem / I'm looking for …", "kern"),
                    ("Kunt u …?", "Could you …?", "verzoek"),
                    ("Dank je / Dank u wel", "Thanks / Thank you", "slot"),
                ],
            ),
            pl(
                "m10-l05-pl1",
                "Practice — 6×",
                ["perron", "helpen", "excuseer"],
                [
                    mcq(
                        "m10-l05-a1",
                        "Beste opener als het druk is",
                        ["Excuseer, heel kort …", "Hé, maak ruimte!", "Zwijg."],
                        "Excuseer, heel kort …",
                    ),
                    fb("m10-l05-a2", "___ u mij naar de uitgang wijzen? (could)", ["Kunt", "Eet", "Zwem"], "Kunt"),
                    ro_tokens("m10-l05-r1", ["helpen?", "mij", "Kunt", "u"], "Kunt u mij helpen?"),
                    mcq(
                        "m10-l05-a3",
                        "Als je de route niet onthoudt",
                        ["Kunt u dat opschrijven voor mij?", "Raad maar.", "Geen hulp."],
                        "Kunt u dat opschrijven voor mij?",
                    ),
                    mcq(
                        "m10-l05-a4",
                        "Check: goed begrepen?",
                        ["Dus eerst de trap op en dan rechts?", "Dus nergens naartoe?", "Dus zonder richting?"],
                        "Dus eerst de trap op en dan rechts?",
                    ),
                    match_ex(
                        "m10-l05-m1",
                        "Situatie → eerste zin",
                        [
                            ("Verdwaald", "Sorry, ik ben de weg kwijt."),
                            ("Ruis/lawaai", "Sorry, ik hoor het niet goed."),
                            ("Te snel", "Kunt u langzamer praten?"),
                        ],
                        {"Verdwaald": "Sorry, ik ben de weg kwijt.", "Ruis/lawaai": "Sorry, ik hoor het niet goed.", "Te snel": "Kunt u langzamer praten?"},
                    ),
                ],
            ),
            pl(
                "m10-l05-pl2",
                "Variatie — 6×",
                ["balie", "vraag", "dank"],
                [
                    mcq(
                        "m10-l05-b1",
                        "Aan de balie",
                        ["Goedemiddag. Ik heb een vraag over mijn ticket.", "Geef nu alles.", "Zwijg aan de balie."],
                        "Goedemiddag. Ik heb een vraag over mijn ticket.",
                    ),
                    fb("m10-l05-b2", "___ ik even storen? (may)", ["Mag", "Eet", "Zwem"], "Mag"),
                    ro_tokens("m10-l05-r2", ["wel!", "Dank", "u"], "Dank u wel!"),
                    mcq(
                        "m10-l05-b3",
                        "Als je hulp krijgt",
                        ["Super, bedankt voor uw hulp.", "Eindelijk, het was jouw plicht.", "Geen dank zonder respect."],
                        "Super, bedankt voor uw hulp.",
                    ),
                    mcq(
                        "m10-l05-b4",
                        "Niet panikeren",
                        ["Eén vraag per keer — rustig.", "Vijf vragen tegelijk — hard.", "Paniek is altijd het beste."],
                        "Eén vraag per keer — rustig.",
                    ),
                    mcq(
                        "m10-l05-b5",
                        "Herformuleren",
                        ["Laat me het zo zeggen: ik moet naar …", "Laat me zwijgen.", "Zo zeggen zonder punt."],
                        "Laat me het zo zeggen: ik moet naar …",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m10-l05-sp1",
                "Openen",
                "Excuseer, mag ik u iets vragen?",
                ["Excuseer mag ik u iets vragen", "Excuseer, mag ik u iets vragen?"],
                "Excuseer mag ik u iets vragen",
            ),
            speak_step(
                "m10-l05-sp2",
                "Probleem",
                "Ik zoek perron zes. Kunt u mij helpen?",
                ["Ik zoek perron zes kunt u mij helpen", "Ik zoek perron zes. Kunt u mij helpen?"],
                "Ik zoek perron zes kunt u mij helpen",
            ),
            speak_step(
                "m10-l05-sp3",
                "Herhalen",
                "Sorry, kunt u dat herhalen? Ik hoor het niet goed.",
                ["Sorry kunt u dat herhalen ik hoor het niet goed", "Sorry, kunt u dat herhalen? Ik hoor het niet goed."],
                "Sorry kunt u dat herhalen ik hoor het niet goed",
                tips="*hoor*: long *oo*; *goed*: *kh* + *ood*; pause lightly after *Sorry*.",
            ),
            speak_step(
                "m10-l05-sp4",
                "Bevestigen (zoals in het gesprek)",
                "Dus eerst deze trap op, dan rechts, en dan zie ik het bord?",
                [
                    "Dus eerst deze trap op dan rechts en dan zie ik het bord",
                    "Dus eerst deze trap op, dan rechts, en dan zie ik het bord?",
                ],
                "Dus eerst deze trap op dan rechts en dan zie ik het bord",
                tips="Chain with *dan*: *TRAP op … RECHTS … BORD*—stress each landmark word.",
            ),
            speak_step(
                "m10-l05-sp5",
                "Dank",
                "Dank u wel, fijne dag nog!",
                ["Dank u wel fijne dag nog", "Dank u wel, fijne dag nog!"],
                "Dank u wel fijne dag nog",
            ),
            speak_step(
                "m10-l05-sp6",
                "Balie",
                "Goedemiddag. Ik heb een probleem met mijn bestelling.",
                ["Goedemiddag ik heb een probleem met mijn bestelling", "Goedemiddag. Ik heb een probleem met mijn bestelling."],
                "Goedemiddag ik heb een probleem met mijn bestelling",
            ),
            recap_step(
                "m10-l05-recap",
                "Recap",
                ["excuseer", "helpen", "herhalen"],
                [
                    rt_fb("___ ik u iets vragen? (may)", ["Mag", "Eet", "Zwem"], "Mag"),
                    rt_ro(["niet", "goed.", "het", "hoor", "Ik"], "Ik hoor het niet goed."),
                    rt_speak("Zeg: *Kunt u mij helpen?*", "Kunt u mij helpen?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Geen probleem: trap op, rechts.",
                        ["Uitleg route", "Klacht", "Bestellen"],
                        "Uitleg route",
                    ),
                    rt_fb("Dank ___ wel! (you formal)", ["u", "je", "wij"], "u"),
                    rt_speak("Zeg: *Kunt u dat herhalen?*", "Kunt u dat herhalen?"),
                ],
            ),
        ],
    }


def lesson_l06() -> dict:
    lid = "a2-m10-l06-listening-unexpected-service-transport"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Listening · Unexpected situations (service & transport)",
        "lessonType": "input",
        "order": 5,
        "cefrLevel": "A2",
        "durationEstimate": 16,
        "grammarTargets": ["a2.3-recovery-problems", "a2.3-recovery-repair"],
        "vocabTargets": ["lemma-trein-m10", "lemma-kaartje-m10", "lemma-verwacht-m10", "lemma-fout-m10", "lemma-wacht-m10"],
        "canDoStatements": ["I can follow short service and transport dialogues when plans change (delay, wrong ticket, wrong item)."],
        "mistakeFocus": ["listening-gist", "misunderstanding"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m10-l06-preview",
                "Warm-up — 5 woorden",
                [
                    ("vertraging", "vertraging", "delay", "⏱️"),
                    ("omleiding", "omleiding", "diversion", "↪️"),
                    ("ticket", "kaartje", "ticket", "🎫"),
                    ("verwacht", "verwachten", "to expect", "👀"),
                    ("omruilen", "ruilen", "to exchange", "🔁"),
                ],
            ),
            listening_step(
                "m10-l06-listen",
                "Input — bus omgeleid",
                [
                    ("Chauffeur", "Goedenavond allemaal. Let op: wegens werk aan de weg rijden we niet langs het museum.", "Good evening everyone. Attention: due to roadworks we're not stopping by the museum."),
                    ("Passagier", "Oh nee! Ik moet daar uit. Wat kan ik doen?", "Oh no! I need to get off there. What can I do?"),
                    ("Chauffeur", "U kunt bij het volgende halte uitstappen en bus 12 nemen. Die stopt wel bij het museum.", "You can get off at the next stop and take bus 12. That one does stop at the museum."),
                    ("Passagier", "Kunt u dat herhalen? Welk nummer zei u?", "Could you repeat that? Which number did you say?"),
                    ("Chauffeur", "Bus twaalf. Geen zorgen, er is nog tijd genoeg.", "Bus twelve. Don't worry, there's still enough time."),
                ],
                [
                    ("Wat is er onverwacht?", ["De bus stopt niet bij het museum", "De bus is gratis", "Het regent niet"], "De bus stopt niet bij het museum"),
                    ("Waarom?", ["Wegwerkzaamheden", "Feestdag zonder bus", "Geen passagiers"], "Wegwerkzaamheden"),
                    ("Welke oplossing geeft de chauffeur?", ["Volgende halte + bus 12", "Lopen zonder route", "Wachten tot morgen"], "Volgende halte + bus 12"),
                    ("Wat vraagt de passagier als check?", ["Herhaling: welk busnummer", "Geld terug", "Koffie"], "Herhaling: welk busnummer"),
                    ("Hoe blijft de toon?", ["Rustig en behulpzaam", "Boos", "Onduidelijk"], "Rustig en behulpzaam"),
                ],
            ),
            discovery_step(
                "m10-l06-discovery",
                "Onverwacht, maar oké",
                [
                    ("Let op: …", "Attention: …", "aankondiging"),
                    ("Wat kan ik doen?", "What can I do?", "oplossing zoeken"),
                    ("Welk nummer zei u?", "Which number did you say?", "check"),
                    ("Geen zorgen.", "Don't worry.", "kalmeren"),
                ],
            ),
            pl(
                "m10-l06-pl1",
                "Practice — 6×",
                ["omleiding", "trein", "halte"],
                [
                    mcq(
                        "m10-l06-a1",
                        "Als je reis anders wordt",
                        ["Dat is anders dan verwacht. Wat nu?", "Dat is altijd perfect.", "Verwacht zonder verandering."],
                        "Dat is anders dan verwacht. Wat nu?",
                    ),
                    fb("m10-l06-a2", "De trein heeft ___. (delay)", ["vertraging", "feest", "kaas"], "vertraging"),
                    ro_tokens("m10-l06-r1", ["omruilen?", "kunnen", "We", "het"], "We kunnen het omruilen?"),
                    mcq(
                        "m10-l06-a3",
                        "Als je het bericht niet hoort",
                        ["Sorry, ik hoor het niet goed. Kunt u het nog een keer zeggen?", "Hoor zonder vragen.", "Schreeuw terug."],
                        "Sorry, ik hoor het niet goed. Kunt u het nog een keer zeggen?",
                    ),
                    mcq(
                        "m10-l06-a4",
                        "In de winkel: verkeerd product",
                        ["Dit is niet wat ik bestelde.", "Dit is altijd goed.", "Bestel zonder check."],
                        "Dit is niet wat ik bestelde.",
                    ),
                    match_ex(
                        "m10-l06-m1",
                        "Koppel",
                        [
                            ("Te laat", "Ik ben te laat door de vertraging."),
                            ("Verkeerde dag", "Dit kaartje is voor morgen."),
                            ("Verkeerde richting", "Ik denk dat we de verkeerde kant op gaan."),
                        ],
                        {"Te laat": "Ik ben te laat door de vertraging.", "Verkeerde dag": "Dit kaartje is voor morgen.", "Verkeerde richting": "Ik denk dat we de verkeerde kant op gaan."},
                    ),
                ],
            ),
            pl(
                "m10-l06-pl2",
                "Variatie — 6×",
                ["wacht", "bedoelen", "prima"],
                [
                    mcq(
                        "m10-l06-b1",
                        "Samenvatten om zeker te zijn",
                        ["Dus ik stap hier uit en dan bus twaalf?", "Dus ik doe niks?", "Dus zonder plan."],
                        "Dus ik stap hier uit en dan bus twaalf?",
                    ),
                    fb("m10-l06-b2", "___ even — welke halte is dit? (wait)", ["Wacht", "Loop", "Spring"], "Wacht"),
                    ro_tokens("m10-l06-r2", ["geen", "zorgen.", "Geen"], "Geen zorgen."),
                    mcq(
                        "m10-l06-b3",
                        "Als je twijfelt",
                        ["Ik weet het niet zeker — kunt u bevestigen?", "Ik weet alles zonder twijfel.", "Twijfel zonder vraag."],
                        "Ik weet het niet zeker — kunt u bevestigen?",
                    ),
                    mcq(
                        "m10-l06-b4",
                        "Vriendelijk slot",
                        ["Prima, dan probeer ik dat. Dank u!", "Slecht, ik geef op.", "Prima zonder dank."],
                        "Prima, dan probeer ik dat. Dank u!",
                    ),
                    mcq(
                        "m10-l06-b5",
                        "Werk (licht): collega verkeerd begrepen",
                        ["Sorry, dat is niet wat ik bedoelde. Ik bedoelde de deadline van vrijdag.", "Jij bent altijd fout.", "Bedoel zonder sorry."],
                        "Sorry, dat is niet wat ik bedoelde. Ik bedoelde de deadline van vrijdag.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m10-l06-sp1",
                "Onverwacht",
                "Dat is anders dan verwacht. Wat kan ik doen?",
                ["Dat is anders dan verwacht wat kan ik doen", "Dat is anders dan verwacht. Wat kan ik doen?"],
                "Dat is anders dan verwacht wat kan ik doen",
            ),
            speak_step(
                "m10-l06-sp2",
                "Herhalen",
                "Kunt u dat herhalen, alstublieft? Welk busnummer?",
                ["Kunt u dat herhalen alstublieft welk busnummer", "Kunt u dat herhalen, alstublieft? Welk busnummer?"],
                "Kunt u dat herhalen alstublieft welk busnummer",
                tips="*busnummer*: *BUS-num-mer*; good place to slow down and separate the number.",
            ),
            speak_step(
                "m10-l06-sp3",
                "Bevestigen",
                "Dus bus twaalf bij de volgende halte?",
                ["Dus bus twaalf bij de volgende halte", "Dus bus twaalf bij de volgende halte?"],
                "Dus bus twaalf bij de volgende halte",
                tips="*volgende*: *VOL-gun-duh*; *halte*: clear *l*; confirm with rising tone on *halte?*.",
            ),
            speak_step(
                "m10-l06-sp4",
                "Trein",
                "Sorry, ik ben te laat door vertraging van de trein.",
                ["Sorry ik ben te laat door vertraging van de trein", "Sorry, ik ben te laat door vertraging van de trein."],
                "Sorry ik ben te laat door vertraging van de trein",
            ),
            speak_step(
                "m10-l06-sp5",
                "Winkel",
                "Dit is niet wat ik bestelde. Kunt u het checken?",
                ["Dit is niet wat ik bestelde kunt u het checken", "Dit is niet wat ik bestelde. Kunt u het checken?"],
                "Dit is niet wat ik bestelde kunt u het checken",
            ),
            recap_step(
                "m10-l06-recap",
                "Recap",
                ["vertraging", "herhalen", "bus"],
                [
                    rt_fb("De trein heeft ___.", ["vertraging", "brood", "lied"], "vertraging"),
                    rt_ro(["zorgen.", "Geen"], "Geen zorgen."),
                    rt_speak("Zeg: *Wat kan ik doen?*", "Wat kan ik doen?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Bus twaalf. Geen zorgen.",
                        ["Oplossing + geruststellen", "Boos worden", "Stoppen"],
                        "Oplossing + geruststellen",
                    ),
                    rt_fb("___ is niet wat ik bestelde. (this)", ["Dit", "Zij", "Wij"], "Dit"),
                    rt_speak("Zeg: *Kunt u dat bevestigen?*", "Kunt u dat bevestigen?"),
                ],
            ),
        ],
    }


def lesson_l07() -> dict:
    lid = "a2-m10-l07-grammar-explaining-correcting"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Grammar & patterns · Explaining and correcting",
        "lessonType": "pattern",
        "order": 6,
        "cefrLevel": "A2",
        "durationEstimate": 17,
        "grammarTargets": ["a2.3-recovery-explain", "a2.3-recovery-repair"],
        "vocabTargets": ["lemma-want-m10", "lemma-omdat-m10", "lemma-maar-m10", "lemma-uitleg-m10", "lemma-betekenen-m10"],
        "canDoStatements": ["I can give a short correction or reason using want, omdat, and simple repair phrases."],
        "mistakeFocus": ["connectors", "word-order"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m10-l07-preview",
                "Warm-up — 5 woorden",
                [
                    ("want", "want", "because (coord.)", "🔗"),
                    ("omdat", "omdat", "because (subord.)", "🔗"),
                    ("maar", "maar", "but", "↩️"),
                    ("uitleg", "uitleg", "explanation", "📝"),
                    ("fout", "fout", "mistake", "❌"),
                ],
            ),
            grammar_card(
                "m10-l07-grammar",
                "Uitleg & correctie (kort)",
                "A2-blokken",
                "Gebruik *want* tussen twee zinnen. *Omdat* start vaak de reden-zin. *Maar* voor een tegenstelling. Houd het kort.",
                [
                    ("Sorry, ik bedoelde vandaag, want morgen ben ik weg.", "Sorry, I meant today, because tomorrow I'm away."),
                    ("Omdat het druk was, begreep ik het verkeerd.", "Because it was busy, I misunderstood."),
                    ("Dat klopt niet, maar ik snap de verwarring.", "That's not right, but I understand the confusion."),
                ],
            ),
            discovery_step(
                "m10-l07-discovery",
                "Mini-patronen",
                [
                    ("Ik bedoelde …", "I meant …", "correctie"),
                    ("Niet …, maar …", "Not …, but …", "contrast"),
                    ("Omdat ik …, …", "Because I …, …", "reden eerst"),
                    ("…, want ik …", "…, because I …", "reden na"),
                    ("Laat me het anders zeggen.", "Let me put it another way.", "herstart"),
                ],
            ),
            pl(
                "m10-l07-pl1",
                "Practice — 7×",
                ["want", "omdat", "bedoelde"],
                [
                    mcq(
                        "m10-l07-a1",
                        "Correctie + reden",
                        ["Sorry, ik bedoelde de andere deur, want deze is dicht.", "Sorry zonder uitleg.", "Deur zonder want."],
                        "Sorry, ik bedoelde de andere deur, want deze is dicht.",
                    ),
                    fb("m10-l07-a2", "___ het lawaai hoorde ik het niet. (because)", ["Omdat", "Maar", "En"], "Omdat"),
                    ro_tokens("m10-l07-r1", ["niet", "wat", "Dat", "bedoelde", "ik."], "Dat is niet wat ik bedoelde."),
                    mcq(
                        "m10-l07-a3",
                        "Tegenstelling",
                        ["Ik wil helpen, maar ik spreek niet zo goed Nederlands.", "Ik wil helpen want ik spreek nooit.", "Help zonder maar."],
                        "Ik wil helpen, maar ik spreek niet zo goed Nederlands.",
                    ),
                    mcq(
                        "m10-l07-a4",
                        "Geen lange speech",
                        ["Eén idee per zin is genoeg.", "Zeven ideeën in één zin is altijd beter.", "Geen idee is het beste."],
                        "Eén idee per zin is genoeg.",
                    ),
                    match_ex(
                        "m10-l07-m1",
                        "Koppel: begin → logische vervolgzin",
                        [
                            ("Omdat ik ziek was, …", "… kon ik niet komen."),
                            ("Ik was te laat, …", "… want de trein had vertraging."),
                            ("Dat is niet wat ik bedoelde, …", "… sorry voor de verwarring."),
                        ],
                        {
                            "Omdat ik ziek was, …": "… kon ik niet komen.",
                            "Ik was te laat, …": "… want de trein had vertraging.",
                            "Dat is niet wat ik bedoelde, …": "… sorry voor de verwarring.",
                        },
                    ),
                    mcq(
                        "m10-l07-a5",
                        "Herformuleren",
                        ["Laat me het anders zeggen: ik wilde om zevenen.", "Laat me zwijgen.", "Anders zeggen zonder inhoud."],
                        "Laat me het anders zeggen: ik wilde om zevenen.",
                    ),
                ],
            ),
            pl(
                "m10-l07-pl2",
                "Variatie — 6×",
                ["maar", "verwarring", "duidelijk"],
                [
                    mcq(
                        "m10-l07-b1",
                        "Excuses + uitleg",
                        ["Sorry voor de verwarring — ik bedoelde …", "Geen excuses nodig.", "Verwarring zonder sorry."],
                        "Sorry voor de verwarring — ik bedoelde …",
                    ),
                    fb("m10-l07-b2", "Ik spreek Nederlands, ___ het is nog moeilijk. (but)", ["maar", "want", "omdat"], "maar"),
                    ro_tokens("m10-l07-r2", ["zeker.", "niet", "het", "weet", "Ik"], "Ik weet het niet zeker."),
                    mcq(
                        "m10-l07-b3",
                        "Check begrip",
                        ["Is het zo goed begrepen?", "Begrijp nooit iets.", "Begrip zonder vraag."],
                        "Is het zo goed begrepen?",
                    ),
                    mcq(
                        "m10-l07-b4",
                        "Werk: deadline",
                        ["De deadline is vrijdag, niet donderdag.", "De deadline is altijd onduidelijk.", "Deadline zonder correctie."],
                        "De deadline is vrijdag, niet donderdag.",
                    ),
                    mcq(
                        "m10-l07-b5",
                        "Sociaal: zachte correctie",
                        ["Ik denk dat er een misverstand is — ik bedoelde …", "Jij liegt.", "Misverstand zonder oplossing."],
                        "Ik denk dat er een misverstand is — ik bedoelde …",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m10-l07-sp1",
                "Correctie",
                "Sorry, ik bedoelde morgenochtend, niet vanavond.",
                ["Sorry ik bedoelde morgenochtend niet vanavond", "Sorry, ik bedoelde morgenochtend, niet vanavond."],
                "Sorry ik bedoelde morgenochtend niet vanavond",
            ),
            speak_step(
                "m10-l07-sp2",
                "Want",
                "Ik moet nu weg, want ik heb een afspraak.",
                ["Ik moet nu weg want ik heb een afspraak", "Ik moet nu weg, want ik heb een afspraak."],
                "Ik moet nu weg want ik heb een afspraak",
            ),
            speak_step(
                "m10-l07-sp3",
                "Omdat",
                "Omdat het zo druk was, begreep ik het verkeerd.",
                ["Omdat het zo druk was begreep ik het verkeerd", "Omdat het zo druk was, begreep ik het verkeerd."],
                "Omdat het zo druk was begreep ik het verkeerd",
            ),
            speak_step(
                "m10-l07-sp4",
                "Maar",
                "Dat klopt niet, maar ik snap het.",
                ["Dat klopt niet maar ik snap het", "Dat klopt niet, maar ik snap het."],
                "Dat klopt niet maar ik snap het",
            ),
            speak_step(
                "m10-l07-sp5",
                "Herstart",
                "Laat me het anders zeggen: ik zoek de uitgang.",
                ["Laat me het anders zeggen ik zoek de uitgang", "Laat me het anders zeggen: ik zoek de uitgang."],
                "Laat me het anders zeggen ik zoek de uitgang",
                tips="*Laat me*: casual repair opener; *uitgang*: *UYT-khang* with guttural *g*.",
            ),
            recap_step(
                "m10-l07-recap",
                "Recap",
                ["want", "omdat", "bedoelde"],
                [
                    rt_fb("Ik was moe, ___ ik begreep het verkeerd. (because coord.)", ["want", "maar", "of"], "want"),
                    rt_ro(["verwarring.", "de", "voor", "Sorry"], "Sorry voor de verwarring."),
                    rt_speak("Zeg: *Dat is niet wat ik bedoelde.*", "Dat is niet wat ik bedoelde."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Omdat het druk was, hoorde ik het niet goed.",
                        ["Reden + probleem", "Bestellen", "Groeten"],
                        "Reden + probleem",
                    ),
                    rt_fb("___ ik ziek was, bleef ik thuis. (because subord.)", ["Omdat", "Want", "Maar"], "Omdat"),
                    rt_speak("Zeg: *Laat me het anders zeggen.*", "Laat me het anders zeggen."),
                ],
            ),
        ],
    }


def lesson_l08() -> dict:
    lid = "a2-m10-l08-writing-short-problem-messages"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Writing · Short problem messages",
        "lessonType": "writing",
        "order": 7,
        "cefrLevel": "A2",
        "durationEstimate": 17,
        "grammarTargets": ["a2.3-recovery-problems", "a2.3-recovery-clarify"],
        "vocabTargets": ["lemma-probleem-m10", "lemma-werken-m10", "lemma-vraag-m10", "lemma-sorry-m10", "lemma-helpen-m10"],
        "canDoStatements": ["I can write a very short message to report a problem or ask for help (app, email, note)."],
        "mistakeFocus": ["incorrect-phrasing", "weak-clarification"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m10-l08-preview",
                "Warm-up — 5 woorden",
                [
                    ("app", "app", "app", "📱"),
                    ("bericht", "bericht", "message", "💬"),
                    ("klacht", "klacht", "complaint", "📣"),
                    ("werkt niet", "werken", "doesn't work", "🚫"),
                    ("alstublieft", "alstublieft", "please", "🙏"),
                ],
            ),
            listen_read_step(
                "m10-l08-lr",
                "Input — voorbeeldberichten",
                [
                    ("Systeem", "Voorbeeld A: ‘Dag! Dit werkt niet bij mij. Kunt u helpen?’", "Example A: ‘Hi! This doesn't work for me. Can you help?’"),
                    ("Systeem", "Voorbeeld B: ‘Sorry, er is een probleem met mijn bestelling (#1234).’", "Example B: ‘Sorry, there's a problem with my order (#1234).’"),
                    ("Systeem", "Voorbeeld C: ‘Kunt u dat herhalen? Ik snap het niet.’ — ook prima in chat.", "Example C: ‘Could you repeat that? I don't get it.’ — fine in chat too."),
                    ("Systeem", "Tip: kort + duidelijk + wat je wilt.", "Tip: short + clear + what you want."),
                ],
                [
                    ("Wat is goed aan voorbeeld A?", ["Kort en vraagt om hulp", "Te lang en onduidelijk", "Geen groet"], "Kort en vraagt om hulp"),
                    ("Wat voegt B toe?", ["Een ordernummer", "Een gedicht", "Geen info"], "Een ordernummer"),
                    ("Welke toon past bij een app-bericht?", ["Vriendelijk en rustig", "Aggressief", "Geen woorden"], "Vriendelijk en rustig"),
                    ("Wat doet voorbeeld C?", ["Vraagt om herhaling", "Bestelt eten", "Stopt de app"], "Vraagt om herhaling"),
                ],
            ),
            discovery_step(
                "m10-l08-discovery",
                "Handige brokjes",
                [
                    ("Dit werkt niet.", "This doesn't work.", "tech"),
                    ("Ik heb een probleem met …", "I have a problem with …", "start"),
                    ("Kunt u mij helpen?", "Can you help me? (formeel)", "vraag"),
                    ("Kun je dat uitleggen?", "Can you explain that? (informeel chat)", "clarify"),
                ],
            ),
            pl(
                "m10-l08-pl1",
                "Practice — 6×",
                ["bericht", "helpen", "probleem"],
                [
                    mcq(
                        "m10-l08-a1",
                        "Beste openingsregel",
                        ["Goedemiddag, ik heb een vraag.", "Luister nu.", "Zwijg."],
                        "Goedemiddag, ik heb een vraag.",
                    ),
                    fb("m10-l08-a2", "Dit ___ niet op mijn telefoon. (works)", ["werkt", "eet", "zingt"], "werkt"),
                    ro_tokens("m10-l08-r1", ["helpen?", "mij", "Kunt", "u"], "Kunt u mij helpen?"),
                    mcq(
                        "m10-l08-a3",
                        "Als je iets niet begrijpt (chat)",
                        ["Ik begrijp dit bericht niet. Kunt u het simpeler uitleggen?", "Begrijp nooit.", "Chat zonder vraag."],
                        "Ik begrijp dit bericht niet. Kunt u het simpeler uitleggen?",
                    ),
                    mcq(
                        "m10-l08-a4",
                        "Geen spam aan details",
                        ["Eén probleem + één vraag", "Twintig problemen tegelijk", "Geen vraag"],
                        "Eén probleem + één vraag",
                    ),
                    match_ex(
                        "m10-l08-m1",
                        "Doel → zin",
                        [
                            ("Technisch", "Het werkt niet sinds vanochtend."),
                            ("Bestelling", "Er is een fout in mijn bestelling."),
                            ("Tijd", "Kunt u bevestigen welke tijd?"),
                        ],
                        {"Technisch": "Het werkt niet sinds vanochtend.", "Bestelling": "Er is een fout in mijn bestelling.", "Tijd": "Kunt u bevestigen welke tijd?"},
                    ),
                ],
            ),
            pl(
                "m10-l08-pl2",
                "Variatie — 6×",
                ["sorry", "vraag", "dank"],
                [
                    mcq(
                        "m10-l08-b1",
                        "Slotregel",
                        ["Alvast bedankt voor uw hulp.", "Geen dank ooit.", "Dank zonder respect."],
                        "Alvast bedankt voor uw hulp.",
                    ),
                    fb("m10-l08-b2", "Ik heb een ___ over de levering. (question)", ["vraag", "brood", "lied"], "vraag"),
                    ro_tokens("m10-l08-r2", ["niet.", "begrijp", "Ik", "het"], "Ik begrijp het niet."),
                    mcq(
                        "m10-l08-b3",
                        "Als je tijd nodig hebt",
                        ["Kunt u even geduld hebben? Ik zoek de code.", "Geen geduld.", "Geduld zonder vraag."],
                        "Kunt u even geduld hebben? Ik zoek de code.",
                    ),
                    mcq(
                        "m10-l08-b4",
                        "Formuleer beleefd",
                        ["Zou u dit kunnen nakijken, alstublieft?", "Doe nu alles.", "Nakijken zonder vraag."],
                        "Zou u dit kunnen nakijken, alstublieft?",
                    ),
                    mcq(
                        "m10-l08-b5",
                        "Herhaling in tekst",
                        ["Kunt u dat herhalen in één zin?", "Herhaal nooit.", "Zin zonder herhaling."],
                        "Kunt u dat herhalen in één zin?",
                    ),
                ],
                depth=True,
            ),
            writing_step(
                "m10-l08-w1",
                "Schrijven — kort",
                "Schrijf een kort bericht (min. 12 tekens).",
                "Schrijf: *Dit werkt niet. Kunt u mij helpen?* (of zoiets)",
                ["dit werkt niet kunt u mij helpen", "Dit werkt niet. Kunt u mij helpen?"],
                "Dit werkt niet. Kunt u mij helpen?",
                tips="Read like a short message: pause after the full stop; stress *WERKT*, *NIEET*, and *HE-len*.",
            ),
            writing_step(
                "m10-l08-w2",
                "Schrijven — bestelling",
                "Nog een mini-bericht.",
                "Schrijf: *Sorry, er is een probleem met mijn bestelling.*",
                ["sorry er is een probleem met mijn bestelling", "Sorry, er is een probleem met mijn bestelling."],
                "Sorry, er is een probleem met mijn bestelling.",
                tips="*bestelling*: bus-TEL-ling; *met mijn*: link smoothly; don’t drop the *n* in *mijn*.",
            ),
            speak_step(
                "m10-l08-sp1",
                "Hardop: hulp",
                "Ik heb een vraag. Kunt u mij helpen?",
                ["Ik heb een vraag kunt u mij helpen", "Ik heb een vraag. Kunt u mij helpen?"],
                "Ik heb een vraag kunt u mij helpen",
                tips="*vraag*: one syllable *vrakh*; second sentence polite, slightly slower.",
            ),
            speak_step(
                "m10-l08-sp2",
                "Hardop: werkt niet",
                "Het werkt niet. Wat moet ik doen?",
                ["Het werkt niet wat moet ik doen", "Het werkt niet. Wat moet ik doen?"],
                "Het werkt niet wat moet ik doen",
                tips="*Wat moet ik doen?*: stress *WAT* and *DOEN*; natural question melody.",
            ),
            speak_step(
                "m10-l08-sp3",
                "Bal terug",
                "Begrijpt u wat ik bedoel?",
                ["Begrijpt u wat ik bedoel", "Begrijpt u wat ik bedoel?"],
                "Begrijpt u wat ik bedoel",
                tips="*Begrijpt*: *buh-GRAYPT*; *bedoel*: *buh-DOOL*; rising intonation at the end.",
            ),
            recap_step(
                "m10-l08-recap",
                "Recap",
                ["bericht", "probleem", "helpen"],
                [
                    rt_fb("Dit ___ niet. (works)", ["werkt", "eet", "zingt"], "werkt"),
                    rt_ro(["bestelling.", "mijn", "met", "probleem", "een", "Er", "is"], "Er is een probleem met mijn bestelling."),
                    rt_speak("Zeg: *Ik begrijp het niet.*", "Ik begrijp het niet."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Kunt u dat uitleggen?",
                        ["Verduidelijking vragen", "Bestellen", "Zwemmen"],
                        "Verduidelijking vragen",
                    ),
                    rt_fb("___ u mij helpen? (could)", ["Kunt", "Eet", "Zwem"], "Kunt"),
                    rt_speak("Zeg: *Alvast bedankt.*", "Alvast bedankt."),
                ],
            ),
        ],
    }
