from .common import (
    LM,
    MID,
    discovery_step,
    fb,
    grammar_card,
    listen_read_step,
    listening_step,
    match_ex,
    mcq,
    pl,
    preview_step,
    recap_step,
    ro_tokens,
    rt_fb,
    rt_listen_mcq,
    rt_ro,
    rt_speak,
    speak_step,
)


def lesson_l01() -> dict:
    lid = "a2-m10-l01-listening-something-wrong-catch-situation"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Listening · Something went wrong · catch the situation",
        "lessonType": "input",
        "order": 0,
        "cefrLevel": "A2",
        "durationEstimate": 18,
        "grammarTargets": ["a2.3-recovery-problems", "a2.3-recovery-clarify"],
        "vocabTargets": ["lemma-probleem-m10", "lemma-bestelling-m10", "lemma-fout-m10", "lemma-sorry-m10", "lemma-helpen-m10"],
        "canDoStatements": ["I can follow a short dialogue where something is wrong and say what the problem is."],
        "mistakeFocus": ["listening-gist", "weak-clarification"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m10-l01-preview",
                "Warm-up — 5 woorden",
                [
                    ("probleem", "probleem", "problem", "⚠️"),
                    ("sorry", "sorry", "sorry", "🙏"),
                    ("bestelling", "bestelling", "order", "🧾"),
                    ("begrijpen", "begrijpen", "to understand", "🧠"),
                    ("helpen", "helpen", "to help", "🤝"),
                ],
            ),
            listening_step(
                "m10-l01-listen",
                "Input — verkeerde koffie",
                [
                    ("Emma", "Goedemiddag! Hier is uw bestelling: een cappuccino.", "Good afternoon! Here's your order: a cappuccino."),
                    ("Jij (Sam)", "Oh, sorry — ik had een thee besteld, geen koffie.", "Oh, sorry — I ordered tea, not coffee."),
                    ("Emma", "O jee! Mijn fout. Een momentje, ik maak een nieuwe.", "Oh dear! My mistake. One moment, I'll make a new one."),
                    ("Jij (Sam)", "Prima. Mag ik even checken: zwarte thee, zonder melk?", "Great. Can I just check: black tea, without milk?"),
                    ("Emma", "Ja, zwarte thee. Komt eraan.", "Yes, black tea. Coming up."),
                ],
                [
                    ("Wat is het probleem?", ["Verkeerde drank (koffie i.p.v. thee)", "Te duur", "De deur zit vast"], "Verkeerde drank (koffie i.p.v. thee)"),
                    ("Hoe reageert Sam?", ["Rustig en duidelijk", "Boos en hard", "Hij zegt niets"], "Rustig en duidelijk"),
                    ("Wat zegt Emma?", ["Ze geeft haar fout toe en helpt", "Ze weigert alles", "Ze belt de politie"], "Ze geeft haar fout toe en helpt"),
                    ("Wat wil Sam nog weten?", ["Check: zwarte thee zonder melk", "Het weer", "Haar adres"], "Check: zwarte thee zonder melk"),
                    ("Waar gebeurt dit?", ["In een café", "Op het strand", "In de sportschool"], "In een café"),
                ],
            ),
            discovery_step(
                "m10-l01-discovery",
                "Zinnen om te herkennen",
                [
                    ("Sorry, ik begrijp het niet.", "Sorry, I don't understand.", "rustig"),
                    ("Er is een probleem met …", "There's a problem with …", "probleem"),
                    ("Kunt u dat herhalen?", "Could you repeat that?", "formeel"),
                    ("Geen probleem.", "No problem. / That's OK.", "kalmeren"),
                    ("Pardon, ik verstond u niet.", "Pardon, I didn't catch that.", "kort herhalen"),
                ],
            ),
            pl(
                "m10-l01-pl1",
                "Practice — 6×",
                ["sorry", "bestelling", "fout"],
                [
                    mcq(
                        "m10-l01-a1",
                        "Als iets niet klopt, klinkt dit het meest natuurlijk",
                        ["Sorry, dit klopt niet. Ik had … besteld.", "Jij bent dom, altijd.", "Zwijg zonder uitleg."],
                        "Sorry, dit klopt niet. Ik had … besteld.",
                    ),
                    fb("m10-l01-a2", "Er is een ___ met mijn kaartje. (problem)", ["probleem", "feest", "lied"], "probleem"),
                    ro_tokens("m10-l01-r1", ["niet.", "Het", "werkt"], "Het werkt niet."),
                    mcq(
                        "m10-l01-a3",
                        "‘Mijn fout’ betekent ongeveer",
                        ["Ik heb een fout gemaakt", "Jij liegt", "Geen idee"],
                        "Ik heb een fout gemaakt",
                    ),
                    mcq(
                        "m10-l01-a4",
                        "Vriendelijke start",
                        ["Sorry, mag ik even iets zeggen?", "Hé, luister eens nu!", "Stil zijn."],
                        "Sorry, mag ik even iets zeggen?",
                    ),
                    match_ex(
                        "m10-l01-m1",
                        "Koppel: situatie → zin",
                        [
                            ("Te snel praten", "Kunt u langzamer spreken?"),
                            ("Niet verstaan", "Ik begrijp het niet."),
                            ("Foute order", "Dit is niet wat ik bestelde."),
                        ],
                        {"Te snel praten": "Kunt u langzamer spreken?", "Niet verstaan": "Ik begrijp het niet.", "Foute order": "Dit is niet wat ik bestelde."},
                    ),
                ],
            ),
            pl(
                "m10-l01-pl2",
                "Variatie — 6×",
                ["helpen", "wacht", "thee"],
                [
                    mcq(
                        "m10-l01-b1",
                        "Als je tijd nodig hebt om te denken",
                        ["Wacht even …", "Stop de wereld.", "Nu meteen beslissen."],
                        "Wacht even …",
                    ),
                    fb("m10-l01-b2", "Kunt u mij ___? (help)", ["helpen", "zingen", "dansen"], "helpen"),
                    ro_tokens("m10-l01-r2", ["herhalen?", "dat", "Kunt", "u"], "Kunt u dat herhalen?"),
                    mcq(
                        "m10-l01-b3",
                        "Zelfde idee: ‘nog een keer’",
                        ["Kunt u dat nog een keer zeggen?", "Zeg nooit iets.", "Herhaal zonder beleefdheid."],
                        "Kunt u dat nog een keer zeggen?",
                    ),
                    mcq(
                        "m10-l01-b4",
                        "Als je niet zeker bent",
                        ["Ik weet het niet zeker, maar …", "Ik weet alles perfect.", "Zeker zonder twijfel altijd."],
                        "Ik weet het niet zeker, maar …",
                    ),
                    mcq(
                        "m10-l01-b5",
                        "Tone: blijven in gesprek",
                        ["Geen probleem, dat kan gebeuren.", "Ik wil nooit meer praten.", "Fout zonder oplossing."],
                        "Geen probleem, dat kan gebeuren.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m10-l01-sp1",
                "Jouw beurt",
                "Sorry, dit klopt niet. Ik had water besteld.",
                ["Sorry dit klopt niet ik had water besteld", "Sorry, dit klopt niet. Ik had water besteld."],
                "Sorry dit klopt niet ik had water besteld",
                tips="Soft *SOR-rie*; stress *KLOPT* and *WAA-ter*.",
            ),
            speak_step(
                "m10-l01-sp2",
                "Verduidelijken",
                "Ik begrijp het niet. Kunt u dat herhalen?",
                ["Ik begrijp het niet kunt u dat herhalen", "Ik begrijp het niet. Kunt u dat herhalen?"],
                "Ik begrijp het niet kunt u dat herhalen",
                tips="Stress *BEG-rip* and *HEER-ha-len*; *u* is a short rounded vowel after *Kunt*.",
            ),
            speak_step(
                "m10-l01-sp3",
                "Langzamer",
                "Kunt u iets langzamer praten, alstublieft?",
                ["Kunt u iets langzamer praten alstublieft", "Kunt u iets langzamer praten, alstublieft?"],
                "Kunt u iets langzamer praten alstublieft",
                tips="*Lang-ZAA-mer*: long *aa*; *alstublieft* flows as one polite phrase (AL-stu-BLIEFT).",
            ),
            speak_step(
                "m10-l01-sp4",
                "Hulp",
                "Kunt u mij helpen? Het werkt niet.",
                ["Kunt u mij helpen het werkt niet", "Kunt u mij helpen? Het werkt niet."],
                "Kunt u mij helpen het werkt niet",
                tips="Stress *HE-len*; *werkt*: clear *r*; *niet* with a firm *t* at the end.",
            ),
            speak_step(
                "m10-l01-sp5",
                "Kalmeren",
                "Geen probleem. Even geduld.",
                ["Geen probleem even geduld", "Geen probleem. Even geduld."],
                "Geen probleem even geduld",
            ),
            speak_step(
                "m10-l01-sp6",
                "Check (herstel)",
                "Dus zwarte thee zonder melk, klopt dat?",
                ["Dus zwarte thee zonder melk klopt dat", "Dus zwarte thee zonder melk, klopt dat?"],
                "Dus zwarte thee zonder melk klopt dat",
                tips="*Dus* leads the question; *zonder*: stress *ZON-der*; rising intonation on *dat?*.",
            ),
            recap_step(
                "m10-l01-recap",
                "Recap",
                ["probleem", "sorry", "herhalen"],
                [
                    rt_fb("Er is een ___ met mijn bestelling.", ["probleem", "feest", "lied"], "probleem"),
                    rt_ro(["niet.", "Het", "werkt"], "Het werkt niet."),
                    rt_speak("Zeg: *Ik begrijp het niet.*", "Ik begrijp het niet."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Kunt u dat herhalen?",
                        ["Herhalen / verduidelijken", "Bestellen zonder hulp", "Afscheid"],
                        "Herhalen / verduidelijken",
                    ),
                    rt_fb("Kunt u ___ spreken? (slow)", ["langzamer", "harder", "stiller"], "langzamer"),
                    rt_speak("Zeg: *Kunt u mij helpen?*", "Kunt u mij helpen?"),
                ],
            ),
        ],
    }


def lesson_l02() -> dict:
    lid = "a2-m10-l02-listen-read-problems-misunderstandings"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Listening & reading · Problems and misunderstandings",
        "lessonType": "input",
        "order": 1,
        "cefrLevel": "A2",
        "durationEstimate": 17,
        "grammarTargets": ["a2.3-recovery-repair", "a2.3-recovery-clarify"],
        "vocabTargets": ["lemma-misverstand-m10", "lemma-betekenen-m10", "lemma-wacht-m10", "lemma-vraag-m10", "lemma-maar-m10"],
        "canDoStatements": ["I can read a short exchange where people misunderstand each other and say what went wrong."],
        "mistakeFocus": ["instruction-meaning", "misunderstanding"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m10-l02-preview",
                "Warm-up — 5 woorden",
                [
                    ("misverstand", "misverstand", "misunderstanding", "💬"),
                    ("bedoelen", "bedoelen", "to mean", "💭"),
                    ("wacht even", "wacht", "wait a moment", "⏸️"),
                    ("vraag", "vraag", "question", "❓"),
                    ("maar", "maar", "but", "↩️"),
                ],
            ),
            listen_read_step(
                "m10-l02-lr",
                "Input — app-gesprek (afspraak)",
                [
                    ("Noah", "Zie je vanavond om zeven bij de ingang?", "See you tonight at seven at the entrance?"),
                    ("Sara", "Zeven? Ik dacht om halfacht. Wacht even…", "Seven? I thought half past seven. Wait…"),
                    ("Noah", "O! Sorry, ik bedoelde 19:30, niet 19:00.", "Oh! Sorry, I meant 7:30 p.m., not 7:00."),
                    ("Sara", "Ah, nu snap ik het. Geen probleem, tot straks!", "Ah, now I get it. No problem, see you later!"),
                    ("Noah", "Top. Als iets niet klopt, app je me?", "Great. If something's off, text me?"),
                ],
                [
                    ("Wat was het misverstand?", ["Tijd: 19:00 vs 19:30", "De plaats: verkeerde stad", "Het weer"], "Tijd: 19:00 vs 19:30"),
                    ("Hoe lost Noah het op?", ["Hij legt uit wat hij bedoelde", "Hij stopt de chat", "Hij wordt boos"], "Hij legt uit wat hij bedoelde"),
                    ("Wat zegt Sara als ze het snapt?", ["Nu snap ik het", "Ik begrijp nooit iets", "Stop maar"], "Nu snap ik het"),
                    ("Welke ‘repair’-zin gebruikt Noah?", ["Ik bedoelde …", "Ik weet niks", "Zwijg"], "Ik bedoelde …"),
                    ("Waar gaat de chat over?", ["Afspraak + correctie", "Alleen eten", "Werk zonder tijd"], "Afspraak + correctie"),
                ],
            ),
            discovery_step(
                "m10-l02-discovery",
                "Repair in chat",
                [
                    ("Wacht even …", "Wait …", "adem"),
                    ("Dat is niet wat ik bedoelde.", "That's not what I meant.", "correctie"),
                    ("Wat bedoel je precies?", "What do you mean exactly?", "doorvragen"),
                    ("Nu snap ik het.", "Now I get it.", "opgelucht"),
                    ("Sorry, ik hoor je niet goed.", "Sorry, I can't hear you well.", "lawaai / slechte verbinding"),
                ],
            ),
            pl(
                "m10-l02-pl1",
                "Practice — 6×",
                ["bedoelen", "snap", "tijd"],
                [
                    mcq(
                        "m10-l02-a1",
                        "Als de ander het verkeerd begrijpt",
                        ["Sorry, ik bedoelde …", "Jij hoort slecht, altijd.", "Zwijg."],
                        "Sorry, ik bedoelde …",
                    ),
                    fb("m10-l02-a2", "Wat ___ je precies? (mean — informal)", ["bedoel", "eet", "koop"], "bedoel"),
                    ro_tokens("m10-l02-r1", ["niet", "Dat", "wat", "ik", "bedoelde."], "Dat is niet wat ik bedoelde."),
                    mcq(
                        "m10-l02-a3",
                        "‘Snap je?’ vraag je om …",
                        ["Te checken of het duidelijk is", "Te eisen", "Te stoppen"],
                        "Te checken of het duidelijk is",
                    ),
                    mcq(
                        "m10-l02-a4",
                        "Vriendelijke check",
                        ["Begrijp je wat ik bedoel?", "Begrijp je nooit iets?", "Begrijp zonder vraag?"],
                        "Begrijp je wat ik bedoel?",
                    ),
                    match_ex(
                        "m10-l02-m1",
                        "Koppel",
                        [
                            ("Verwarring", "Wacht even, even duidelijk maken …"),
                            ("Excuses", "Sorry voor de verwarring."),
                            ("Check", "Dus morgen, niet vandaag?"),
                        ],
                        {"Verwarring": "Wacht even, even duidelijk maken …", "Excuses": "Sorry voor de verwarring.", "Check": "Dus morgen, niet vandaag?"},
                    ),
                ],
            ),
            pl(
                "m10-l02-pl2",
                "Variatie — 7×",
                ["maar", "vraag", "kloppen"],
                [
                    mcq(
                        "m10-l02-b1",
                        "Als info niet klopt",
                        ["Dat klopt niet — ik had …", "Dat klopt altijd perfect.", "Klopt zonder uitleg."],
                        "Dat klopt niet — ik had …",
                    ),
                    fb("m10-l02-b2", "Ik heb een ___. (question)", ["vraag", "trein", "brood"], "vraag"),
                    ro_tokens("m10-l02-r2", ["u?", "Wat", "bedoelt"], "Wat bedoelt u?"),
                    mcq(
                        "m10-l02-b3",
                        "Informeel: langzamer",
                        ["Kun je iets langzamer praten?", "Zwijg nu.", "Praat altijd hard."],
                        "Kun je iets langzamer praten?",
                    ),
                    mcq(
                        "m10-l02-b4",
                        "Connector: tegenstelling",
                        ["Ik wil mee, maar ik ben te laat.", "Ik wil mee en daarom ben ik te laat zonder logica.", "Mee willen zonder maar."],
                        "Ik wil mee, maar ik ben te laat.",
                    ),
                    mcq(
                        "m10-l02-b5",
                        "Herstart je zin",
                        ["Laat me het anders zeggen: …", "Laat me zwijgen voor altijd.", "Anders zonder zin."],
                        "Laat me het anders zeggen: …",
                    ),
                    mcq(
                        "m10-l02-b6",
                        "Kort signaleren: je mist iets",
                        ["Pardon? Kun je dat nog een keer zeggen?", "Zwijg als je iets mist.", "Pardon zonder vraag."],
                        "Pardon? Kun je dat nog een keer zeggen?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m10-l02-sp1",
                "Correctie",
                "Sorry, ik bedoelde morgen, niet vandaag.",
                ["Sorry ik bedoelde morgen niet vandaag", "Sorry, ik bedoelde morgen, niet vandaag."],
                "Sorry ik bedoelde morgen niet vandaag",
            ),
            speak_step(
                "m10-l02-sp2",
                "Meaning",
                "Wat bedoel je precies?",
                ["Wat bedoel je precies", "wat bedoel je precies"],
                "Wat bedoel je precies",
                tips="Stress *WAT* and *bedoel*; *precies*: second syllable *CIES*.",
            ),
            speak_step(
                "m10-l02-sp3",
                "Formeel",
                "Wat bedoelt u? Ik begrijp het niet helemaal.",
                ["Wat bedoelt u ik begrijp het niet helemaal", "Wat bedoelt u? Ik begrijp het niet helemaal."],
                "Wat bedoelt u ik begrijp het niet helemaal",
                tips="Formal *u* after *bedoelt*; *helemaal*: hay-luh-MAAL with stress on the last part.",
            ),
            speak_step(
                "m10-l02-sp4",
                "Oplossing",
                "Nu snap ik het. Geen probleem!",
                ["Nu snap ik het geen probleem", "Nu snap ik het. Geen probleem!"],
                "Nu snap ik het geen probleem",
            ),
            recap_step(
                "m10-l02-recap",
                "Recap",
                ["bedoelen", "misverstand", "wacht"],
                [
                    rt_fb("___ even — ik leg het uit. (wait)", ["Wacht", "Loop", "Spring"], "Wacht"),
                    rt_ro(["bedoelde.", "ik", "Dat", "niet", "is", "wat"], "Dat is niet wat ik bedoelde."),
                    rt_speak("Zeg: *Wat bedoel je?*", "Wat bedoel je?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Nu snap ik het.",
                        ["Begrip / opluchting", "Boos worden", "Stoppen"],
                        "Begrip / opluchting",
                    ),
                    rt_fb("Ik heb een ___. (question)", ["vraag", "fiets", "kaas"], "vraag"),
                    rt_speak("Zeg: *Dat klopt niet.*", "Dat klopt niet."),
                ],
            ),
        ],
    }


def lesson_l03() -> dict:
    lid = "a2-m10-l03-grammar-clarifying-asking-help"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Grammar & patterns · Clarifying and asking for help",
        "lessonType": "pattern",
        "order": 2,
        "cefrLevel": "A2",
        "durationEstimate": 18,
        "grammarTargets": ["a2.3-recovery-clarify", "a2.3-recovery-modals"],
        "vocabTargets": ["lemma-begrijpen-m10", "lemma-herhalen-m10", "lemma-langzaam-m10", "lemma-kunnen-m10", "lemma-mogen-m10"],
        "canDoStatements": ["I can use fixed patterns to ask for repetition, slower speech, and help without sounding rude."],
        "mistakeFocus": ["register", "word-order"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m10-l03-preview",
                "Warm-up — 5 woorden",
                [
                    ("herhalen", "herhalen", "to repeat", "🔁"),
                    ("langzaam", "langzaam", "slow", "🐢"),
                    ("kunnen", "kunnen", "can", "✅"),
                    ("mogen", "mogen", "may", "🚦"),
                    ("alstublieft", "alstublieft", "please (formal)", "🙏"),
                ],
            ),
            grammar_card(
                "m10-l03-grammar",
                "Patronen — verduidelijken & hulp",
                "Vaste blokken (A2)",
                "Kies *u* bij vreemden/dienst, *je/jij* bij vrienden. Combineer: sorry + vraag + (optioneel) waarom.",
                [
                    ("Ik begrijp het niet. Kunt u dat herhalen?", "I don't understand. Could you repeat that?"),
                    ("Kunt u langzamer spreken, alstublieft?", "Could you speak more slowly, please?"),
                    ("Mag ik u iets vragen?", "May I ask you something?"),
                    ("Kunt u mij helpen met …?", "Could you help me with …?"),
                ],
            ),
            discovery_step(
                "m10-l03-discovery",
                "Welke toon?",
                [
                    ("Kunt u …? (winkel)", "Could you …? (shop)", "formeel"),
                    ("Kun je …? (vriend)", "Can you …? (friend)", "informeel"),
                    ("Sorry, even storen …", "Sorry to bother you …", "soft start"),
                    ("Eén vraag per keer", "One question at a time", "duidelijk"),
                    ("Pardon? / Sorry, ik verstond u niet.", "Pardon? / Sorry, I didn't catch that.", "kort signaleren"),
                ],
            ),
            pl(
                "m10-l03-pl1",
                "Practice — 6×",
                ["herhalen", "langzaam", "helpen"],
                [
                    mcq(
                        "m10-l03-a1",
                        "Beste opening in de supermarkt",
                        ["Sorry, mag ik u iets vragen?", "Hé, luister!", "Zwijg."],
                        "Sorry, mag ik u iets vragen?",
                    ),
                    fb("m10-l03-a2", "___ u dat nog een keer zeggen? (could)", ["Kunt", "Eet", "Zwem"], "Kunt"),
                    ro_tokens("m10-l03-r1", ["spreken?", "langzamer", "Kunt", "u", "iets"], "Kunt u iets langzamer spreken?"),
                    mcq(
                        "m10-l03-a3",
                        "Als je het woord niet kent",
                        ["Hoe zeg je dat in het Nederlands?", "Stop de taal.", "Geen vraag stellen."],
                        "Hoe zeg je dat in het Nederlands?",
                    ),
                    mcq(
                        "m10-l03-a4",
                        "Niet overdreven formeel voor A2",
                        ["Kunt u mij helpen? (winkel/balie)", "Gij zijt … (archaïsch)", "Zonder vraag eisen."],
                        "Kunt u mij helpen? (winkel/balie)",
                    ),
                    match_ex(
                        "m10-l03-m1",
                        "Formeel ↔ informeel (zelfde idee)",
                        [
                            ("Kunt u helpen?", "Kun je helpen?"),
                            ("Wat bedoelt u?", "Wat bedoel je?"),
                            ("Spreekt u Nederlands?", "Spreek je Nederlands?"),
                        ],
                        {"Kunt u helpen?": "Kun je helpen?", "Wat bedoelt u?": "Wat bedoel je?", "Spreekt u Nederlands?": "Spreek je Nederlands?"},
                    ),
                ],
            ),
            pl(
                "m10-l03-pl2",
                "Variatie — 7×",
                ["mogen", "vraag", "wacht"],
                [
                    mcq(
                        "m10-l03-b1",
                        "Als het druk is",
                        ["Sorry, heel kort: waar is …?", "Duw zonder woorden.", "Schreeuw."],
                        "Sorry, heel kort: waar is …?",
                    ),
                    fb("m10-l03-b2", "Mag ik een ___ stellen? (question)", ["vraag", "brood", "lied"], "vraag"),
                    ro_tokens("m10-l03-r2", ["begrijp", "het", "Ik", "niet."], "Ik begrijp het niet."),
                    mcq(
                        "m10-l03-b3",
                        "Modal: verzoek",
                        ["Kunt u dit voor mij checken?", "U moet altijd ja zeggen.", "Check zonder vraag."],
                        "Kunt u dit voor mij checken?",
                    ),
                    mcq(
                        "m10-l03-b4",
                        "Als je de richting niet snapt",
                        ["Kunt u dat op de kaart aanwijzen?", "Raad maar.", "Geen uitleg."],
                        "Kunt u dat op de kaart aanwijzen?",
                    ),
                    mcq(
                        "m10-l03-b5",
                        "Samenvatting in één zin",
                        ["Ik begrijp het niet — kunt u het herhalen?", "Ik begrijp alles perfect altijd.", "Herhaal zonder sorry."],
                        "Ik begrijp het niet — kunt u het herhalen?",
                    ),
                    mcq(
                        "m10-l03-b6",
                        "Als je het geluid of accent niet volgt",
                        ["Sorry, ik versta u niet goed. Kunt u langzamer praten?", "Versta alles altijd perfect.", "Versta zonder sorry."],
                        "Sorry, ik versta u niet goed. Kunt u langzamer praten?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m10-l03-sp1",
                "Formeel",
                "Mag ik u iets vragen? Ik begrijp het niet.",
                ["Mag ik u iets vragen ik begrijp het niet", "Mag ik u iets vragen? Ik begrijp het niet."],
                "Mag ik u iets vragen ik begrijp het niet",
            ),
            speak_step(
                "m10-l03-sp2",
                "Herhalen",
                "Kunt u dat herhalen, alstublieft?",
                ["Kunt u dat herhalen alstublieft", "Kunt u dat herhalen, alstublieft?"],
                "Kunt u dat herhalen alstublieft",
                tips="Roll the *r* in *herhalen* lightly; keep *Kunt u* crisp and polite.",
            ),
            speak_step(
                "m10-l03-sp3",
                "Langzamer",
                "Kunt u langzamer spreken?",
                ["Kunt u langzamer spreken", "kunt u langzamer spreken"],
                "Kunt u langzamer spreken",
                tips="*spreken*: *spr* cluster then *AY-kuhn*; question intonation rises at the end.",
            ),
            speak_step(
                "m10-l03-sp4",
                "Hulp",
                "Kunt u mij helpen? Ik heb een vraag.",
                ["Kunt u mij helpen ik heb een vraag", "Kunt u mij helpen? Ik heb een vraag."],
                "Kunt u mij helpen ik heb een vraag",
            ),
            speak_step(
                "m10-l03-sp5",
                "Informeel",
                "Kun je dat nog een keer zeggen? Ik snap het niet.",
                ["Kun je dat nog een keer zeggen ik snap het niet", "Kun je dat nog een keer zeggen? Ik snap het niet."],
                "Kun je dat nog een keer zeggen ik snap het niet",
                tips="Informal *kun je*: *je* is short; *zeggen*: *ZEG-uh*; *snap*: one crisp syllable.",
            ),
            recap_step(
                "m10-l03-recap",
                "Recap",
                ["kunt", "herhalen", "langzaam"],
                [
                    rt_fb("___ ik u iets vragen? (may)", ["Mag", "Eet", "Zwem"], "Mag"),
                    rt_ro(["alstublieft?", "herhalen,", "dat", "Kunt", "u"], "Kunt u dat herhalen, alstublieft?"),
                    rt_speak("Zeg: *Ik begrijp het niet.*", "Ik begrijp het niet."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Kunt u langzamer spreken?",
                        ["Tempo aanpassen", "Bestellen", "Groeten"],
                        "Tempo aanpassen",
                    ),
                    rt_fb("Kun ___ dat nog een keer zeggen? (you informal)", ["je", "u", "wij"], "je"),
                    rt_speak("Zeg: *Kunt u mij helpen?*", "Kunt u mij helpen?"),
                ],
            ),
        ],
    }


def lesson_l04() -> dict:
    lid = "a2-m10-l04-practice-problem-statements-responses"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Controlled practice · Problem statements and responses",
        "lessonType": "practice",
        "order": 3,
        "cefrLevel": "A2",
        "durationEstimate": 16,
        "grammarTargets": ["a2.3-recovery-problems", "a2.3-recovery-connectors"],
        "vocabTargets": ["lemma-werken-m10", "lemma-kloppen-m10", "lemma-winkel-m10", "lemma-want-m10", "lemma-omdat-m10"],
        "canDoStatements": ["I can choose natural replies when someone states a problem or when I need to respond helpfully."],
        "mistakeFocus": ["incorrect-phrasing", "connectors"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m10-l04-preview",
                "Warm-up — 5 woorden",
                [
                    ("het werkt niet", "werken", "it doesn't work", "🔧"),
                    ("klopt", "kloppen", "correct", "✔️"),
                    ("want", "want", "because", "➡️"),
                    ("omdat", "omdat", "because", "➡️"),
                    ("winkel", "winkel", "shop", "🛒"),
                ],
            ),
            listening_step(
                "m10-l04-listen",
                "Input — kassa (kort)",
                [
                    ("Klant", "Excuseer, dit kaartje werkt niet bij de poortjes.", "Excuse me, this ticket doesn't work at the gates."),
                    ("Medewerker", "Geen zorgen. Laat even zien … Ah, dit is voor morgen, niet voor vandaag.", "Don't worry. Let me see … Ah, this is for tomorrow, not for today."),
                    ("Klant", "O! Sorry, mijn fout. Wat kan ik doen?", "Oh! Sorry, my mistake. What can I do?"),
                    ("Medewerker", "We kunnen het omwisselen bij de balie. Komt u mee?", "We can exchange it at the counter. Will you come with me?"),
                ],
                [
                    ("Wat is het probleem?", ["Kaartje werkt niet + verkeerde dag", "Te veel regen", "Geen probleem"], "Kaartje werkt niet + verkeerde dag"),
                    ("Waarom werkt het niet?", ["Het is voor morgen", "Het is te klein", "Het is te duur"], "Het is voor morgen"),
                    ("Hoe reageert de klant?", ["Sorry, eigen fout", "Boos naar medewerker", "Zwijgen"], "Sorry, eigen fout"),
                    ("Wat stelt de medewerker voor?", ["Omruilen bij de balie", "Niets", "Wegrennen"], "Omruilen bij de balie"),
                ],
            ),
            discovery_step(
                "m10-l04-discovery",
                "Reageren op een probleem",
                [
                    ("Geen zorgen.", "Don't worry.", "kalmeren"),
                    ("Laat even zien.", "Let me see.", "help stap 1"),
                    ("We kunnen …", "We can …", "oplossing"),
                    ("Komt u mee?", "Will you come with me?", "begeleiden"),
                ],
            ),
            pl(
                "m10-l04-pl1",
                "Practice — 6×",
                ["werkt", "want", "balie"],
                [
                    mcq(
                        "m10-l04-a1",
                        "Als iets technisch niet gaat",
                        ["Het werkt niet. Kunt u kijken?", "Het werkt nooit, altijd jouw schuld.", "Werkt zonder uitleg."],
                        "Het werkt niet. Kunt u kijken?",
                    ),
                    fb("m10-l04-a2", "Dat ___ niet — ik had een andere datum. (correct)", ["klopt", "zingt", "danst"], "klopt"),
                    ro_tokens("m10-l04-r1", ["probleem", "een", "Er", "met", "is", "mijn", "kaartje."], "Er is een probleem met mijn kaartje."),
                    mcq(
                        "m10-l04-a3",
                        "Geef een korte reden met *want*",
                        ["Ik moet nu weg, want ik ben te laat.", "Ik moet nu weg omdat zonder zin.", "Weg zonder want."],
                        "Ik moet nu weg, want ik ben te laat.",
                    ),
                    mcq(
                        "m10-l04-a4",
                        "Geef een korte reden met *omdat*",
                        ["Omdat de trein vertraging had, ben ik te laat.", "Omdat zonder werkwoord altijd.", "Trein zonder omdat."],
                        "Omdat de trein vertraging had, ben ik te laat.",
                    ),
                    match_ex(
                        "m10-l04-m1",
                        "Probleem → passende reactie",
                        [
                            ("Ik begrijp het niet.", "Kunt u dat herhalen?"),
                            ("Het werkt niet.", "Laat even zien."),
                            ("Dit is niet mijn bestelling.", "Sorry, ik check het."),
                        ],
                        {"Ik begrijp het niet.": "Kunt u dat herhalen?", "Het werkt niet.": "Laat even zien.", "Dit is niet mijn bestelling.": "Sorry, ik check het."},
                    ),
                ],
            ),
            pl(
                "m10-l04-pl2",
                "Variatie — 6×",
                ["maar", "anders", "verwacht"],
                [
                    mcq(
                        "m10-l04-b1",
                        "Tegenstelling",
                        ["Ik wil helpen, maar ik weet het niet zeker.", "Ik wil helpen want ik weet zeker zonder logica.", "Help zonder maar."],
                        "Ik wil helpen, maar ik weet het niet zeker.",
                    ),
                    fb("m10-l04-b2", "Dit is ___ dan ik verwachtte. (different)", ["anders", "hetzelfde", "klein"], "anders"),
                    ro_tokens("m10-l04-r2", ["niet", "Ik", "zeker.", "het", "weet", "niet"], "Ik weet het niet zeker."),
                    mcq(
                        "m10-l04-b3",
                        "Als de info anders is",
                        ["Dat is anders dan verwacht.", "Dat is altijd exact hetzelfde.", "Verwacht zonder verschil."],
                        "Dat is anders dan verwacht.",
                    ),
                    mcq(
                        "m10-l04-b4",
                        "Service: bevestigen",
                        ["Dus u bedoelt perron zes?", "Dus u bedoelt niks?", "Bedoel zonder check."],
                        "Dus u bedoelt perron zes?",
                    ),
                    mcq(
                        "m10-l04-b5",
                        "Slot: vriendelijk",
                        ["Prima, dan lossen we het zo op.", "Nooit oplossen.", "Probleem zonder oplossing."],
                        "Prima, dan lossen we het zo op.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m10-l04-sp1",
                "Probleem",
                "Er is een probleem. Het werkt niet.",
                ["Er is een probleem het werkt niet", "Er is een probleem. Het werkt niet."],
                "Er is een probleem het werkt niet",
            ),
            speak_step(
                "m10-l04-sp2",
                "Niet correct",
                "Dat klopt niet. Ik had iets anders besteld.",
                ["Dat klopt niet ik had iets anders besteld", "Dat klopt niet. Ik had iets anders besteld."],
                "Dat klopt niet ik had iets anders besteld",
                tips="Stress *KLOPT* and *NIEET*; *besteld*: second syllable *STELD*.",
            ),
            speak_step(
                "m10-l04-sp3",
                "Reden",
                "Ik ben te laat, want de bus had vertraging.",
                ["Ik ben te laat want de bus had vertraging", "Ik ben te laat, want de bus had vertraging."],
                "Ik ben te laat want de bus had vertraging",
            ),
            speak_step(
                "m10-l04-sp4",
                "Hulp",
                "Kunt u mij naar de balie brengen?",
                ["Kunt u mij naar de balie brengen", "kunt u mij naar de balie brengen"],
                "Kunt u mij naar de balie brengen",
            ),
            recap_step(
                "m10-l04-recap",
                "Recap",
                ["probleem", "werkt", "want"],
                [
                    rt_fb("Het ___ niet. (works)", ["werkt", "eet", "zingt"], "werkt"),
                    rt_ro(["niet.", "klopt", "Dat"], "Dat klopt niet."),
                    rt_speak("Zeg: *Er is een probleem.*", "Er is een probleem."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Komt u mee naar de balie?",
                        ["Begeleiden / oplossen", "Afscheid", "Bestellen eten"],
                        "Begeleiden / oplossen",
                    ),
                    rt_fb("Ik spreek Nederlands, ___ het is moeilijk. (but)", ["maar", "want", "omdat"], "maar"),
                    rt_speak("Zeg: *Ik weet het niet zeker.*", "Ik weet het niet zeker."),
                ],
            ),
        ],
    }
