from .common import (
    LM,
    MID,
    discovery_step,
    fb,
    grammar_card,
    listen_read_step,
    listening_step,
    match_ex,
    mcq,
    pl,
    preview_step,
    recap_step,
    ro_tokens,
    rt_fb,
    rt_listen_mcq,
    rt_ro,
    rt_speak,
    speak_step,
    writing_step,
)


def lesson_l01() -> dict:
    lid = "a2-m07-l01-listening-station-catch-situation"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Listening · At the station · catch the situation",
        "lessonType": "input",
        "order": 0,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-transport-questions", "a2.2-announcements-chunks"],
        "vocabTargets": ["lemma-station", "lemma-perron", "lemma-trein", "lemma-vertraging", "lemma-kaartje"],
        "canDoStatements": [
            "I can follow a short station help desk talk and pick out platform, delay, and what the traveller needs.",
        ],
        "mistakeFocus": ["listening-gist", "vocab", "announcement-chunks"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m07-l01-preview",
                "Warm-up — 5 woorden",
                [
                    ("station", "station", "station", "🚉"),
                    ("perron", "perron", "platform", "🚏"),
                    ("trein", "trein", "train", "🚆"),
                    ("vertraging", "vertraging", "delay", "⏱️"),
                    ("kaartje", "kaartje", "ticket", "🎫"),
                ],
            ),
            listening_step(
                "m07-l01-listen",
                "Input — reizigersbalie",
                [
                    (
                        "Medewerker",
                        "Goedemiddag. Waar wilt u naartoe?",
                        "Good afternoon. Where do you want to go?",
                    ),
                    (
                        "Alex",
                        "Ik wil naar Utrecht Centraal. Hoe laat vertrekt de trein?",
                        "I want to go to Utrecht Central. What time does the train leave?",
                    ),
                    (
                        "Medewerker",
                        "De trein vertrekt om kwart over drie, maar er is tien minuten vertraging.",
                        "The train leaves at a quarter past three, but there is a ten-minute delay.",
                    ),
                    (
                        "Alex",
                        "Oké. Van welk perron?",
                        "Okay. From which platform?",
                    ),
                    (
                        "Medewerker",
                        "Van perron zeven. U moet nu snel lopen.",
                        "From platform seven. You need to walk quickly now.",
                    ),
                ],
                [
                    ("Waar wil Alex naartoe?", ["Utrecht Centraal", "Amsterdam Arena", "Rotterdam Zuid"], "Utrecht Centraal"),
                    ("Wat zegt de medewerker over de tijd?", ["Vertrek + vertraging", "Geen trein vandaag", "Gratis koffie"], "Vertrek + vertraging"),
                    ("Hoeveel vertraging is er?", ["Tien minuten", "Eén minuut", "Geen"], "Tien minuten"),
                    ("Van welk perron?", ["Perron zeven", "Perron twee", "Perron twintig"], "Perron zeven"),
                    ("Wat moet Alex doen?", ["Snel naar het perron", "Naar huis", "Een pizza kopen"], "Snel naar het perron"),
                ],
            ),
            discovery_step(
                "m07-l01-discovery",
                "Kernzinnen op het station",
                [
                    ("Hoe laat vertrekt de trein?", "What time does the train leave?", "tijd"),
                    ("Er is vertraging.", "There is a delay.", "vertraging"),
                    ("Van welk perron?", "From which platform?", "perron"),
                    ("Waar wilt u naartoe?", "Where do you want to go? (formal)", "bestemming"),
                ],
            ),
            pl(
                "m07-l01-pl1",
                "Practice — 6×",
                ["perron", "vertraging", "vertrekken"],
                [
                    mcq(
                        "m07-l01-a1",
                        "Natuurlijke vraag over tijd",
                        ["Hoe laat vertrekt de bus?", "Hoe laat is je schoenmaat?", "Vertrek bus hoe laat vraag."],
                        "Hoe laat vertrekt de bus?",
                    ),
                    fb("m07-l01-a2", "Er is vijf minuten ___.", ["vertraging", "kaas", "zon"], "vertraging"),
                    ro_tokens("m07-l01-r1", ["perron", "Welk", "van", "trein", "de", "Vertrekt"], "Van welk perron vertrekt de trein?"),
                    mcq(
                        "m07-l01-a3",
                        "‘Perron’ betekent hier ongeveer",
                        ["Platform / waar de trein stopt", "Een café", "Een fiets"],
                        "Platform / waar de trein stopt",
                    ),
                    mcq(
                        "m07-l01-a4",
                        "Beleefd: bestemming",
                        ["Ik wil graag een kaartje naar Den Haag.", "Ik wil graag een kaartje naar de maan.", "Kaartje ik wil nu."],
                        "Ik wil graag een kaartje naar Den Haag.",
                    ),
                    mcq(
                        "m07-l01-a5",
                        "Wat hoort bij ‘er is vertraging’?",
                        ["De trein komt later", "De trein is gratis", "Er is geen station"],
                        "De trein komt later",
                    ),
                ],
            ),
            pl(
                "m07-l01-pl2",
                "Variatie — 6×",
                ["spoor", "helpen", "snel"],
                [
                    fb("m07-l01-b1", "De trein vertrekt van ___ 5. (synoniem met perron in NL)", ["spoor", "strand", "boom"], "spoor"),
                    ro_tokens("m07-l01-r2", ["naartoe?", "u", "Waar", "wilt"], "Waar wilt u naartoe?"),
                    mcq(
                        "m07-l01-b2",
                        "Als je niet begrijpt",
                        ["Kunt u dat herhalen?", "Kunt u stoppen met praten?", "Herhaal u dat nooit."],
                        "Kunt u dat herhalen?",
                    ),
                    mcq(
                        "m07-l01-b3",
                        "Kies de beste zin op straat (informeel)",
                        ["Sorry, weet jij waar het station is?", "Sorry, weet jij waar de maan woont?", "Station waar is jij."],
                        "Sorry, weet jij waar het station is?",
                    ),
                    mcq(
                        "m07-l01-b4",
                        "‘U moet snel lopen’ betekent",
                        ["Haast je", "Ga slapen", "Koop ijs"],
                        "Haast je",
                    ),
                    mcq(
                        "m07-l01-b5",
                        "OV-chipkaart in één zin",
                        ["Ik check in met mijn OV-chipkaart.", "Ik bak een OV-chipkaart.", "OV-chipkaart is een broodje."],
                        "Ik check in met mijn OV-chipkaart.",
                    ),
                    mcq(
                        "m07-l01-b6",
                        "Wat vraag je bij vertraging?",
                        ["Hoe laat vertrekt de trein nu?", "Hoe laat is je verjaardag?", "Trein nu laat hoe."],
                        "Hoe laat vertrekt de trein nu?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m07-l01-sp1",
                "Production",
                "Hoe laat vertrekt de trein naar Utrecht?",
                ["Hoe laat vertrekt de trein naar Utrecht", "hoe laat vertrekt de trein naar utrecht"],
                "Hoe laat vertrekt de trein naar Utrecht",
            ),
            speak_step(
                "m07-l01-sp2",
                "Production",
                "Van welk perron vertrekt de trein?",
                ["Van welk perron vertrekt de trein", "van welk perron vertrekt de trein"],
                "Van welk perron vertrekt de trein",
            ),
            speak_step(
                "m07-l01-sp3",
                "Production",
                "Er is tien minuten vertraging.",
                ["Er is tien minuten vertraging", "er is tien minuten vertraging"],
                "Er is tien minuten vertraging",
            ),
            speak_step(
                "m07-l01-sp4",
                "Production",
                "Kunt u dat herhalen, alstublieft?",
                ["Kunt u dat herhalen alstublieft", "Kunt u dat herhalen, alstublieft?"],
                "Kunt u dat herhalen alstublieft",
            ),
            recap_step(
                "m07-l01-recap",
                "Recap",
                ["vertraging", "perron", "vertrekken"],
                [
                    rt_fb("Er is tien minuten ___.", ["vertraging", "pizza", "rust"], "vertraging"),
                    rt_ro(["trein?", "vertrekt", "Hoe", "laat", "de"], "Hoe laat vertrekt de trein?"),
                    rt_speak("Zeg: *Van welk perron?*", "Van welk perron?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "U moet nu snel lopen.",
                        ["Advies: haast", "Advies: ga slapen", "Advies: koop schoenen"],
                        "Advies: haast",
                    ),
                    rt_fb("Ik wil graag een ___ naar Leiden. (ticket)", ["kaartje", "huis", "ei"], "kaartje"),
                    rt_speak("Zeg: *Waar is het station?*", "Waar is het station?"),
                    rt_fb("De trein vertrekt van ___ 3. (spoor)", ["spoor", "brood", "kat"], "spoor"),
                    rt_speak("Zeg: *Kunt u mij helpen?*", "Kunt u mij helpen?"),
                ],
            ),
        ],
    }


def lesson_l02() -> dict:
    lid = "a2-m07-l02-listen-read-directions-route-questions"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Listening & reading · Directions and route questions",
        "lessonType": "input",
        "order": 1,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-directions-core", "a2.2-transport-questions"],
        "vocabTargets": ["lemma-rechtdoor", "lemma-links", "lemma-rechts", "lemma-halte", "lemma-station"],
        "canDoStatements": [
            "I can read a short direction message and match it to the right turns and landmarks.",
        ],
        "mistakeFocus": ["direction-words", "question-forms"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m07-l02-preview",
                "Warm-up — 5 woorden",
                [
                    ("rechtdoor", "rechtdoor", "straight ahead", "➡️"),
                    ("links", "links", "left", "↩️"),
                    ("rechts", "rechts", "right", "↪️"),
                    ("halte", "halte", "stop", "🚏"),
                    ("ingang", "ingang", "entrance", "🚪"),
                ],
            ),
            listen_read_step(
                "m07-l02-lr",
                "Input — app-bericht + straatgesprek",
                [
                    (
                        "Lisa (app)",
                        "Hoi! Vanaf Centraal: loop uit bij hoofduitgang, ga rechtdoor tot het kruispunt, sla dan links. De tramhalte is naast de supermarkt.",
                        "Hi! From Central: exit at the main entrance, go straight to the junction, then turn left. The tram stop is next to the supermarket.",
                    ),
                    (
                        "Jij",
                        "Dank je! Welke tram moet ik naar het museum nemen?",
                        "Thanks! Which tram should I take to the museum?",
                    ),
                    (
                        "Lisa",
                        "Tram 12 richting museumkwartier. Stap uit bij halte ‘Museumplein’.",
                        "Tram 12 towards the museum district. Get off at stop ‘Museumplein’.",
                    ),
                ],
                [
                    ("Wat is de eerste stap na de uitgang?", ["Rechtdoor lopen", "Meteen rechts", "Terug naar huis"], "Rechtdoor lopen"),
                    ("Waar sla je af?", ["Links bij het kruispunt", "Rechts bij de bakker", "Nergens"], "Links bij het kruispunt"),
                    ("Waar is de halte?", ["Naast de supermarkt", "In de supermarkt", "Onder de brug"], "Naast de supermarkt"),
                    ("Welke tram noemt Lisa?", ["Tram 12", "Tram 2", "Bus 55"], "Tram 12"),
                    ("Waar moet je uitstappen?", ["Halte Museumplein", "Halte Station", "Halte Luchthaven"], "Halte Museumplein"),
                    ("Welke vraag stuur jij in de chat?", ["Welke tram naar het museum?", "Welke pizza is lekker?", "Tram welke museum?"], "Welke tram naar het museum?"),
                ],
            ),
            discovery_step(
                "m07-l02-discovery",
                "Richting + halte",
                [
                    ("Ga rechtdoor.", "Go straight.", "rechtdoor"),
                    ("Sla linksaf / rechtsaf.", "Turn left / right.", "afslaan"),
                    ("De halte is naast …", "The stop is next to …", "halte"),
                    ("Welke tram moet ik nemen?", "Which tram should I take?", "welke"),
                ],
            ),
            pl(
                "m07-l02-pl1",
                "Practice — 6×",
                ["links", "rechts", "halte"],
                [
                    mcq(
                        "m07-l02-p1",
                        "Natuurlijke routezin",
                        ["Ga rechtdoor en sla bij de brug rechtsaf.", "Ga rechtsaf en sla bij de brug rechtdoor.", "Rechtdoor ga brug rechtsaf."],
                        "Ga rechtdoor en sla bij de brug rechtsaf.",
                    ),
                    fb("m07-l02-p2", "De bus___ is om de hoek. (stop)", ["halte", "trein", "kat"], "halte"),
                    ro_tokens("m07-l02-r1", ["tram", "ik", "Welke", "moet", "nemen?", "Ik"], "Welke tram moet ik nemen?"),
                    mcq(
                        "m07-l02-p3",
                        "Tegenover =",
                        ["Aan de andere kant van de straat", "Achter de supermarkt", "In de tram"],
                        "Aan de andere kant van de straat",
                    ),
                    mcq(
                        "m07-l02-p4",
                        "Hoe vraag je waar het station is?",
                        ["Waar is het station?", "Waar is het station pizza?", "Station waar is het vraag."],
                        "Waar is het station?",
                    ),
                    mcq(
                        "m07-l02-p5",
                        "‘Naast’ betekent",
                        ["Direct ernaast", "Ver weg", "Boven de wolken"],
                        "Direct ernaast",
                    ),
                ],
            ),
            pl(
                "m07-l02-pl2",
                "Variatie — 6×",
                ["richting", "uitstappen", "volgende"],
                [
                    mcq(
                        "m07-l02-q1",
                        "Vraag: moet ik uitstappen?",
                        ["Moet ik hier uitstappen?", "Moet ik hier slapen?", "Uitstappen ik hier moet?"],
                        "Moet ik hier uitstappen?",
                    ),
                    fb("m07-l02-q2", "Ga hier ___ en dan zie je de ingang. (straight)", ["rechtdoor", "diagonaal", "achteruit"], "rechtdoor"),
                    ro_tokens("m07-l02-r2", ["bij", "de", "volgende", "Stap", "uit", "halte."], "Stap uit bij de volgende halte."),
                    mcq(
                        "m07-l02-q3",
                        "Kies de beste hulpvraag",
                        ["Sorry, ik ben verdwaald. Waar is de metro?", "Sorry, ik ben verdwaald. Waar is de maan?", "Verdwaald ben ik metro waar."],
                        "Sorry, ik ben verdwaald. Waar is de metro?",
                    ),
                    mcq(
                        "m07-l02-q4",
                        "‘Richting centrum’ op een bord betekent ongeveer",
                        ["Naar het centrum toe", "Weg van het centrum", "Geen metro vandaag"],
                        "Naar het centrum toe",
                    ),
                    mcq(
                        "m07-l02-q5",
                        "Welke zin is het meest A2-praktisch?",
                        ["Hoe kom ik bij het station?", "Hoe kom ik bij je geheim?", "Kom ik hoe station bij?"],
                        "Hoe kom ik bij het station?",
                    ),
                    mcq(
                        "m07-l02-q6",
                        "‘Bij de volgende halte’ hoor je vaak in",
                        ["Tram of bus", "Alleen in een restaurant", "Alleen thuis"],
                        "Tram of bus",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m07-l02-sp1",
                "Production",
                "Hoe kom ik bij het station?",
                ["Hoe kom ik bij het station", "hoe kom ik bij het station"],
                "Hoe kom ik bij het station",
            ),
            speak_step(
                "m07-l02-sp2",
                "Production",
                "Welke tram moet ik naar het centrum nemen?",
                ["Welke tram moet ik naar het centrum nemen", "welke tram moet ik naar het centrum nemen"],
                "Welke tram moet ik naar het centrum nemen",
            ),
            speak_step(
                "m07-l02-sp3",
                "Production",
                "Ga rechtdoor en sla links bij de brug.",
                ["Ga rechtdoor en sla links bij de brug", "ga rechtdoor en sla links bij de brug"],
                "Ga rechtdoor en sla links bij de brug",
            ),
            speak_step(
                "m07-l02-sp4",
                "Production",
                "Moet ik hier uitstappen?",
                ["Moet ik hier uitstappen", "moet ik hier uitstappen"],
                "Moet ik hier uitstappen",
            ),
            recap_step(
                "m07-l02-recap",
                "Recap",
                ["rechtdoor", "halte", "tram"],
                [
                    rt_fb("Ga hier ___ tot het kruispunt.", ["rechtdoor", "omhoog", "achteruit"], "rechtdoor"),
                    rt_speak("Zeg: *Waar is de tramhalte?*", "Waar is de tramhalte?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Stap uit bij halte ‘Museumplein’.",
                        ["Stap uit bij die halte", "Stap in bij de bakker", "Blijf zitten voor altijd"],
                        "Stap uit bij die halte",
                    ),
                    rt_ro(["nemen?", "Welke", "bus", "moet", "ik"], "Welke bus moet ik nemen?"),
                    rt_fb("Sorry, ik ben ___. (lost)", ["verdwaald", "blij", "vol"], "verdwaald"),
                    rt_speak("Zeg: *Sla hier linksaf.*", "Sla hier linksaf."),
                ],
            ),
        ],
    }


def lesson_l03() -> dict:
    lid = "a2-m07-l03-grammar-route-questions"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Grammar & patterns · Asking questions about routes and transport",
        "lessonType": "pattern",
        "order": 2,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-transport-questions", "a2.2-moeten-kunnen-transport"],
        "vocabTargets": ["lemma-waar", "lemma-hoe", "lemma-welke", "lemma-overstappen", "lemma-herhalen"],
        "mistakeFocus": ["word-order", "question-forms"],
        "canDoStatements": ["I can form clear Waar/Hoe/Welke/Moet-questions about travel without odd word order."],
        "metadata": LM,
        "steps": [
            preview_step(
                "m07-l03-preview",
                "Warm-up — 4 woorden",
                [
                    ("waar", "waar", "where", "📍"),
                    ("hoe", "hoe", "how", "❓"),
                    ("welke", "welke", "which", "🔢"),
                    ("moet", "moeten", "must / have to", "✋"),
                ],
            ),
            grammar_card(
                "m07-l03-gc",
                "Patroon",
                "Vragen onderweg",
                "**Waar** is …? **Hoe kom** ik bij …? **Welke** tram/bus …? **Moet ik** hier overstappen/uitstappen? **Hoe laat** vertrekt …? — werkwoord vaak op plek 2 na vraagwoord.",
                [
                    ("Waar is de ingang van het station?", "Where is the station entrance?"),
                    ("Hoe kom ik bij perron 5?", "How do I get to platform 5?"),
                ],
            ),
            listening_step(
                "m07-l03-listen-mini",
                "Input — korte hulp op straat",
                [
                    (
                        "Jij",
                        "Excuseer, hoe kom ik bij de metro?",
                        "Excuse me, how do I get to the metro?",
                    ),
                    (
                        "Passant",
                        "Ga deze straat in, tweede straat rechts. De ingang is naast de bloemenwinkel.",
                        "Go into this street, second street on the right. The entrance is next to the flower shop.",
                    ),
                    (
                        "Jij",
                        "Moet ik een kaartje kopen?",
                        "Do I have to buy a ticket?",
                    ),
                    (
                        "Passant",
                        "Ja, bij de automaat of bij de balie.",
                        "Yes, at the machine or at the desk.",
                    ),
                ],
                [
                    ("Wat vraag je eerst?", ["Hoe kom ik bij de metro?", "Waar koop ik een kat?", "Metro hoe bij kom ik?"], "Hoe kom ik bij de metro?"),
                    ("Welke richting noemt de passant?", ["Tweede straat rechts", "Derde straat links", "Rechtdoor tot Parijs"], "Tweede straat rechts"),
                    ("Waar is de ingang?", ["Naast de bloemenwinkel", "In de tram", "Op het dak"], "Naast de bloemenwinkel"),
                    ("Wat vraag je over betalen?", ["Moet ik een kaartje kopen?", "Moet ik een huis kopen?", "Kaartje ik moet kopen?"], "Moet ik een kaartje kopen?"),
                    ("Waar kun je een kaartje kopen?", ["Automaat of balie", "Alleen in de trein", "Nergens"], "Automaat of balie"),
                ],
            ),
            discovery_step(
                "m07-l03-discovery",
                "Guided noticing",
                [
                    ("Hoe kom ik bij …?", "How do I get to …?", "hoe"),
                    ("Waar is …?", "Where is …?", "waar"),
                    ("Welke lijn / tram / bus?", "Which line / tram / bus?", "welke"),
                    ("Moet ik …?", "Do I have to …?", "moet"),
                ],
            ),
            pl(
                "m07-l03-pl1",
                "Practice — 6×",
                ["waar", "hoe", "welke"],
                [
                    mcq(
                        "m07-l03-a1",
                        "Juiste vraag",
                        ["Waar is het perron?", "Waar is het perron vraag is?", "Perron waar is het vraag."],
                        "Waar is het perron?",
                    ),
                    fb("m07-l03-a2", "___ kom ik bij het museum? (question word)", ["Hoe", "Wat", "Waarom"], "Hoe"),
                    ro_tokens("m07-l03-r1", ["bus", "moet", "ik", "Welke", "naar", "Schiphol?", "nemen"], "Welke bus moet ik naar Schiphol nemen?"),
                    mcq(
                        "m07-l03-a3",
                        "Welke vraag past bij ‘tweede halte’?",
                        ["Moet ik hier uitstappen?", "Moet ik hier trouwen?", "Uitstappen ik hier moet?"],
                        "Moet ik hier uitstappen?",
                    ),
                    mcq(
                        "m07-l03-a4",
                        "Kies natuurlijk Nederlands",
                        ["Hoe laat vertrekt de tram?", "Hoe laat vertrekt de tram vraag?", "Vertrek tram hoe laat."],
                        "Hoe laat vertrekt de tram?",
                    ),
                    mcq(
                        "m07-l03-a5",
                        "‘Welke’ gebruik je voor",
                        ["Kiezen tussen opties (lijn, tram, uitgang)", "Alleen kleuren", "Alleen dieren"],
                        "Kiezen tussen opties (lijn, tram, uitgang)",
                    ),
                    mcq(
                        "m07-l03-a6",
                        "Vraag om herhaling",
                        ["Kunt u dat herhalen?", "Kunt u dat vergeten?", "Herhaal u nooit dat."],
                        "Kunt u dat herhalen?",
                    ),
                ],
            ),
            pl(
                "m07-l03-pl2",
                "Variatie — 6×",
                ["overstappen", "kunnen", "ticketautomaat"],
                [
                    mcq(
                        "m07-l03-b1",
                        "Moet ik overstappen?",
                        ["Moet ik in Arnhem overstappen?", "Moet ik in Arnhem slapen?", "Overstappen ik Arnhem moet?"],
                        "Moet ik in Arnhem overstappen?",
                    ),
                    fb("m07-l03-b2", "Kun je dat ___ zeggen? (repeat)", ["herhalen", "bakken", "zwemmen"], "herhalen"),
                    ro_tokens("m07-l03-r2", ["kaartje", "bij", "de", "Ik", "koop", "automaat."], "Ik koop een kaartje bij de automaat."),
                    mcq(
                        "m07-l03-b3",
                        "Kunnen-vraag (beleefd)",
                        ["Kunt u mij helpen?", "Kunt u mij repareren als fiets?", "Help u mij kunt?"],
                        "Kunt u mij helpen?",
                    ),
                    mcq(
                        "m07-l03-b4",
                        "Fout woordorde",
                        ["Waar is het station? ✓", "Waar het station is?", "Is waar het station?"],
                        "Waar is het station? ✓",
                    ),
                    mcq(
                        "m07-l03-b5",
                        "Praktische OV-zin",
                        ["Ik check in bij de poortjes.", "Ik check in bij de pizza.", "Poortjes check ik in nooit."],
                        "Ik check in bij de poortjes.",
                    ),
                    mcq(
                        "m07-l03-b6",
                        "Vraag over bestemming bord",
                        ["Is dit de tram richting centrum?", "Is dit de tram richting maan?", "Tram dit is centrum richting?"],
                        "Is dit de tram richting centrum?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m07-l03-sp1",
                "Production",
                "Waar is de ingang van het station?",
                ["Waar is de ingang van het station", "waar is de ingang van het station"],
                "Waar is de ingang van het station",
            ),
            speak_step(
                "m07-l03-sp2",
                "Production",
                "Hoe kom ik bij perron 3?",
                ["Hoe kom ik bij perron 3", "hoe kom ik bij perron 3"],
                "Hoe kom ik bij perron 3",
            ),
            speak_step(
                "m07-l03-sp3",
                "Production",
                "Moet ik hier overstappen?",
                ["Moet ik hier overstappen", "moet ik hier overstappen"],
                "Moet ik hier overstappen",
            ),
            recap_step(
                "m07-l03-recap",
                "Recap",
                ["waar", "hoe", "moet"],
                [
                    rt_fb("___ is de ticketautomaat? (where)", ["Waar", "Wie", "Welke"], "Waar"),
                    rt_ro(["bij", "het", "kom", "Hoe", "ik", "station?"], "Hoe kom ik bij het station?"),
                    rt_speak("Zeg: *Welke bus moet ik nemen?*", "Welke bus moet ik nemen?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Bij de automaat of bij de balie.",
                        ["Waar je een kaartje koopt", "Waar je pizza bakt", "Waar je slaapt"],
                        "Waar je een kaartje koopt",
                    ),
                    rt_fb("Moet ik hier ___? (change trains)", ["overstappen", "zwemmen", "zingen"], "overstappen"),
                    rt_speak("Zeg: *Kunt u dat herhalen?*", "Kunt u dat herhalen?"),
                ],
            ),
        ],
    }


def lesson_l04() -> dict:
    lid = "a2-m07-l04-practice-directions-turns"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Controlled practice · Directions, turns, and transport chunks",
        "lessonType": "practice",
        "order": 3,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-directions-core", "a2.2-sequence-travel"],
        "vocabTargets": ["lemma-rechtdoor", "lemma-links", "lemma-rechts", "lemma-ingang", "lemma-volgende-halte"],
        "canDoStatements": ["I can reorder and fix short direction sentences and pick natural replies."],
        "mistakeFocus": ["direction-words", "particle-order"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m07-l04-preview",
                "Warm-up — 5 woorden",
                [
                    ("brug", "brug", "bridge", "🌉"),
                    ("kruispunt", "kruispunt", "junction / crossing", "✖️"),
                    ("om de hoek", "hoek", "around the corner", "↩️"),
                    ("ingang", "ingang", "entrance", "🚪"),
                    ("uitgang", "uitgang", "exit", "🚶"),
                ],
            ),
            listening_step(
                "m07-l04-listen",
                "Input — iemand wijst de weg",
                [
                    (
                        "Sara",
                        "Excuseer, waar is de dichtstbijzijnde tramhalte?",
                        "Excuse me, where's the nearest tram stop?",
                    ),
                    (
                        "Man",
                        "Ga hier rechtdoor tot het kruispunt. Sla dan links. De halte is naast de bibliotheek.",
                        "Go straight here to the junction. Then turn left. The stop is next to the library.",
                    ),
                    (
                        "Sara",
                        "Oké. Is het ver?",
                        "Okay. Is it far?",
                    ),
                    (
                        "Man",
                        "Nee hoor, twee minuten lopen.",
                        "No, just two minutes' walk.",
                    ),
                ],
                [
                    ("Wat zoekt Sara?", ["Een tramhalte", "Een restaurant", "Een hotelkamer"], "Een tramhalte"),
                    ("Wat moet je eerst doen?", ["Rechtdoor tot het kruispunt", "Meteen de tram in", "Terug naar het station"], "Rechtdoor tot het kruispunt"),
                    ("Waar sla je af na het kruispunt?", ["Links", "Rechts", "Drie keer om de kerktoren"], "Links"),
                    ("Waar is de halte?", ["Naast de bibliotheek", "Op het dak van het station", "In de trein"], "Naast de bibliotheek"),
                    ("Hoe ver is het ongeveer?", ["Twee minuten lopen", "Twee uur met de taxi", "Heel ver, neem een vliegtuig"], "Twee minuten lopen"),
                ],
            ),
            discovery_step(
                "m07-l04-discovery",
                "Brokken die je vaak hoort",
                [
                    ("Ga rechtdoor tot …", "Go straight until …", "tot"),
                    ("Sla linksaf bij …", "Turn left at …", "linksaf"),
                    ("Het is om de hoek.", "It's around the corner.", "hoek"),
                    ("Eerst …, dan …", "First …, then …", "volgorde"),
                ],
            ),
            pl(
                "m07-l04-pl1",
                "Practice — 8×",
                ["rechtdoor", "links", "rechts"],
                [
                    ro_tokens("m07-l04-r1", ["brug.", "bij", "de", "links", "Sla"], "Sla links bij de brug."),
                    mcq(
                        "m07-l04-a1",
                        "Beste route-advies",
                        ["Ga rechtdoor, dan zie je het station.", "Ga rechts, dan zie je de oceaan.", "Rechtdoor ga dan station zie."],
                        "Ga rechtdoor, dan zie je het station.",
                    ),
                    fb("m07-l04-a2", "Het museum is ___ de hoek. (around)", ["om", "in", "onder"], "om"),
                    mcq(
                        "m07-l04-a3",
                        "Welke zin klopt?",
                    ["De uitgang is aan de linkerkant.", "De uitgang is aan de linkerkant station.", "Uitgang links is aan de."],
                        "De uitgang is aan de linkerkant.",
                    ),
                    ro_tokens("m07-l04-r2", ["supermarkt.", "naast", "de", "is", "De", "halte"], "De halte is naast de supermarkt."),
                    mcq(
                        "m07-l04-a4",
                        "‘Tegenover’",
                        ["Aan de overkant", "Achter je rug", "In je tas"],
                        "Aan de overkant",
                    ),
                    mcq(
                        "m07-l04-a5",
                        "Eerst / dan",
                        ["Eerst de metro, dan vijf minuten lopen.", "Eerst de metro, dan vijf minuten slapen.", "Metro eerst dan minuten vijf."],
                        "Eerst de metro, dan vijf minuten lopen.",
                    ),
                    match_ex(
                        "m07-l04-m1",
                        "Match",
                        [("rechtdoor", "straight"), ("linksaf", "left turn"), ("rechtsaf", "right turn")],
                        {"rechtdoor": "straight", "linksaf": "left turn", "rechtsaf": "right turn"},
                    ),
                ],
            ),
            pl(
                "m07-l04-pl2",
                "Variatie — 8×",
                ["uitstappen", "volgende", "metro"],
                [
                    mcq(
                        "m07-l04-b1",
                        "Natuurlijke waarschuwing in de tram",
                        ["Let op: deuren sluiten.", "Let op: deuren zingen.", "Let op deuren nooit."],
                        "Let op: deuren sluiten.",
                    ),
                    fb("m07-l04-b2", "Bij de ___ halte stappen we uit. (next)", ["volgende", "laatste", "eerste"], "volgende"),
                    ro_tokens("m07-l04-r3", ["uit", "Stap", "bij", "Centraal.", "Station"], "Stap uit bij Centraal Station."),
                    mcq(
                        "m07-l04-b3",
                        "Welke zin is het meest nuttig?",
                        ["Waar kan ik een kaartje kopen?", "Waar kan ik een taxi voor de bus halen?", "Kaartje waar koop ik kan?"],
                        "Waar kan ik een kaartje kopen?",
                    ),
                    mcq(
                        "m07-l04-b4",
                        "Fix de zin",
                        ["Ik moet naar spoor 4.", "Ik moet naar spoor vierde huis.", "Moet ik naar spoor vier."],
                        "Ik moet naar spoor 4.",
                    ),
                    mcq(
                        "m07-l04-b5",
                        "Kies antwoord op straat",
                        ["Dank je wel voor de uitleg!", "Dank je wel voor de verwarring!", "Dank uitleg wel je."],
                        "Dank je wel voor de uitleg!",
                    ),
                    mcq(
                        "m07-l04-b6",
                        "‘In de buurt’ betekent",
                        ["Dichtbij", "Ver weg", "In een andere stad"],
                        "Dichtbij",
                    ),
                    mcq(
                        "m07-l04-b7",
                        "Metro → ingang",
                        ["Volg de borden ‘Metro’.", "Volg de borden ‘Pizza’.", "Borden metro volg nooit."],
                        "Volg de borden ‘Metro’.",
                    ),
                    mcq(
                        "m07-l04-b8",
                        "Welke zin hoort bij overstappen?",
                        ["Je stapt uit en neemt een andere trein.", "Je stapt uit en koopt brood.", "Overstappen is slapen."],
                        "Je stapt uit en neemt een andere trein.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m07-l04-sp1",
                "Production",
                "Ga rechtdoor en sla bij het kruispunt rechtsaf.",
                ["Ga rechtdoor en sla bij het kruispunt rechtsaf", "ga rechtdoor en sla bij het kruispunt rechtsaf"],
                "Ga rechtdoor en sla bij het kruispunt rechtsaf",
            ),
            speak_step(
                "m07-l04-sp2",
                "Production",
                "De halte is om de hoek, naast de bakker.",
                ["De halte is om de hoek naast de bakker", "De halte is om de hoek, naast de bakker."],
                "De halte is om de hoek naast de bakker",
            ),
            speak_step(
                "m07-l04-sp3",
                "Production",
                "Eerst neem ik de bus, dan loop ik vijf minuten.",
                ["Eerst neem ik de bus dan loop ik vijf minuten", "Eerst neem ik de bus, dan loop ik vijf minuten."],
                "Eerst neem ik de bus dan loop ik vijf minuten",
            ),
            recap_step(
                "m07-l04-recap",
                "Recap",
                ["rechtdoor", "halte", "uitstappen"],
                [
                    rt_ro(["brug.", "de", "bij", "rechts", "Sla"], "Sla rechts bij de brug."),
                    rt_fb("Bij de ___ halte. (next)", ["volgende", "oude", "rare"], "volgende"),
                    rt_speak("Zeg: *Het is om de hoek.*", "Het is om de hoek."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Ga deze straat in, tweede straat rechts.",
                        ["Stap-voor-stap route", "Bestel een pizza", "Ga naar bed"],
                        "Stap-voor-stap route",
                    ),
                    rt_fb("Ik moet naar ___ 2. (platform/track)", ["spoor", "brood", "kat"], "spoor"),
                    rt_speak("Zeg: *Stap uit bij de volgende halte.*", "Stap uit bij de volgende halte."),
                    rt_fb("___ de metro, dan loop je twee minuten. (first)", ["Eerst", "Daarna", "Misschien"], "Eerst"),
                    rt_speak("Zeg: *Waar is de uitgang?*", "Waar is de uitgang?"),
                ],
            ),
        ],
    }
