from .common import (
    LM,
    MID,
    discovery_step,
    fb,
    grammar_card,
    listen_read_step,
    listening_step,
    mcq,
    pl,
    preview_step,
    recap_step,
    ro_tokens,
    rt_fb,
    rt_listen_mcq,
    rt_ro,
    rt_speak,
    speak_step,
    writing_step,
)


def lesson_l05() -> dict:
    lid = "a2-m07-l05-speaking-ask-directions"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Speaking · Ask for directions and respond",
        "lessonType": "speaking",
        "order": 4,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-directions-core", "a2.2-transport-questions"],
        "vocabTargets": ["lemma-verdwaald", "lemma-helpen-m7", "lemma-station", "lemma-rechtdoor", "lemma-links"],
        "canDoStatements": [
            "I can ask where something is, thank someone, and confirm I understood a short direction.",
        ],
        "mistakeFocus": ["production", "direction-words"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m07-l05-preview",
                "Warm-up — 5 woorden",
                [
                    ("helpen", "helpen", "to help", "🤝"),
                    ("verdwaald", "verdwaald", "lost", "🧭"),
                    ("dichtbij", "dichtbij", "nearby", "📍"),
                    ("ver", "ver", "far", "🛣️"),
                    ("begrijpen", "begrijpen", "to understand", "💡"),
                ],
            ),
            listening_step(
                "m07-l05-model",
                "Model — vraag + antwoord",
                [
                    (
                        "Noor",
                        "Excuseer, ik ben een beetje verdwaald. Waar is het station?",
                        "Excuse me, I'm a bit lost. Where is the station?",
                    ),
                    (
                        "Man",
                        "Het station? Ga hier rechtdoor, bij het stoplicht links. Het is ongeveer vijf minuten.",
                        "The station? Go straight here, left at the lights. It's about five minutes.",
                    ),
                    (
                        "Noor",
                        "Oké, dank u wel. Moet ik een brug oversteken?",
                        "Okay, thank you. Do I have to cross a bridge?",
                    ),
                    (
                        "Man",
                        "Ja, een kleine brug. Daarna ziet u het bord ‘Station’.",
                        "Yes, a small bridge. After that you'll see the ‘Station’ sign.",
                    ),
                ],
                [
                    ("Wat vraagt Noor eerst?", ["Waar is het station?", "Waar is de brug?", "Waar is de pizza?"], "Waar is het station?"),
                    ("Welke richting na het stoplicht?", ["Links", "Rechts", "Omhoog"], "Links"),
                    ("Hoe lang ongeveer?", ["Vijf minuten", "Vijf uur", "Vijf weken"], "Vijf minuten"),
                    ("Wat vraagt Noor daarna?", ["Over de brug?", "Over de maan?", "Brug moet ik?"], "Over de brug?"),
                    ("Wat zegt de man over het bord?", ["Je ziet ‘Station’", "Je ziet ‘Pizza’", "Geen borden"], "Je ziet ‘Station’"),
                ],
            ),
            discovery_step(
                "m07-l05-discovery",
                "Handige set: vragen + bevestigen",
                [
                    ("Ik ben verdwaald.", "I'm lost.", "hulp"),
                    ("Waar is …?", "Where is …?", "plek"),
                    ("Kunt u dat herhalen?", "Could you repeat that?", "herhaling"),
                    ("Dank u wel / Dank je wel.", "Thank you.", "dank"),
                ],
            ),
            pl(
                "m07-l05-pl1",
                "Variatie — 6×",
                ["verdwaald", "station", "brug"],
                [
                    mcq(
                        "m07-l05-a1",
                        "Beste openingszin",
                        ["Sorry, ik ben verdwaald. Waar is de metro?", "Sorry, ik ben verdwaald. Waar is de zon?", "Verdwaald ben ik metro waar."],
                        "Sorry, ik ben verdwaald. Waar is de metro?",
                    ),
                    fb("m07-l05-a2", "Het is niet ver, ___ vijf minuten. (only)", ["maar", "want", "omdat"], "maar"),
                    ro_tokens("m07-l05-r1", ["wel", "Dank", "u", "."], "Dank u wel."),
                    mcq(
                        "m07-l05-a3",
                        "Als je het niet snapt",
                        ["Ik begrijp het niet helemaal.", "Ik begrijp het nooit met taart.", "Begrijp ik niet het."],
                        "Ik begrijp het niet helemaal.",
                    ),
                    mcq(
                        "m07-l05-a4",
                        "Bevestigen: goed verstaan?",
                        ["Dus eerst rechtdoor en dan links?", "Dus eerst pizza en dan slapen?", "Dus rechtdoor eerst links dan?"],
                        "Dus eerst rechtdoor en dan links?",
                    ),
                    mcq(
                        "m07-l05-a5",
                        "Afsluiten beleefd",
                        ["Fijne dag nog!", "Fijne trein zonder station!", "Dag fijne nog nooit."],
                        "Fijne dag nog!",
                    ),
                    mcq(
                        "m07-l05-a6",
                        "‘In de buurt’ vraag",
                        ["Is er een halte in de buurt?", "Is er een halte in de oceaan?", "Halte buurt in de is er?"],
                        "Is er een halte in de buurt?",
                    ),
                ],
                depth=True,
            ),
            pl(
                "m07-l05-pl2",
                "Follow-up — 6×",
                ["uitgang", "ingang", "ticketautomaat"],
                [
                    mcq(
                        "m07-l05-b1",
                        "Waar is de ingang vs uitgang",
                        ["De uitgang is aan de andere kant.", "De uitgang is een broodje.", "Uitgang is kant andere aan."],
                        "De uitgang is aan de andere kant.",
                    ),
                    fb("m07-l05-b2", "Waar is de ___ van het station? (way in)", ["ingang", "uitgang", "tram"], "ingang"),
                    ro_tokens("m07-l05-r2", ["herhalen?", "dat", "Kun", "je", "even"], "Kun je dat even herhalen?"),
                    mcq(
                        "m07-l05-b3",
                        "Praktische check",
                        ["Moet ik hier overstappen?", "Moet ik hier trouwen?", "Overstappen moet hier ik?"],
                        "Moet ik hier overstappen?",
                    ),
                    mcq(
                        "m07-l05-b4",
                        "Reactie op hulp",
                        ["Super, dank je wel!", "Super, ik eet je schoenen!", "Dank super je wel nooit."],
                        "Super, dank je wel!",
                    ),
                    mcq(
                        "m07-l05-b5",
                        "Vraag om langzamer",
                        ["Kunt u wat langzamer praten?", "Kunt u wat harder slapen?", "Langzamer u praten kunt?"],
                        "Kunt u wat langzamer praten?",
                    ),
                    mcq(
                        "m07-l05-b6",
                        "Na uitleg: wat zeg je?",
                        ["Oké, ik ga deze kant op.", "Oké, ik ga naar de maan.", "Oké ga ik kant deze op nooit."],
                        "Oké, ik ga deze kant op.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m07-l05-sp1",
                "Jouw beurt — vraag",
                "Excuseer, waar is het station?",
                ["Excuseer waar is het station", "Excuseer, waar is het station?"],
                "Excuseer waar is het station",
            ),
            speak_step(
                "m07-l05-sp2",
                "Jouw beurt — verdwaald",
                "Sorry, ik ben verdwaald. Kunt u mij helpen?",
                ["Sorry ik ben verdwaald kunt u mij helpen", "Sorry, ik ben verdwaald. Kunt u mij helpen?"],
                "Sorry ik ben verdwaald kunt u mij helpen",
            ),
            speak_step(
                "m07-l05-sp3",
                "Bevestigen",
                "Dus eerst rechtdoor en dan bij het stoplicht links?",
                ["Dus eerst rechtdoor en dan bij het stoplicht links", "dus eerst rechtdoor en dan bij het stoplicht links"],
                "Dus eerst rechtdoor en dan bij het stoplicht links",
            ),
            speak_step(
                "m07-l05-sp4",
                "Afsluiten",
                "Dank u wel voor uw hulp. Fijne dag!",
                ["Dank u wel voor uw hulp fijne dag", "Dank u wel voor uw hulp. Fijne dag!"],
                "Dank u wel voor uw hulp fijne dag",
            ),
            speak_step(
                "m07-l05-sp5",
                "Herhaling",
                "Kunt u dat nog een keer zeggen, alstublieft?",
                ["Kunt u dat nog een keer zeggen alstublieft", "Kunt u dat nog een keer zeggen, alstublieft?"],
                "Kunt u dat nog een keer zeggen alstublieft",
            ),
            recap_step(
                "m07-l05-recap",
                "Recap",
                ["verdwaald", "helpen", "rechtdoor"],
                [
                    rt_speak("Zeg: *Waar is de tramhalte?*", "Waar is de tramhalte?"),
                    rt_fb("Ik ben ___. (lost)", ["verdwaald", "klaar", "vol"], "verdwaald"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Het is ongeveer vijf minuten.",
                        ["Afstand / tijd", "Prijs van brood", "Trein is weg"],
                        "Afstand / tijd",
                    ),
                    rt_ro(["links", "bij", "het", "stoplicht", "Sla"], "Sla links bij het stoplicht."),
                    rt_speak("Zeg: *Kunt u dat herhalen?*", "Kunt u dat herhalen?"),
                    rt_fb("___ u wel! (thanks formal)", ["Dank", "Eet", "Loop"], "Dank"),
                    rt_speak("Zeg: *Moet ik hier uitstappen?*", "Moet ik hier uitstappen?"),
                ],
            ),
        ],
    }


def lesson_l06() -> dict:
    lid = "a2-m07-l06-listening-delays-announcements"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Listening · Delays, platforms, and announcements",
        "lessonType": "input",
        "order": 5,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-announcements-chunks", "a2.2-separable-transport"],
        "vocabTargets": ["lemma-vertraging", "lemma-spoor", "lemma-eindbestemming", "lemma-volgende-halte", "lemma-omleiding"],
        "canDoStatements": [
            "I can catch key info from short delay and platform-style lines in Dutch.",
        ],
        "mistakeFocus": ["listening-detail", "announcement-chunks"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m07-l06-preview",
                "Warm-up — 5 woorden",
                [
                    ("omleiding", "omleiding", "diversion", "↪️"),
                    ("eindbestemming", "eindbestemming", "final destination", "🏁"),
                    ("volgende halte", "halte", "next stop", "🚏"),
                    ("storing", "storing", "disruption / fault", "⚠️"),
                    ("in-/uitstappen", "instappen", "get on/off", "🚪"),
                ],
            ),
            listening_step(
                "m07-l06-listen-a",
                "Input — perron (twee stemmen)",
                [
                    (
                        "Omroeper",
                        "Aandacht alstublieft. De intercity naar Rotterdam heeft tien minuten vertraging. U vertrekt van spoor 8.",
                        "Attention please. The intercity to Rotterdam is ten minutes late. It departs from track 8.",
                    ),
                    (
                        "Reiziger A",
                        "Moet ik nu naar spoor 8?",
                        "Do I have to go to track 8 now?",
                    ),
                    (
                        "Reiziger B",
                        "Ja, en je moet wel opschieten. De lift is kapot, neem de trap.",
                        "Yes, and you should hurry. The lift is broken, take the stairs.",
                    ),
                ],
                [
                    ("Waar gaat de trein naartoe?", ["Rotterdam", "Groningen", "Maastricht"], "Rotterdam"),
                    ("Hoeveel vertraging?", ["Tien minuten", "Twee uur", "Geen"], "Tien minuten"),
                    ("Van welk spoor?", ["Spoor 8", "Spoor 1", "Spoor 99"], "Spoor 8"),
                    ("Wat is er met de lift?", ["Kapot", "Nieuw", "Gratis"], "Kapot"),
                    ("Wat adviseert reiziger B?", ["Trap nemen en opschieten", "Koffie drinken", "Wachten tot morgen"], "Trap nemen en opschieten"),
                ],
            ),
            listening_step(
                "m07-l06-listen-b",
                "Input — tram (kort)",
                [
                    (
                        "Bestuurder",
                        "Goedemiddag. Door een omleiding stopt deze tram niet bij halte ‘Park’. Stap uit bij halte ‘Museum’ en loop drie minuten terug.",
                        "Good afternoon. Due to a diversion this tram does not stop at ‘Park’. Get off at ‘Museum’ and walk back three minutes.",
                    ),
                    (
                        "Passagier",
                        "Oh nee. Moet ik extra betalen?",
                        "Oh no. Do I have to pay extra?",
                    ),
                    (
                        "Bestuurder",
                        "Nee, uw kaartje blijft geldig.",
                        "No, your ticket remains valid.",
                    ),
                ],
                [
                    ("Waarom andere halte?", ["Omleiding", "Feest", "Sneeuw op TV"], "Omleiding"),
                    ("Waar moet je uitstappen?", ["Halte Museum", "Halte Luchthaven", "Halte Maan"], "Halte Museum"),
                    ("Hoe lang lopen?", ["Drie minuten terug", "Drie uur", "Niet lopen"], "Drie minuten terug"),
                    ("Moet passagier extra betalen?", ["Nee", "Ja, altijd", "Alleen met kaas"], "Nee"),
                ],
            ),
            discovery_step(
                "m07-l06-discovery",
                "Chunks uit omroepen",
                [
                    ("… heeft … minuten vertraging.", "… is … minutes late.", "vertraging"),
                    ("U vertrekt van spoor …", "It departs from track …", "spoor"),
                    ("Volgende halte: …", "Next stop: …", "halte"),
                    ("Door een omleiding …", "Due to a diversion …", "omleiding"),
                ],
            ),
            pl(
                "m07-l06-pl1",
                "Practice — 6×",
                ["vertraging", "spoor", "uitstappen"],
                [
                    mcq(
                        "m07-l06-a1",
                        "Welke zin hoort bij vertraging?",
                        ["De trein heeft vijf minuten vertraging.", "De trein heeft vijf minuten pizza.", "Vijf minuten trein heeft vertraging de."],
                        "De trein heeft vijf minuten vertraging.",
                    ),
                    fb("m07-l06-a2", "De eindbestemming is ___. (The Hague)", ["Den Haag", "Den Bosch", "Den Helder"], "Den Haag"),
                    ro_tokens("m07-l06-r1", ["8.", "spoor", "van", "Vertrekt", "De", "trein"], "De trein vertrekt van spoor 8."),
                    mcq(
                        "m07-l06-a3",
                        "‘Storing’ in OV-context",
                        ["Er is een storing: de metro rijdt niet.", "Er is een storing: de metro is een taart.", "Storing is metro nooit."],
                        "Er is een storing: de metro rijdt niet.",
                    ),
                    mcq(
                        "m07-l06-a4",
                        "Uitstappen",
                        ["U moet hier uitstappen.", "U moet hier slapen.", "Uitstappen moet u hier nooit."],
                        "U moet hier uitstappen.",
                    ),
                    mcq(
                        "m07-l06-a5",
                        "Juiste vraag bij twijfel",
                        ["Is dit de juiste tram richting centrum?", "Is dit de juiste pizza richting centrum?", "Tram dit juiste is centrum?"],
                        "Is dit de juiste tram richting centrum?",
                    ),
                ],
            ),
            pl(
                "m07-l06-pl2",
                "Variatie — 6×",
                ["volgende", "instappen", "poortjes"],
                [
                    mcq(
                        "m07-l06-b1",
                        "Veiligheidssnuisterij (realistisch)",
                        ["Let op de afstand tussen trein en perron.", "Let op de afstand tussen trein en pizza.", "Let op perron trein nooit."],
                        "Let op de afstand tussen trein en perron.",
                    ),
                    fb("m07-l06-b2", "___ halte: Centraal Station. (next)", ["Volgende", "Laatste", "Eerste"], "Volgende"),
                    ro_tokens("m07-l06-r2", ["geldig.", "blijft", "Uw", "kaartje"], "Uw kaartje blijft geldig."),
                    mcq(
                        "m07-l06-b3",
                        "Wat betekent ‘eindbestemming’ ongeveer?",
                        ["Waar de trein/tram uiteindelijk naartoe gaat", "Waar je brood koopt", "Eerste halte"],
                        "Waar de trein/tram uiteindelijk naartoe gaat",
                    ),
                    mcq(
                        "m07-l06-b4",
                        "Instappen",
                        ["Stap in via de openstaande deuren.", "Stap in via het plafond.", "Instap via deuren openstaande."],
                        "Stap in via de openstaande deuren.",
                    ),
                    mcq(
                        "m07-l06-b5",
                        "Check-in",
                        ["Vergeet niet in te checken bij de poortjes.", "Vergeet niet te zwemmen bij de poortjes.", "Check in vergeet poortjes."],
                        "Vergeet niet in te checken bij de poortjes.",
                    ),
                    mcq(
                        "m07-l06-b6",
                        "Synoniem in gesprek: perron",
                        ["Vaak hetzelfde idee als ‘spoor’ op stations", "Altijd een café", "Een soort brood"],
                        "Vaak hetzelfde idee als ‘spoor’ op stations",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m07-l06-sp1",
                "Production",
                "De trein heeft tien minuten vertraging.",
                ["De trein heeft tien minuten vertraging", "de trein heeft tien minuten vertraging"],
                "De trein heeft tien minuten vertraging",
            ),
            speak_step(
                "m07-l06-sp2",
                "Production",
                "Van welk spoor vertrekt de trein?",
                ["Van welk spoor vertrekt de trein", "van welk spoor vertrekt de trein"],
                "Van welk spoor vertrekt de trein",
            ),
            speak_step(
                "m07-l06-sp3",
                "Production",
                "Stap uit bij de volgende halte.",
                ["Stap uit bij de volgende halte", "stap uit bij de volgende halte"],
                "Stap uit bij de volgende halte",
            ),
            speak_step(
                "m07-l06-sp4",
                "Production",
                "Is er vandaag een omleiding?",
                ["Is er vandaag een omleiding", "is er vandaag een omleiding"],
                "Is er vandaag een omleiding",
            ),
            recap_step(
                "m07-l06-recap",
                "Recap",
                ["vertraging", "spoor", "halte"],
                [
                    rt_fb("De trein heeft vijf minuten ___.", ["vertraging", "kaas", "rust"], "vertraging"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Uw kaartje blijft geldig.",
                        ["Je hoeft niet extra te betalen", "Je moet dubbel betalen", "Kaartje is ongeldig"],
                        "Je hoeft niet extra te betalen",
                    ),
                    rt_ro(["halte:", "volgende", "De", "is", "Leidseplein."], "De volgende halte is Leidseplein."),
                    rt_speak("Zeg: *Moet ik hier uitstappen?*", "Moet ik hier uitstappen?"),
                    rt_fb("Door een ___ rijdt de bus een andere route. (detour)", ["omleiding", "pizza", "film"], "omleiding"),
                    rt_speak("Zeg: *Van welk spoor vertrekt de trein?*", "Van welk spoor vertrekt de trein?"),
                ],
            ),
        ],
    }


def lesson_l07() -> dict:
    lid = "a2-m07-l07-grammar-moeten-kunnen-transport"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Grammar & patterns · Must / can + transport verbs in context",
        "lessonType": "pattern",
        "order": 6,
        "cefrLevel": "A2",
        "durationEstimate": 14,
        "grammarTargets": ["a2.2-moeten-kunnen-transport", "a2.2-separable-transport"],
        "vocabTargets": ["lemma-overstappen", "lemma-uitstappen", "lemma-instappen", "lemma-herhalen", "lemma-ov-chipkaart"],
        "canDoStatements": ["I can use moeten/kunnen naturally with uitstappen, overstappen, and asking for repetition."],
        "mistakeFocus": ["modal-use", "separable-verbs"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m07-l07-preview",
                "Warm-up — 4 woorden",
                [
                    ("moeten", "moeten", "must / have to", "📌"),
                    ("kunnen", "kunnen", "can / be able", "✅"),
                    ("uitstappen", "uitstappen", "get off", "🚪"),
                    ("overstappen", "overstappen", "change (vehicles)", "🔁"),
                ],
            ),
            grammar_card(
                "m07-l07-gc",
                "Patroon",
                "Moeten / kunnen + reizen",
                "**Moet ik** hier **uitstappen**? **Kunt u** dat **herhalen**? **We moeten** in Utrecht **overstappen**. — bij scheidbare werkwoorden: **uit**/**over**/**in** vaak aan het eind in een normale zin.",
                [
                    ("Moet ik bij Station Zuid uitstappen?", "Do I have to get off at Station Zuid?"),
                    ("Kun je langzamer praten, alsjeblieft?", "Can you speak more slowly, please?"),
                ],
            ),
            listening_step(
                "m07-l07-listen",
                "Input — in de tram",
                [
                    (
                        "Passagier",
                        "Excuseer, moet ik bij de volgende halte uitstappen voor het museum?",
                        "Excuse me, do I have to get off at the next stop for the museum?",
                    ),
                    (
                        "Conducteur",
                        "Nee, u moet nog twee haltes blijven zitten. Dan stapt u uit bij ‘Museumplein’.",
                        "No, you have to stay seated for two more stops. Then you get off at ‘Museumplein’.",
                    ),
                    (
                        "Passagier",
                        "Oké. Kan ik daar overstappen op bus 48?",
                        "Okay. Can I change there to bus 48?",
                    ),
                    (
                        "Conducteur",
                        "Ja, dat kan. De bushalte is naast de tramhalte.",
                        "Yes, you can. The bus stop is next to the tram stop.",
                    ),
                ],
                [
                    (
                        "Wat vraagt de passagier eerst?",
                        [
                            "Moet ik bij de volgende halte uitstappen voor het museum?",
                            "Moet ik hier slapen?",
                            "Museum halte volgende ik moet?",
                        ],
                        "Moet ik bij de volgende halte uitstappen voor het museum?",
                    ),
                    ("Wat zegt de conducteur?", ["Nog twee haltes wachten", "Nu meteen uit", "Ga naar huis"], "Nog twee haltes wachten"),
                    ("Waar uitstappen?", ["Museumplein", "Centraal", "Schiphol"], "Museumplein"),
                    ("Wat wil de passagier daarna?", ["Overstappen op bus 48", "Een pizza kopen", "Zwemmen"], "Overstappen op bus 48"),
                    ("Waar is de bushalte?", ["Naast de tramhalte", "In de tram", "Onder water"], "Naast de tramhalte"),
                ],
            ),
            discovery_step(
                "m07-l07-discovery",
                "Let op het einde van de zin",
                [
                    ("… uitstappen.", "… get off.", "uit"),
                    ("… overstappen.", "… change.", "over"),
                    ("… instappen.", "… get on.", "in"),
                    ("Kunt u … herhalen?", "Could you repeat …?", "herhalen"),
                ],
            ),
            pl(
                "m07-l07-pl1",
                "Practice — 6×",
                ["moeten", "kunnen", "uitstappen"],
                [
                    mcq(
                        "m07-l07-a1",
                        "Juiste vraag",
                        ["Moet ik hier uitstappen?", "Moet ik hier uitstappen vraag?", "Uitstappen moet ik hier vraag?"],
                        "Moet ik hier uitstappen?",
                    ),
                    fb("m07-l07-a2", "We moeten in Arnhem ___ op de trein naar Berlin. (change)", ["overstappen", "zwemmen", "zingen"], "overstappen"),
                    ro_tokens("m07-l07-r1", ["herhalen?", "dat", "Kunt", "u"], "Kunt u dat herhalen?"),
                    mcq(
                        "m07-l07-a3",
                        "Kunnen: beleefd",
                        ["Kunt u mij helpen?", "Kunt u mij repareren als fiets?", "Help u mij kunt?"],
                        "Kunt u mij helpen?",
                    ),
                    mcq(
                        "m07-l07-a4",
                        "Instappen",
                        ["U kunt hier instappen.", "U kunt hier slapen.", "Instappen kunt u hier nooit."],
                        "U kunt hier instappen.",
                    ),
                    mcq(
                        "m07-l07-a5",
                        "Moeten + infinitief aan het eind",
                        ["Ik moet nu snel lopen.", "Ik moet nu snel lopen station.", "Moet ik nu snel lopen moet."],
                        "Ik moet nu snel lopen.",
                    ),
                    mcq(
                        "m07-l07-a6",
                        "Praktisch",
                        ["Vergeet niet uit te checken.", "Vergeet niet uit te eten bij de poortjes.", "Check uit vergeet nooit."],
                        "Vergeet niet uit te checken.",
                    ),
                ],
            ),
            pl(
                "m07-l07-pl2",
                "Variatie — 6×",
                ["inchecken", "poortjes", "geldig"],
                [
                    mcq(
                        "m07-l07-b1",
                        "OV-chipkaart",
                        ["Mijn OV-chipkaart is niet geldig.", "Mijn OV-chipkaart is een broodje.", "OV-chipkaart geldig is nooit."],
                        "Mijn OV-chipkaart is niet geldig.",
                    ),
                    fb("m07-l07-b2", "Je moet eerst ___ voordat je reist. (in-check)", ["inchecken", "uitchecken", "ontbijten"], "inchecken"),
                    ro_tokens("m07-l07-r2", ["bij", "de", "poortjes.", "Check", "in"], "Check in bij de poortjes."),
                    mcq(
                        "m07-l07-b3",
                        "Kan / mag (simpel verschil in context)",
                        ["Hier mag je niet roken.", "Hier mag je niet ademen.", "Roken mag je hier altijd."],
                        "Hier mag je niet roken.",
                    ),
                    mcq(
                        "m07-l07-b4",
                        "Moeten in advies",
                        ["Je moet nu rennen, anders mis je de trein.", "Je moet nu slapen, anders mis je de trein.", "Je moet nu rennen anders trein mis je nooit."],
                        "Je moet nu rennen, anders mis je de trein.",
                    ),
                    mcq(
                        "m07-l07-b5",
                        "Kunnen + niet",
                        ["Ik kan de omroep niet goed verstaan.", "Ik kan de omroep niet goed bakken.", "Kan ik omroep verstaan niet."],
                        "Ik kan de omroep niet goed verstaan.",
                    ),
                    mcq(
                        "m07-l07-b6",
                        "Separable in imperatief-stijl",
                        ["Stap hier uit.", "Stap hier in de soep.", "Uitstap hier."],
                        "Stap hier uit.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m07-l07-sp1",
                "Production",
                "Moet ik bij de volgende halte uitstappen?",
                ["Moet ik bij de volgende halte uitstappen", "moet ik bij de volgende halte uitstappen"],
                "Moet ik bij de volgende halte uitstappen",
            ),
            speak_step(
                "m07-l07-sp2",
                "Production",
                "We moeten in Utrecht overstappen.",
                ["We moeten in Utrecht overstappen", "we moeten in utrecht overstappen"],
                "We moeten in Utrecht overstappen",
            ),
            speak_step(
                "m07-l07-sp3",
                "Production",
                "Kunt u dat langzamer herhalen?",
                ["Kunt u dat langzamer herhalen", "kunt u dat langzamer herhalen"],
                "Kunt u dat langzamer herhalen",
            ),
            recap_step(
                "m07-l07-recap",
                "Recap",
                ["moeten", "uitstappen", "overstappen"],
                [
                    rt_fb("___ ik hier uitstappen? (do I have to)", ["Moet", "Wil", "Kan"], "Moet"),
                    rt_ro(["48.", "op", "bus", "overstappen", "Ik", "kan", "daar"], "Ik kan daar overstappen op bus 48."),
                    rt_speak("Zeg: *Vergeet niet uit te checken.*", "Vergeet niet uit te checken."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Dan stapt u uit bij ‘Museumplein’.",
                        ["Waar je uitstapt", "Waar je instapt", "Waar je pizza koopt"],
                        "Waar je uitstapt",
                    ),
                    rt_fb("Check ___ bij de poortjes. (in)", ["in", "uit", "op"], "in"),
                    rt_speak("Zeg: *U kunt hier instappen.*", "U kunt hier instappen."),
                ],
            ),
        ],
    }


def lesson_l08() -> dict:
    lid = "a2-m07-l08-writing-travel-messages"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Writing · Short travel messages and route updates",
        "lessonType": "writing",
        "order": 7,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.2-sequence-travel", "a2.2-transport-questions"],
        "vocabTargets": ["lemma-vertraging", "lemma-trein", "lemma-tram", "lemma-aankomen", "lemma-vertrekken"],
        "canDoStatements": ["I can send a short Dutch message about being late, my route, or where to meet."],
        "mistakeFocus": ["word-order", "practical-phrases"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m07-l08-preview",
                "Warm-up — 4 woorden",
                [
                    ("te laat", "laat", "too late / late", "⏰"),
                    ("onderweg", "onderweg", "on the way", "🚶"),
                    ("aankomen", "aankomen", "to arrive", "📍"),
                    ("trein", "trein", "train", "🚆"),
                ],
            ),
            listen_read_step(
                "m07-l08-lr",
                "Model — twee appjes",
                [
                    (
                        "Sam",
                        "Hoi! Ik ben onderweg. De trein heeft 8 minuten vertraging. Ik kom rond 17:10 aan op Centraal. Zullen we afspreken bij ingang hoofdgebouw?",
                        "Hi! I'm on the way. The train is 8 minutes late. I'll arrive around 17:10 at Central. Shall we meet at the main building entrance?",
                    ),
                    (
                        "Kim",
                        "Oké, geen probleem. Ik wacht bij de grote klok. Neem de uitgang ‘Stationsplein’.",
                        "Okay, no problem. I'll wait by the big clock. Take the ‘Stationsplein’ exit.",
                    ),
                ],
                [
                    ("Waarom is Sam later?", ["Treinvertraging", "Hij vergeet de tijd", "Hij is in Frankrijk"], "Treinvertraging"),
                    ("Hoe laat komt Sam ongeveer?", ["Rond 17:10", "Rond 07:10", "Rond 23:10"], "Rond 17:10"),
                    ("Waar wil Sam afspreken?", ["Bij ingang hoofdgebouw", "Bij het verkeerde perron", "In de trein zonder uitgang"], "Bij ingang hoofdgebouw"),
                    ("Waar wacht Kim?", ["Bij de grote klok", "Bij de OV-fietsstalling", "Bij de taxistandplaats"], "Bij de grote klok"),
                    ("Welke uitgang noemt Kim?", ["Stationsplein", "Museumplein", "Leidseplein"], "Stationsplein"),
                ],
            ),
            discovery_step(
                "m07-l08-discovery",
                "Handige app-zinnen",
                [
                    ("Ik ben onderweg.", "I'm on my way.", "status"),
                    ("Ik heb vertraging.", "I'm delayed.", "probleem"),
                    ("Ik kom … aan.", "I'll arrive …", "aankomen"),
                    ("Zullen we afspreken bij …?", "Shall we meet at …?", "afspraak"),
                ],
            ),
            grammar_card(
                "m07-l08-gc",
                "Mini-patroon",
                "Kort reisbericht (app)",
                "**1)** Waar ben je? (*Ik ben onderweg.*) **2)** Wat is er aan de hand? (*vertraging / overstappen*) **3)** Wanneer + waar afspreken? (*Ik kom … aan … Zullen we … bij …?*) — 2–4 zinnen is genoeg.",
                [
                    ("Sorry, ik heb 10 minuten vertraging. Ik kom rond 18:15 aan.", "Sorry, I'm 10 minutes late. I'll arrive around 18:15."),
                    ("Laten we afspreken bij de ingang naast spoor 4.", "Let's meet at the entrance next to platform 4."),
                ],
            ),
            listening_step(
                "m07-l08-listen-vn",
                "Input — spraakbericht (alleen luisteren eerst)",
                [
                    (
                        "Tim",
                        "Hoi, ik zit in de trein naar Utrecht.",
                        "Hi, I'm on the train to Utrecht.",
                    ),
                    (
                        "Tim",
                        "Er is een kwartier vertraging door een sein storing.",
                        "There's a quarter of an hour delay because of a signal fault.",
                    ),
                    (
                        "Tim",
                        "Ik kom ongeveer om zes uur tien aan op Centraal.",
                        "I'll arrive at Central at about ten past six.",
                    ),
                    (
                        "Tim",
                        "Laten we afspreken bij de koffiehoek naast spoor zes, oké?",
                        "Let's meet at the coffee corner next to platform six, okay?",
                    ),
                ],
                [
                    ("Waar is Tim?", ["In de trein naar Utrecht", "In de bus naar Utrecht", "Al thuis"], "In de trein naar Utrecht"),
                    ("Waarom is hij later?", ["Vertraging door een sein storing", "Hij vergeet de tijd", "De trein rijdt te snel"], "Vertraging door een sein storing"),
                    ("Hoe laat komt hij ongeveer aan?", ["Rond 6:10 op Centraal", "Rond 9:00 ’s ochtends", "Morgen pas"], "Rond 6:10 op Centraal"),
                    ("Waar wil hij afspreken?", ["Bij de koffiehoek naast spoor 6", "Bij spoor 16 zonder café", "Buiten het station"], "Bij de koffiehoek naast spoor 6"),
                ],
            ),
            pl(
                "m07-l08-pl1",
                "Practice — 6×",
                ["vertraging", "aankomen", "afspreken"],
                [
                    mcq(
                        "m07-l08-a1",
                        "Natuurlijk bericht",
                        ["Sorry, ik ben een beetje te laat door de tram.", "Sorry, ik ben een beetje te laat door de maan.", "Laat sorry tram door ben ik."],
                        "Sorry, ik ben een beetje te laat door de tram.",
                    ),
                    fb("m07-l08-a2", "Ik ___ rond half zes aan. (arrive: ik)", ["kom", "eet", "slaap"], "kom"),
                    ro_tokens("m07-l08-r1", ["vertraging.", "minuten", "vijf", "De", "bus", "heeft"], "De bus heeft vijf minuten vertraging."),
                    mcq(
                        "m07-l08-a3",
                        "Afspraakplek",
                        ["Laten we afspreken bij de ingang.", "Laten we afspreken bij het verkeerde perron.", "Afspraak laten we ingang nooit."],
                        "Laten we afspreken bij de ingang.",
                    ),
                    mcq(
                        "m07-l08-a4",
                        "Kort en duidelijk",
                        ["Ik neem tram 5 en stuur je een bericht als ik er bijna ben.", "Ik neem tram 5 en bel je pas morgen.", "Tram 5 neem ik bericht stuur."],
                        "Ik neem tram 5 en stuur je een bericht als ik er bijna ben.",
                    ),
                    mcq(
                        "m07-l08-a5",
                        "‘Ik moet overstappen’ in een update",
                        ["Ik moet in Hilversum overstappen, dus ik ben later.", "Ik moet in Hilversum slapen, dus ik ben later.", "Overstappen moet ik Hilversum."],
                        "Ik moet in Hilversum overstappen, dus ik ben later.",
                    ),
                ],
            ),
            pl(
                "m07-l08-pl2",
                "Variatie — 6×",
                ["uitgang", "wachten", "onderweg"],
                [
                    mcq(
                        "m07-l08-b1",
                        "Beleefd uitstellen",
                        ["Sorry voor de vertraging!", "Sorry voor de pizza!", "Vertraging sorry voor nooit."],
                        "Sorry voor de vertraging!",
                    ),
                    fb("m07-l08-b2", "Ik ___ bij de klok. (wait: ik)", ["wacht", "ren", "zwem"], "wacht"),
                    ro_tokens("m07-l08-r2", ["uitgang", "Neem", "de", "‘Zuid’.",], "Neem de uitgang ‘Zuid’."),
                    mcq(
                        "m07-l08-b3",
                        "Praktische route-update",
                        ["Eerst metro, dan 2 minuten lopen.", "Eerst metro, dan 2 uur slapen.", "Metro eerst minuten twee."],
                        "Eerst metro, dan 2 minuten lopen.",
                    ),
                    mcq(
                        "m07-l08-b4",
                        "Waar treffen?",
                        ["Zien we elkaar bij perron 3?", "Zien we elkaar bij perron pizza?", "Elkaar zien perron 3?"],
                        "Zien we elkaar bij perron 3?",
                    ),
                    mcq(
                        "m07-l08-b5",
                        "Ik ben er zo",
                        ["Ik ben er over vijf minuten.", "Ik ben er over vijf jaar.", "Ben ik er minuten vijf."],
                        "Ik ben er over vijf minuten.",
                    ),
                    mcq(
                        "m07-l08-b6",
                        "Check verstaan",
                        ["Begrijp je mijn bericht?", "Begrijp je deze route zonder kaart?", "Bericht mijn begrijp je?"],
                        "Begrijp je mijn bericht?",
                    ),
                    fb(
                        "m07-l08-b7",
                        "Ik ___ je een bericht als ik bijna ben. (send: ik)",
                        ["stuur", "eet", "vergeet"],
                        "stuur",
                    ),
                    mcq(
                        "m07-l08-b8",
                        "Welke zin klinkt het meest natuurlijk in een app?",
                        [
                            "Ik ben onderweg — er is vertraging, ik kom ~10 min later.",
                            "Ik ben onderweg en ik weet niet waar ik ben en alles is raar.",
                            "Onderweg ben ik vertraging later.",
                        ],
                        "Ik ben onderweg — er is vertraging, ik kom ~10 min later.",
                    ),
                ],
                depth=True,
            ),
            writing_step(
                "m07-l08-w1",
                "Schrijven — te laat",
                "Schrijf in het Nederlands (jij/je): je bent onderweg en je hebt 5–10 minuten vertraging. Noem ‘tram’ of ‘bus’.",
                [
                    "ik ben onderweg",
                    "onderweg",
                    "vertraging",
                    "tram heeft vertraging",
                    "de tram heeft vertraging",
                    "sorry",
                    "ik kom later",
                ],
                "Sorry! Ik ben onderweg maar mijn tram heeft een paar minuten vertraging.",
                min_chars=14,
            ),
            speak_step(
                "m07-l08-sp1",
                "Hardop — zelfde idee als je bericht",
                "Ik kom een paar minuten later door vertraging.",
                [
                    "Ik kom een paar minuten later door vertraging",
                    "ik kom een paar minuten later door vertraging",
                ],
                "Ik kom een paar minuten later door vertraging",
            ),
            writing_step(
                "m07-l08-w2",
                "Schrijven — afspreken",
                "Schrijf een kort bericht: stel voor om elkaar te treffen bij een duidelijke plek op het station (bijv. grote klok, ingang, perron).",
                [
                    "laten we afspreken",
                    "afspreken bij",
                    "ik wacht",
                    "bij de klok",
                    "bij de ingang",
                    "perron",
                ],
                "Laten we afspreken bij de grote klok bij het Stationsplein.",
                min_chars=14,
            ),
            speak_step(
                "m07-l08-sp2",
                "Hardop — voorstel om te treffen",
                "Zullen we afspreken bij de ingang naast spoor 4?",
                [
                    "Zullen we afspreken bij de ingang naast spoor 4",
                    "zullen we afspreken bij de ingang naast spoor 4",
                ],
                "Zullen we afspreken bij de ingang naast spoor 4",
            ),
            recap_step(
                "m07-l08-recap",
                "Recap",
                ["vertraging", "onderweg", "afspreken"],
                [
                    rt_fb("Ik ben ___. (on the way)", ["onderweg", "bovenweg", "achterweg"], "onderweg"),
                    rt_speak("Zeg: *De trein heeft vertraging.*", "De trein heeft vertraging."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Neem de uitgang ‘Stationsplein’.",
                        ["Welke uitgang kiezen", "Neem een andere trein", "Ga naar huis"],
                        "Welke uitgang kiezen",
                    ),
                    rt_listen_mcq(
                        "Snippet (Tim):",
                        "Laten we afspreken bij de koffiehoek naast spoor zes, oké?",
                        ["Waar afspreken", "Waar inchecken", "Welke trein nemen"],
                        "Waar afspreken",
                    ),
                    rt_ro(["aan", "half", "zeven.", "kom", "Ik", "rond"], "Ik kom rond half zeven aan."),
                    rt_fb("Sorry voor de ___!", ["vertraging", "verwarring", "verjaardag"], "vertraging"),
                    rt_speak("Zeg: *Zullen we afspreken bij de ingang?*", "Zullen we afspreken bij de ingang?"),
                ],
            ),
        ],
    }
