from .common import (
    LM,
    MID,
    discovery_step,
    fb,
    grammar_card,
    listen_read_step,
    listening_step,
    match_ex,
    mcq,
    pl,
    preview_step,
    recap_step,
    ro_tokens,
    rt_fb,
    rt_listen_mcq,
    rt_ro,
    rt_speak,
    speak_step,
    writing_step,
)


def lesson_l05() -> dict:
    lid = "a2-m09-l05-speaking-talk-hobbies"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Speaking · Talk about your hobbies",
        "lessonType": "speaking",
        "order": 4,
        "cefrLevel": "A2",
        "durationEstimate": 16,
        "grammarTargets": ["a2.3-leisure-conversation-flow", "a2.3-leisure-reactions"],
        "vocabTargets": ["lemma-hobby-m9", "lemma-vrije-tijd", "lemma-echt-m9", "lemma-vaak-m9", "lemma-soms-m9"],
        "canDoStatements": ["I can say what I do for fun, react, and ask follow-ups in several short turns."],
        "mistakeFocus": ["production", "reactions"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m09-l05-preview",
                "Warm-up — 5 woorden",
                [
                    ("echt", "echt", "really", "✨"),
                    ("oh leuk", "leuk", "oh nice!", "🎉"),
                    ("waarom", "waarom", "why", "❓"),
                    ("vaak", "vaak", "often", "🔁"),
                    ("soms", "soms", "sometimes", "🔀"),
                ],
            ),
            listening_step(
                "m09-l05-model",
                "Model — doorvragen",
                [
                    ("Julia", "Wat doe jij zoal in het weekend?", "What do you usually do at the weekend?"),
                    ("Finn", "Ik klim graag in een hal. Jij?", "I like climbing at a gym. You?"),
                    ("Julia", "Echt? Ik durf dat niet. Waarom vind jij dat leuk?", "Really? I wouldn't dare. Why do you like it?"),
                    ("Finn", "Omdat ik er sterk van word en ik ontspan. Hoe vaak ga jij uit?", "Because I get strong from it and I relax. How often do you go out?"),
                    ("Julia", "Soms naar een café met vrienden. Misschien volgende week samen?", "Sometimes to a café with friends. Maybe together next week?"),
                ],
                [
                    ("Wat doet Finn graag?", ["Klimmen in een hal", "Alleen slapen", "Niet sporten"], "Klimmen in een hal"),
                    ("Hoe reageert Julia eerst?", ["Echt? + ze durft niet", "Ze wordt boos", "Ze hangt op"], "Echt? + ze durft niet"),
                    ("Welke vervolgvraag stelt Julia?", ["Waarom vind je dat leuk?", "Waarom ben jij?", "Waarom zonder vraag?"],
                        "Waarom vind je dat leuk?"),
                    ("Wat zegt Finn over klimmen?", ["Hij wordt er sterk van + ontspanning", "Alleen duur", "Hij noemt geen reden"], "Hij wordt er sterk van + ontspanning"),
                    ("Hoe sluit Julia af?", ["Uitnodiging voor later", "Ze weigert praten", "Ze stopt zonder idee"], "Uitnodiging voor later"),
                ],
            ),
            discovery_step(
                "m09-l05-discovery",
                "Reacties die echt gebruikt worden",
                [
                    ("Echt?", "Really?", "verwondering"),
                    ("Oh leuk!", "Oh nice!", "enthousiasme"),
                    ("Waarom?", "Why?", "doorvragen"),
                    ("Hoe vaak …?", "How often …?", "frequentie"),
                ],
            ),
            pl(
                "m09-l05-pl1",
                "Variatie — 6×",
                ["reactie", "vraag", "weekend"],
                [
                    mcq(
                        "m09-l05-a1",
                        "Goede reactie",
                        ["Oh leuk! Vertel eens meer.", "Oh leuk. Zwijg nu.", "Leuk oh zonder interesse."],
                        "Oh leuk! Vertel eens meer.",
                    ),
                    fb("m09-l05-a2", "Ik vind dat ___, want het is creatief. (nice)", ["leuk", "saai", "duur"], "leuk"),
                    ro_tokens("m09-l05-r1", ["jij?", "vind", "Wat", "daar", "van"], "Wat vind jij daar van?"),
                    mcq(
                        "m09-l05-a3",
                        "Natuurlijke bevestiging",
                        ["Dat vind ik ook!", "Dat vind ik nooit!", "Vind dat ik ook zonder."],
                        "Dat vind ik ook!",
                    ),
                    mcq(
                        "m09-l05-a4",
                        "Als je nieuwsgierig bent",
                        ["En wat doe je daar precies?", "En wat eet je zonder hobby?", "Wat en precies zonder?"],
                        "En wat doe je daar precies?",
                    ),
                    mcq(
                        "m09-l05-a5",
                        "Voorzichtige mening",
                        ["Misschien is dat niet mijn ding.", "Jij bent fout met je ding.", "Misschien zonder respect."],
                        "Misschien is dat niet mijn ding.",
                    ),
                ],
                depth=True,
            ),
            pl(
                "m09-l05-pl2",
                "Follow-up — 6×",
                ["uitgaan", "vriend", "plannen"],
                [
                    mcq(
                        "m09-l05-b1",
                        "Weekendplannen vragen",
                        ["Wat heb je dit weekend gedaan?", "Wat heb je dit weekend gekocht zonder reden?", "Weekend wat zonder?"],
                        "Wat heb je dit weekend gedaan?",
                    ),
                    fb("m09-l05-b2", "Ik ga ___ met vrienden naar het park. (often)", ["vaak", "nooit", "alleen"], "vaak"),
                    ro_tokens("m09-l05-r2", ["me?", "Ga", "je", "mee"], "Ga je mee?"),
                    mcq(
                        "m09-l05-b3",
                        "Als je het ermee eens bent",
                        ["Ik ben het eens, dat klinkt goed.", "Ik ben het oneens, zonder reden.", "Eens ben ik zonder luisteren."],
                        "Ik ben het eens, dat klinkt goed.",
                    ),
                    mcq(
                        "m09-l05-b4",
                        "Open vraag",
                        ["Wat vind jij het leukst?", "Wat vind jij het minst zonder?", "Leukst wat jij?"],
                        "Wat vind jij het leukst?",
                    ),
                    mcq(
                        "m09-l05-b5",
                        "Korte brug",
                        ["En verder?", "En stop.", "Verder en zonder."],
                        "En verder?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m09-l05-sp1",
                "Jouw beurt",
                "In het weekend ga ik graag naar de bioscoop.",
                [
                    "In het weekend ga ik graag naar de bioscoop",
                    "in het weekend ga ik graag naar de bioscoop",
                ],
                "In het weekend ga ik graag naar de bioscoop",
            ),
            speak_step(
                "m09-l05-sp2",
                "Reactie",
                "Echt? Welke films kijk je het liefst?",
                ["Echt welke films kijk je het liefst", "Echt? Welke films kijk je het liefst?"],
                "Echt welke films kijk je het liefst",
            ),
            speak_step(
                "m09-l05-sp3",
                "Mening",
                "Ik vind actiefilms spannend, maar ik hou ook van komedie.",
                [
                    "Ik vind actiefilms spannend maar ik hou ook van komedie",
                    "Ik vind actiefilms spannend, maar ik hou ook van komedie.",
                ],
                "Ik vind actiefilms spannend maar ik hou ook van komedie",
            ),
            speak_step(
                "m09-l05-sp4",
                "Frequentie",
                "Meestal één keer per maand, soms vaker.",
                ["Meestal één keer per maand soms vaker", "Meestal één keer per maand, soms vaker."],
                "Meestal één keer per maand soms vaker",
            ),
            speak_step(
                "m09-l05-sp5",
                "Uitnodiging",
                "Zullen we volgende week samen iets leuks doen?",
                [
                    "Zullen we volgende week samen iets leuks doen",
                    "zullen we volgende week samen iets leuks doen",
                ],
                "Zullen we volgende week samen iets leuks doen",
            ),
            speak_step(
                "m09-l05-sp6",
                "Slot",
                "Top! Dan spreken we later af.",
                ["Top dan spreken we later af", "Top! Dan spreken we later af."],
                "Top dan spreken we later af",
            ),
            recap_step(
                "m09-l05-recap",
                "Recap",
                ["echt", "waarom", "leuk"],
                [
                    rt_speak("Zeg: *Echt?*", "Echt?"),
                    rt_fb("Oh __! Dat wil ik ook proberen. (nice)", ["leuk", "saai", "duur"], "leuk"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Waarom vind jij dat leuk?",
                        ["Vraag naar reden", "Vraag naar adres", "Stopwoord"],
                        "Vraag naar reden",
                    ),
                    rt_ro(["vind", "Dat", "ik", "ook!"], "Dat vind ik ook!"),
                    rt_fb("Hoe ___ ga je naar het theater? (often)", ["vaak", "lang", "oud"], "vaak"),
                    rt_speak("Zeg: *Misschien volgende week?*", "Misschien volgende week?"),
                ],
            ),
        ],
    }


def lesson_l06() -> dict:
    lid = "a2-m09-l06-listening-social-weekend-plans"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Listening · Social conversations (friends, weekend plans)",
        "lessonType": "input",
        "order": 5,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.3-leisure-conversation-flow", "a2.3-leisure-reactions"],
        "vocabTargets": ["lemma-weekend-m9", "lemma-vriend-m9", "lemma-uitgaan-m9", "lemma-festival-m9", "lemma-misschien-m9"],
        "canDoStatements": ["I can follow friends making weekend plans and reacting to each other’s ideas."],
        "mistakeFocus": ["listening-detail", "connectors"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m09-l06-preview",
                "Warm-up — 5 woorden",
                [
                    ("afspreken", "afspreken", "to arrange to meet", "📱"),
                    ("festival", "festival", "festival", "🎪"),
                    ("terras", "terras", "terrace / outdoor seating", "☕"),
                    ("gratis", "gratis", "free", "🆓"),
                    ("misschien", "misschien", "maybe", "🤷"),
                ],
            ),
            listening_step(
                "m09-l06-a",
                "Input — zaterdag plannen",
                [
                    ("Lars", "Zullen we zaterdag iets doen? Er is een klein festival op het plein.", "Shall we do something Saturday? There's a small festival on the square."),
                    ("Iris", "Oh ja? Is het gratis?", "Oh yeah? Is it free?"),
                    ("Lars", "De muziek buiten wel. Voor eten betaal je normaal.", "The outdoor music yes. For food you pay as usual."),
                    ("Iris", "Ik ben in! Maar ik moet om zes weg, want ik werk ’s avonds.", "I'm in! But I have to leave at six because I work in the evening."),
                    ("Lars", "Prima. Dan drinken we eerst koffie op een terras.", "Fine. Then we'll have coffee on a terrace first."),
                ],
                [
                    ("Wat stelt Lars voor?", ["Festival op het plein", "Naar de tandarts", "Alleen thuis blijven"], "Festival op het plein"),
                    ("Wat wil Iris weten?", ["Of het gratis is", "Of er sneeuw is", "Of Lars verhuist"], "Of het gratis is"),
                    ("Waarom moet Iris om zes weg?", ["Ze werkt ’s avonds", "Ze haat muziek", "Zonder reden"], "Ze werkt ’s avonds"),
                    ("Wat is het plan met koffie?", ["Eerst terras", "Geen koffie", "Alleen bier zonder koffie"], "Eerst terras"),
                    ("Hoe reageert Iris op het idee?", ["Enthousiast (ik ben in!)", "Boos", "Ze weigert"], "Enthousiast (ik ben in!)"),
                ],
            ),
            listening_step(
                "m09-l06-b",
                "Input — zondag rustig",
                [
                    ("Puck", "Zondag wil ik rustig aan. Misschien een museum?", "Sunday I want to take it easy. Maybe a museum?"),
                    ("Ruben", "Hmm, ik ben meer van de markt. Maar ik ga wel mee als het niet te lang duurt.", "Hmm, I'm more of a market person. But I'll come along if it doesn't take too long."),
                    ("Puck", "Top. We kunnen daarna iets eten. Wat lijkt jou lekker?", "Great. We can eat something afterwards. What sounds good to you?"),
                    ("Ruben", "Pizza of iets vegetarisch. Jij kiest.", "Pizza or something vegetarian. You choose."),
                ],
                [
                    ("Wat wil Puck op zondag?", ["Rustig + misschien museum", "Marathon rennen", "Alleen feesten"], "Rustig + misschien museum"),
                    ("Wat wil Ruben liever?", ["De markt", "Een discotheek", "Niets"], "De markt"),
                    ("Hoe lost Ruben het op?", ["Hij gaat mee met voorwaarde", "Hij weigert", "Hij stopt de chat"], "Hij gaat mee met voorwaarde"),
                    ("Wat bespreken ze na het museum?", ["Eten", "Alleen slapen", "Werk zonder eten"], "Eten"),
                    ("Wie kiest het eten?", ["Puck (jij)", "Ruben alleen", "De ober"], "Puck (jij)"),
                ],
            ),
            discovery_step(
                "m09-l06-discovery",
                "Handige zinnen",
                [
                    ("Zullen we …?", "Shall we …?", "voorstel"),
                    ("Ik ben in!", "I'm in!", "ja"),
                    ("Hmm, ik ben meer van …", "Hmm, I'm more into …", "voorkeur"),
                    ("Wat lijkt jou …?", "What sounds … to you?", "kiezen"),
                ],
            ),
            pl(
                "m09-l06-pl1",
                "Practice — 6×",
                ["weekend", "festival", "terras"],
                [
                    mcq(
                        "m09-l06-a1",
                        "Voorstel doen",
                        ["Zullen we vanavond een filmpje pakken?", "Zullen we vanavond zonder idee?", "Zullen wij vanavond?"],
                        "Zullen we vanavond een filmpje pakken?",
                    ),
                    fb("m09-l06-a2", "Het concert is ___. (free)", ["gratis", "duur", "gesloten"], "gratis"),
                    ro_tokens("m09-l06-r1", ["in!", "Ik", "ben"], "Ik ben in!"),
                    mcq(
                        "m09-l06-a3",
                        "Als je twijfelt",
                        ["Misschien, ik weet het nog niet.", "Misschien, ik weiger alles.", "Misschien zonder antwoord."],
                        "Misschien, ik weet het nog niet.",
                    ),
                    mcq(
                        "m09-l06-a4",
                        "Compromis",
                        ["Oké, maar dan niet te laat.", "Oké, maar dan altijd oneindig.", "Oké zonder voorwaarde nooit."],
                        "Oké, maar dan niet te laat.",
                    ),
                    mcq(
                        "m09-l06-a5",
                        "Brug naar eten",
                        ["Heb je al honger?", "Heb je al slaap zonder eten?", "Honger heb je?"],
                        "Heb je al honger?",
                    ),
                ],
            ),
            pl(
                "m09-l06-pl2",
                "Variatie — 6×",
                ["meer", "mee", "kiezen"],
                [
                    mcq(
                        "m09-l06-b1",
                        "‘Meer van’ =",
                        ["Dat past beter bij mij", "Ik haat dat altijd", "Meer zonder voorkeur"],
                        "Dat past beter bij mij",
                    ),
                    fb("m09-l06-b2", "Ik ga ___, als jij ook wilt. (along)", ["mee", "weg", "alleen"], "mee"),
                    ro_tokens("m09-l06-r2", ["lekker?", "lijkt", "Wat", "jou"], "Wat lijkt jou lekker?"),
                    mcq(
                        "m09-l06-b3",
                        "Als je ja zegt met voorwaarde",
                        ["Ik ga mee, maar ik moet om vijf weg.", "Ik ga mee, maar ik verdwijn zonder reden.", "Ga ik mee maar zonder."],
                        "Ik ga mee, maar ik moet om vijf weg.",
                    ),
                    mcq(
                        "m09-l06-b4",
                        "Natuurlijke slotzin",
                        ["Laten we zo afspreken.", "Laten we nooit praten.", "Zo laten zonder."],
                        "Laten we zo afspreken.",
                    ),
                    mcq(
                        "m09-l06-b5",
                        "Check begrip (zaterdag)",
                        ["Dus eerst koffie op een terras, daarna naar het festival?", "Dus eerst festival, daarna slapen zonder koffie?", "Dus eerst zonder volgorde?"],
                        "Dus eerst koffie op een terras, daarna naar het festival?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m09-l06-sp1",
                "Production",
                "Zullen we zaterdag iets leuks doen?",
                ["Zullen we zaterdag iets leuks doen", "zullen we zaterdag iets leuks doen"],
                "Zullen we zaterdag iets leuks doen",
            ),
            speak_step(
                "m09-l06-sp2",
                "Production",
                "Ik ben in! Wat had je in gedachten?",
                ["Ik ben in wat had je in gedachten", "Ik ben in! Wat had je in gedachten?"],
                "Ik ben in wat had je in gedachten",
            ),
            speak_step(
                "m09-l06-sp3",
                "Production",
                "Misschien kunnen we naar het festival gaan.",
                [
                    "Misschien kunnen we naar het festival gaan",
                    "misschien kunnen we naar het festival gaan",
                ],
                "Misschien kunnen we naar het festival gaan",
            ),
            speak_step(
                "m09-l06-sp4",
                "Production",
                "Ik moet wel om zeven weg, want ik werk later.",
                [
                    "Ik moet wel om zeven weg want ik werk later",
                    "Ik moet wel om zeven weg, want ik werk later.",
                ],
                "Ik moet wel om zeven weg want ik werk later",
            ),
            recap_step(
                "m09-l06-recap",
                "Recap",
                ["festival", "misschien", "mee"],
                [
                    rt_fb("___ we zondag naar de markt? (shall)", ["Zullen", "Willen", "Kunnen"], "Zullen"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Ik ben in!",
                        ["Ja / meedoen", "Nee / weigeren", "Stoppen"],
                        "Ja / meedoen",
                    ),
                    rt_ro(["in!", "ben", "Ik"], "Ik ben in!"),
                    rt_speak("Zeg: *Wat lijkt jou lekker?*", "Wat lijkt jou lekker?"),
                    rt_fb("Het is ___. (free)", ["gratis", "dicht", "vol"], "gratis"),
                    rt_speak("Zeg: *Laten we zo afspreken.*", "Laten we zo afspreken."),
                ],
            ),
        ],
    }


def lesson_l07() -> dict:
    lid = "a2-m09-l07-grammar-past-experiences-light-perfectum"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Grammar & patterns · Past experiences (light perfectum)",
        "lessonType": "pattern",
        "order": 6,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.3-leisure-perfectum-light", "a2.3-leisure-connectors"],
        "vocabTargets": ["lemma-gisteren-m9", "lemma-vandaag-m9", "lemma-film-m9", "lemma-museum-m9", "lemma-want-m9"],
        "canDoStatements": ["I can say what I did yesterday or at the weekend using simple heb … ge- / ben … geweest patterns."],
        "mistakeFocus": ["past-tense-light", "auxiliary"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m09-l07-preview",
                "Warm-up — 4 woorden",
                [
                    ("gisteren", "gisteren", "yesterday", "📅"),
                    ("geweest", "zijn", "been", "📍"),
                    ("gekeken", "kijken", "watched", "👀"),
                    ("gegaan", "gaan", "gone", "🚶"),
                ],
            ),
            grammar_card(
                "m09-l07-gc",
                "Patroon",
                "Licht verleden (perfectum, kort)",
                "**Gisteren heb ik** + ge- + activiteit. **Ik ben** … **geweest** (naar een plek). In de praattaal hoor je ook kort: *Gisteren was ik bij …* — prima. Geen lang verhaal: één zin is genoeg. Combineer met **want** als je wilt.",
                [
                    ("Gisteren heb ik een podcast geluisterd.", "Yesterday I listened to a podcast."),
                    ("Ik ben in het park geweest.", "I've been to the park."),
                ],
                hint="Kies *heb* bij veel activiteiten; *ben* vaak bij *naar … gaan* / *zijn* op een plek.",
            ),
            listening_step(
                "m09-l07-listen",
                "Input — maandagochtend",
                [
                    ("Sofie", "Hé, hoe was je weekend?", "Hey, how was your weekend?"),
                    ("Daan", "Leuk! Gisteren ben ik naar een markt geweest en ik heb verse stroopwafels gekocht.", "Nice! Yesterday I went to a market and I bought fresh stroopwafels."),
                    ("Sofie", "Yum. Ik heb thuis gebleven en een film gekeken.", "Yum. I stayed home and watched a film."),
                    ("Daan", "Echt? Welke film?", "Really? Which film?"),
                    ("Sofie", "Een komedie. Saai begin, maar het einde was grappig.", "A comedy. Boring start, but the ending was funny."),
                ],
                [
                    ("Waar is Daan gisteren geweest?", ["Naar een markt", "Naar de maan", "Nergens"], "Naar een markt"),
                    ("Wat heeft Daan gekocht?", ["Stroopwafels", "Een fiets", "Niets"], "Stroopwafels"),
                    ("Wat heeft Sofie gedaan?", ["Thuis gebleven + film gekeken", "Marathon gelopen", "Alleen gewerkt"], "Thuis gebleven + film gekeken"),
                    ("Welk genre noemt Sofie?", ["Komedie", "Horror zonder grap", "Documentaire over pizza"], "Komedie"),
                    ("Hoe was het begin van de film volgens Sofie?", ["Saai", "Perfect", "Ze noemt geen begin"], "Saai"),
                ],
            ),
            discovery_step(
                "m09-l07-discovery",
                "Vaste brokken",
                [
                    ("Gisteren heb ik … gekeken.", "Yesterday I watched …", "hebben + tv"),
                    ("Ik ben … geweest.", "I have been …", "zijn + plek"),
                    ("Ik heb … gekocht.", "I bought …", "hebben + shop"),
                    ("Het was …", "It was …", "korte evaluatie"),
                ],
            ),
            pl(
                "m09-l07-pl1",
                "Practice — 6×",
                ["gisteren", "gekeken", "geweest"],
                [
                    mcq(
                        "m09-l07-a1",
                        "Juiste hulpwerkwoord (plek)",
                        ["Ik ben in Utrecht geweest.", "Ik heb in Utrecht geweest zonder ben.", "Ben ik Utrecht zonder."],
                        "Ik ben in Utrecht geweest.",
                    ),
                    fb("m09-l07-a2", "Gisteren heb ik een uur ___. (walked)", ["gewandeld", "geweest", "gegeten"], "gewandeld"),
                    ro_tokens("m09-l07-r1", ["gekeken.", "heb", "Ik", "een", "documentaire"], "Ik heb een documentaire gekeken."),
                    mcq(
                        "m09-l07-a3",
                        "Activiteit met hebben",
                        ["Ik heb pizza gegeten.", "Ik ben pizza gegeten.", "Ik eet pizza gisteren zonder heb."],
                        "Ik heb pizza gegeten.",
                    ),
                    mcq(
                        "m09-l07-a4",
                        "Korte evaluatie",
                        ["Het was gezellig, maar druk.", "Het was gezellig, maar onmogelijk zonder reden.", "Was het gezellig maar."],
                        "Het was gezellig, maar druk.",
                    ),
                    mcq(
                        "m09-l07-a5",
                        "Vandaag vs gisteren",
                        ["Vandaag werk ik; gisteren heb ik gerust.", "Vandaag gisteren zonder verschil.", "Gisteren vandaag zonder."],
                        "Vandaag werk ik; gisteren heb ik gerust.",
                    ),
                ],
            ),
            pl(
                "m09-l07-pl2",
                "Variatie — 6×",
                ["weekend", "omdat", "want"],
                [
                    mcq(
                        "m09-l07-b1",
                        "Reden achteraf",
                        ["Ik ben moe, want ik heb hard gewerkt.", "Ik ben moe, want ik heb nooit geslapen altijd.", "Moe ben want."],
                        "Ik ben moe, want ik heb hard gewerkt.",
                    ),
                    fb("m09-l07-b2", "Ik ___ naar het strand geweest. (have been)", ["ben", "heb", "wil"], "ben"),
                    ro_tokens("m09-l07-r2", ["geweest.", "ben", "niet", "Ik", "daar"], "Ik ben daar niet geweest."),
                    mcq(
                        "m09-l07-b3",
                        "Te ingewikkeld? Blijf kort",
                        ["Gisteren concert. Leuk!", "Gisteren heb ik zonder einde verteld over alles.", "Gisteren zonder zin."],
                        "Gisteren concert. Leuk!",
                    ),
                    mcq(
                        "m09-l07-b4",
                        "Doorvragen",
                        ["En wat heb je daarna gedaan?", "En wat heb je zonder daarna?", "Wat en daarna?"],
                        "En wat heb je daarna gedaan?",
                    ),
                    mcq(
                        "m09-l07-b5",
                        "Transform (informeel)",
                        ["Ik keek tv → Ik heb tv gekeken.", "Ik keek tv → Ik ben tv geweest.", "Keek ik tv zonder."],
                        "Ik keek tv → Ik heb tv gekeken.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m09-l07-sp1",
                "Production",
                "Gisteren heb ik lang met vrienden gepraat.",
                ["Gisteren heb ik lang met vrienden gepraat", "gisteren heb ik lang met vrienden gepraat"],
                "Gisteren heb ik lang met vrienden gepraat",
            ),
            speak_step(
                "m09-l07-sp2",
                "Production",
                "Ik ben in het museum geweest.",
                ["Ik ben in het museum geweest", "ik ben in het museum geweest"],
                "Ik ben in het museum geweest",
            ),
            speak_step(
                "m09-l07-sp3",
                "Production",
                "Het was relaxed, want het regende.",
                ["Het was relaxed want het regende", "Het was relaxed, want het regende."],
                "Het was relaxed want het regende",
            ),
            speak_step(
                "m09-l07-sp4",
                "Production",
                "Wat heb jij gisteren gedaan?",
                ["Wat heb jij gisteren gedaan", "wat heb jij gisteren gedaan"],
                "Wat heb jij gisteren gedaan",
            ),
            recap_step(
                "m09-l07-recap",
                "Recap",
                ["gisteren", "geweest", "gekeken"],
                [
                    rt_fb("Gisteren heb ik een film ___. (watched)", ["gekeken", "geweest", "gegaan"], "gekeken"),
                    rt_ro(["geweest.", "ben", "Ik", "daar"], "Ik ben daar geweest."),
                    rt_speak("Zeg: *Het was gezellig.*", "Het was gezellig."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Ik heb thuis gebleven en een film gekeken.",
                        ["Thuis + film gisteren", "Alleen werken", "Geen activiteit"],
                        "Thuis + film gisteren",
                    ),
                    rt_fb("Ik ___ moe, want ik heb weinig geslapen. (am)", ["ben", "heb", "word"], "ben"),
                    rt_speak("Zeg: *En jij?*", "En jij?"),
                ],
            ),
        ],
    }


def lesson_l08() -> dict:
    lid = "a2-m09-l08-writing-short-messages-weekend-hobbies"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Writing · Short personal messages (weekend / hobbies)",
        "lessonType": "writing",
        "order": 7,
        "cefrLevel": "A2",
        "durationEstimate": 16,
        "grammarTargets": ["a2.3-leisure-perfectum-light", "a2.3-leisure-conversation-flow"],
        "vocabTargets": ["lemma-weekend-m9", "lemma-vriend-m9", "lemma-leuk-m9", "lemma-gisteren-m9", "lemma-muziek-m9"],
        "canDoStatements": ["I can write a short informal message about my weekend or hobbies."],
        "mistakeFocus": ["register", "past-simple"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m09-l08-preview",
                "Warm-up — 4 woorden",
                [
                    ("bericht", "bericht", "message", "💬"),
                    ("stuur", "sturen", "to send", "📤"),
                    ("even", "even", "a moment / quickly", "⏱️"),
                    ("groetjes", "groetjes", "cheers / bye (informal)", "👋"),
                ],
            ),
            listen_read_step(
                "m09-l08-lr",
                "Model — appje",
                [
                    (
                        "Jij (voorbeeld)",
                        "Hoi! Gisteren ben ik naar een concert geweest. Het was echt leuk. Zullen we volgende week samen iets doen? Groetjes!",
                        "Hi! Yesterday I went to a concert. It was really fun. Shall we do something together next week? Cheers!",
                    ),
                ],
                [
                    ("Wat deed de schrijver gisteren?", ["Naar een concert", "Naar de dokter", "Niets"], "Naar een concert"),
                    ("Hoe vond de schrijver het?", ["Echt leuk", "Saai", "Zonder mening"], "Echt leuk"),
                    ("Wat stelt de schrijver voor?", ["Volgende week samen iets", "Nooit meer praten", "Alleen werken"], "Volgende week samen iets"),
                    ("Welke toon past?", ["Informeel en vriendelijk", "Formeel met *Geachte*", "Boos"], "Informeel en vriendelijk"),
                ],
            ),
            discovery_step(
                "m09-l08-discovery",
                "Mini-sjabloon",
                [
                    ("Hoi! …", "Hi! …", "open"),
                    ("Gisteren heb/ben ik …", "Yesterday I …", "verleden"),
                    ("Het was …", "It was …", "gevoel"),
                    ("Zullen we …? Groetjes!", "Shall we …? Bye!", "afsluiting"),
                ],
            ),
            pl(
                "m09-l08-pl1",
                "Practice — 6×",
                ["bericht", "weekend", "kort"],
                [
                    mcq(
                        "m09-l08-p1",
                        "Natuurlijke openingszin",
                        ["Hoi! Hoe was je weekend?", "Geachte heer/mevrouw, hierbij mijn weekend.", "Hoi zonder vraag nooit."],
                        "Hoi! Hoe was je weekend?",
                    ),
                    fb("m09-l08-p2", "Ik heb zondag ___. (relaxed)", ["gerust", "gegeten", "gekocht"], "gerust"),
                    ro_tokens("m09-l08-r1", ["leuk!", "was", "Het", "heel"], "Het was heel leuk!"),
                    mcq(
                        "m09-l08-p3",
                        "Te formeel voor een vriend (in een appje)",
                        ["Met vriendelijke groet, hierbij mijn weekendverslag", "Groetjes!", "Hey, hoe was je weekend?"],
                        "Met vriendelijke groet, hierbij mijn weekendverslag",
                    ),
                    mcq(
                        "m09-l08-p4",
                        "Korte persoonlijke update",
                        ["Ik was bij mijn zus. Gezellig!", "Ik was bij mijn zus zonder gezellig.", "Was ik zus zonder."],
                        "Ik was bij mijn zus. Gezellig!",
                    ),
                    mcq(
                        "m09-l08-p5",
                        "Uitnodiging in appje",
                        ["Zin om vrijdag te komen eten?", "Zin om nooit te praten?", "Zin vrijdag zonder?"],
                        "Zin om vrijdag te komen eten?",
                    ),
                ],
            ),
            pl(
                "m09-l08-pl2",
                "Variatie — 6×",
                ["gisteren", "vandaag", "misschien"],
                [
                    mcq(
                        "m09-l08-q1",
                        "Zin herschrijven: informeel",
                        ["Ik ben naar de bioscoop geweest → Gisteren film gekeken!", "Ik ben naar de bioscoop geweest → Geachte bioscoop", "Bioscoop zonder zin."],
                        "Ik ben naar de bioscoop geweest → Gisteren film gekeken!",
                    ),
                    fb("m09-l08-q2", "___ spreken we af bij het station? (shall)", ["Zullen", "Moeten", "Willen"], "Zullen"),
                    ro_tokens("m09-l08-r2", ["weekend!", "fijn", "Prettig"], "Prettig weekend!"),
                    mcq(
                        "m09-l08-q3",
                        "Als je twijfelt",
                        ["Misschien tot snel!", "Misschien nooit meer!", "Misschien zonder groet."],
                        "Misschien tot snel!",
                    ),
                    mcq(
                        "m09-l08-q4",
                        "Emoji-stijl (tekst)",
                        ["Ik vond het top 😊", "Ik vond het zonder woorden", "Top vond ik zonder."],
                        "Ik vond het top 😊",
                    ),
                    mcq(
                        "m09-l08-q5",
                        "Vraag toevoegen",
                        ["En jij, wat heb jij gedaan?", "En jij, wat heb jij zonder?", "Jij en wat zonder?"],
                        "En jij, wat heb jij gedaan?",
                    ),
                ],
                depth=True,
            ),
            writing_step(
                "m09-l08-w1",
                "Schrijven — kort",
                "Schrijf een kort appje over je weekend (2–4 zinnen). Gebruik minstens één zin met *gisteren* of met *ik ben … geweest* / *ik heb …*.",
                [
                    "hoi",
                    "gisteren",
                    "park",
                    "geweest",
                    "leuk",
                    "groetjes",
                ],
                "Hoi! Gisteren ben ik naar het park geweest. Het was leuk! Groetjes!",
                min_chars=20,
            ),
            writing_step(
                "m09-l08-w2",
                "Schrijven — uitnodiging",
                "Schrijf een kort berichtje aan een vriend: stel voor om samen iets te doen (noem dag + activiteit).",
                ["hey", "zullen", "zaterdag", "koffie", "samen", "groetjes"],
                "Hey! Zullen we zaterdag samen koffie drinken? Groetjes!",
                min_chars=18,
            ),
            speak_step(
                "m09-l08-sp1",
                "Hardop hetzelfde idee",
                "Hoi! Gisteren heb ik gewandeld. Het was mooi weer.",
                [
                    "Hoi gisteren heb ik gewandeld het was mooi weer",
                    "Hoi! Gisteren heb ik gewandeld. Het was mooi weer.",
                ],
                "Hoi gisteren heb ik gewandeld het was mooi weer",
            ),
            speak_step(
                "m09-l08-sp2",
                "Uitnodiging hardop",
                "Zullen we morgen even bellen?",
                ["Zullen we morgen even bellen", "zullen we morgen even bellen"],
                "Zullen we morgen even bellen",
            ),
            speak_step(
                "m09-l08-sp3",
                "Bal terug",
                "En jij? Wat heb jij dit weekend gedaan?",
                [
                    "En jij wat heb jij dit weekend gedaan",
                    "En jij? Wat heb jij dit weekend gedaan?",
                ],
                "En jij wat heb jij dit weekend gedaan",
            ),
            recap_step(
                "m09-l08-recap",
                "Recap",
                ["bericht", "gisteren", "groetjes"],
                [
                    rt_fb("___! Gisteren was het gezellig. (hi)", ["Hoi", "Geachte", "Hoogachtend"], "Hoi"),
                    rt_ro(["geweest.", "ben", "Ik", "concert", "naar", "een"], "Ik ben naar een concert geweest."),
                    rt_speak("Zeg: *Groetjes!*", "Groetjes!"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Zullen we volgende week samen iets doen?",
                        ["Uitnodiging", "Klacht", "Werkmail"],
                        "Uitnodiging",
                    ),
                    rt_fb("Het was ___. (really nice)", ["echt leuk", "echt duur", "echt gesloten"], "echt leuk"),
                    rt_speak("Zeg: *En jij?*", "En jij?"),
                ],
            ),
        ],
    }
