from .common import (
    LM,
    MID,
    discovery_step,
    fb,
    listening_step,
    mcq,
    pl,
    preview_step,
    recap_step,
    ro_tokens,
    rt_fb,
    rt_listen_mcq,
    rt_ro,
    rt_speak,
    scenario_chat_step,
    speak_step,
)


def lesson_l09() -> dict:
    lid = "a2-m09-l09-task-short-conversation-guided"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Real-life task · Have a short conversation (guided)",
        "lessonType": "task",
        "order": 8,
        "cefrLevel": "A2",
        "durationEstimate": 16,
        "grammarTargets": ["a2.3-leisure-conversation-flow", "a2.3-leisure-reactions"],
        "vocabTargets": ["lemma-hobby-m9", "lemma-weekend-m9", "lemma-leuk-m9", "lemma-echt-m9", "lemma-vriend-m9"],
        "canDoStatements": ["I can hold a short guided chat: react, ask back, and share a simple opinion."],
        "mistakeFocus": ["conversation-flow", "reactions"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m09-l09-preview",
                "Warm-up — 5 woorden",
                [
                    ("kennismaken", "kennismaken", "to get to know", "🤝"),
                    ("vertellen", "vertellen", "to tell", "💬"),
                    ("luisteren", "luisteren", "to listen", "👂"),
                    ("meer", "meer", "more", "➕"),
                    ("zelfde", "zelfde", "same", "🔄"),
                ],
            ),
            listening_step(
                "m09-l09-listen",
                "Model — nieuw iemand op een borrel",
                [
                    ("Mila", "Hoi, ik ben Mila. Ik werk hier in de buurt. En jij?", "Hi, I'm Mila. I work around here. And you?"),
                    ("Jij", "Hoi! Ik ben Alex. Ik studeer hier sinds dit jaar.", "Hi! I'm Alex. I've been studying here since this year."),
                    ("Mila", "Oh leuk! Wat studeer je?", "Oh nice! What do you study?"),
                    ("Jij", "International business. En wat doe jij in je vrije tijd?", "International business. And what do you do in your free time?"),
                    ("Mila", "Ik schilder graag. Vind jij dat ook ontspannend?", "I like painting. Do you find that relaxing too?"),
                    ("Jij", "Echt? Ik vind tekenen ook leuk, maar ik heb weinig tijd.", "Really? I like drawing too, but I have little time."),
                ],
                [
                    ("Waar werkt Mila?", ["In de buurt", "In de ruimte", "Nergens"], "In de buurt"),
                    ("Wat studeert Alex?", ["International business", "Geneeskunde zonder detail", "Niets"], "International business"),
                    ("Welke hobby noemt Mila?", ["Schilderen", "Zwemmen professioneel", "Koken zonder schilderen"], "Schilderen"),
                    ("Hoe reageert Alex op schilderen?", ["Hij vindt tekenen ook leuk", "Hij haat kunst", "Hij stopt het gesprek"], "Hij vindt tekenen ook leuk"),
                    ("Welke vervolgvraag stelt Mila over hobby?", ["Vind jij dat ook ontspannend?", "Vind jij werk saai?", "Vind jij zonder hobby?"],
                        "Vind jij dat ook ontspannend?"),
                    ("Wat is een goede brugzin van Alex?", ["En wat doe jij in je vrije tijd?", "En wat eet jij?", "Vrije tijd zonder vraag?"],
                        "En wat doe jij in je vrije tijd?"),
                ],
            ),
            scenario_chat_step(
                "m09-l09-chat",
                "Mini-sim — kies je antwoord",
                [
                    ("Sam", "Gisteren ben ik naar een klein concert geweest. Het was gezellig!", "Yesterday I went to a small concert. It was cosy!"),
                    ("Jij (kies)", "Echt? Wat voor muziek was het?", "Really? What kind of music was it?"),
                    ("Sam", "Indie-folk. Niet te hard.", "Indie-folk. Not too loud."),
                    ("Jij (kies)", "Dat lijkt me leuk. Ik hou van live muziek.", "That sounds fun. I love live music."),
                    ("Sam", "Ja! Ga je vaak naar optredens?", "Yeah! Do you often go to gigs?"),
                    ("Jij (kies)", "Soms. Misschien kunnen we een keer samen?", "Sometimes. Maybe we could go together sometime?"),
                    ("Sam", "Top idee. Laten we volgende week appen.", "Great idea. Let's text next week."),
                ],
                [
                    ("Hoe reageer je op Sam’s verhaal?", ["Echt? Wat voor muziek was het?", "Stop.", "Oké zonder vraag."],
                        "Echt? Wat voor muziek was het?"),
                    ("Welke stijl noemt Sam?", ["Indie-folk", "Heavy metal alleen", "Klassiek zonder uitleg"], "Indie-folk"),
                    ("Wat zeg je over live muziek?", ["Dat lijkt me leuk. Ik hou van live muziek.", "Ik haat muziek altijd.", "Live zonder mening."],
                        "Dat lijkt me leuk. Ik hou van live muziek."),
                    ("Wat stel je voor op het eind?", ["Misschien samen een keer", "Nooit meer praten", "Samen zonder idee."],
                        "Misschien samen een keer"),
                    ("Hoe sluit Sam af?", ["Laten we volgende week appen", "Laten we nooit praten", "Appen zonder week."],
                        "Laten we volgende week appen"),
                ],
            ),
            discovery_step(
                "m09-l09-discovery",
                "Gesprek laten lopen",
                [
                    ("Echt? + vervolgvraag", "Really? + follow-up", "reactie"),
                    ("Dat lijkt me leuk.", "That sounds fun.", "beleefd mee"),
                    ("En jij? / En wat doe jij …?", "And you? …", "bal terug"),
                    ("Laten we … appen / afspreken.", "Let's text / arrange …", "vervolg buiten nu"),
                ],
            ),
            pl(
                "m09-l09-pl1",
                "Practice — 6×",
                ["reactie", "vraag", "mening"],
                [
                    mcq(
                        "m09-l09-a1",
                        "Openingsreactie",
                        ["Oh nice! Vertel eens.", "Oh nice. Zwijg.", "Nice oh zonder."],
                        "Oh nice! Vertel eens.",
                    ),
                    fb("m09-l09-a2", "Ik ___ het eens met je. (agree)", ["ben", "heb", "word"], "ben"),
                    ro_tokens("m09-l09-r1", ["leuk!", "lijkt", "Dat", "me"], "Dat lijkt me leuk!"),
                    mcq(
                        "m09-l09-a3",
                        "Als je het niet weet",
                        ["Interessant! Ik weet daar weinig van.", "Interessant! Ik stop altijd.", "Interessant zonder respect."],
                        "Interessant! Ik weet daar weinig van.",
                    ),
                    mcq(
                        "m09-l09-a4",
                        "Bal terug",
                        ["En jij, wat vind jij daarvan?", "En jij, wat vind jij zonder?", "Jij en wat zonder?"],
                        "En jij, wat vind jij daarvan?",
                    ),
                    mcq(
                        "m09-l09-a5",
                        "Vriendelijke oneens",
                        ["Ik zie het anders, maar dat is oké.", "Jij bent fout, punt.", "Anders zie ik zonder."],
                        "Ik zie het anders, maar dat is oké.",
                    ),
                ],
                depth=True,
            ),
            pl(
                "m09-l09-pl2",
                "Variatie — 6×",
                ["misschien", "volgende week", "afspreken"],
                [
                    mcq(
                        "m09-l09-b1",
                        "Voorstel zonder druk",
                        ["Misschien een andere keer?", "Misschien nooit?", "Misschien zonder idee?"],
                        "Misschien een andere keer?",
                    ),
                    fb("m09-l09-b2", "___ je vaak naar musea? (go)", ["Ga", "Ben", "Word"], "Ga"),
                    ro_tokens("m09-l09-r2", ["jij?", "denk", "Wat"], "Wat denk jij?"),
                    mcq(
                        "m09-l09-b3",
                        "Check interesse",
                        ["Vind je dat ook leuk?", "Vind je dat ook verplicht?", "Vind je zonder?"],
                        "Vind je dat ook leuk?",
                    ),
                    mcq(
                        "m09-l09-b4",
                        "Korte samenvatting",
                        ["Dus jij houdt van …, en ik ook een beetje.", "Dus jij houdt van niets.", "Dus jij zonder samenvatting."],
                        "Dus jij houdt van …, en ik ook een beetje.",
                    ),
                    mcq(
                        "m09-l09-b5",
                        "Slot",
                        ["Was leuk om te praten!", "Was saai om te praten altijd.", "Praten was zonder."],
                        "Was leuk om te praten!",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m09-l09-sp1",
                "Jouw beurt",
                "Hoi! Ik ben Lisa. Wat doe jij graag in je vrije tijd?",
                [
                    "Hoi ik ben Lisa wat doe jij graag in je vrije tijd",
                    "Hoi! Ik ben Lisa. Wat doe jij graag in je vrije tijd?",
                ],
                "Hoi ik ben Lisa wat doe jij graag in je vrije tijd",
            ),
            speak_step(
                "m09-l09-sp2",
                "Reactie",
                "Echt? Dat klinkt interessant!",
                ["Echt dat klinkt interessant", "Echt? Dat klinkt interessant!"],
                "Echt dat klinkt interessant",
            ),
            speak_step(
                "m09-l09-sp3",
                "Doorvragen",
                "Waarom vind je dat leuk?",
                ["Waarom vind je dat leuk", "waarom vind je dat leuk"],
                "Waarom vind je dat leuk",
            ),
            speak_step(
                "m09-l09-sp4",
                "Mening + brug",
                "Ik vind dat ook wel leuk. En jij?",
                ["Ik vind dat ook wel leuk en jij", "Ik vind dat ook wel leuk. En jij?"],
                "Ik vind dat ook wel leuk en jij",
            ),
            speak_step(
                "m09-l09-sp5",
                "Afsluiten",
                "Was leuk om te praten! Laten we nog eens afspreken.",
                [
                    "Was leuk om te praten laten we nog eens afspreken",
                    "Was leuk om te praten! Laten we nog eens afspreken.",
                ],
                "Was leuk om te praten laten we nog eens afspreken",
            ),
            recap_step(
                "m09-l09-recap",
                "Recap",
                ["echt", "leuk", "en jij"],
                [
                    rt_fb("___? Wat voor muziek was het? (really)", ["Echt", "Snel", "Stil"], "Echt"),
                    rt_ro(["leuk!", "me", "lijkt", "Dat"], "Dat lijkt me leuk!"),
                    rt_speak("Zeg: *En jij?*", "En jij?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Laten we volgende week appen.",
                        ["Afspraak om te appen", "Stop met praten", "Werkmail"],
                        "Afspraak om te appen",
                    ),
                    rt_fb("Ik ben het ___ met je. (agree)", ["eens", "oneens", "bang"], "eens"),
                    rt_speak("Zeg: *Was leuk om te praten!*", "Was leuk om te praten!"),
                ],
            ),
        ],
    }


def lesson_l10() -> dict:
    lid = "a2-m09-l10-task-social-discussion-simulation"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Real-life task · Social discussion simulation",
        "lessonType": "task",
        "order": 9,
        "cefrLevel": "A2",
        "durationEstimate": 17,
        "grammarTargets": ["a2.3-leisure-opinions", "a2.3-leisure-reactions"],
        "vocabTargets": ["lemma-mening-m9", "lemma-eens-m9", "lemma-oneens-m9", "lemma-misschien-m9", "lemma-film-m9"],
        "canDoStatements": ["I can take part in a short discussion: agree, disagree softly, and ask why."],
        "mistakeFocus": ["opinion-structure", "agree-disagree"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m09-l10-preview",
                "Warm-up — 4 woorden",
                [
                    ("discussie", "discussie", "discussion", "🗣️"),
                    ("eens", "eens", "agree (in agreement)", "✅"),
                    ("oneens", "oneens", "disagree", "↔️"),
                    ("waarom", "waarom", "why", "❓"),
                ],
            ),
            scenario_chat_step(
                "m09-l10-chat",
                "Sim — serie of film?",
                [
                    ("Noa", "Ik vind die nieuwe detective-serie veel te langzaam. Jij?", "I find that new detective series way too slow. You?"),
                    ("Jij (kies)", "Hmm, volgens mij is het juist spannend. Maar ik snap wat je bedoelt.", "Hmm, I think it's actually suspenseful. But I get what you mean."),
                    ("Noa", "Echt? Waarom vind jij het spannend?", "Really? Why do you find it suspenseful?"),
                    ("Jij (kies)", "Omdat je niet weet wie de dader is. En jij, waarom vind jij het saai?", "Because you don't know who the culprit is. And you, why do you find it boring?"),
                    ("Noa", "Te veel dialogen. Ik hou meer van actie.", "Too much dialogue. I prefer action."),
                    ("Jij (kies)", "Snap ik. Misschien is deze serie gewoon niet jouw smaak.", "I get it. Maybe this series just isn't your taste."),
                    ("Noa", "Ja, misschien. Laten we volgende week iets met actie kijken.", "Yeah, maybe. Let's watch something with action next week."),
                ],
                [
                    ("Wat vindt Noa van de serie?", ["Te langzaam", "Perfect", "Te kort"], "Te langzaam"),
                    ("Hoe reageer je eerst?", ["Je geeft tegengas + begrip", "Je schreeuwt", "Je stopt"], "Je geeft tegengas + begrip"),
                    ("Welke vervolgvraag stelt Noa?", ["Waarom vind jij het spannend?", "Waarom ben jij?", "Waarom zonder?"],
                        "Waarom vind jij het spannend?"),
                    ("Welke reden geef jij?", ["Je weet niet wie de dader is", "Je weet alles altijd", "Geen reden"], "Je weet niet wie de dader is"),
                    ("Waarom vindt Noa het saai?", ["Te veel dialogen", "Te weinig eten", "Geen personages"], "Te veel dialogen"),
                    ("Hoe eindigt het?", ["Afspraak: volgende week actie", "Ruzie zonder einde", "Geen plan"], "Afspraak: volgende week actie"),
                ],
            ),
            listening_step(
                "m09-l10-listen",
                "Input — podcast ja of nee?",
                [
                    ("Tim", "Ik luister elke week naar een geschiedenis-podcast. Superleuk!", "I listen to a history podcast every week. Super fun!"),
                    ("Sara", "Ik vind podcasts vaak te lang. Ik lees liever een artikel.", "I often find podcasts too long. I'd rather read an article."),
                    ("Tim", "Oké, maar soms is het handig onderweg, toch?", "Okay, but sometimes it's handy on the go, right?"),
                    ("Sara", "Dat is waar. Misschien probeer ik een korte aflevering.", "That's true. Maybe I'll try a short episode."),
                ],
                [
                    ("Wat doet Tim wekelijks?", ["Naar geschiedenis-podcast luisteren", "Naar metal alleen", "Niets"], "Naar geschiedenis-podcast luisteren"),
                    ("Wat vindt Sara?", ["Podcasts te lang; leest liever", "Podcasts altijd perfect", "Ze leest nooit"], "Podcasts te lang; leest liever"),
                    ("Welk argument geeft Tim?", ["Handig onderweg", "Altijd gratis", "Geen argument"], "Handig onderweg"),
                    ("Hoe reageert Sara op het eind?", ["Ze wil een korte aflevering proberen", "Ze weigert alles", "Ze stopt zonder idee"], "Ze wil een korte aflevering proberen"),
                ],
            ),
            discovery_step(
                "m09-l10-discovery",
                "Zacht oneens",
                [
                    ("Ik snap wat je bedoelt.", "I get what you mean.", "begrip"),
                    ("Volgens mij is het anders.", "In my view it's different.", "tegengas"),
                    ("Misschien is het niet jouw smaak.", "Maybe it's not your taste.", "soft close"),
                    ("Laten we … samen proberen.", "Let's try … together.", "compromis"),
                ],
            ),
            pl(
                "m09-l10-pl1",
                "Practice — 6×",
                ["eens", "oneens", "waarom"],
                [
                    mcq(
                        "m09-l10-a1",
                        "Respectvol",
                        ["Ik ben het niet eens, maar ik begrijp je punt.", "Ik ben het niet eens, dus jij bent dom.", "Oneens ben zonder luisteren."],
                        "Ik ben het niet eens, maar ik begrijp je punt.",
                    ),
                    fb("m09-l10-a2", "___ vind ik dat te duur. (in my opinion)", ["Volgens", "Tegen", "Achter"], "Volgens"),
                    ro_tokens("m09-l10-r1", ["jij?", "vind", "Wat"], "Wat vind jij?"),
                    mcq(
                        "m09-l10-a3",
                        "Doorvragen zonder aanval",
                        ["Waarom denk je dat?", "Waarom ben jij?", "Waarom zonder vraag?"],
                        "Waarom denk je dat?",
                    ),
                    mcq(
                        "m09-l10-a4",
                        "Compromis",
                        ["Laten we een andere optie zoeken.", "Laten we nooit zoeken.", "Optie zonder zoeken."],
                        "Laten we een andere optie zoeken.",
                    ),
                    mcq(
                        "m09-l10-a5",
                        "Bevestiging",
                        ["Dat is waar.", "Dat is onmogelijk altijd.", "Waar dat zonder."],
                        "Dat is waar.",
                    ),
                ],
                depth=True,
            ),
            pl(
                "m09-l10-pl2",
                "Variatie — 6×",
                ["misschien", "maar", "smaak"],
                [
                    mcq(
                        "m09-l10-b1",
                        "Transform: zachter",
                        ["Dit is niks voor mij. → Misschien is dit niet mijn ding.", "Dit is niks voor mij. → Jij bent niks.", "Niks dit zonder."],
                        "Dit is niks voor mij. → Misschien is dit niet mijn ding.",
                    ),
                    fb("m09-l10-b2", "Ik hou ___ van actie dan van lange dialogen. (more)", ["meer", "minder", "veel"], "meer"),
                    ro_tokens("m09-l10-r2", ["eens.", "het", "ben", "Ik", "niet"], "Ik ben het niet eens."),
                    mcq(
                        "m09-l10-b3",
                        "Fout herstellen",
                        ["Ik vind saai → Ik vind het saai.", "Ik vind saai → Ik vind saai het.", "Vind ik saai."],
                        "Ik vind saai → Ik vind het saai.",
                    ),
                    mcq(
                        "m09-l10-b4",
                        "Brug na mening",
                        ["En wat vind jij daarvan?", "En wat eet jij zonder mening?", "Wat en jij zonder?"],
                        "En wat vind jij daarvan?",
                    ),
                    mcq(
                        "m09-l10-b5",
                        "Voorzichtig",
                        ["Misschien heb ik het mis.", "Misschien heb ik altijd gelijk.", "Misschien zonder twijfel."],
                        "Misschien heb ik het mis.",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m09-l10-sp1",
                "Jouw beurt",
                "Ik vind deze film best goed, maar het einde was zwak.",
                [
                    "Ik vind deze film best goed maar het einde was zwak",
                    "Ik vind deze film best goed, maar het einde was zwak.",
                ],
                "Ik vind deze film best goed maar het einde was zwak",
            ),
            speak_step(
                "m09-l10-sp2",
                "Tegengas + begrip",
                "Volgens mij is het juist sterk. Maar ik snap je punt.",
                [
                    "Volgens mij is het juist sterk maar ik snap je punt",
                    "Volgens mij is het juist sterk. Maar ik snap je punt.",
                ],
                "Volgens mij is het juist sterk maar ik snap je punt",
            ),
            speak_step(
                "m09-l10-sp3",
                "Vraag",
                "Waarom vind jij het einde zwak?",
                ["Waarom vind jij het einde zwak", "waarom vind jij het einde zwak"],
                "Waarom vind jij het einde zwak",
            ),
            speak_step(
                "m09-l10-sp4",
                "Eens",
                "Ik ben het daar deels mee eens.",
                ["Ik ben het daar deels mee eens", "ik ben het daar deels mee eens"],
                "Ik ben het daar deels mee eens",
            ),
            speak_step(
                "m09-l10-sp5",
                "Compromis",
                "Misschien kijken we volgende week samen iets anders.",
                [
                    "Misschien kijken we volgende week samen iets anders",
                    "misschien kijken we volgende week samen iets anders",
                ],
                "Misschien kijken we volgende week samen iets anders",
            ),
            speak_step(
                "m09-l10-sp6",
                "Slot",
                "Goed plan. Tot snel!",
                ["Goed plan tot snel", "Goed plan. Tot snel!"],
                "Goed plan tot snel",
            ),
            recap_step(
                "m09-l10-recap",
                "Recap",
                ["mening", "eens", "misschien"],
                [
                    rt_fb("Ik ben het niet ___. (agree: negative)", ["eens", "bang", "moe"], "eens"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Misschien is deze serie gewoon niet jouw smaak.",
                        ["Soft close / smaak", "Belediging", "Werkmail"],
                        "Soft close / smaak",
                    ),
                    rt_ro(["bedoelt.", "snap", "wat", "je", "Ik"], "Ik snap wat je bedoelt."),
                    rt_speak("Zeg: *Waarom denk je dat?*", "Waarom denk je dat?"),
                    rt_fb("___ niet? (really)", ["Echt", "Snel", "Stil"], "Echt"),
                    rt_speak("Zeg: *Dat is waar.*", "Dat is waar."),
                    rt_speak("Zeg: *Laten we volgende week iets met actie kijken.*", "Laten we volgende week iets met actie kijken."),
                ],
            ),
        ],
    }


def lesson_l11() -> dict:
    lid = "a2-m09-l11-review-leisure-conversations"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Review · Leisure & conversations",
        "lessonType": "review",
        "order": 10,
        "cefrLevel": "A2",
        "durationEstimate": 17,
        "grammarTargets": ["a2.3-leisure-opinions", "a2.3-leisure-perfectum-light", "a2.3-leisure-reactions"],
        "vocabTargets": ["lemma-hobby-m9", "lemma-vinden-m9", "lemma-gisteren-m9", "lemma-want-m9", "lemma-echt-m9"],
        "canDoStatements": ["I can mix opinions, past snippets, and reactions from this module in retrieval tasks."],
        "mistakeFocus": ["mixed-retrieval", "connectors"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m09-l11-preview",
                "Warm-up — 5 woorden",
                [
                    ("mix", "mix", "mix", "🎛️"),
                    ("herhaling", "herhaling", "repetition", "🔁"),
                    ("flow", "flow", "flow", "🌊"),
                    ("natuurlijk", "natuurlijk", "natural", "🌿"),
                    ("tempo", "tempo", "pace", "⏱️"),
                ],
            ),
            listening_step(
                "m09-l11-listen",
                "Mix — koffieafspraak",
                [
                    ("Evi", "Gisteren heb ik eindelijk die tent aan het water geprobeerd. Lekker!", "Yesterday I finally tried that place by the water. Nice!"),
                    ("Joep", "Oh leuk! Ik denk dat ik daar ook naartoe wil. Wat at je?", "Oh nice! I think I want to go there too. What did you eat?"),
                    ("Evi", "Vis met groente. Maar het was wel druk. Volgens mij moet je reserveren.", "Fish with veg. But it was busy. I think you have to book."),
                    ("Joep", "Snap ik. Zullen we volgende week samen gaan?", "I get it. Shall we go together next week?"),
                ],
                [
                    ("Wat deed Evi gisteren?", ["Nieuwe tent geprobeerd", "Alleen geslapen", "Naar de maan"], "Nieuwe tent geprobeerd"),
                    ("Hoe reageert Joep?", ["Oh leuk + vervolgvraag", "Boos", "Geen reactie"], "Oh leuk + vervolgvraag"),
                    ("Wat zegt Evi over drukte?", ["Reserveren is slim", "Nooit reserveren", "Drukte zonder tip"], "Reserveren is slim"),
                    ("Wat stelt Joep voor?", ["Volgende week samen", "Nooit meer eten", "Alleen alleen"], "Volgende week samen"),
                ],
            ),
            pl(
                "m09-l11-pl1",
                "Mixed loop — 12×",
                ["mening", "gisteren", "reactie"],
                [
                    mcq("m09-l11-m1", "Hobby", ["Ik hou van zwemmen.", "Ik hou van slapen altijd verplicht.", "Hou ik van zwemmen."], "Ik hou van zwemmen."),
                    fb("m09-l11-m2", "Ik vind dat ___, want het is grappig. (fun)", ["leuk", "saai", "duur"], "leuk"),
                    ro_tokens("m09-l11-m3", ["jij?", "vind", "Wat"], "Wat vind jij?"),
                    mcq("m09-l11-m4", "Mening + denken", ["Ik denk dat dit een goed idee is.", "Ik denk dat zonder idee.", "Denk ik dat goed."], "Ik denk dat dit een goed idee is."),
                    mcq("m09-l11-m5", "Volgens mij", ["Volgens mij is dit te duur.", "Volgens mij ben jij fout altijd.", "Volgens zonder mening."], "Volgens mij is dit te duur."),
                    mcq("m09-l11-m6", "Reactie", ["Echt? Vertel!", "Echt? Stop.", "Echt zonder."], "Echt? Vertel!"),
                    mcq("m09-l11-m7", "Perfectum (kort)", ["Gisteren heb ik gewandeld.", "Gisteren ben ik gewandeld zonder heb.", "Gisteren wandel ik."], "Gisteren heb ik gewandeld."),
                    mcq("m09-l11-m8", "Geweest", ["Ik ben in Rotterdam geweest.", "Ik heb in Rotterdam geweest.", "Ben Rotterdam zonder."], "Ik ben in Rotterdam geweest."),
                    ro_tokens("m09-l11-m9", ["leuk!", "me", "lijkt", "Dat"], "Dat lijkt me leuk!"),
                    mcq("m09-l11-m10", "Eens", ["Ik ben het met je eens.", "Ik ben het met je pizza.", "Eens ben zonder jou."], "Ik ben het met je eens."),
                    mcq("m09-l11-m11", "Want", ["Ik blijf thuis, want ik ben moe.", "Ik blijf thuis, want pizza.", "Thuis blijf want."], "Ik blijf thuis, want ik ben moe."),
                    mcq("m09-l11-m12", "Brug", ["En jij, wat heb jij gedaan?", "En jij, wat heb jij zonder?", "Jij en wat zonder?"], "En jij, wat heb jij gedaan?"),
                ],
                depth=True,
            ),
            pl(
                "m09-l11-pl2",
                "Speaking prep — 6×",
                ["weekend", "vriend", "plan"],
                [
                    mcq("m09-l11-s1", "Uitnodiging", ["Zullen we zaterdag iets doen?", "Zullen we zaterdag niets?", "Zullen zaterdag zonder?"], "Zullen we zaterdag iets doen?"),
                    fb("m09-l11-s2", "Het was ___, maar ik was moe. (fun)", ["leuk", "saai", "dicht"], "leuk"),
                    ro_tokens("m09-l11-s3", ["jij?", "Waarom", "vind", "je", "dat"], "Waarom vind je dat?"),
                    mcq("m09-l11-s4", "Natuurlijk slot", ["Groetjes, tot snel!", "Groetjes, nooit meer!", "Groetjes zonder."], "Groetjes, tot snel!"),
                    mcq("m09-l11-s5", "Hypothese voorzichtig", ["Misschien vind ik het later leuker.", "Misschien vind ik alles fout.", "Misschien zonder."], "Misschien vind ik het later leuker."),
                    mcq("m09-l11-s6", "Samenvatting", ["Dus jij houdt van live muziek, en ik soms ook.", "Dus jij houdt van niets.", "Dus jij zonder."], "Dus jij houdt van live muziek, en ik soms ook."),
                ],
                depth=True,
            ),
            speak_step(
                "m09-l11-sp1",
                "Output — mix",
                "Ik hou van koken. Gisteren heb ik pasta gemaakt. Wat vind jij van koken?",
                [
                    "Ik hou van koken gisteren heb ik pasta gemaakt wat vind jij van koken",
                    "Ik hou van koken. Gisteren heb ik pasta gemaakt. Wat vind jij van koken?",
                ],
                "Ik hou van koken gisteren heb ik pasta gemaakt wat vind jij van koken",
            ),
            speak_step(
                "m09-l11-sp2",
                "Output — reactie",
                "Echt? Dat lijkt me leuk! Waarom doe je dat graag?",
                [
                    "Echt dat lijkt me leuk waarom doe je dat graag",
                    "Echt? Dat lijkt me leuk! Waarom doe je dat graag?",
                ],
                "Echt dat lijkt me leuk waarom doe je dat graag",
            ),
            speak_step(
                "m09-l11-sp3",
                "Output — oneens + soft",
                "Ik ben het niet helemaal eens, maar ik snap je wel.",
                [
                    "Ik ben het niet helemaal eens maar ik snap je wel",
                    "Ik ben het niet helemaal eens, maar ik snap je wel.",
                ],
                "Ik ben het niet helemaal eens maar ik snap je wel",
            ),
            speak_step(
                "m09-l11-sp4",
                "Output — weekend",
                "In het weekend ga ik graag naar buiten. Zullen we een keer samen wandelen?",
                [
                    "In het weekend ga ik graag naar buiten zullen we een keer samen wandelen",
                    "In het weekend ga ik graag naar buiten. Zullen we een keer samen wandelen?",
                ],
                "In het weekend ga ik graag naar buiten zullen we een keer samen wandelen",
            ),
            recap_step(
                "m09-l11-recap",
                "Recap — lang",
                ["leisure", "gesprek", "brug"],
                [
                    rt_fb("Ik ___ van fietsen in de stad. (love)", ["hou", "ben", "doe"], "hou"),
                    rt_ro(["gekeken.", "heb", "Ik", "een", "film"], "Ik heb een film gekeken."),
                    rt_speak("Zeg: *Volgens mij is dat leuk.*", "Volgens mij is dat leuk."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Zullen we volgende week samen gaan?",
                        ["Plan maken", "Stoppen", "Klacht"],
                        "Plan maken",
                    ),
                    rt_fb("___ je dat ook ontspannend? (find)", ["Vind", "Eet", "Zwem"], "Vind"),
                    rt_speak("Zeg: *Dat vind ik ook.*", "Dat vind ik ook."),
                    rt_ro(["praten!", "leuk", "om", "te", "Was"], "Was leuk om te praten!"),
                    rt_speak("Zeg: *Misschien een andere keer.*", "Misschien een andere keer."),
                    rt_speak("Zeg: *Groetjes!*", "Groetjes!"),
                ],
            ),
        ],
    }
