from .common import (
    LM,
    MID,
    discovery_step,
    fb,
    grammar_card,
    listen_read_step,
    listening_step,
    match_ex,
    mcq,
    pl,
    preview_step,
    recap_step,
    ro_tokens,
    rt_fb,
    rt_listen_mcq,
    rt_ro,
    rt_speak,
    speak_step,
)


def lesson_l01() -> dict:
    lid = "a2-m09-l01-listening-hobbies-catch-gist"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Listening · Talking about hobbies · catch the gist",
        "lessonType": "input",
        "order": 0,
        "cefrLevel": "A2",
        "durationEstimate": 16,
        "grammarTargets": ["a2.3-leisure-hobbies", "a2.3-leisure-conversation-flow"],
        "vocabTargets": ["lemma-hobby-m9", "lemma-vrije-tijd", "lemma-weekend-m9", "lemma-sport-m9", "lemma-muziek-m9"],
        "canDoStatements": ["I can follow friends talking about hobbies and pick out what they like and how often they do it."],
        "mistakeFocus": ["listening-gist", "vocab"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m09-l01-preview",
                "Warm-up — 5 woorden",
                [
                    ("hobby", "hobby", "hobby", "🎯"),
                    ("vrije tijd", "tijd", "free time", "⏰"),
                    ("weekend", "weekend", "weekend", "🗓️"),
                    ("sport", "sport", "sport", "⚽"),
                    ("muziek", "muziek", "music", "🎵"),
                ],
            ),
            listening_step(
                "m09-l01-listen",
                "Input — koffie met vrienden",
                [
                    ("Nina", "Hé Tom, wat doe jij graag in je vrije tijd?", "Hey Tom, what do you like to do in your free time?"),
                    ("Tom", "Ik hou van voetbal kijken en af en toe zelf spelen. En jij?", "I love watching football and sometimes playing myself. And you?"),
                    ("Nina", "Ik ga graag naar concerten. Soms ook naar een museum.", "I like going to concerts. Sometimes to a museum too."),
                    ("Tom", "Echt? Wat voor muziek luister je?", "Really? What kind of music do you listen to?"),
                    ("Nina", "Meestal indie en wat jazz. Niks te luid.", "Mostly indie and some jazz. Nothing too loud."),
                ],
                [
                    ("Wat houdt Tom van?", ["Voetbal kijken en spelen", "Alleen slapen", "Alleen werken"], "Voetbal kijken en spelen"),
                    ("Waar gaat Nina graag naartoe?", ["Concerten en soms museum", "Alleen naar de supermarkt", "Nergens"], "Concerten en soms museum"),
                    ("Hoe reageert Tom op Nina’s hobby?", ["Hij vraagt door over muziek", "Hij stopt het gesprek", "Hij wordt boos"], "Hij vraagt door over muziek"),
                    ("Welke stijl noemt Nina?", ["Indie en jazz", "Alleen klassiek zonder uitleg", "Geen muziek"], "Indie en jazz"),
                    ("Waar gaat dit gesprek over?", ["Hobby’s en interesses", "Alleen het weer", "Politiek diepgaand"], "Hobby’s en interesses"),
                ],
            ),
            discovery_step(
                "m09-l01-discovery",
                "Zinnen om te herkennen",
                [
                    ("Ik hou van …", "I love … (strong like)", "hobby"),
                    ("Ik ga graag …", "I like going …", "activiteit"),
                    ("Wat doe jij graag …?", "What do you like to do …?", "vraag"),
                    ("En jij?", "And you?", "teruggeven"),
                ],
            ),
            pl(
                "m09-l01-pl1",
                "Practice — 6×",
                ["hobby", "weekend", "gratis"],
                [
                    mcq(
                        "m09-l01-a1",
                        "Natuurlijke openingsvraag",
                        ["Wat doe jij graag in het weekend?", "Wat moet jij in het weekend?", "Weekend jij wat doet?"],
                        "Wat doe jij graag in het weekend?",
                    ),
                    fb("m09-l01-a2", "Ik ___ van lezen. (love)", ["hou", "eet", "zwem"], "hou"),
                    ro_tokens("m09-l01-r1", ["zaterdag?", "op", "graag", "je", "doe", "Wat"], "Wat doe je graag op zaterdag?"),
                    mcq(
                        "m09-l01-a3",
                        "‘Af en toe’ betekent ongeveer",
                        ["Soms / niet elke dag", "Elke minuut", "Nooit"],
                        "Soms / niet elke dag",
                    ),
                    mcq(
                        "m09-l01-a4",
                        "Doorgaan met praten",
                        ["En jij? Doe jij ook aan sport?", "En jij? Zwijg nu.", "Jij en zonder vraag?"],
                        "En jij? Doe jij ook aan sport?",
                    ),
                    mcq(
                        "m09-l01-a5",
                        "Meestal =",
                        ["Vaak / normaal gesproken", "Nooit", "Alleen op maandag om 3 uur ’s nachts"],
                        "Vaak / normaal gesproken",
                    ),
                ],
            ),
            pl(
                "m09-l01-pl2",
                "Variatie — 6×",
                ["museum", "concert", "luisteren"],
                [
                    mcq(
                        "m09-l01-b1",
                        "Keuze: hobby klinkt positief",
                        ["Ik vind schilderen heel ontspannend.", "Ik vind schilderen altijd verplicht en stom.", "Schilderen vind ik zonder mening."],
                        "Ik vind schilderen heel ontspannend.",
                    ),
                    fb("m09-l01-b2", "Ik ga graag naar een ___. (live music)", ["concert", "broodje", "station"], "concert"),
                    ro_tokens("m09-l01-r2", ["spelen.", "Ik", "gitaar", "graag"], "Ik speel graag gitaar."),
                    mcq(
                        "m09-l01-b3",
                        "Zelfde idee, andere woorden",
                        ["Ik ga drie keer per week sporten. ≈ Ik sport vaak.", "Ik sport nooit. ≈ Ik sport elke minuut.", "Sport ik week zonder."],
                        "Ik ga drie keer per week sporten. ≈ Ik sport vaak.",
                    ),
                    mcq(
                        "m09-l01-b4",
                        "Als iemand iets leuk vindt",
                        ["Oh leuk! Vertel eens.", "Oh leuk! Zwijg voortaan.", "Leuk oh zonder interesse."],
                        "Oh leuk! Vertel eens.",
                    ),
                    mcq(
                        "m09-l01-b5",
                        "Niks te luid betekent hier",
                        ["Liever rustige muziek", "Altijd harde metal alleen", "Geen geluid betekent luid"],
                        "Liever rustige muziek",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m09-l01-sp1",
                "Jouw beurt",
                "Ik hou van lezen en koken.",
                ["Ik hou van lezen en koken", "ik hou van lezen en koken"],
                "Ik hou van lezen en koken",
            ),
            speak_step(
                "m09-l01-sp2",
                "Vervolg",
                "In het weekend ga ik graag naar de markt.",
                ["In het weekend ga ik graag naar de markt", "in het weekend ga ik graag naar de markt"],
                "In het weekend ga ik graag naar de markt",
            ),
            speak_step(
                "m09-l01-sp3",
                "Vraag",
                "Wat doe jij graag in je vrije tijd?",
                ["Wat doe jij graag in je vrije tijd", "wat doe jij graag in je vrije tijd"],
                "Wat doe jij graag in je vrije tijd",
            ),
            speak_step(
                "m09-l01-sp4",
                "Reactie",
                "Echt? Dat klinkt leuk!",
                ["Echt dat klinkt leuk", "Echt? Dat klinkt leuk!"],
                "Echt dat klinkt leuk",
            ),
            recap_step(
                "m09-l01-recap",
                "Recap",
                ["hobby", "weekend", "concert"],
                [
                    rt_fb("Ik ___ van yoga. (love)", ["hou", "ben", "doe"], "hou"),
                    rt_ro(["naar", "Ik", "graag", "museum.", "een", "ga"], "Ik ga graag naar een museum."),
                    rt_speak("Zeg: *En jij?*", "En jij?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Ik ga graag naar concerten.",
                        ["Hobby / uitgaan", "Alleen slapen", "Werken zonder hobby"],
                        "Hobby / uitgaan",
                    ),
                    rt_fb("___ voor muziek luister je graag? (what kind)", ["Wat", "Waar", "Wie"], "Wat"),
                    rt_speak("Zeg: *Ik speel graag …*", "Ik speel graag piano."),
                ],
            ),
            speak_step(
                "m09-l01-sp5",
                "Bal terug",
                "En jij? Wat doe jij het liefst in het weekend?",
                [
                    "En jij wat doe jij het liefst in het weekend",
                    "En jij? Wat doe jij het liefst in het weekend?",
                ],
                "En jij wat doe jij het liefst in het weekend",
            ),
        ],
    }


def lesson_l02() -> dict:
    lid = "a2-m09-l02-listen-read-interests-preferences"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Listening & reading · Interests and preferences",
        "lessonType": "input",
        "order": 1,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.3-leisure-hobbies", "a2.3-leisure-opinions"],
        "vocabTargets": ["lemma-film-m9", "lemma-boek-m9", "lemma-leuk-m9", "lemma-saai-m9", "lemma-vriend-m9"],
        "canDoStatements": ["I can read a short chat about films and books and say who likes what."],
        "mistakeFocus": ["instruction-meaning", "opinion-words"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m09-l02-preview",
                "Warm-up — 5 woorden",
                [
                    ("film", "film", "film", "🎬"),
                    ("boek", "boek", "book", "📚"),
                    ("leuk", "leuk", "nice / fun", "😊"),
                    ("saai", "saai", "boring", "😴"),
                    ("serie", "serie", "series", "📺"),
                ],
            ),
            listen_read_step(
                "m09-l02-lr",
                "Input — app-gesprek",
                [
                    ("Lisa", "Hebben jullie die nieuwe serie op StreamNL gezien? Ik vind hem superleuk.", "Have you guys seen that new series on StreamNL? I think it's great."),
                    ("Youri", "Nog niet! Is het spannend of meer komedie?", "Not yet! Is it suspenseful or more comedy?"),
                    ("Lisa", "Beetje van beide. Maar sommige afleveringen zijn een beetje saai, vind ik.", "A bit of both. But some episodes are a bit boring, I think."),
                    ("Mila", "Ik lees liever een boek. Ik hou niet zo van lange series.", "I'd rather read a book. I don't really like long series."),
                    ("Youri", "Snap ik. Wat lees jij nu?", "I get it. What are you reading now?"),
                ],
                [
                    ("Wat vindt Lisa van de serie?", ["Superleuk, met een beetje saai soms", "Helemaal saai", "Ze kijkt nooit tv"], "Superleuk, met een beetje saai soms"),
                    ("Wat wil Youri weten?", ["Of het spannend of komisch is", "Hoeveel de popcorn kost", "Waar Lisa woont"], "Of het spannend of komisch is"),
                    ("Wat doet Mila liever?", ["Een boek lezen", "Marathon hardlopen zonder boek", "Niets lezen"], "Een boek lezen"),
                    ("Hoe reageert Youri op Mila?", ["Hij stelt een vervolgvraag", "Hij lacht haar uit", "Hij stopt de chat"], "Hij stelt een vervolgvraag"),
                    ("Waar gaat de chat over?", ["Series, boeken, smaak", "Alleen werk", "Alleen eten"], "Series, boeken, smaak"),
                ],
            ),
            discovery_step(
                "m09-l02-discovery",
                "Handige brokken",
                [
                    ("Ik vind … leuk / saai.", "I find … fun / boring.", "mening"),
                    ("Ik lees liever …", "I'd rather read …", "voorkeur"),
                    ("Snap ik.", "I get it.", "reactie"),
                    ("Nog niet!", "Not yet!", "status"),
                ],
            ),
            pl(
                "m09-l02-pl1",
                "Practice — 6×",
                ["film", "boek", "serie"],
                [
                    mcq(
                        "m09-l02-p1",
                        "Mening over film",
                        ["Ik vind die film interessant.", "Ik vind die film zonder mening.", "Vind ik film die interessant."],
                        "Ik vind die film interessant.",
                    ),
                    fb("m09-l02-p2", "Ik kijk niet graag naar horror, ___ ik bang ben. (because)", ["want", "maar", "dus"], "want"),
                    ro_tokens("m09-l02-r1", ["jij?", "vind", "Wat"], "Wat vind jij?"),
                    mcq(
                        "m09-l02-p3",
                        "Liever =",
                        ["Ik heb liever A dan B", "Ik wil nooit kiezen", "Liever zonder voorkeur"],
                        "Ik heb liever A dan B",
                    ),
                    mcq(
                        "m09-l02-p4",
                        "Beetje van beide",
                        ["Een mix van twee dingen", "Geen van beide", "Alleen het einde"],
                        "Een mix van twee dingen",
                    ),
                    mcq(
                        "m09-l02-p5",
                        "Natuurlijke reactie",
                        ["Oh ja? Vertel!", "Oh ja? Stop.", "Ja oh zonder luisteren."],
                        "Oh ja? Vertel!",
                    ),
                ],
            ),
            pl(
                "m09-l02-pl2",
                "Variatie — 6×",
                ["saai", "leuk", "kijken"],
                [
                    mcq(
                        "m09-l02-q1",
                        "Zin transformeren (stijl)",
                        ["Dat is niet mijn ding. ≈ Dat vind ik niet zo leuk.", "Dat is niet mijn ding. ≈ Ik vind het perfect.", "Ding mijn dat niet is."],
                        "Dat is niet mijn ding. ≈ Dat vind ik niet zo leuk.",
                    ),
                    fb("m09-l02-q2", "Sommige afleveringen zijn een beetje ___. (boring)", ["saai", "leuk", "duur"], "saai"),
                    ro_tokens("m09-l02-r2", ["boek.", "een", "Ik", "lees", "graag"], "Ik lees graag een boek."),
                    match_ex(
                        "m09-l02-m1",
                        "Match",
                        [("leuk", "fun"), ("saai", "boring"), ("interessant", "interesting")],
                        {"leuk": "fun", "saai": "boring", "interessant": "interesting"},
                    ),
                    mcq(
                        "m09-l02-q3",
                        "Als je het niet eens bent (vriendelijk)",
                        ["Ik zie het anders, maar dat mag.", "Jij bent fout, punt.", "Anders zie ik zonder respect."],
                        "Ik zie het anders, maar dat mag.",
                    ),
                    mcq(
                        "m09-l02-q4",
                        "Vervolgvraag",
                        ["Welke film raad je aan?", "Welke film eet je op?", "Film welke raad je?"],
                        "Welke film raad je aan?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m09-l02-sp1",
                "Jouw beurt",
                "Ik vind die serie erg leuk.",
                ["Ik vind die serie erg leuk", "ik vind die serie erg leuk"],
                "Ik vind die serie erg leuk",
            ),
            speak_step(
                "m09-l02-sp2",
                "Voorkeur",
                "Ik lees liever een boek dan een lange serie.",
                [
                    "Ik lees liever een boek dan een lange serie",
                    "ik lees liever een boek dan een lange serie",
                ],
                "Ik lees liever een boek dan een lange serie",
            ),
            speak_step(
                "m09-l02-sp3",
                "Mening + reden",
                "Ik vind documentaires interessant, want ik leer iets.",
                [
                    "Ik vind documentaires interessant want ik leer iets",
                    "Ik vind documentaires interessant, want ik leer iets.",
                ],
                "Ik vind documentaires interessant want ik leer iets",
            ),
            speak_step(
                "m09-l02-sp4",
                "Reactie + doorvraag",
                "Snap ik. En wat kijk jij nog zoal?",
                ["Snap ik en wat kijk jij nog zoal", "Snap ik. En wat kijk jij nog zoal?"],
                "Snap ik en wat kijk jij nog zoal",
            ),
            recap_step(
                "m09-l02-recap",
                "Recap",
                ["serie", "boek", "mening"],
                [
                    rt_fb("Ik ___ die film saai. (find)", ["vind", "ben", "doe"], "vind"),
                    rt_speak("Zeg: *Wat vind jij?*", "Wat vind jij?"),
                    rt_listen_mcq(
                        "Snippet:",
                        "Ik hou niet zo van lange series.",
                        ["Geen zin in lange series", "Houdt van alle series", "Series zonder mening"],
                        "Geen zin in lange series",
                    ),
                    rt_ro(["leuk!", "Oh", "serie", "die", "vind", "Ik"], "Oh, ik vind die serie leuk!"),
                    rt_fb("Ik lees ___ een thriller. (rather)", ["liever", "nooit", "altijd"], "liever"),
                    rt_speak("Zeg: *Nog niet!*", "Nog niet!"),
                ],
            ),
        ],
    }


def lesson_l03() -> dict:
    lid = "a2-m09-l03-grammar-opinions-ik-vind-ik-denk"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Grammar & patterns · Expressing opinions (ik vind / ik denk)",
        "lessonType": "pattern",
        "order": 2,
        "cefrLevel": "A2",
        "durationEstimate": 15,
        "grammarTargets": ["a2.3-leisure-opinions", "a2.3-leisure-connectors"],
        "vocabTargets": ["lemma-vinden-m9", "lemma-denken-m9", "lemma-volgens-mij-m9", "lemma-mening-m9", "lemma-want-m9"],
        "canDoStatements": ["I can form short opinion sentences with ik vind, ik denk dat, and volgens mij."],
        "mistakeFocus": ["opinion-structure", "word-order"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m09-l03-preview",
                "Warm-up — 4 woorden",
                [
                    ("vinden", "vinden", "to think/find", "💭"),
                    ("denken", "denken", "to think", "🧠"),
                    ("volgens mij", "volgens mij", "in my opinion", "🗣️"),
                    ("mening", "mening", "opinion", "💬"),
                ],
            ),
            grammar_card(
                "m09-l03-gc",
                "Patroon",
                "Meningszinnetjes",
                "**Ik vind** + naam/het + **leuk/saai/mooi**. **Ik denk dat** + zin. **Volgens mij** + korte zin. Geen lange uitleg nodig — één idee is genoeg.",
                [
                    ("Ik vind koken relaxed.", "I find cooking relaxing."),
                    ("Ik denk dat dit festival druk is.", "I think this festival is busy."),
                    ("Volgens mij is dat te duur.", "In my opinion that's too expensive."),
                ],
            ),
            listening_step(
                "m09-l03-listen",
                "Input — terras",
                [
                    ("Sam", "Vind jij dat nieuwe museum de moeite waard?", "Do you think that new museum is worth it?"),
                    ("Jij", "Volgens mij wel. Ik denk dat de tentoonstelling erg mooi is.", "I think so. I think the exhibition is really beautiful."),
                    ("Sam", "Ik vind het prijsje hoog, maar misschien is het normaal in de stad.", "I find the price high, but maybe it's normal in the city."),
                    ("Jij", "Snap ik. Ik ga graag, want ik hou van moderne kunst.", "I get it. I like going because I love modern art."),
                ],
                [
                    ("Wat zegt de tweede spreker over het museum?", ["Volgens haar is het de moeite waard", "Ze vindt het altijd saai", "Ze wil nooit naar buiten"], "Volgens haar is het de moeite waard"),
                    ("Wat vindt Sam van de prijs?", ["Hoog, maar misschien normaal", "Altijd gratis", "Hij noemt geen prijs"], "Hoog, maar misschien normaal"),
                    ("Waarom gaat de ander graag?", ["Want ze houdt van moderne kunst", "Want ze haat kunst", "Zonder reden"], "Want ze houdt van moderne kunst"),
                    ("Welke mening-hulpwoord hoor je?", ["Volgens mij / ik denk dat / ik vind", "Alleen formele brieven", "Geen meningen"],
                        "Volgens mij / ik denk dat / ik vind"),
                    ("Wat vraagt Sam eerst?", ["Of het museum de moeite waard is", "Of er pizza is", "Naar de wc"], "Of het museum de moeite waard is"),
                ],
            ),
            discovery_step(
                "m09-l03-discovery",
                "Let op",
                [
                    ("Ik vind het …", "I find it …", "vinden"),
                    ("Ik denk dat …", "I think that …", "denken"),
                    ("Volgens mij …", "In my opinion …", "soft claim"),
                    ("Misschien …", "Maybe …", "voorzichtig"),
                ],
            ),
            pl(
                "m09-l03-pl1",
                "Practice — 6×",
                ["vinden", "denken", "volgens"],
                [
                    mcq(
                        "m09-l03-a1",
                        "Juiste structuur",
                        ["Ik vind voetbal spannend.", "Ik vind spannend voetbal zonder het.", "Vind ik voetbal spannend altijd."],
                        "Ik vind voetbal spannend.",
                    ),
                    fb("m09-l03-a2", "Ik denk ___ het leuk wordt. (that)", ["dat", "want", "maar"], "dat"),
                    ro_tokens("m09-l03-r1", ["mooi.", "is", "Volgens", "deze", "mij", "film"], "Volgens mij is deze film mooi."),
                    mcq(
                        "m09-l03-a3",
                        "Zachter formuleren",
                        ["Misschien vind ik comedy niet zo grappig.", "Jij bent dom met comedy.", "Comedy is fout voor iedereen."],
                        "Misschien vind ik comedy niet zo grappig.",
                    ),
                    mcq(
                        "m09-l03-a4",
                        "ik denk dat + werkwoord",
                        ["Ik denk dat hij gelijk heeft.", "Ik denk dat gelijk hij heeft zonder dat.", "Denk ik dat hij."],
                        "Ik denk dat hij gelijk heeft.",
                    ),
                    mcq(
                        "m09-l03-a5",
                        "Mooi waard =",
                        ["Het loont om te gaan", "Je moet betalen dubbel", "Nooit de moeite"],
                        "Het loont om te gaan",
                    ),
                ],
            ),
            pl(
                "m09-l03-pl2",
                "Variatie — 6×",
                ["mening", "maar", "want"],
                [
                    mcq(
                        "m09-l03-b1",
                        "Tegenstelling",
                        ["Ik vind het druk, maar gezellig.", "Ik vind het druk, en daarom haat ik mensen altijd.", "Druk vind ik maar zonder."],
                        "Ik vind het druk, maar gezellig.",
                    ),
                    fb("m09-l03-b2", "___ mij is dit te duur. (in my opinion)", ["Volgens", "Tegen", "Achter"], "Volgens"),
                    ro_tokens("m09-l03-r2", ["leuk.", "Ik", "vind", "wandelen", "heel"], "Ik vind wandelen heel leuk."),
                    mcq(
                        "m09-l03-b3",
                        "Transform: formeel → vriendelijk informeel",
                        ["Het is mijn inschatting dat … → Ik denk dat …", "Het is mijn inschatting dat … → Jij bent fout", "Inschatting zonder zin."],
                        "Het is mijn inschatting dat … → Ik denk dat …",
                    ),
                    mcq(
                        "m09-l03-b4",
                        "Reden toevoegen",
                        ["Ik vind yoga fijn, want ik ontspan.", "Ik vind yoga fijn, want pizza.", "Yoga vind fijn want."],
                        "Ik vind yoga fijn, want ik ontspan.",
                    ),
                    mcq(
                        "m09-l03-b5",
                        "Vraag naar mening",
                        ["Wat vind jij van dit restaurant?", "Wat vind jij van de lucht?", "Vind wat jij van?"],
                        "Wat vind jij van dit restaurant?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m09-l03-sp1",
                "Production",
                "Ik vind live muziek het leukst.",
                ["Ik vind live muziek het leukst", "ik vind live muziek het leukst"],
                "Ik vind live muziek het leukst",
            ),
            speak_step(
                "m09-l03-sp2",
                "Production",
                "Ik denk dat dit concert uitverkocht is.",
                [
                    "Ik denk dat dit concert uitverkocht is",
                    "ik denk dat dit concert uitverkocht is",
                ],
                "Ik denk dat dit concert uitverkocht is",
            ),
            speak_step(
                "m09-l03-sp3",
                "Production",
                "Volgens mij is wandelen gratis en gezond.",
                [
                    "Volgens mij is wandelen gratis en gezond",
                    "volgens mij is wandelen gratis en gezond",
                ],
                "Volgens mij is wandelen gratis en gezond",
            ),
            speak_step(
                "m09-l03-sp4",
                "Production",
                "Misschien vind ik dat later anders.",
                [
                    "Misschien vind ik dat later anders",
                    "misschien vind ik dat later anders",
                ],
                "Misschien vind ik dat later anders",
            ),
            speak_step(
                "m09-l03-sp5",
                "Production",
                "Wat vind jij van dit idee?",
                ["Wat vind jij van dit idee", "wat vind jij van dit idee"],
                "Wat vind jij van dit idee",
            ),
            recap_step(
                "m09-l03-recap",
                "Recap",
                ["vinden", "denken", "volgens mij"],
                [
                    rt_fb("Ik ___ dat het regent. (think)", ["denk", "vind", "hou"], "denk"),
                    rt_ro(["leuk!", "vind", "Ik", "dat", "heel"], "Ik vind dat heel leuk!"),
                    rt_speak("Zeg: *Volgens mij klopt dat.*", "Volgens mij klopt dat."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Ik vind het prijsje hoog.",
                        ["Mening over prijs", "Mening over weer", "Geen mening"],
                        "Mening over prijs",
                    ),
                    rt_fb("___ vind ik dit te druk. (maybe)", ["Misschien", "Altijd", "Nooit"], "Misschien"),
                    rt_speak("Zeg: *Wat vind jij?*", "Wat vind jij?"),
                ],
            ),
        ],
    }


def lesson_l04() -> dict:
    lid = "a2-m09-l04-practice-likes-dislikes-reasons"
    return {
        "id": lid,
        "moduleId": MID,
        "title": "Controlled practice · Likes, dislikes, and reasons",
        "lessonType": "practice",
        "order": 3,
        "cefrLevel": "A2",
        "durationEstimate": 16,
        "grammarTargets": ["a2.3-leisure-opinions", "a2.3-leisure-connectors"],
        "vocabTargets": ["lemma-leuk-m9", "lemma-saai-m9", "lemma-interessant-m9", "lemma-want-m9", "lemma-omdat-m9"],
        "canDoStatements": ["I can say what I like or dislike and add a simple want/omdat reason."],
        "mistakeFocus": ["linking", "opinion-vocab"],
        "metadata": LM,
        "steps": [
            preview_step(
                "m09-l04-preview",
                "Warm-up — 5 woorden",
                [
                    ("leuk", "leuk", "fun", "🙂"),
                    ("saai", "saai", "boring", "😐"),
                    ("want", "want", "because", "🔗"),
                    ("omdat", "omdat", "because", "🔗"),
                    ("maar", "maar", "but", "↩️"),
                ],
            ),
            listening_step(
                "m09-l04-listen",
                "Input — korte meningen",
                [
                    ("Emma", "Ik vind boardgames leuk, want je praat samen.", "I like board games because you talk together."),
                    ("Noah", "Ik vind ze soms saai, omdat ik liever buiten ben.", "I sometimes find them boring, because I'd rather be outside."),
                    ("Emma", "Oh ja? Wat doe je dan graag buiten?", "Oh yeah? What do you like to do outside then?"),
                    ("Noah", "Vaak fietsen. En jij? Blijf je binnen?", "Often cycling. And you? Do you stay indoors?"),
                    ("Emma", "Soms wel, maar in de zomer ga ik graag picknicken.", "Sometimes yes, but in summer I like to go picnicking."),
                ],
                [
                    ("Waarom vindt Emma boardgames leuk?", ["Want je praat samen", "Want ze zijn altijd gratis", "Zonder reden"], "Want je praat samen"),
                    ("Hoe voelt Noah zich soms over boardgames?", ["Soms saai", "Altijd perfect", "Nooit"], "Soms saai"),
                    ("Wat doet Noah graag buiten?", ["Fietsen", "Alleen gamen", "Zwemmen in de woonkamer"], "Fietsen"),
                    ("Wat doet Emma in de zomer?", ["Picknicken", "Alleen slapen", "Niet naar buiten"], "Picknicken"),
                    ("Welke woorden verbinden oorzaak?", ["Want / omdat", "Alleen hallo", "En / maar alleen"], "Want / omdat"),
                ],
            ),
            discovery_step(
                "m09-l04-discovery",
                "Koppelwoordjes",
                [
                    ("…, want …", "…, because … (two main clauses)", "want"),
                    ("…, omdat ik …", "…, because I …", "omdat"),
                    ("…, maar …", "…, but …", "tegenstelling"),
                    ("Soms …, vaak …", "Sometimes …, often …", "frequentie"),
                ],
            ),
            pl(
                "m09-l04-pl1",
                "Practice — 6×",
                ["leuk", "saai", "want"],
                [
                    mcq(
                        "m09-l04-a1",
                        "Natuurlijke mening",
                        ["Ik vind karaoke grappig, maar ik zing niet graag.", "Ik vind karaoke grappig, dus ik zwijg voor altijd.", "Karaoke vind grappig maar."],
                        "Ik vind karaoke grappig, maar ik zing niet graag.",
                    ),
                    fb("m09-l04-a2", "Ik blijf thuis, ___ ik moe ben. (because)", ["want", "en", "dus"], "want"),
                    ro_tokens("m09-l04-r1", ["leuk.", "vind", "Ik", "dat", "niet"], "Ik vind dat niet leuk."),
                    mcq(
                        "m09-l04-a3",
                        "Omdat: typische fout",
                        ["Ik blijf binnen, omdat het regent.", "Ik blijf binnen omdat regent het.", "Binnen blijf omdat."],
                        "Ik blijf binnen, omdat het regent.",
                    ),
                    mcq(
                        "m09-l04-a4",
                        "Eens / oneens (vriendelijk)",
                        ["Ik ben het eens, maar ik snap jouw punt ook.", "Ik ben het oneens, dus jij bent slecht.", "Eens ben ik zonder luisteren."],
                        "Ik ben het eens, maar ik snap jouw punt ook.",
                    ),
                    mcq(
                        "m09-l04-a5",
                        "Frequentie",
                        ["Ik ga vaak naar de sportschool.", "Ik ga nooit vaak altijd tegelijk.", "Vaak ga ik zonder sport."],
                        "Ik ga vaak naar de sportschool.",
                    ),
                    mcq(
                        "m09-l04-a6",
                        "Dat lijkt me …",
                        ["Dat lijkt me leuk!", "Dat lijkt me zonder mening.", "Lijkt dat me zonder."],
                        "Dat lijkt me leuk!",
                    ),
                ],
            ),
            pl(
                "m09-l04-pl2",
                "Variatie — 6×",
                ["omdat", "maar", "misschien"],
                [
                    mcq(
                        "m09-l04-b1",
                        "Transform: korter",
                        ["Ik vind films te lang → Ik vind ze soms te lang.", "Ik vind films te lang → Ik haat alle mensen.", "Films vind te lang."],
                        "Ik vind films te lang → Ik vind ze soms te lang.",
                    ),
                    fb("m09-l04-b2", "Ik ga mee, ___ ik zin heb. (because)", ["want", "maar", "of"], "want"),
                    ro_tokens("m09-l04-r2", ["niet", "Ik", "ben", "eens", "het", "met", "je."], "Ik ben het niet eens met je."),
                    match_ex(
                        "m09-l04-m1",
                        "Match",
                        [("Ik ben het eens", "I agree"), ("Ik ben het niet eens", "I disagree"), ("Misschien", "maybe")],
                        {"Ik ben het eens": "I agree", "Ik ben het niet eens": "I disagree", "Misschien": "maybe"},
                    ),
                    mcq(
                        "m09-l04-b3",
                        "Waarom-vraag",
                        ["Waarom vind je dat?", "Waarom ben jij?", "Waarom zonder vraag?"],
                        "Waarom vind je dat?",
                    ),
                    mcq(
                        "m09-l04-b4",
                        "Reactie + doorvragen",
                        ["Echt? Hoe vaak doe je dat?", "Echt? Stop met praten.", "Echt zonder vervolg."],
                        "Echt? Hoe vaak doe je dat?",
                    ),
                ],
                depth=True,
            ),
            speak_step(
                "m09-l04-sp1",
                "Jouw beurt",
                "Ik vind koken leuk, want ik vind smaken interessant.",
                [
                    "Ik vind koken leuk want ik vind smaken interessant",
                    "Ik vind koken leuk, want ik vind smaken interessant.",
                ],
                "Ik vind koken leuk want ik vind smaken interessant",
            ),
            speak_step(
                "m09-l04-sp2",
                "Tegenstelling",
                "Ik vind festivals leuk, maar ik hou niet van drukte.",
                [
                    "Ik vind festivals leuk maar ik hou niet van drukte",
                    "Ik vind festivals leuk, maar ik hou niet van drukte.",
                ],
                "Ik vind festivals leuk maar ik hou niet van drukte",
            ),
            speak_step(
                "m09-l04-sp3",
                "Oneens",
                "Ik ben het niet eens, maar dat geeft niet.",
                [
                    "Ik ben het niet eens maar dat geeft niet",
                    "Ik ben het niet eens, maar dat geeft niet.",
                ],
                "Ik ben het niet eens maar dat geeft niet",
            ),
            speak_step(
                "m09-l04-sp4",
                "Vraag",
                "Waarom vind jij dat?",
                ["Waarom vind jij dat", "waarom vind jij dat"],
                "Waarom vind jij dat",
            ),
            speak_step(
                "m09-l04-sp5",
                "Misschien",
                "Misschien vind ik dat later leuker.",
                ["Misschien vind ik dat later leuker", "misschien vind ik dat later leuker"],
                "Misschien vind ik dat later leuker",
            ),
            recap_step(
                "m09-l04-recap",
                "Recap",
                ["want", "omdat", "eens"],
                [
                    rt_fb("Ik vind dat saai, ___ het zo lang duurt. (because)", ["want", "maar", "dus"], "want"),
                    rt_ro(["binnen,", "blijf", "Ik", "omdat", "het", "regent."], "Ik blijf binnen, omdat het regent."),
                    rt_speak("Zeg: *Ik ben het eens.*", "Ik ben het eens."),
                    rt_listen_mcq(
                        "Snippet:",
                        "Ik vind ze soms saai, omdat ik liever buiten ben.",
                        ["Reden met omdat", "Geen reden", "Alleen weer"],
                        "Reden met omdat",
                    ),
                    rt_fb("___ niet? (really)", ["Echt", "Snel", "Stil"], "Echt"),
                    rt_speak("Zeg: *Dat lijkt me leuk!*", "Dat lijkt me leuk!"),
                ],
            ),
        ],
    }
