import { getPracticeScenarioHref } from '@/lib/practice/getPracticeScenarioHref'
import type { MissionTemplateDef } from '@/lib/missions/types'

const capHref = (ctx: { atScenarioCap: boolean }, scenarioHref: string) =>
  ctx.atScenarioCap ? '/app/premium' : scenarioHref

const capCta = (ctx: { atScenarioCap: boolean }, start: string) => (ctx.atScenarioCap ? 'See plans' : start)

export const MISSION_TEMPLATES: MissionTemplateDef[] = [
  {
    id: 'd_complete_guided',
    slot: 'daily',
    title: 'One quick scenario today',
    description: 'A quick guided rep to keep your Dutch moving — low pressure.',
    target: 1,
    xpReward: 25,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'scenario_complete', modes: ['guided'] },
    buildAction: (ctx) => ({
      href: capHref(ctx, getPracticeScenarioHref('cafe')),
      ctaLabel: capCta(ctx, 'Start now'),
    }),
  },
  {
    id: 'd_semi_social',
    slot: 'daily',
    title: 'One social chat today',
    description: 'Semi-guided turns — easy practice for cafés and plans.',
    target: 1,
    xpReward: 28,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'scenario_complete', modes: ['semi_guided'], category: 'social' },
    buildAction: (ctx) => ({
      href: capHref(ctx, getPracticeScenarioHref(ctx.suggestedScenarioId ?? 'social_plans')),
      ctaLabel: capCta(ctx, 'Open social scenario'),
    }),
  },
  {
    id: 'd_mistake_fix_session',
    slot: 'daily',
    title: 'Fix weak items in review',
    description: 'One focused review session on your slips (3+ cards) — ties back to Learn & Review.',
    target: 1,
    xpReward: 22,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'mistake_fix_sessions', minCards: 3 },
    buildAction: () => ({
      href: '/app/review/mistakes',
      ctaLabel: 'Start mistake fix',
    }),
  },
  {
    id: 'd_skill_track_any',
    slot: 'daily',
    title: 'Complete 1 skill track session',
    description: 'A micro-drill that builds confidence without a full scenario.',
    target: 1,
    xpReward: 20,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'skill_track_complete', anyTrack: true },
    buildAction: () => ({
      href: '/app/practice/tracks/listening_confidence',
      ctaLabel: 'Open skill tracks',
    }),
  },
  {
    id: 'd_listening_track',
    slot: 'daily',
    title: 'Do 1 listening confidence session',
    description: 'Short listening bursts — gist and detail without a full chat.',
    target: 1,
    xpReward: 22,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'skill_track_complete', trackIds: ['listening_confidence'] },
    buildAction: () => ({
      href: '/app/practice/tracks/listening_confidence',
      ctaLabel: 'Start listening track',
    }),
    rationale: () => 'Listening shows up often in real Dutch — this keeps it lightweight.',
  },
  {
    id: 'd_transport_scenario',
    slot: 'daily',
    title: 'Complete 1 transport scenario',
    description: 'Stations, tickets, and timing — high-frequency real life.',
    target: 1,
    xpReward: 26,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'scenario_complete', category: 'transport' },
    buildAction: (ctx) => ({
      href: capHref(ctx, getPracticeScenarioHref('train')),
      ctaLabel: capCta(ctx, 'Practice transport'),
    }),
  },
  {
    id: 'd_health_scenario',
    slot: 'daily',
    title: 'Complete 1 doctor / health scenario',
    description: 'Calm, clear Dutch for huisarts and apotheek moments.',
    target: 1,
    xpReward: 26,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'scenario_complete', category: 'health' },
    buildAction: (ctx) => ({
      href: capHref(ctx, getPracticeScenarioHref('doctor')),
      ctaLabel: capCta(ctx, 'Open health scenario'),
    }),
  },
  {
    id: 'w_three_scenarios',
    slot: 'weekly',
    title: 'Finish 3 scenarios this week',
    description: 'Breadth beats perfection — three short conversations add up fast.',
    target: 3,
    xpReward: 55,
    countsForStreak: false,
    requiresPremium: false,
    rule: { kind: 'scenario_completes_week' },
    buildAction: (ctx) => ({
      href: ctx.atScenarioCap ? '/app/premium' : '/app/practice/scenarios',
      ctaLabel: ctx.atScenarioCap ? 'See plans' : 'Browse scenarios',
    }),
  },
  {
    id: 'w_three_tracks',
    slot: 'weekly',
    title: 'Practice 3 different skills this week',
    description: 'Mix listening, writing, or repair tracks — balanced reps.',
    target: 3,
    xpReward: 60,
    countsForStreak: false,
    requiresPremium: false,
    rule: { kind: 'distinct_skill_tracks_week' },
    buildAction: () => ({
      href: '/app/practice/tracks',
      ctaLabel: 'View skill tracks',
    }),
  },
  {
    id: 'w_two_health',
    slot: 'weekly',
    title: 'Complete 2 health-related sessions',
    description: 'Two reps in health-themed practice (scenarios count).',
    target: 2,
    xpReward: 50,
    countsForStreak: false,
    requiresPremium: false,
    rule: { kind: 'health_scenarios_week' },
    buildAction: (ctx) => ({
      href: capHref(ctx, getPracticeScenarioHref('doctor')),
      ctaLabel: capCta(ctx, 'Start health practice'),
    }),
  },
  {
    id: 'w_five_practice_days',
    slot: 'weekly',
    title: 'Practice on 5 days this week',
    description: 'Little-and-often beats rare marathons — any scenario, track, or review counts.',
    target: 5,
    xpReward: 65,
    countsForStreak: false,
    requiresPremium: false,
    rule: { kind: 'practice_days_week' },
    buildAction: () => ({
      href: '/app/talk',
      ctaLabel: 'Go to Talk',
    }),
  },
  {
    id: 'w_two_mistake_fix',
    slot: 'weekly',
    title: 'Improve 1 weak area',
    description: 'Two solid mistake-fix sessions (3+ cards each) to close loops on errors.',
    target: 2,
    xpReward: 58,
    countsForStreak: false,
    requiresPremium: false,
    rule: { kind: 'mistake_fix_sessions', minCards: 3 },
    buildAction: () => ({
      href: '/app/review/mistakes',
      ctaLabel: 'Fix mistakes',
    }),
  },
  {
    id: 'sf_listening',
    slot: 'skill_focus',
    title: 'Listening micro-session',
    description: 'One listening confidence drill — build ear stamina in minutes.',
    target: 1,
    xpReward: 18,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'skill_track_complete', trackIds: ['listening_confidence'] },
    buildAction: () => ({
      href: '/app/practice/tracks/listening_confidence',
      ctaLabel: 'Start listening',
    }),
  },
  {
    id: 'sf_writing',
    slot: 'skill_focus',
    title: 'Writing practice',
    description: 'Polite, clear lines for messages you actually send.',
    target: 1,
    xpReward: 18,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'skill_track_complete', trackIds: ['writing_messages'] },
    buildAction: () => ({
      href: '/app/practice/tracks/writing_messages',
      ctaLabel: 'Open writing track',
    }),
  },
  {
    id: 'sf_repair',
    slot: 'skill_focus',
    title: 'Reaction speed & repair',
    description: 'Clarify, recover, and keep the conversation moving.',
    target: 1,
    xpReward: 18,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'skill_track_complete', trackIds: ['conversation_repair'] },
    buildAction: () => ({
      href: '/app/practice/tracks/conversation_repair',
      ctaLabel: 'Practice repair lines',
    }),
  },
  {
    id: 'sf_speaking_guided',
    slot: 'skill_focus',
    title: 'Speaking rep (guided scenario)',
    description: 'Say it out loud in a guided scenario — momentum before harder modes.',
    target: 1,
    xpReward: 20,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'scenario_complete', modes: ['guided'] },
    buildAction: (ctx) => ({
      href: capHref(ctx, getPracticeScenarioHref('cafe')),
      ctaLabel: capCta(ctx, 'Guided speaking rep'),
    }),
  },
  {
    id: 'sf_speaking_fluency_premium',
    slot: 'skill_focus',
    title: 'Speaking fluency track',
    description: 'Premium micro-drills for smoother spoken Dutch.',
    target: 1,
    xpReward: 22,
    countsForStreak: true,
    requiresPremium: true,
    rule: { kind: 'skill_track_complete', trackIds: ['speaking_fluency'] },
    buildAction: (ctx) => ({
      href: ctx.tier === 'free' ? '/app/premium' : '/app/practice/tracks/speaking_fluency',
      ctaLabel: ctx.tier === 'free' ? 'Unlock with Premium' : 'Open speaking track',
    }),
  },
  {
    id: 'd_exam_speaking_train',
    slot: 'daily',
    title: 'Complete 1 speaking task',
    description: 'One exam-style speaking prompt with structured feedback — small rep, clear progress.',
    target: 1,
    xpReward: 24,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'exam_prep_completion', domains: ['speaking'], modes: ['training'] },
    buildAction: () => ({
      href: '/app/exam-prep/speaking/training',
      ctaLabel: 'Start speaking task',
    }),
  },
  {
    id: 'd_exam_writing_train',
    slot: 'daily',
    title: 'Finish 1 writing exercise',
    description: 'A short writing item with rubric feedback — builds exam execution without a marathon.',
    target: 1,
    xpReward: 24,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'exam_prep_completion', domains: ['writing'], modes: ['training'] },
    buildAction: () => ({
      href: '/app/exam-prep/writing/training',
      ctaLabel: 'Open writing training',
    }),
  },
  {
    id: 'd_exam_listening_task',
    slot: 'daily',
    title: 'Practice 1 listening clip',
    description: 'One focused listening item — gist or detail, exam-style pacing.',
    target: 1,
    xpReward: 22,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'exam_prep_completion', domains: ['listening'], modes: ['training'] },
    buildAction: () => ({
      href: '/app/exam-prep/listening/training',
      ctaLabel: 'Start listening',
    }),
  },
  {
    id: 'd_exam_reading_task',
    slot: 'daily',
    title: 'Complete 1 reading item',
    description: 'A single reading task with instant check — keeps comprehension sharp.',
    target: 1,
    xpReward: 22,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'exam_prep_completion', domains: ['reading'], modes: ['training'] },
    buildAction: () => ({
      href: '/app/exam-prep/reading/training',
      ctaLabel: 'Open reading training',
    }),
  },
  {
    id: 'd_exam_kmn_quiz',
    slot: 'daily',
    title: 'Do 1 KMN quiz round',
    description: 'Five quick knowledge questions — keeps KNM material active in your week.',
    target: 1,
    xpReward: 20,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'exam_prep_completion', domains: ['kmn'], modes: ['training'] },
    buildAction: () => ({
      href: '/app/exam-prep/kmn',
      ctaLabel: 'Pick a KMN topic',
    }),
  },
  {
    id: 'd_exam_writing_grammar_up',
    slot: 'daily',
    title: 'Improve your grammar score',
    description: 'Finish a writing task where your grammar rubric is stronger than last time — quality over volume.',
    target: 1,
    xpReward: 26,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'exam_category_improved', domain: 'writing', categoryKey: 'grammar', minDelta: 1 },
    buildAction: () => ({
      href: '/app/exam-prep/writing/training',
      ctaLabel: 'Practice writing',
    }),
    rationale: () =>
      'We only count a real step up on the grammar rubric — repeat tasks until you beat your last score.',
  },
  {
    id: 'd_exam_speaking_fluency_up',
    slot: 'daily',
    title: 'Improve speaking fluency',
    description: 'Complete speaking training with a higher fluency rubric score than your last session.',
    target: 1,
    xpReward: 26,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'exam_category_improved', domain: 'speaking', categoryKey: 'fluency', minDelta: 1 },
    buildAction: () => ({
      href: '/app/exam-prep/speaking/training',
      ctaLabel: 'Train speaking',
    }),
    rationale: () => 'Fluency moves when you push past your last rubric baseline — one honest rep counts.',
  },
  {
    id: 'w_exam_mixed_4',
    slot: 'weekly',
    title: 'Complete 4 exam-prep actions',
    description: 'Speaking, writing, listening, reading, KMN, simulations, or practice exams — mix is fine.',
    target: 4,
    xpReward: 62,
    countsForStreak: false,
    requiresPremium: false,
    rule: { kind: 'exam_prep_week_count' },
    buildAction: () => ({
      href: '/app/exam-prep',
      ctaLabel: 'Open Exam Prep',
    }),
  },
  {
    id: 'w_exam_speaking_3',
    slot: 'weekly',
    title: 'Complete 3 speaking tasks this week',
    description: 'Three short speaking reps add up — training or simulation both count.',
    target: 3,
    xpReward: 58,
    countsForStreak: false,
    requiresPremium: false,
    rule: { kind: 'exam_prep_week_count', domain: 'speaking' },
    buildAction: () => ({
      href: '/app/exam-prep/speaking/training',
      ctaLabel: 'Speaking practice',
    }),
  },
  {
    id: 'w_exam_simulation_1',
    slot: 'weekly',
    title: 'Complete 1 exam simulation',
    description: 'Timed, exam-realistic run — use it when you are ready for pressure practice.',
    target: 1,
    xpReward: 70,
    countsForStreak: false,
    requiresPremium: true,
    rule: { kind: 'exam_prep_completion', domains: ['speaking', 'writing'], modes: ['simulation'] },
    buildAction: (ctx) => ({
      href: ctx.tier === 'free' ? '/app/premium' : '/app/exam-prep/speaking/simulation',
      ctaLabel: ctx.tier === 'free' ? 'Unlock simulations' : 'Start simulation',
    }),
  },
  {
    id: 'w_exam_practice_exam_2',
    slot: 'weekly',
    title: 'Finish 2 practice exam sections',
    description: 'Two fixed practice-exam runs — any module counts toward exam readiness.',
    target: 2,
    xpReward: 64,
    countsForStreak: false,
    requiresPremium: false,
    rule: { kind: 'exam_prep_practice_exam_week' },
    buildAction: () => ({
      href: '/app/exam-prep/speaking/practice-exams',
      ctaLabel: 'Browse practice exams',
    }),
  },
  {
    id: 'w_exam_writing_grammar_week',
    slot: 'weekly',
    title: 'Improve writing grammar this week',
    description: 'Lift your grammar rubric on a writing task compared with your last attempt.',
    target: 1,
    xpReward: 60,
    countsForStreak: false,
    requiresPremium: false,
    rule: { kind: 'exam_category_improved', domain: 'writing', categoryKey: 'grammar', minDelta: 1 },
    buildAction: () => ({
      href: '/app/exam-prep/writing/training',
      ctaLabel: 'Writing training',
    }),
  },
  {
    id: 'sf_exam_speaking',
    slot: 'skill_focus',
    title: 'Exam speaking rep',
    description: 'One speaking training task — keeps exam mode familiar.',
    target: 1,
    xpReward: 18,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'exam_prep_completion', domains: ['speaking'], modes: ['training'] },
    buildAction: () => ({
      href: '/app/exam-prep/speaking/training',
      ctaLabel: 'Speaking task',
    }),
  },
  {
    id: 'sf_exam_writing',
    slot: 'skill_focus',
    title: 'Exam writing rep',
    description: 'One writing exercise with rubric feedback.',
    target: 1,
    xpReward: 18,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'exam_prep_completion', domains: ['writing'], modes: ['training'] },
    buildAction: () => ({
      href: '/app/exam-prep/writing/training',
      ctaLabel: 'Writing exercise',
    }),
  },
  {
    id: 'sf_exam_listening',
    slot: 'skill_focus',
    title: 'Exam listening micro-hit',
    description: 'One listening item — low friction, exam-relevant focus.',
    target: 1,
    xpReward: 18,
    countsForStreak: true,
    requiresPremium: false,
    rule: { kind: 'exam_prep_completion', domains: ['listening'], modes: ['training'] },
    buildAction: () => ({
      href: '/app/exam-prep/listening/training',
      ctaLabel: 'Listening clip',
    }),
  },
]

const byId = new Map<string, MissionTemplateDef>()
for (const t of MISSION_TEMPLATES) {
  byId.set(t.id, t)
}

export function getMissionTemplate(id: string): MissionTemplateDef | undefined {
  return byId.get(id)
}

export function templatesForSlot(slot: MissionTemplateDef['slot']): MissionTemplateDef[] {
  return MISSION_TEMPLATES.filter((t) => t.slot === slot)
}
