/**
 * Central registry of skill metadata — powers Skills UI, recommendations, and coach copy.
 */
import type { ReadAloudPassagePersonalizationProfileId } from '../learningMemory/readAloudPersonalizationFromProfile'
import type { SkillGroup, SkillId } from './skillTypes'
import { skillGroupForId } from './skillTypes'

export type SkillDefinition = {
  id: SkillId
  group: SkillGroup
  label: string
  shortDescription: string
  /** Coach / product copy — richer than {@link shortDescription}. */
  longDescription: string
  whyItMatters: string
  iconToken: string
  relatedScenarioSlugs: string[]
  relatedReadAloudProfiles: ReadAloudPassagePersonalizationProfileId[]
  relatedCoachGoals: string[]
  /** Sort key within catalog UIs (lower first). */
  displayOrder: number
}

const DEFS: Omit<SkillDefinition, 'group' | 'displayOrder'>[] = [
  {
    id: 'pronunciation',
    label: 'Pronunciation',
    shortDescription: 'Clear Dutch sounds and stress patterns when you speak.',
    whyItMatters: 'Carries meaning in Dutch — listeners understand you faster with cleaner sounds.',
    iconToken: 'audio-waveform',
    longDescription:
      'Blend of individual sounds, word stress, and comfortable pacing so you sound natural. Progress shows up as clearer lines, fewer “say again?” moments, and more relaxed endings.',
    relatedScenarioSlugs: ['train-station', 'ordering_food', 'phone_call', 'read_aloud'],
    relatedReadAloudProfiles: ['pronunciation_focus', 'weak_sounds_focus', 'fluency_focus'],
    relatedCoachGoals: ['confidence', 'fluency', 'clarity'],
  },
  {
    id: 'fluency',
    label: 'Fluency',
    shortDescription: 'Smooth delivery without tripping over every phrase.',
    whyItMatters: 'Keeps conversations relaxed — you stay in flow instead of restarting.',
    iconToken: 'wind',
    longDescription: 'Fewer long stalls, smoother hand-offs between ideas, natural fillers when needed.',
    relatedScenarioSlugs: ['storytelling', 'small_talk', 'language_coach', 'train-station'],
    relatedReadAloudProfiles: ['fluency_focus', 'mixed_review', 'everyday_dutch'],
    relatedCoachGoals: ['fluency', 'confidence', 'naturalness'],
  },
  {
    id: 'pacing',
    label: 'Pacing',
    shortDescription: 'Rhythm, pauses, and breath-friendly phrasing.',
    whyItMatters: 'Gives listeners time to follow — and you sound more in control.',
    iconToken: 'timer',
    longDescription: 'Steady tempo, clean pauses at clause boundaries, avoiding rushed tails.',
    relatedScenarioSlugs: ['read_aloud', 'presentation_light', 'language_coach'],
    relatedReadAloudProfiles: ['fluency_focus', 'pronunciation_focus', 'everyday_dutch'],
    relatedCoachGoals: ['presence', 'fluency'],
  },
  {
    id: 'asking_questions',
    label: 'Asking questions',
    shortDescription: 'Natural Dutch question forms in real situations.',
    whyItMatters: 'Questions unlock information — tickets, menus, directions, meetings.',
    iconToken: 'help-circle',
    longDescription: 'Word order, polite openers, and quick clarifiers that fit the context.',
    relatedScenarioSlugs: ['train-station', 'ordering_food', 'supermarket_shop', 'work_colleague'],
    relatedReadAloudProfiles: ['grammar_focus', 'everyday_dutch', 'scenario_linked'],
    relatedCoachGoals: ['practical_dutch', 'confidence'],
  },
  {
    id: 'reacting',
    label: 'Reacting',
    shortDescription: 'Short, natural reactions that keep rapport warm.',
    whyItMatters: 'Small acknowledgements make Dutch feel social, not transactional.',
    iconToken: 'message-smile',
    longDescription: 'Brief agreements, empathy markers, and follow-up sounds that match tone.',
    relatedScenarioSlugs: ['small_talk', 'ordering_food', 'language_coach'],
    relatedReadAloudProfiles: ['everyday_dutch', 'fluency_focus'],
    relatedCoachGoals: ['warmth', 'confidence'],
  },
  {
    id: 'keeping_flow',
    label: 'Keeping flow',
    shortDescription: 'Hold the thread without dropping the conversational ball.',
    whyItMatters: 'Flow is what makes chats feel effortless — even when vocabulary is simple.',
    iconToken: 'git-branch',
    longDescription: 'Linking ideas, soft transitions, and gentle recovery when you lose a beat.',
    relatedScenarioSlugs: ['language_coach', 'small_talk', 'storytelling'],
    relatedReadAloudProfiles: ['fluency_focus', 'mixed_review'],
    relatedCoachGoals: ['fluency', 'naturalness'],
  },
  {
    id: 'follow_up_questions',
    label: 'Follow-up questions',
    shortDescription: 'Curious second questions that deepen the exchange.',
    whyItMatters: 'Signals engagement — people open up and you get richer practice.',
    iconToken: 'messages-square',
    longDescription: 'Light “how / what / where next” moves without sounding like an interview.',
    relatedScenarioSlugs: ['language_coach', 'small_talk', 'work_colleague', 'storytelling'],
    relatedReadAloudProfiles: ['everyday_dutch', 'scenario_linked', 'confidence_build'],
    relatedCoachGoals: ['conversation_depth', 'confidence'],
  },
  {
    id: 'repair_clarification',
    label: 'Repair & clarification',
    shortDescription: 'When something is unclear, you fix it calmly.',
    whyItMatters: 'Real life is noisy — repair keeps you understood without panic.',
    iconToken: 'refresh-ccw',
    longDescription: 'Asking to repeat, narrowing meaning, paraphrasing back to confirm.',
    relatedScenarioSlugs: ['train-station', 'phone_call', 'store_service_issue', 'supermarket_shop'],
    relatedReadAloudProfiles: ['everyday_dutch', 'mixed_review'],
    relatedCoachGoals: ['resilience', 'practical_dutch'],
  },
  {
    id: 'turn_taking',
    label: 'Turn-taking',
    shortDescription: 'Balanced space — you speak, they speak, naturally.',
    whyItMatters: 'Good rhythm avoids talking over people or going silent too long.',
    iconToken: 'arrow-left-right',
    longDescription: 'Hand-backs, short confirmations, and timing that matches the setting.',
    relatedScenarioSlugs: ['language_coach', 'work_colleague', 'phone_call'],
    relatedReadAloudProfiles: ['fluency_focus'],
    relatedCoachGoals: ['professionalism', 'naturalness'],
  },
  {
    id: 'explaining',
    label: 'Explaining',
    shortDescription: 'Make a point clear in a few ordered sentences.',
    whyItMatters: 'Explaining is how you help others follow your thinking — at work and socially.',
    iconToken: 'lightbulb',
    longDescription: 'Topic sentence, one or two supports, and a clean close without rambling.',
    relatedScenarioSlugs: ['work_colleague', 'explaining_something', 'language_coach'],
    relatedReadAloudProfiles: ['grammar_focus', 'mixed_review'],
    relatedCoachGoals: ['clarity', 'structure'],
  },
  {
    id: 'storytelling',
    label: 'Storytelling',
    shortDescription: 'Past experiences with a beginning, middle, and payoff.',
    whyItMatters: 'Stories are how people bond — birthdays, trips, mishaps, wins.',
    iconToken: 'book-open',
    longDescription: 'Time markers, small details, and emotional color without overloading.',
    relatedScenarioSlugs: ['storytelling', 'small_talk', 'language_coach'],
    relatedReadAloudProfiles: ['storytelling_focus', 'fluency_focus', 'mixed_review', 'everyday_dutch'],
    relatedCoachGoals: ['confidence', 'fluency', 'warmth'],
  },
  {
    id: 'sequencing',
    label: 'Sequencing',
    shortDescription: 'First / then / after that — clear order in speech.',
    whyItMatters: 'Listeners trust you when the order matches what happened.',
    iconToken: 'list-ordered',
    longDescription: 'Connectors, clean chronology, and small signposts for what comes next.',
    relatedScenarioSlugs: ['storytelling', 'explaining_something', 'train-station'],
    relatedReadAloudProfiles: ['storytelling_focus', 'grammar_focus', 'fluency_focus'],
    relatedCoachGoals: ['structure', 'clarity'],
  },
  {
    id: 'step_by_step_speaking',
    label: 'Step-by-step speaking',
    shortDescription: 'Break a process into speakable beats.',
    whyItMatters: 'Helps in directions, recipes, troubleshooting, and light instructions.',
    iconToken: 'footprints',
    longDescription: 'Numbering lightly, grouping steps, checking in after each chunk.',
    relatedScenarioSlugs: ['explaining_something', 'work_colleague', 'language_coach'],
    relatedReadAloudProfiles: ['grammar_focus', 'everyday_dutch'],
    relatedCoachGoals: ['structure', 'professionalism'],
  },
  {
    id: 'response_structure',
    label: 'Response structure',
    shortDescription: 'Answer the question you were asked, cleanly.',
    whyItMatters: 'Structure reduces confusion — especially in work Dutch.',
    iconToken: 'layout-template',
    longDescription: 'Lead with the answer, add one layer of detail, optional example.',
    relatedScenarioSlugs: ['work_colleague', 'phone_call', 'language_coach'],
    relatedReadAloudProfiles: ['grammar_focus', 'mixed_review'],
    relatedCoachGoals: ['clarity', 'professionalism'],
  },
  {
    id: 'grammar',
    label: 'Grammar',
    shortDescription: 'Agreement, tense, and word order that match the situation.',
    whyItMatters: 'Grammar carries precision — who did what, when, and how sure you are.',
    iconToken: 'pen-line',
    longDescription: 'Patterns that show up in your feedback, recycled in realistic sentences.',
    relatedScenarioSlugs: ['read_aloud', 'language_coach', 'work_colleague'],
    relatedReadAloudProfiles: ['grammar_focus', 'mixed_review'],
    relatedCoachGoals: ['accuracy', 'confidence'],
  },
  {
    id: 'vocabulary',
    label: 'Vocabulary',
    shortDescription: 'Useful words you can deploy under mild pressure.',
    whyItMatters: 'Right words reduce friction — less circumlocution, more momentum.',
    iconToken: 'library',
    longDescription: 'High-utility collocations for the scenes you actually practice.',
    relatedScenarioSlugs: ['supermarket_shop', 'ordering_food', 'train-station', 'read_aloud'],
    relatedReadAloudProfiles: ['weak_vocabulary_focus', 'mixed_review'],
    relatedCoachGoals: ['breadth', 'practical_dutch'],
  },
  {
    id: 'sentence_structure',
    label: 'Sentence structure',
    shortDescription: 'Clause stacking that still sounds Dutch.',
    whyItMatters: 'Lets you pack more information without sounding translated.',
    iconToken: 'braces',
    longDescription: 'Subclauses, inversion, and clean endings that match register.',
    relatedScenarioSlugs: ['work_colleague', 'language_coach', 'read_aloud'],
    relatedReadAloudProfiles: ['grammar_focus', 'mixed_review'],
    relatedCoachGoals: ['accuracy', 'naturalness'],
  },
  {
    id: 'word_choice',
    label: 'Word choice',
    shortDescription: 'Pick words that match tone and nuance.',
    whyItMatters: 'Word choice is how you sound polite, direct, or warm — by intent.',
    iconToken: 'sparkles',
    longDescription: 'Softer vs firmer verbs, natural particles, avoiding heavy calques.',
    relatedScenarioSlugs: ['language_coach', 'work_colleague', 'small_talk'],
    relatedReadAloudProfiles: ['everyday_dutch', 'mixed_review'],
    relatedCoachGoals: ['naturalness', 'tone'],
  },
  {
    id: 'natural_dutch',
    label: 'Natural Dutch',
    shortDescription: 'Idiomatic rhythm — not textbook-perfect but believably native.',
    whyItMatters: 'Naturalness is what makes advanced learners feel “at home”.',
    iconToken: 'leaf',
    longDescription: 'Chunks, fillers, and collocations Dutch speakers actually use.',
    relatedScenarioSlugs: ['language_coach', 'small_talk', 'storytelling'],
    relatedReadAloudProfiles: ['confidence_build', 'everyday_dutch', 'fluency_focus'],
    relatedCoachGoals: ['naturalness', 'confidence'],
  },
  {
    id: 'opinions',
    label: 'Opinions',
    shortDescription: 'State a view with a clear stance — still respectful.',
    whyItMatters: 'Opinions drive real adult conversations — media, work, friends.',
    iconToken: 'message-circle',
    longDescription: 'Soft framing, stance + reason, space for the other person.',
    relatedScenarioSlugs: ['opinions_light', 'language_coach', 'small_talk'],
    relatedReadAloudProfiles: ['mixed_review', 'everyday_dutch'],
    relatedCoachGoals: ['voice', 'confidence'],
  },
  {
    id: 'reasoning',
    label: 'Reasoning',
    shortDescription: 'Because / so / that’s why — tight logic in speech.',
    whyItMatters: 'Reasoning helps you persuade gently and explain decisions.',
    iconToken: 'brain',
    longDescription: 'One main claim, compact support, and a clean recap line.',
    relatedScenarioSlugs: ['opinions_light', 'work_colleague', 'language_coach'],
    relatedReadAloudProfiles: ['mixed_review', 'grammar_focus'],
    relatedCoachGoals: ['clarity', 'voice'],
  },
  {
    id: 'nuance',
    label: 'Nuance',
    shortDescription: 'Shades of meaning — not only black-and-white answers.',
    whyItMatters: 'Nuance is how sophisticated Dutch sounds kind, fair, and precise.',
    iconToken: 'blend',
    longDescription: 'Hedging, scope, and careful qualifiers without sounding unsure.',
    relatedScenarioSlugs: ['opinions_light', 'language_coach', 'work_colleague'],
    relatedReadAloudProfiles: ['mixed_review', 'everyday_dutch'],
    relatedCoachGoals: ['tone', 'naturalness'],
  },
  {
    id: 'contrast_comparison',
    label: 'Contrast & comparison',
    shortDescription: 'A vs B, similarities, trade-offs — spoken cleanly.',
    whyItMatters: 'Comparisons show up in choices — routes, products, plans.',
    iconToken: 'split',
    longDescription: 'Parallel structures, clear comparatives, and tidy contrasts.',
    relatedScenarioSlugs: ['opinions_light', 'work_colleague', 'supermarket_shop'],
    relatedReadAloudProfiles: ['grammar_focus', 'mixed_review'],
    relatedCoachGoals: ['structure', 'voice'],
  },
  {
    id: 'softer_disagreement',
    label: 'Softer disagreement',
    shortDescription: 'Push back politely — firm boundary, warm tone.',
    whyItMatters: 'Keeps relationships steady while you still advocate for yourself.',
    iconToken: 'handshake',
    longDescription: 'Acknowledge → gentle counter → invite dialogue.',
    relatedScenarioSlugs: ['work_colleague', 'language_coach', 'opinions_light'],
    relatedReadAloudProfiles: ['everyday_dutch', 'mixed_review'],
    relatedCoachGoals: ['tone', 'professionalism'],
  },
  {
    id: 'gist_understanding',
    label: 'Gist understanding',
    shortDescription: 'Catch the main point from Dutch audio without every word.',
    whyItMatters: 'Most real listening is “good enough” comprehension first — then details.',
    iconToken: 'audio-waveform',
    longDescription: 'Topic, intent, and emotional tone from short clips and noisy lines.',
    relatedScenarioSlugs: ['train-station', 'ordering_food', 'supermarket_shop', 'phone_call'],
    relatedReadAloudProfiles: ['everyday_dutch', 'scenario_linked'],
    relatedCoachGoals: ['practical_dutch', 'confidence'],
  },
  {
    id: 'detail_recognition',
    label: 'Detail recognition',
    shortDescription: 'Lock onto specifics after you have the gist.',
    whyItMatters: 'Tickets, prices, and plans hinge on small words and numbers.',
    iconToken: 'search',
    longDescription: 'Who / what / when / where style details from single passes when possible.',
    relatedScenarioSlugs: ['train-station', 'supermarket_shop', 'booking_reservations'],
    relatedReadAloudProfiles: ['scenario_linked', 'mixed_review'],
    relatedCoachGoals: ['practical_dutch', 'clarity'],
  },
  {
    id: 'instruction_following',
    label: 'Instruction following',
    shortDescription: 'Track multi-step Dutch instructions under time pressure.',
    whyItMatters: 'Counters, desks, and machines often give short command chains.',
    iconToken: 'list-checks',
    longDescription: 'Order of steps, negation, and polite imperatives in service Dutch.',
    relatedScenarioSlugs: ['supermarket_shop', 'train-station', 'store_service_issue'],
    relatedReadAloudProfiles: ['everyday_dutch', 'scenario_linked'],
    relatedCoachGoals: ['practical_dutch', 'resilience'],
  },
  {
    id: 'response_readiness',
    label: 'Response readiness',
    shortDescription: 'Answer promptly after listening — without long stalls.',
    whyItMatters: 'Live exchanges reward quick, appropriate replies.',
    iconToken: 'zap',
    longDescription: 'Short listen–respond loops with confident first attempts.',
    relatedScenarioSlugs: ['phone_call', 'train-station', 'small_talk'],
    relatedReadAloudProfiles: ['fluency_focus', 'everyday_dutch'],
    relatedCoachGoals: ['fluency', 'confidence'],
  },
  {
    id: 'fast_speech_handling',
    label: 'Fast speech handling',
    shortDescription: 'Follow Dutch that comes at natural native speed.',
    whyItMatters: 'Announcements and busy staff rarely slow down for learners.',
    iconToken: 'gauge',
    longDescription: 'Chunking, stress cues, and recovery when a burst slips past.',
    relatedScenarioSlugs: ['train-station', 'phone_call', 'ordering_food'],
    relatedReadAloudProfiles: ['fluency_focus', 'mixed_review'],
    relatedCoachGoals: ['fluency', 'practical_dutch'],
  },
  {
    id: 'reduced_spoken_dutch',
    label: 'Reduced / elliptical Dutch',
    shortDescription: 'Understand clipped phrases and dropped words.',
    whyItMatters: 'Real Dutch often omits subjects and softens grammar in speech.',
    iconToken: 'ellipsis',
    longDescription: 'Telegraphic counters, platform blurbs, and implied subjects.',
    relatedScenarioSlugs: ['train-station', 'supermarket_shop', 'ordering_food'],
    relatedReadAloudProfiles: ['everyday_dutch', 'mixed_review'],
    relatedCoachGoals: ['naturalness', 'practical_dutch'],
  },
  {
    id: 'filler_tolerance',
    label: 'Filler tolerance',
    shortDescription: 'Stay oriented through “eh”, restarts, and self-corrections.',
    whyItMatters: 'Natural speech is messy — tolerance keeps you in the conversation.',
    iconToken: 'waypoints',
    longDescription: 'Holds meaning across hedges, repairs, and overlapping sounds.',
    relatedScenarioSlugs: ['small_talk', 'work_colleague', 'language_coach'],
    relatedReadAloudProfiles: ['fluency_focus', 'everyday_dutch'],
    relatedCoachGoals: ['naturalness', 'confidence'],
  },
  {
    id: 'speaker_variation',
    label: 'Speaker variation',
    shortDescription: 'Adapt across accents, ages, and registers.',
    whyItMatters: 'The same words sound different from person to person.',
    iconToken: 'users',
    longDescription: 'Stability across gender, age, and informal vs service tone.',
    relatedScenarioSlugs: ['meeting_new_people', 'train-station', 'language_coach'],
    relatedReadAloudProfiles: ['mixed_review', 'scenario_linked'],
    relatedCoachGoals: ['confidence', 'naturalness'],
  },
  {
    id: 'numbers_and_times',
    label: 'Numbers & times',
    shortDescription: 'Catch prices, durations, and clock times in speech.',
    whyItMatters: 'Mistakes here are costly for tickets, plans, and payments.',
    iconToken: 'hash',
    longDescription: 'Cardinal chains, 24h-style times, and compact “half / kwart” phrasing.',
    relatedScenarioSlugs: ['train-station', 'booking_reservations', 'ordering_food'],
    relatedReadAloudProfiles: ['everyday_dutch', 'grammar_focus'],
    relatedCoachGoals: ['practical_dutch', 'clarity'],
  },
  {
    id: 'route_words',
    label: 'Route words',
    shortDescription: 'Prepositions and landmarks in spoken directions.',
    whyItMatters: 'Small words change where you walk or which exit you take.',
    iconToken: 'map-pin',
    longDescription: 'Links between “naar”, “af”, “over”, and named places.',
    relatedScenarioSlugs: ['directions_getting_somewhere', 'train-station'],
    relatedReadAloudProfiles: ['scenario_linked', 'everyday_dutch'],
    relatedCoachGoals: ['practical_dutch', 'clarity'],
  },
  {
    id: 'service_replies',
    label: 'Service replies',
    shortDescription: 'Short back-and-forth at counters and desks.',
    whyItMatters: 'Service Dutch is compressed — one missed line queues the wrong item.',
    iconToken: 'store',
    longDescription: 'Polite bundles, yes/no checks, and quick clarifiers.',
    relatedScenarioSlugs: ['supermarket_shop', 'ordering_food', 'store_service_issue'],
    relatedReadAloudProfiles: ['scenario_linked', 'everyday_dutch'],
    relatedCoachGoals: ['practical_dutch', 'warmth'],
  },
  {
    id: 'quantities_and_items',
    label: 'Quantities & items',
    shortDescription: 'Track counts, units, and order items in audio.',
    whyItMatters: 'Wrong quantity or item is the classic listening slip at shops.',
    iconToken: 'shopping-bag',
    longDescription: 'Pairs of numbers + nouns, weights, and “nog een …” patterns.',
    relatedScenarioSlugs: ['supermarket_shop', 'ordering_food'],
    relatedReadAloudProfiles: ['everyday_dutch', 'scenario_linked'],
    relatedCoachGoals: ['practical_dutch', 'clarity'],
  },
]

const READ_ALOUD_VALID = new Set<string>([
  'pronunciation_focus',
  'weak_sounds_focus',
  'weak_vocabulary_focus',
  'grammar_focus',
  'fluency_focus',
  'mixed_review',
  'everyday_dutch',
  'scenario_linked',
  'storytelling_focus',
  'confidence_build',
])

function sanitizeReadAloud(
  profiles: ReadAloudPassagePersonalizationProfileId[],
): ReadAloudPassagePersonalizationProfileId[] {
  return profiles.filter((p) => READ_ALOUD_VALID.has(p)) as ReadAloudPassagePersonalizationProfileId[]
}

export const SKILL_DEFINITIONS: SkillDefinition[] = DEFS.map((d, idx) => ({
  ...d,
  group: skillGroupForId(d.id),
  displayOrder: idx + 1,
  relatedReadAloudProfiles: sanitizeReadAloud(d.relatedReadAloudProfiles),
}))

const BY_ID: Map<SkillId, SkillDefinition> = new Map(SKILL_DEFINITIONS.map((d) => [d.id, d]))

export function getSkillDefinition(id: SkillId): SkillDefinition {
  return BY_ID.get(id)!
}

export function allSkillDefinitionsForGroup(group: SkillGroup): SkillDefinition[] {
  return SKILL_DEFINITIONS.filter((d) => d.group === group).sort((a, b) => a.displayOrder - b.displayOrder)
}
