import type { ExamLevel, ExamProfile } from '../types'
import {
  INBURGERING_KNM_A1,
  INBURGERING_KNM_A2,
  INBURGERING_KNM_B1,
  INBURGERING_LISTENING_A1,
  INBURGERING_LISTENING_A2,
  INBURGERING_LISTENING_B1,
  INBURGERING_READING_A1,
  INBURGERING_READING_A2,
  INBURGERING_READING_B1,
  INBURGERING_WRITING_A1,
  INBURGERING_WRITING_A2,
  INBURGERING_WRITING_B1,
} from './inburgeringModalityProfiles'
import {
  INBURGERING_SPEAKING_A1,
  INBURGERING_SPEAKING_A2,
  INBURGERING_SPEAKING_B1,
} from './inburgeringSpeakingProfiles'

/** Legacy default id — same authoring as {@link INBURGERING_SPEAKING_A2}. */
export const INBURGERING_SPEAKING_V1_LEGACY: ExamProfile = {
  ...INBURGERING_SPEAKING_A2,
  examId: 'inburgering_speaking_v1',
}

const BY_ID: Record<string, ExamProfile> = {
  [INBURGERING_SPEAKING_A1.examId]: INBURGERING_SPEAKING_A1,
  [INBURGERING_SPEAKING_A2.examId]: INBURGERING_SPEAKING_A2,
  [INBURGERING_SPEAKING_B1.examId]: INBURGERING_SPEAKING_B1,
  [INBURGERING_SPEAKING_V1_LEGACY.examId]: INBURGERING_SPEAKING_V1_LEGACY,
  [INBURGERING_LISTENING_A1.examId]: INBURGERING_LISTENING_A1,
  [INBURGERING_LISTENING_A2.examId]: INBURGERING_LISTENING_A2,
  [INBURGERING_LISTENING_B1.examId]: INBURGERING_LISTENING_B1,
  [INBURGERING_WRITING_A1.examId]: INBURGERING_WRITING_A1,
  [INBURGERING_WRITING_A2.examId]: INBURGERING_WRITING_A2,
  [INBURGERING_WRITING_B1.examId]: INBURGERING_WRITING_B1,
  [INBURGERING_READING_A1.examId]: INBURGERING_READING_A1,
  [INBURGERING_READING_A2.examId]: INBURGERING_READING_A2,
  [INBURGERING_READING_B1.examId]: INBURGERING_READING_B1,
  [INBURGERING_KNM_A1.examId]: INBURGERING_KNM_A1,
  [INBURGERING_KNM_A2.examId]: INBURGERING_KNM_A2,
  [INBURGERING_KNM_B1.examId]: INBURGERING_KNM_B1,
}

/** Catalog rows (one per authored level per modality; excludes legacy alias id). */
const CATALOG: ExamProfile[] = [
  INBURGERING_SPEAKING_A1,
  INBURGERING_SPEAKING_A2,
  INBURGERING_SPEAKING_B1,
  INBURGERING_LISTENING_A1,
  INBURGERING_LISTENING_A2,
  INBURGERING_LISTENING_B1,
  INBURGERING_WRITING_A1,
  INBURGERING_WRITING_A2,
  INBURGERING_WRITING_B1,
  INBURGERING_READING_A1,
  INBURGERING_READING_A2,
  INBURGERING_READING_B1,
  INBURGERING_KNM_A1,
  INBURGERING_KNM_A2,
  INBURGERING_KNM_B1,
]

export function listExamProfiles(): ExamProfile[] {
  return CATALOG
}

export function getExamProfile(examId: string): ExamProfile | undefined {
  return BY_ID[examId]
}

export function getExamProfileByCodeAndLevel(examCode: string, level: ExamLevel): ExamProfile | undefined {
  const hit = CATALOG.find((p) => p.examCode === examCode && p.level === level)
  return hit
}

export function listAllProfileIds(): string[] {
  return Object.keys(BY_ID)
}
